/-
MACHINE-GENERATED by `ny-cert`'s `lrat_to_lean` — do not edit.

sat_relu Route A instance transcript:
* DIMACS source : v92c117.cnf  (p cnf 92 117)
* LRAT source   : v92c117.lrat  (112 addition steps kept)

The kernel replays the full LRAT refutation with PLAIN `decide`
(no `native_decide`, no extra axioms) through
`RupChecker.checkRefutation`, then composes
`checkRefutation_sound` (CNF-unsat) with
`SatReluVerdict.safe_of_unsat` (gadget real-arithmetic safety).
-/
import NyProof.SatReluVerdict

namespace Crownproof

namespace SatReluDemo_v92c117

open RupImport.RUP RupChecker

set_option maxRecDepth 8192

/-- The recovered DIMACS formula, literal-for-literal. -/
def F : Formula :=
  [ [(1, true), (47, true), (48, true), (59, false), (75, true), (84, true), (89, false), (90, true)]
  , [(1, true), (13, true), (47, true), (48, false), (51, true)]
  , [(1, false), (10, true), (58, true), (69, true), (78, false), (82, false)]
  , [(1, false), (10, true), (30, true), (46, false), (49, false), (58, true), (82, true), (84, false)]
  , [(1, true), (47, true), (48, true), (59, true), (67, true), (75, true), (89, false)]
  , [(1, false), (7, false), (10, false), (27, true), (59, true), (62, true), (92, false)]
  , [(1, true), (7, true), (15, true), (42, true), (47, false), (68, false), (70, true), (78, false)]
  , [(1, true), (13, true), (17, true), (47, true), (48, true), (75, false)]
  , [(1, true), (13, false), (47, true), (48, true), (68, true), (75, false), (77, false)]
  , [(1, true), (7, false), (15, true), (42, true), (47, false), (68, false), (70, true), (78, false), (83, false)]
  , [(1, false), (7, false), (10, false), (27, false), (39, true), (48, true), (59, true), (70, true)]
  , [(1, true), (13, false), (47, true), (48, false), (58, true), (82, true)]
  , [(1, true), (11, true), (14, false), (41, true), (47, false), (59, false), (68, true)]
  , [(1, false), (7, false), (10, false), (27, true), (59, true), (62, false)]
  , [(1, false), (10, true), (46, false), (57, true), (58, true), (82, true), (84, true)]
  , [(1, true), (38, true), (41, false), (47, false), (68, true)]
  , [(1, false), (10, true), (34, false), (46, false), (58, false), (65, false), (66, false)]
  , [(1, true), (6, false), (11, false), (14, false), (41, true), (47, false), (59, false), (68, true), (78, false)]
  , [(1, false), (6, false), (7, true), (10, false), (15, true), (32, false), (68, false)]
  , [(1, false), (6, false), (7, true), (10, false), (15, true), (32, true), (68, false)]
  , [(1, false), (5, true), (6, false), (7, true), (10, false), (15, true), (68, true)]
  , [(1, true), (14, false), (38, false), (41, true), (47, false), (59, true), (68, true)]
  , [(1, true), (3, true), (13, true), (30, true), (47, true), (48, false), (51, false), (75, true)]
  , [(1, false), (10, true), (58, true), (76, true), (78, true), (82, false)]
  , [(1, true), (11, false), (14, false), (41, true), (47, false), (59, false), (68, true), (78, true)]
  , [(1, false), (10, true), (31, true), (34, true), (43, false), (46, true), (47, true), (58, false)]
  , [(1, true), (13, true), (17, false), (37, false), (42, false), (47, true), (48, true), (51, true), (75, false)]
  , [(1, false), (10, true), (34, false), (46, false), (58, false), (65, true), (66, false)]
  , [(1, true), (13, true), (17, false), (23, false), (37, false), (42, true), (47, true), (48, true), (51, true), (75, false)]
  , [(1, false), (7, true), (10, false), (15, false), (26, false), (27, false), (65, true), (69, false)]
  , [(1, true), (21, true), (40, false), (42, false), (47, false), (68, false)]
  , [(1, false), (6, true), (7, true), (10, false), (15, true)]
  , [(1, true), (15, true), (36, false), (42, true), (47, false), (68, false), (78, true)]
  , [(1, true), (4, true), (13, false), (47, true), (48, true), (75, false), (77, true)]
  , [(1, false), (5, false), (6, false), (7, true), (8, false), (10, false), (15, true), (68, true)]
  , [(1, true), (8, false), (15, true), (23, true), (36, true), (42, true), (47, false), (68, false), (78, true)]
  , [(1, true), (13, false), (41, false), (47, true), (48, false), (58, false)]
  , [(1, true), (13, true), (17, false), (37, false), (47, true), (48, true), (51, false), (75, false)]
  , [(1, true), (8, false), (15, true), (23, false), (36, true), (42, true), (47, false), (68, false), (78, true)]
  , [(1, true), (3, true), (13, true), (30, false), (47, true), (48, false), (51, false), (75, true)]
  , [(1, true), (13, false), (41, true), (47, true), (48, false), (58, false)]
  , [(1, true), (3, false), (13, true), (47, true), (48, false), (51, false)]
  , [(1, false), (10, true), (34, false), (46, true), (56, false), (58, false), (66, false)]
  , [(1, false), (10, true), (17, false), (46, true), (55, true), (58, true), (82, true)]
  , [(1, false), (10, true), (17, false), (46, true), (55, false), (58, true), (82, true)]
  , [(1, false), (7, false), (10, false), (31, true), (59, false), (61, false), (78, false)]
  , [(1, false), (10, true), (17, true), (46, true), (58, true), (82, true)]
  , [(1, true), (14, false), (38, true), (41, true), (47, false), (57, false), (59, true), (68, true)]
  , [(1, false), (7, false), (10, false), (27, false), (39, false), (48, true), (59, true), (70, true)]
  , [(1, true), (13, false), (47, true), (48, true), (68, false), (75, false), (77, false)]
  , [(1, true), (7, false), (15, true), (42, true), (47, false), (68, false), (70, true), (78, false), (83, true)]
  , [(1, false), (10, true), (34, false), (46, true), (56, true), (58, false), (66, false)]
  , [(1, false), (7, false), (10, false), (31, true), (49, false), (59, false), (78, true)]
  , [(1, false), (10, true), (30, false), (33, true), (46, false), (49, false), (58, true), (82, true), (84, false)]
  , [(1, true), (11, true), (38, false), (41, false), (47, false), (52, false), (60, false), (68, true)]
  , [(1, true), (5, true), (11, true), (24, false), (38, false), (41, false), (47, false), (60, true), (68, true)]
  , [(1, false), (10, true), (31, true), (34, true), (43, false), (46, false), (47, true), (58, false)]
  , [(1, true), (15, true), (42, true), (47, false), (68, false), (70, false), (78, false), (92, false)]
  , [(1, true), (47, true), (48, true), (59, false), (75, true), (84, false), (89, false)]
  , [(1, false), (6, true), (10, true), (31, false), (34, true), (43, false), (47, true), (58, false)]
  , [(1, false), (7, true), (10, false), (15, false), (65, false), (69, false), (78, true)]
  , [(1, false), (10, true), (24, false), (46, false), (49, true), (58, true), (82, true), (84, false)]
  , [(1, true), (3, true), (13, true), (47, true), (48, false), (51, false), (75, false)]
  , [(1, false), (7, true), (10, false), (15, false), (26, true), (65, true), (69, false)]
  , [(1, false), (10, true), (34, false), (51, false), (58, false), (66, true), (72, false)]
  , [(1, false), (7, false), (10, false), (27, false), (39, false), (48, false), (59, true), (70, true)]
  , [(1, true), (13, true), (17, false), (37, true), (39, true), (47, true), (48, true), (75, false)]
  , [(1, false), (7, true), (10, false), (15, false), (26, false), (27, true), (65, true), (69, false)]
  , [(1, true), (14, false), (38, true), (41, true), (47, false), (57, true), (59, true), (68, true)]
  , [(1, false), (10, true), (18, false), (58, true), (69, false), (78, false), (82, false)]
  , [(1, true), (47, true), (48, true), (75, true), (89, true)]
  , [(1, false), (5, false), (6, false), (7, true), (8, true), (9, false), (10, false), (15, true), (68, true)]
  , [(1, false), (10, true), (24, true), (46, false), (49, true), (58, true), (82, true), (84, false)]
  , [(1, false), (5, false), (6, false), (7, true), (8, true), (9, true), (10, false), (15, true), (68, true)]
  , [(1, false), (10, true), (16, false), (34, true), (43, true), (58, false)]
  , [(1, false), (10, true), (18, true), (58, true), (69, false), (78, false), (82, false)]
  , [(1, false), (10, true), (39, true), (58, true), (76, false), (78, true), (82, false)]
  , [(1, true), (14, true), (17, true), (41, true), (47, false), (68, true)]
  , [(1, false), (7, false), (10, false), (31, true), (49, true), (59, false), (78, true)]
  , [(1, true), (40, true), (42, false), (47, false), (68, false)]
  , [(1, false), (10, true), (34, false), (58, false), (66, true), (72, true), (80, true)]
  , [(1, false), (10, true), (22, true), (34, true), (43, false), (47, false), (58, false)]
  , [(1, false), (7, false), (10, false), (27, true), (59, true), (62, true), (92, true)]
  , [(1, true), (8, true), (15, true), (36, true), (42, true), (47, false), (68, false), (78, true)]
  , [(1, true), (21, false), (40, false), (42, false), (47, false), (68, false), (75, true)]
  , [(1, true), (13, true), (17, false), (37, true), (39, false), (47, true), (48, true), (75, false)]
  , [(1, true), (47, true), (48, true), (59, false), (75, true), (84, true), (89, false), (90, false)]
  , [(1, true), (14, true), (17, false), (41, true), (47, false), (68, true)]
  , [(1, false), (10, true), (30, false), (33, false), (46, false), (49, false), (58, true), (66, false), (82, true), (84, false)]
  , [(1, true), (47, true), (48, true), (59, true), (67, false), (75, true), (89, false)]
  , [(1, true), (15, false), (23, true), (42, true), (47, false), (68, false)]
  , [(1, false), (6, false), (10, true), (31, false), (34, true), (43, false), (47, true), (58, false)]
  , [(1, true), (13, false), (47, true), (48, false), (58, true), (82, false)]
  , [(1, true), (15, false), (23, false), (42, true), (47, false), (68, false)]
  , [(1, false), (10, true), (16, true), (34, true), (43, true), (58, false)]
  , [(1, true), (11, false), (38, false), (41, false), (47, false), (68, true)]
  , [(1, true), (5, false), (11, true), (24, false), (38, false), (41, false), (47, false), (60, true), (68, true)]
  , [(1, false), (10, true), (22, false), (34, true), (43, false), (47, false), (58, false)]
  , [(1, false), (10, true), (39, false), (58, true), (76, false), (78, true), (82, false)]
  , [(1, false), (10, true), (34, false), (58, false), (66, true), (72, true), (80, false)]
  , [(1, false), (7, true), (10, false), (15, false), (69, true)]
  , [(1, false), (7, true), (10, false), (15, false), (65, false), (69, false), (78, false)]
  , [(1, true), (21, false), (40, false), (42, false), (47, false), (68, false), (75, false), (81, true)]
  , [(1, true), (11, true), (24, true), (38, false), (41, false), (47, false), (60, true), (68, true)]
  , [(1, true), (6, true), (11, false), (14, false), (41, true), (47, false), (59, false), (68, true), (78, false)]
  , [(1, true), (21, false), (40, false), (42, false), (47, false), (68, false), (75, false), (81, false)]
  , [(1, false), (7, false), (10, false), (27, false), (59, true), (70, false)]
  , [(1, false), (7, false), (10, false), (31, true), (59, false), (61, true), (78, false)]
  , [(1, true), (15, true), (42, true), (47, false), (68, false), (70, false), (78, false), (92, true)]
  , [(1, false), (10, true), (30, false), (33, false), (46, false), (49, false), (58, true), (66, true), (82, true), (84, false)]
  , [(1, false), (10, true), (46, false), (57, false), (58, true), (82, true), (84, true)]
  , [(1, false), (7, false), (10, false), (27, false), (39, true), (48, false), (59, true), (70, true)]
  , [(1, false), (7, false), (10, false), (31, false), (59, false)]
  , [(1, true), (11, true), (38, false), (41, false), (47, false), (52, true), (60, false), (68, true)]
  , [(1, false), (10, true), (34, false), (51, true), (58, false), (66, true), (72, false)]
  , [(1, true), (4, false), (13, false), (47, true), (48, true), (75, false), (77, true)]
  , [(1, true), (13, true), (17, false), (23, true), (37, false), (42, true), (47, true), (48, true), (51, true), (75, false)]
  ]

/-- The LRAT refutation: derived clause + database-index hints per step. -/
def steps : List RStep :=
  [ ⟨[(39, false), (59, true), (7, false), (10, false), (27, false), (1, false)], [106, 48, 65]⟩
  , ⟨[(59, true), (27, false), (7, false), (10, false), (1, false)], [106, 117, 10, 111]⟩
  , ⟨[(78, false), (59, false), (7, false), (10, false), (1, false)], [112, 45, 107]⟩
  , ⟨[(59, false), (10, false), (7, false), (1, false)], [112, 119, 52, 78]⟩
  , ⟨[(10, false), (7, false), (1, false)], [120, 118, 13, 5, 82]⟩
  , ⟨[(66, true), (58, false), (10, true), (34, false), (1, false), (51, false)], [64, 80, 99]⟩
  , ⟨[(58, false), (51, false), (10, true), (34, false), (46, false), (1, false)], [122, 16, 27]⟩
  , ⟨[(82, true), (57, false), (10, true), (46, false), (58, true), (1, false), (49, true), (24, false)], [61, 110]⟩
  , ⟨[(82, false), (58, true), (10, true), (39, true), (78, true), (1, false)], [23, 76]⟩
  , ⟨[(58, true), (46, false), (10, true), (1, false), (49, true), (24, false), (39, true), (78, true)], [125, 61, 14, 124]⟩
  , ⟨[(66, true), (58, false), (10, true), (34, false), (1, false), (51, true)], [114, 80, 99]⟩
  , ⟨[(46, false), (34, false), (10, true), (1, false), (49, true), (24, false), (39, true), (78, true)], [126, 123, 127, 16, 27]⟩
  , ⟨[(58, false), (51, true), (10, true), (46, true), (34, false), (1, false)], [127, 42, 51]⟩
  , ⟨[(58, true), (46, true), (10, true), (17, false), (1, false), (39, true), (78, true)], [125, 43, 44]⟩
  , ⟨[(34, false), (24, false), (10, true), (17, false), (39, true), (78, true), (49, true), (1, false)], [128, 130, 129, 122, 42, 51]⟩
  , ⟨[(46, true), (34, true), (10, true), (22, false), (1, false), (31, true), (16, false), (17, false), (39, true), (78, true)], [130, 74, 25, 97]⟩
  , ⟨[(24, false), (22, false), (10, true), (1, false), (31, true), (16, false), (49, true), (39, true), (78, true), (17, false)], [131, 132, 126, 74, 56, 97]⟩
  , ⟨[(68, false), (40, false), (21, false), (47, false), (1, true), (15, false), (23, false)], [93, 84, 102, 105]⟩
  , ⟨[(68, true), (38, false), (11, false), (47, false), (1, true), (14, false), (59, true)], [21, 95]⟩
  , ⟨[(68, false), (23, false), (47, false), (21, false), (15, false), (1, true)], [93, 134, 79]⟩
  , ⟨[(68, true), (14, false), (1, true), (47, false), (57, false), (59, true), (11, false)], [135, 15, 47]⟩
  , ⟨[(21, false), (15, false), (47, false), (68, false), (1, true)], [136, 90, 79, 84, 102, 105]⟩
  , ⟨[(42, false), (21, true), (1, true), (47, false), (68, false)], [79, 30]⟩
  , ⟨[(15, false), (68, false), (47, false), (1, true)], [138, 139, 90, 93]⟩
  , ⟨[(42, true), (68, false), (78, true), (47, false), (8, false), (1, true)], [140, 32, 35, 38]⟩
  , ⟨[(68, false), (8, false), (47, false), (78, true), (1, true)], [141, 79, 139, 84, 102, 105]⟩
  , ⟨[(11, false), (68, true), (47, false), (1, true), (17, false), (57, false), (59, true)], [137, 87, 15, 95]⟩
  , ⟨[(41, false), (68, true), (24, false), (47, false), (5, false), (1, true), (11, true)], [15, 96, 54, 113]⟩
  , ⟨[(68, true), (5, false), (47, false), (57, false), (59, true), (17, false), (24, false), (1, true)], [143, 144, 87, 21, 47]⟩
  , ⟨[(42, false), (21, false), (1, true), (47, false), (68, false)], [79, 84, 102, 105]⟩
  , ⟨[(42, true), (68, false), (78, true), (47, false), (1, true)], [142, 140, 32, 83]⟩
  , ⟨[(68, false), (47, false), (1, true), (78, true)], [147, 139, 146]⟩
  , ⟨[(38, true), (14, false), (68, true), (47, false), (59, true), (57, false), (1, true)], [15, 47]⟩
  , ⟨[(14, false), (57, false), (24, false), (68, true), (47, false), (59, true), (1, true), (11, true), (5, true)], [149, 21, 55, 54, 113]⟩
  , ⟨[(57, false), (59, true), (24, false), (17, false), (68, true), (47, false), (1, true)], [143, 145, 150, 87, 15, 55, 54, 113]⟩
  , ⟨[(16, false), (31, true), (10, true), (34, true), (47, false), (58, false), (24, false), (1, false), (49, true), (39, true), (78, true), (17, false)], [74, 133, 81]⟩
  , ⟨[(43, false), (58, false), (10, true), (34, true), (47, false), (1, false)], [97, 81]⟩
  , ⟨[(58, false), (34, true), (10, true), (1, false), (47, false)], [153, 74, 94]⟩
  , ⟨[(39, true), (49, true), (1, false), (58, true), (24, false), (10, true), (78, true), (17, false)], [130, 126]⟩
  , ⟨[(82, false), (39, false), (10, true), (58, true), (78, true), (1, false)], [23, 98]⟩
  , ⟨[(49, true), (58, true), (10, true), (17, false), (1, false), (57, false), (24, false), (78, true)], [155, 156, 124, 43, 44]⟩
  , ⟨[(46, true), (82, true), (10, true), (17, false), (58, true), (1, false)], [43, 44]⟩
  , ⟨[(82, true), (58, true), (57, false), (17, false), (10, true), (1, false), (49, false)], [158, 110, 3, 53, 88, 109]⟩
  , ⟨[(58, true), (10, true), (1, false), (78, true), (57, false), (17, false), (24, false)], [157, 159, 23, 125, 98]⟩
  , ⟨[(46, false), (10, true), (1, false), (58, false), (34, false)], [123, 127, 16, 27]⟩
  , ⟨[(10, true), (24, false), (47, false), (78, true), (57, false), (17, false), (1, false)], [160, 154, 161, 129, 122, 42, 51]⟩
  , ⟨[(15, true), (10, false), (68, false), (1, false)], [121, 31, 18, 19]⟩
  , ⟨[(10, false), (78, true), (1, false), (68, false)], [121, 163, 100, 60, 63, 29, 67]⟩
  , ⟨[(58, false), (34, false), (10, true), (1, false)], [161, 129, 122, 42, 51]⟩
  , ⟨[(46, true), (58, true), (10, true), (78, true), (17, false), (1, false)], [130, 158, 156]⟩
  , ⟨[(82, true), (58, true), (57, false), (10, true), (24, true), (17, false), (1, false), (46, false)], [159, 72, 110]⟩
  , ⟨[(58, true), (17, false), (57, false), (10, true), (78, true), (1, false), (24, true)], [166, 167, 23, 125, 98]⟩
  , ⟨[(58, false), (10, true), (1, false), (47, false)], [154, 165]⟩
  , ⟨[(15, false), (78, true), (10, false), (1, false)], [121, 100, 60, 63, 29, 67]⟩
  , ⟨[(78, true), (10, false), (1, false)], [121, 164, 170, 31, 20, 34, 71, 73]⟩
  , ⟨[(15, true), (10, false), (1, false)], [121, 31, 163, 20, 34, 71, 73]⟩
  , ⟨[(10, false), (1, false)], [121, 171, 172, 100, 101, 63, 29, 67]⟩
  , ⟨[(82, false), (58, true), (78, false), (69, false), (1, false)], [173, 69, 75]⟩
  , ⟨[(24, true), (17, false), (82, true), (58, true), (1, false)], [173, 158, 167, 14, 72, 3, 53, 88, 109]⟩
  , ⟨[(84, false), (17, false), (82, true), (58, true), (1, false)], [173, 175, 158, 61, 3, 53, 88, 109]⟩
  , ⟨[(17, false), (58, true), (1, false), (82, true)], [173, 158, 176, 110, 14]⟩
  , ⟨[(49, false), (84, false), (82, true), (58, true), (1, false)], [173, 177, 46, 3, 53, 88, 109]⟩
  , ⟨[(84, false), (58, true), (1, false), (82, true)], [173, 177, 46, 178, 61, 72]⟩
  , ⟨[(58, true), (69, false), (78, false), (1, false)], [173, 174, 177, 46, 179, 110, 14]⟩
  , ⟨[(43, false), (6, false), (58, false), (46, false), (1, false)], [173, 169, 165, 56, 91]⟩
  , ⟨[(43, true), (58, false), (1, false)], [173, 165, 74, 94]⟩
  , ⟨[(46, false), (58, false), (1, false)], [173, 182, 169, 165, 56, 181, 59]⟩
  , ⟨[(58, false), (1, false)], [173, 165, 169, 182, 183, 25, 91, 59]⟩
  , ⟨[(82, true), (1, false)], [184, 173, 177, 179, 46, 110, 14]⟩
  , ⟨[(78, false), (1, false)], [185, 184, 173, 180, 2]⟩
  , ⟨[(1, false)], [173, 184, 185, 186, 23, 125, 98]⟩
  , ⟨[(48, false), (51, false), (47, true), (3, false), (58, true), (82, false)], [187, 92, 41]⟩
  , ⟨[(59, true), (75, true), (48, true), (47, true)], [187, 70, 4, 89]⟩
  , ⟨[(75, true), (48, true), (47, true), (84, true)], [187, 70, 189, 0, 86]⟩
  , ⟨[(48, true), (68, true), (47, true), (17, true), (84, true)], [187, 190, 7, 8, 33, 115]⟩
  , ⟨[(48, false), (47, true), (3, false), (58, true), (82, false)], [187, 92, 188, 1]⟩
  , ⟨[(47, true), (17, true), (84, true), (3, false), (58, true), (82, false)], [187, 192, 190, 191, 7, 49, 33, 115]⟩
  , ⟨[(41, false), (24, true), (47, false), (68, true)], [187, 15, 95, 103, 54, 113]⟩
  , ⟨[(41, true), (59, false), (47, false), (17, true), (78, true)], [187, 148, 77, 12, 24]⟩
  , ⟨[(41, false), (68, true), (47, false)], [187, 15, 95, 194, 144, 55, 54, 113]⟩
  , ⟨[(17, true), (84, true), (78, true), (57, true), (3, false), (58, true), (82, false)], [187, 193, 148, 196, 77, 195, 21, 68]⟩
  , ⟨[(59, true), (47, false), (57, true), (68, true), (14, false)], [187, 196, 68, 21]⟩
  , ⟨[(47, false), (17, false), (57, true), (78, true)], [187, 148, 196, 87, 198, 12, 24]⟩
  , ⟨[(13, false), (68, true), (48, true), (47, true), (75, false)], [187, 8, 33, 115]⟩
  , ⟨[(13, true), (17, false), (39, false), (48, true), (47, true), (75, false)], [187, 85, 37, 26, 116, 28]⟩
  , ⟨[(84, true), (57, true), (3, false), (58, true), (82, false), (39, false), (78, true)], [187, 197, 199, 192, 190, 201, 200, 49, 33, 115]⟩
  , ⟨[(13, false), (48, true), (68, false), (47, true), (75, false)], [187, 49, 33, 115]⟩
  , ⟨[(48, true), (84, true), (47, true), (68, false), (17, false)], [187, 190, 203, 201, 66, 37, 26, 116, 28]⟩
  , ⟨[(48, false), (82, false), (47, true), (58, true), (3, true)], [187, 92, 1, 62, 22, 39]⟩
  , ⟨[(75, true), (48, true), (47, true), (84, false)], [187, 70, 58, 189]⟩
  , ⟨[(48, true), (68, false), (47, true), (17, false)], [187, 204, 206, 203, 201, 66, 37, 26, 116, 28]⟩
  , ⟨[(13, true), (75, false), (47, true), (48, false), (3, true)], [187, 1, 62]⟩
  , ⟨[(58, true), (13, false), (47, true), (48, false), (3, true)], [187, 205, 11]⟩
  , ⟨[(13, false), (48, false), (47, true), (3, true)], [187, 209, 36, 40]⟩
  , ⟨[(48, false), (47, true), (3, true)], [187, 210, 1, 208, 22, 39]⟩
  , ⟨[(75, true), (48, true), (47, true)], [190, 206]⟩
  , ⟨[(68, false), (48, true), (47, true)], [187, 212, 207, 203, 7]⟩
  , ⟨[(47, true), (3, true)], [187, 211, 212, 213, 200, 7, 201, 66, 37, 26, 116, 28]⟩
  , ⟨[(59, false), (14, false), (68, true), (47, false)], [187, 196, 12, 24, 17, 104]⟩
  , ⟨[(14, false), (68, true), (47, false)], [187, 196, 215, 21, 198, 47]⟩
  , ⟨[(68, true), (47, false)], [187, 196, 216, 77, 87]⟩
  , ⟨[(70, false), (42, true), (47, false)], [187, 217, 148, 140, 57, 108]⟩
  , ⟨[(42, true), (47, false)], [187, 217, 148, 140, 218, 6, 9, 50]⟩
  , ⟨[(47, false)], [187, 217, 219, 139, 146]⟩
  , ⟨[(3, true)], [220, 214]⟩
  , ⟨[(48, true)], [187, 220, 221, 212, 213, 200, 7, 201, 66, 37, 26, 28, 116]⟩
  , ⟨[(13, false), (41, true)], [187, 220, 222, 40, 11, 92]⟩
  , ⟨[(13, true)], [187, 220, 221, 222, 1, 41]⟩
  , ⟨[(41, true)], [224, 223]⟩
  , ⟨[(58, false)], [225, 187, 220, 222, 224, 36]⟩
  , ⟨[(82, true)], [226, 187, 220, 224, 222, 11]⟩
  , ⟨[], [187, 220, 222, 224, 225, 226, 227, 92]⟩
  ]

set_option maxHeartbeats 40000000 in
/-- KERNEL replay of the refutation — plain `decide`, no `native_decide`. -/
theorem check_ok : checkRefutation F steps = true := by decide

/-- The recovered CNF is unsatisfiable (kernel-checked LRAT replay +
`rup_sound` composition). -/
theorem instance_unsat : ¬ ∃ σ, satFormula σ F :=
  RupChecker.checkRefutation_sound F steps check_ok

/-- The gadget's variable set: DIMACS variables `1..92`. -/
def s : Finset ℕ := Finset.Icc 1 92

set_option maxHeartbeats 4000000 in
/-- END-TO-END VERDICT: no point of the `[0,1]` box reaches the sat_relu
gadget's unsafe region `{Y₀ ≥ 1 ∧ Y₁ ≤ 0}` — real-arithmetic SAFE. -/
theorem instance_safe :
    ∀ x : ℕ → ℝ, (∀ j ∈ s, 0 ≤ x j ∧ x j ≤ 1) →
      ¬ (1 ≤ SatRelu.Y0 (SatReluVerdict.clausesOf F) x ∧
         SatRelu.Y1 s x ≤ 0) :=
  SatReluVerdict.safe_of_unsat F s (by decide) instance_unsat

end SatReluDemo_v92c117

end Crownproof

/-! ## Trust-base check -/

#print axioms Crownproof.SatReluDemo_v92c117.check_ok
#print axioms Crownproof.SatReluDemo_v92c117.instance_unsat
#print axioms Crownproof.SatReluDemo_v92c117.instance_safe
