/-
`SatReluSweepAll` — one lake target that kernel-checks the ENTIRE sat_relu
UNSAT sweep: all 49 unique `unsat_*` instances of the VNN-COMP'25 `sat_relu`
benchmark (the benchmark's `instances.csv` lists 50 unsat rows, but
`unsat_v6_c30` appears twice — 49 unique instances).

* 45 instances live under `NyProof/SatReluSweep/` (machine-generated by
  `ny-cert`'s `lrat_to_lean --fast`; see
  `crates/ny-cert/scripts/certify_sat_relu_sweep.sh` for the full
  artifact -> Lean -> kernel pipeline).
* 4 instances landed earlier as the `SatReluDemo_*` modules and are imported
  here unchanged.

Every instance certifies the SAME shape of end-to-end theorem
(`<ns>.instance_safe`): no point of the `[0,1]^n` input box reaches the
sat_relu gadget's unsafe region `{Y0 >= 1 /\ Y1 <= 0}` — real-arithmetic
SAFE, obtained by composing a kernel-replayed LRAT refutation of the
recovered CNF (`checkRefutation[Fast]`, plain `decide`, no `native_decide`)
with `SatReluVerdict.safe_of_unsat`.

`lake build NyProof.SatReluSweepAll` therefore checks the whole sweep;
the `#print axioms` manifest below must show ONLY
`[propext, Classical.choice, Quot.sound]` for every entry.
-/
import NyProof.SatReluSweep.V6C30
import NyProof.SatReluSweep.V9C9
import NyProof.SatReluSweep.V9C14
import NyProof.SatReluDemo_v10c26
import NyProof.SatReluSweep.V14C57
import NyProof.SatReluSweep.V16C39
import NyProof.SatReluSweep.V18C88
import NyProof.SatReluSweep.V20C40
import NyProof.SatReluSweep.V24C66
import NyProof.SatReluSweep.V25C40
import NyProof.SatReluSweep.V25C45
import NyProof.SatReluSweep.V26C84
import NyProof.SatReluSweep.V30C38
import NyProof.SatReluSweep.V30C44
import NyProof.SatReluSweep.V33C140
import NyProof.SatReluSweep.V34C98
import NyProof.SatReluSweep.V37C63
import NyProof.SatReluSweep.V38C132
import NyProof.SatReluSweep.V39C77
import NyProof.SatReluSweep.V40C142
import NyProof.SatReluSweep.V44C52
import NyProof.SatReluSweep.V46C142
import NyProof.SatReluSweep.V51C255
import NyProof.SatReluSweep.V54C125
import NyProof.SatReluSweep.V56C239
import NyProof.SatReluSweep.V58C75
import NyProof.SatReluSweep.V63C267
import NyProof.SatReluSweep.V63C286
import NyProof.SatReluSweep.V64C234
import NyProof.SatReluSweep.V65C187
import NyProof.SatReluSweep.V67C154
import NyProof.SatReluSweep.V70C178
import NyProof.SatReluSweep.V73C156
import NyProof.SatReluSweep.V75C99
import NyProof.SatReluSweep.V82C130
import NyProof.SatReluSweep.V83C328
import NyProof.SatReluSweep.V85C186
import NyProof.SatReluSweep.V85C207
import NyProof.SatReluSweep.V87C243
import NyProof.SatReluSweep.V90C111
import NyProof.SatReluSweep.V90C449
import NyProof.SatReluSweep.V91C217
import NyProof.SatReluDemo_v92c117
import NyProof.SatReluSweep.V92C180
import NyProof.SatReluSweep.V94C313
import NyProof.SatReluSweep.V94C377
import NyProof.SatReluSweep.V95C275
import NyProof.SatReluDemo_v99c485
import NyProof.SatReluDemo_v100c373

/-! ## Sweep manifest — trust base of every end-to-end verdict -/

#print axioms Crownproof.SatReluSweep_v6c30.instance_safe
#print axioms Crownproof.SatReluSweep_v9c9.instance_safe
#print axioms Crownproof.SatReluSweep_v9c14.instance_safe
#print axioms Crownproof.SatReluDemo_v10c26.instance_safe
#print axioms Crownproof.SatReluSweep_v14c57.instance_safe
#print axioms Crownproof.SatReluSweep_v16c39.instance_safe
#print axioms Crownproof.SatReluSweep_v18c88.instance_safe
#print axioms Crownproof.SatReluSweep_v20c40.instance_safe
#print axioms Crownproof.SatReluSweep_v24c66.instance_safe
#print axioms Crownproof.SatReluSweep_v25c40.instance_safe
#print axioms Crownproof.SatReluSweep_v25c45.instance_safe
#print axioms Crownproof.SatReluSweep_v26c84.instance_safe
#print axioms Crownproof.SatReluSweep_v30c38.instance_safe
#print axioms Crownproof.SatReluSweep_v30c44.instance_safe
#print axioms Crownproof.SatReluSweep_v33c140.instance_safe
#print axioms Crownproof.SatReluSweep_v34c98.instance_safe
#print axioms Crownproof.SatReluSweep_v37c63.instance_safe
#print axioms Crownproof.SatReluSweep_v38c132.instance_safe
#print axioms Crownproof.SatReluSweep_v39c77.instance_safe
#print axioms Crownproof.SatReluSweep_v40c142.instance_safe
#print axioms Crownproof.SatReluSweep_v44c52.instance_safe
#print axioms Crownproof.SatReluSweep_v46c142.instance_safe
#print axioms Crownproof.SatReluSweep_v51c255.instance_safe
#print axioms Crownproof.SatReluSweep_v54c125.instance_safe
#print axioms Crownproof.SatReluSweep_v56c239.instance_safe
#print axioms Crownproof.SatReluSweep_v58c75.instance_safe
#print axioms Crownproof.SatReluSweep_v63c267.instance_safe
#print axioms Crownproof.SatReluSweep_v63c286.instance_safe
#print axioms Crownproof.SatReluSweep_v64c234.instance_safe
#print axioms Crownproof.SatReluSweep_v65c187.instance_safe
#print axioms Crownproof.SatReluSweep_v67c154.instance_safe
#print axioms Crownproof.SatReluSweep_v70c178.instance_safe
#print axioms Crownproof.SatReluSweep_v73c156.instance_safe
#print axioms Crownproof.SatReluSweep_v75c99.instance_safe
#print axioms Crownproof.SatReluSweep_v82c130.instance_safe
#print axioms Crownproof.SatReluSweep_v83c328.instance_safe
#print axioms Crownproof.SatReluSweep_v85c186.instance_safe
#print axioms Crownproof.SatReluSweep_v85c207.instance_safe
#print axioms Crownproof.SatReluSweep_v87c243.instance_safe
#print axioms Crownproof.SatReluSweep_v90c111.instance_safe
#print axioms Crownproof.SatReluSweep_v90c449.instance_safe
#print axioms Crownproof.SatReluSweep_v91c217.instance_safe
#print axioms Crownproof.SatReluDemo_v92c117.instance_safe
#print axioms Crownproof.SatReluSweep_v92c180.instance_safe
#print axioms Crownproof.SatReluSweep_v94c313.instance_safe
#print axioms Crownproof.SatReluSweep_v94c377.instance_safe
#print axioms Crownproof.SatReluSweep_v95c275.instance_safe
#print axioms Crownproof.SatReluDemo_v99c485.instance_safe
#print axioms Crownproof.SatReluDemo_v100c373.instance_safe
