/-
MACHINE-GENERATED by `ny-cert`'s `lrat_to_lean` — do not edit.

sat_relu Route A instance transcript:
* DIMACS source : inst.cnf  (p cnf 25 45)
* LRAT source   : inst.lrat  (86 addition steps kept)

The kernel replays the full LRAT refutation with PLAIN `decide`
(no `native_decide`, no extra axioms) through
`RupCheckerFast.checkRefutationFast`, then composes
`checkRefutationFast_sound` (CNF-unsat) with
`SatReluVerdict.safe_of_unsat` (gadget real-arithmetic safety).
-/
import NyProof.SatReluVerdict
import NyProof.RupCheckerFast

namespace Crownproof

namespace SatReluSweep_v25c45

open RupImport.RUP RupChecker

set_option maxRecDepth 65536

/-- The recovered DIMACS formula, literal-for-literal. -/
def F : Formula :=
  [ [(1, true), (2, true), (3, true), (6, true), (13, true)]
  , [(1, false), (2, false), (4, true), (11, true), (14, false), (16, true), (18, true), (20, false), (24, true)]
  , [(1, false), (2, false), (4, true), (14, false), (16, true), (18, true), (20, true), (24, true)]
  , [(1, true), (6, false), (9, false), (20, true), (22, true), (23, false), (25, false)]
  , [(1, false), (2, false), (4, true), (11, false), (14, false), (18, false), (24, true)]
  , [(1, false), (9, false), (14, true), (18, false), (24, true)]
  , [(1, false), (2, true), (4, true), (14, false), (17, false), (24, true)]
  , [(1, false), (2, true), (4, true), (14, false), (16, true), (19, true), (24, false)]
  , [(1, true), (6, false), (9, false), (20, false), (22, true), (23, false), (25, false)]
  , [(1, false), (14, true), (15, false), (18, true)]
  , [(1, false), (4, true), (13, false), (14, false), (16, false), (17, true), (24, false)]
  , [(1, true), (6, false), (8, false), (9, false), (22, true), (23, true)]
  , [(1, false), (2, false), (4, true), (11, false), (14, false), (16, true), (18, true), (20, false), (24, true)]
  , [(1, false), (2, true), (4, true), (13, false), (14, false), (17, true), (24, true)]
  , [(1, true), (6, false), (10, false), (20, true), (22, false)]
  , [(1, false), (4, false), (14, false), (15, false), (22, false)]
  , [(1, true), (3, false), (6, false), (9, true), (11, true), (22, true)]
  , [(1, false), (14, true), (15, true), (18, true)]
  , [(1, false), (2, false), (4, true), (14, false), (16, true), (19, true), (24, false)]
  , [(1, false), (2, true), (9, false), (14, true), (18, false), (24, false)]
  , [(1, false), (2, false), (4, true), (14, false), (16, false), (18, true), (24, true)]
  , [(1, true), (6, false), (10, false), (20, false), (22, false)]
  , [(1, false), (4, true), (14, false), (16, false), (17, false), (24, false)]
  , [(1, false), (4, false), (13, false), (14, false), (15, true), (22, false)]
  , [(1, true), (2, true), (3, true), (6, true), (13, false)]
  , [(1, false), (4, true), (14, false), (16, true), (19, false), (24, false)]
  , [(1, false), (4, false), (13, true), (14, false), (15, true), (17, true), (22, false)]
  , [(1, true), (3, false), (6, false), (9, true), (11, false), (17, true), (22, true)]
  , [(1, false), (2, false), (9, false), (14, true), (18, false), (24, false)]
  , [(1, true), (2, false), (6, true)]
  , [(1, false), (4, true), (13, true), (14, false), (16, false), (17, true), (24, false)]
  , [(1, false), (4, false), (14, false), (17, true), (22, true)]
  , [(1, false), (9, true), (14, true), (15, false), (18, false)]
  , [(1, false), (4, false), (13, true), (14, false), (15, true), (17, false), (22, false)]
  , [(1, true), (6, false), (9, false), (15, false), (22, true), (23, false), (25, true)]
  , [(1, false), (2, true), (4, true), (13, true), (14, false), (17, true), (24, true)]
  , [(1, true), (3, true), (6, false), (9, true), (22, true)]
  , [(1, true), (3, false), (6, false), (9, true), (11, false), (17, false), (22, true)]
  , [(1, false), (4, false), (14, false), (17, false), (22, true)]
  , [(1, false), (9, true), (14, true), (15, true), (18, false)]
  , [(1, false), (2, false), (4, true), (11, true), (14, false), (18, false), (24, true)]
  , [(1, true), (2, true), (3, false), (6, true)]
  , [(1, true), (6, false), (10, true), (22, false)]
  , [(1, true), (6, false), (9, false), (15, true), (22, true), (23, false), (25, true)]
  , [(1, true), (6, false), (8, true), (9, false), (22, true), (23, true)]
  ]

/-- The LRAT refutation: derived clause + database-index hints per step. -/
def steps : List RStep :=
  [ ⟨[(22, true), (14, false), (4, false), (1, false)], [31, 38]⟩
  , ⟨[(14, false), (13, false), (4, false), (1, false)], [45, 15, 23]⟩
  , ⟨[(18, false), (14, true), (2, false), (9, false), (1, false)], [5, 28]⟩
  , ⟨[(14, true), (9, false), (2, false), (1, false)], [47, 9, 17]⟩
  , ⟨[(14, false), (4, false), (1, false)], [45, 46, 15, 26, 33]⟩
  , ⟨[(15, true), (14, true), (1, false), (9, true)], [17, 39]⟩
  , ⟨[(14, true), (2, false), (1, false)], [48, 50, 9, 32]⟩
  , ⟨[(24, false), (17, false), (2, false), (1, false)], [51, 49, 22, 25, 18]⟩
  , ⟨[(24, true), (18, false), (2, false), (1, false)], [51, 49, 4, 40]⟩
  , ⟨[(16, true), (24, false), (2, false), (1, false)], [51, 49, 25, 18]⟩
  , ⟨[(24, false), (2, false), (1, false)], [51, 49, 52, 54, 10, 30]⟩
  , ⟨[(2, false), (1, false)], [51, 49, 55, 53, 20, 2, 1, 12]⟩
  , ⟨[(24, true), (14, false), (4, true), (1, false)], [56, 6, 13, 35]⟩
  , ⟨[(16, true), (14, false), (4, true), (1, false)], [56, 57, 25, 7]⟩
  , ⟨[(14, false), (4, true), (1, false)], [57, 58, 22, 10, 30]⟩
  , ⟨[(18, true), (14, true), (1, false)], [9, 17]⟩
  , ⟨[(22, false), (20, false), (6, false), (1, true)], [42, 21]⟩
  , ⟨[(9, true), (22, true), (6, false), (1, true), (11, false), (17, true)], [27, 36]⟩
  , ⟨[(23, false), (20, false), (15, true), (6, false), (1, true), (9, false)], [61, 43, 8]⟩
  , ⟨[(20, false), (11, false), (6, false), (15, true), (1, true), (17, true)], [61, 62, 63, 11, 44]⟩
  , ⟨[(23, false), (22, true), (15, true), (6, false), (20, true), (1, true), (9, false)], [43, 3]⟩
  , ⟨[(22, true), (11, false), (15, true), (17, true), (6, false), (1, true)], [64, 62, 65, 11, 44]⟩
  , ⟨[(11, false), (6, false), (1, true), (15, true), (17, true)], [64, 66, 42, 14]⟩
  , ⟨[(22, false), (20, true), (6, false), (1, true)], [42, 14]⟩
  , ⟨[(9, false), (20, true), (15, true), (6, false), (1, true)], [68, 65, 11, 44]⟩
  , ⟨[(20, true), (6, false), (15, true), (1, true), (11, true)], [68, 69, 16, 36]⟩
  , ⟨[(9, true), (6, false), (1, true), (11, true), (22, true)], [16, 36]⟩
  , ⟨[(6, false), (17, true), (15, true), (1, true)], [67, 70, 61, 71, 63, 11, 44]⟩
  , ⟨[(6, true), (1, true)], [29, 41, 0, 24]⟩
  , ⟨[(20, false), (3, true), (15, true), (1, true)], [73, 61, 36, 63, 11, 44]⟩
  , ⟨[(3, true), (15, true), (1, true)], [73, 74, 68, 69, 36]⟩
  , ⟨[(20, true), (15, true), (1, true)], [73, 75, 72, 68, 69, 70, 37]⟩
  , ⟨[(6, true), (2, false), (14, true)], [51, 29]⟩
  , ⟨[(6, true), (2, false), (24, false)], [55, 29]⟩
  , ⟨[(14, false), (1, false)], [49, 59]⟩
  , ⟨[(18, true), (1, false), (4, false)], [49, 60]⟩
  , ⟨[(18, true), (1, false), (4, true)], [59, 60]⟩
  , ⟨[(18, true), (1, false)], [80, 81]⟩
  , ⟨[(18, true), (1, false)], [60, 79]⟩
  , ⟨[(10, true), (22, false), (1, true)], [42, 73]⟩
  , ⟨[(15, true), (9, true), (1, false)], [50, 79]⟩
  , ⟨[(22, false), (20, false), (1, true)], [61, 73]⟩
  , ⟨[(22, false), (6, false), (1, true)], [68, 86]⟩
  , ⟨[(15, true), (17, true), (1, true)], [72, 73]⟩
  , ⟨[(9, false), (24, true), (1, false), (14, true)], [5, 82]⟩
  , ⟨[(10, false), (22, false), (1, true), (6, false)], [14, 86]⟩
  , ⟨[(10, false), (22, false), (1, true), (6, false)], [21, 90]⟩
  , ⟨[(15, false), (9, true), (1, false), (14, true)], [32, 82]⟩
  , ⟨[(9, true), (22, true), (1, true), (3, true)], [36, 73]⟩
  , ⟨[(9, true), (1, false), (14, true), (18, false)], [39, 92]⟩
  , ⟨[(9, true), (11, true), (1, true), (22, true)], [71, 73]⟩
  , ⟨[(9, true), (6, false), (1, true), (22, true), (17, true)], [62, 95]⟩
  , ⟨[(8, true), (23, true), (1, true), (22, true), (9, false)], [44, 73]⟩
  , ⟨[(17, false), (24, true), (1, false), (4, true), (14, false)], [6, 56]⟩
  , ⟨[(9, false), (1, false), (2, true), (14, true), (18, false)], [19, 89]⟩
  , ⟨[(23, false), (9, false), (15, true), (1, true), (20, false)], [63, 73]⟩
  , ⟨[(24, false), (1, false), (2, false), (9, false), (14, true)], [28, 83]⟩
  , ⟨[(23, true), (1, true), (6, false), (22, true), (9, false)], [11, 97]⟩
  , ⟨[(9, false), (15, false), (1, true), (22, true), (23, false), (25, true)], [34, 73]⟩
  , ⟨[(17, true), (13, true), (1, false), (4, true), (14, false), (24, true)], [35, 56]⟩
  , ⟨[(9, true), (11, false), (1, true), (6, false), (22, true), (3, false)], [37, 96]⟩
  , ⟨[(17, true), (13, false), (1, false), (4, true), (14, false), (24, true)], [13, 56]⟩
  , ⟨[(24, true), (11, false), (1, false), (2, false), (14, false), (4, true)], [4, 82]⟩
  , ⟨[(24, true), (11, true), (1, false), (2, false), (14, false), (4, true)], [40, 82]⟩
  , ⟨[(25, true), (23, false), (1, true), (15, true), (22, true), (9, false)], [43, 73]⟩
  , ⟨[(16, true), (19, true), (1, false), (4, true), (14, false), (24, false)], [7, 56]⟩
  , ⟨[(25, false), (23, false), (1, true), (20, false), (22, true), (9, false)], [8, 73]⟩
  , ⟨[(9, true), (22, true), (1, true), (6, false), (11, false), (17, true)], [27, 93]⟩
  , ⟨[(25, false), (23, false), (1, true), (6, false), (22, true), (9, false)], [3, 111]⟩
  , ⟨[(1, true), (6, false), (9, false), (22, true), (23, false)], [113, 73, 87, 102, 109, 103]⟩
  , ⟨[(1, true), (6, false), (9, false), (22, true)], [102, 73, 87, 114, 93, 105, 95]⟩
  , ⟨[(1, false), (14, true), (9, false), (18, false)], [99, 56, 73, 87, 115, 93, 95, 105]⟩
  , ⟨[(1, false), (14, true), (9, false)], [116, 82, 73, 87, 115, 93, 95, 105]⟩
  , ⟨[(1, true), (6, false)], [87, 73, 115, 93, 95, 105]⟩
  , ⟨[(9, false), (1, false)], [117, 79]⟩
  , ⟨[(9, true), (1, false), (14, true)], [92, 85]⟩
  , ⟨[(9, true), (1, false), (18, false)], [94, 79]⟩
  , ⟨[(15, true), (9, false), (1, true), (23, false)], [100, 76]⟩
  , ⟨[(25, false), (20, false), (1, true), (23, false), (9, false)], [111, 86]⟩
  , ⟨[(25, true), (1, true), (23, false), (22, true), (9, false)], [109, 103]⟩
  , ⟨[(1, true)], [118, 73]⟩
  , ⟨[(9, false)], [125, 119]⟩
  , ⟨[(2, false)], [125, 56]⟩
  , ⟨[(18, true)], [125, 83]⟩
  , ⟨[(14, false)], [125, 79]⟩
  , ⟨[], [125, 126, 128, 121]⟩
  ]

set_option maxHeartbeats 40000000 in
/-- KERNEL replay of the refutation — plain `decide`, no `native_decide`. -/
theorem check_ok : RupCheckerFast.checkRefutationFast F steps = true := by decide

/-- The recovered CNF is unsatisfiable (kernel-checked LRAT replay +
`rup_sound` composition). -/
theorem instance_unsat : ¬ ∃ σ, satFormula σ F :=
  RupCheckerFast.checkRefutationFast_sound F steps check_ok

/-- The gadget's variable set: DIMACS variables `1..25`. -/
def s : Finset ℕ := Finset.Icc 1 25

set_option maxHeartbeats 4000000 in
/-- END-TO-END VERDICT: no point of the `[0,1]` box reaches the sat_relu
gadget's unsafe region `{Y₀ ≥ 1 ∧ Y₁ ≤ 0}` — real-arithmetic SAFE. -/
theorem instance_safe :
    ∀ x : ℕ → ℝ, (∀ j ∈ s, 0 ≤ x j ∧ x j ≤ 1) →
      ¬ (1 ≤ SatRelu.Y0 (SatReluVerdict.clausesOf F) x ∧
         SatRelu.Y1 s x ≤ 0) :=
  SatReluVerdict.safe_of_unsat F s (by decide) instance_unsat

end SatReluSweep_v25c45

end Crownproof

/-! ## Trust-base check -/

#print axioms Crownproof.SatReluSweep_v25c45.check_ok
#print axioms Crownproof.SatReluSweep_v25c45.instance_unsat
#print axioms Crownproof.SatReluSweep_v25c45.instance_safe
