/-
MACHINE-GENERATED by `ny-cert`'s `lrat_to_lean` — do not edit.

sat_relu Route A instance transcript:
* DIMACS source : inst.cnf  (p cnf 26 84)
* LRAT source   : inst.lrat  (142 addition steps kept)

The kernel replays the full LRAT refutation with PLAIN `decide`
(no `native_decide`, no extra axioms) through
`RupCheckerFast.checkRefutationFast`, then composes
`checkRefutationFast_sound` (CNF-unsat) with
`SatReluVerdict.safe_of_unsat` (gadget real-arithmetic safety).
-/
import NyProof.SatReluVerdict
import NyProof.RupCheckerFast

namespace Crownproof

namespace SatReluSweep_v26c84

open RupImport.RUP RupChecker

set_option maxRecDepth 65536

/-- The recovered DIMACS formula, literal-for-literal. -/
def F : Formula :=
  [ [(1, true), (3, false), (4, false), (9, false), (19, true), (23, false), (26, true)]
  , [(1, true), (3, true), (11, false), (18, true), (19, false), (23, false), (26, false)]
  , [(1, false), (6, true), (11, false), (16, false), (18, false), (20, true), (24, false)]
  , [(1, true), (2, true), (5, true), (22, false), (23, true), (25, false)]
  , [(1, true), (3, false), (12, false), (17, false), (19, false), (20, true), (21, false), (23, false), (25, true)]
  , [(1, false), (11, false), (13, false), (17, false), (20, false), (24, true)]
  , [(1, false), (5, true), (11, true), (19, true)]
  , [(1, true), (22, true), (23, true), (24, false)]
  , [(1, true), (3, true), (6, false), (11, false), (18, true), (19, true), (23, false), (26, false)]
  , [(1, false), (2, true), (5, false), (9, true), (11, true), (19, true)]
  , [(1, true), (3, true), (7, false), (11, true), (13, true), (16, false), (23, false)]
  , [(1, false), (3, false), (8, false), (11, true), (12, false), (13, true), (18, true), (19, false)]
  , [(1, true), (2, true), (4, true), (5, true), (8, false), (10, false), (22, false), (23, true), (25, true)]
  , [(1, false), (11, false), (20, false), (21, false), (24, false), (25, false)]
  , [(1, true), (2, true), (22, true), (23, true), (24, true)]
  , [(1, true), (3, false), (9, false), (19, true), (23, false), (26, false)]
  , [(1, false), (5, true), (6, true), (11, false), (13, true), (24, true), (25, true)]
  , [(1, false), (4, false), (11, false), (16, true), (20, true), (24, false)]
  , [(1, false), (3, true), (8, false), (11, true), (13, true), (18, false), (19, false), (25, false)]
  , [(1, false), (4, true), (7, false), (11, true), (13, false), (19, false)]
  , [(1, false), (5, false), (11, false), (13, true), (24, true), (25, false)]
  , [(1, true), (2, true), (5, false), (13, false), (22, false), (23, true)]
  , [(1, false), (3, true), (11, false), (20, false), (24, false), (25, true)]
  , [(1, true), (3, false), (7, true), (19, false), (20, true), (23, false), (25, false)]
  , [(1, true), (2, true), (4, false), (5, true), (22, false), (23, true), (25, true)]
  , [(1, true), (2, true), (4, true), (5, true), (8, false), (10, true), (22, false), (23, true), (25, true)]
  , [(1, true), (3, true), (11, false), (18, true), (23, false), (26, true)]
  , [(1, false), (2, false), (4, true), (7, true), (11, true), (13, false), (19, false)]
  , [(1, true), (3, false), (19, false), (20, false), (23, false), (25, false)]
  , [(1, false), (6, true), (11, false), (16, false), (18, true), (20, true), (24, false)]
  , [(1, true), (3, false), (12, false), (17, false), (19, false), (20, false), (21, false), (23, false), (25, true)]
  , [(1, false), (3, true), (8, false), (11, true), (13, true), (18, false), (19, false), (25, true)]
  , [(1, false), (6, false), (11, false), (13, true), (24, true), (25, true)]
  , [(1, false), (6, true), (9, false), (11, false), (13, false), (17, true), (23, false), (24, true)]
  , [(1, true), (3, false), (7, false), (19, false), (20, true), (23, false), (25, false)]
  , [(1, false), (2, false), (5, false), (11, true), (19, true)]
  , [(1, false), (6, true), (9, true), (11, false), (13, false), (17, true), (23, false), (24, true)]
  , [(1, false), (8, true), (11, true), (12, false), (13, true), (18, true), (19, false), (20, true)]
  , [(1, false), (2, true), (4, true), (7, true), (11, true), (13, false), (19, false)]
  , [(1, false), (5, false), (6, true), (11, false), (13, true), (24, true), (25, true)]
  , [(1, true), (3, true), (8, true), (11, false), (18, false), (20, false), (21, false), (23, false)]
  , [(1, true), (3, true), (7, false), (11, true), (13, false), (16, false), (23, false)]
  , [(1, true), (2, false), (6, true), (14, true), (17, false), (22, false), (23, true)]
  , [(1, false), (11, false), (13, false), (17, false), (20, true), (24, true)]
  , [(1, true), (3, true), (8, false), (11, false), (18, false), (20, false), (21, false), (23, false)]
  , [(1, true), (3, true), (11, false), (18, false), (20, true), (23, false)]
  , [(1, true), (3, true), (7, true), (11, true), (22, true), (23, false)]
  , [(1, false), (3, false), (11, true), (13, true), (18, false), (19, false)]
  , [(1, true), (3, false), (4, true), (9, false), (16, true), (19, true), (23, false), (26, true)]
  , [(1, true), (3, true), (11, false), (18, false), (20, false), (21, true), (23, false)]
  , [(1, false), (6, false), (8, true), (11, false), (13, false), (17, true), (24, true)]
  , [(1, false), (6, true), (11, false), (13, false), (17, true), (22, true), (23, true), (24, true)]
  , [(1, true), (3, false), (17, true), (19, false), (21, false), (23, false), (25, true)]
  , [(1, true), (2, false), (6, false), (17, false), (22, false), (23, true)]
  , [(1, false), (3, true), (8, false), (11, true), (12, false), (13, true), (18, true), (19, false)]
  , [(1, false), (7, true), (11, true), (12, true), (13, true), (18, true), (19, false)]
  , [(1, false), (6, false), (8, false), (11, false), (13, false), (17, true), (24, true)]
  , [(1, true), (2, false), (17, true), (22, false), (23, true)]
  , [(1, false), (11, false), (20, false), (21, true), (24, false), (25, false)]
  , [(1, false), (6, true), (11, false), (13, false), (17, true), (22, false), (23, true), (24, true)]
  , [(1, true), (3, false), (9, true), (19, true), (22, true), (23, false)]
  , [(1, false), (3, true), (8, true), (11, true), (13, true), (18, false), (19, false), (23, true)]
  , [(1, true), (3, false), (4, true), (9, false), (16, false), (19, true), (23, false), (26, true)]
  , [(1, true), (2, false), (22, true), (23, true), (24, true)]
  , [(1, false), (3, false), (11, false), (20, false), (24, false), (25, true)]
  , [(1, false), (3, true), (8, true), (11, true), (13, true), (18, false), (19, false), (23, false)]
  , [(1, true), (2, true), (4, true), (5, true), (8, true), (22, false), (23, true), (25, true)]
  , [(1, false), (4, true), (11, false), (16, true), (20, true), (24, false)]
  , [(1, false), (4, false), (11, true), (13, false), (19, false), (24, false)]
  , [(1, true), (3, false), (19, false), (21, true), (23, false), (25, true)]
  , [(1, false), (2, true), (5, false), (8, true), (9, false), (11, true), (19, true)]
  , [(1, false), (7, false), (11, true), (12, true), (13, true), (18, true), (19, false)]
  , [(1, true), (3, false), (12, true), (17, false), (19, false), (21, false), (23, false), (25, true)]
  , [(1, true), (3, false), (9, true), (19, true), (22, false), (23, false)]
  , [(1, true), (2, false), (6, true), (14, false), (17, false), (22, false), (23, true)]
  , [(1, true), (2, true), (5, false), (13, true), (22, false), (23, true)]
  , [(1, false), (4, false), (11, true), (13, false), (19, false), (24, true)]
  , [(1, false), (2, true), (5, false), (8, false), (9, false), (11, true), (19, true)]
  , [(1, true), (3, true), (6, true), (11, false), (18, true), (19, true), (23, false), (26, false)]
  , [(1, false), (5, true), (11, false), (13, true), (24, true), (25, false)]
  , [(1, false), (6, false), (11, false), (16, false), (20, true), (24, false)]
  , [(1, true), (3, true), (7, false), (11, true), (16, true), (23, false)]
  , [(1, true), (3, true), (7, true), (11, true), (22, false), (23, false)]
  , [(1, false), (8, true), (11, true), (12, false), (13, true), (18, true), (19, false), (20, false)]
  ]

/-- The LRAT refutation: derived clause + database-index hints per step. -/
def steps : List RStep :=
  [ ⟨[(20, false), (17, false), (11, false), (3, false), (13, false), (1, false)], [5, 64, 13, 58]⟩
  , ⟨[(17, false), (16, false), (11, false), (13, false), (6, false), (1, false), (3, false)], [84, 80, 43]⟩
  , ⟨[(16, false), (13, false), (11, false), (3, false), (6, false), (8, false), (1, false)], [85, 56, 80, 64, 13, 58]⟩
  , ⟨[(24, false), (16, true), (11, false), (3, false), (4, false), (1, false)], [17, 64, 13, 58]⟩
  , ⟨[(13, false), (11, false), (1, false), (6, false), (8, false), (3, false), (4, false)], [86, 87, 56, 5, 43]⟩
  , ⟨[(24, true), (11, false), (5, false), (6, false), (1, false), (13, true)], [20, 32]⟩
  , ⟨[(11, false), (8, false), (3, false), (6, false), (4, false), (5, false), (1, false)], [88, 89, 87, 80, 64, 13, 58]⟩
  , ⟨[(13, true), (8, false), (3, false), (7, false), (1, false), (11, true), (19, false)], [47, 71, 11]⟩
  , ⟨[(8, false), (7, false), (4, false), (3, false), (1, false), (2, false), (5, false), (6, false)], [90, 35, 91, 68, 76]⟩
  , ⟨[(13, false), (11, true), (4, false), (1, false), (19, false)], [68, 76]⟩
  , ⟨[(11, true), (7, false), (2, false), (3, false), (4, false), (5, false), (1, false), (8, true)], [35, 93, 47, 71, 37, 83]⟩
  , ⟨[(24, false), (11, false), (1, false), (3, false), (6, false), (4, false)], [87, 80, 64, 13, 58]⟩
  , ⟨[(7, false), (6, false), (1, false), (3, false), (5, false), (4, false), (2, false)], [92, 94, 95, 89, 50, 43, 84]⟩
  , ⟨[(11, false), (6, false), (1, false), (3, false), (5, false), (4, false)], [90, 95, 89, 50, 43, 84]⟩
  , ⟨[(6, false), (5, false), (3, false), (4, false), (2, false), (1, false)], [96, 97, 35, 93, 47, 55, 11, 37, 83]⟩
  , ⟨[(8, true), (11, true), (2, false), (3, false), (4, false), (5, false), (1, false)], [35, 93, 47, 94, 55, 37, 83]⟩
  , ⟨[(11, true), (5, false), (3, false), (2, false), (4, false), (1, false)], [35, 93, 47, 99, 91, 11, 55]⟩
  , ⟨[(23, true), (17, false), (2, false), (6, false), (1, true), (24, true)], [63, 53]⟩
  , ⟨[(17, false), (24, true), (3, false), (19, false), (12, true), (20, false), (2, false), (6, false), (1, true)], [101, 28, 69, 72]⟩
  , ⟨[(23, false), (25, true), (3, false), (19, false), (17, true), (1, true)], [69, 52]⟩
  , ⟨[(23, true), (24, true), (2, false), (1, true), (17, true)], [63, 57]⟩
  , ⟨[(24, true), (6, false), (3, false), (19, false), (20, false), (2, false), (12, true), (1, true)], [102, 104, 28, 69, 52]⟩
  , ⟨[(23, true), (17, true), (2, false), (1, true), (24, false)], [7, 57]⟩
  , ⟨[(17, true), (24, false), (3, false), (19, false), (20, false), (2, false), (1, true)], [106, 28, 69, 52]⟩
  , ⟨[(23, false), (25, true), (3, false), (19, false), (12, true), (17, false), (1, true)], [69, 72]⟩
  , ⟨[(23, true), (6, false), (2, false), (1, true), (24, false), (17, false)], [7, 53]⟩
  , ⟨[(6, false), (20, false), (3, false), (19, false), (12, true), (1, true), (2, false)], [105, 107, 109, 28, 69, 72]⟩
  , ⟨[(23, true), (24, false), (2, false), (6, true), (1, true), (17, false)], [7, 42, 74]⟩
  , ⟨[(24, false), (20, false), (3, false), (2, false), (19, false), (12, true), (1, true)], [110, 107, 111, 28, 69, 72]⟩
  , ⟨[(23, true), (17, false), (2, false), (24, true), (6, true), (1, true)], [63, 42, 74]⟩
  , ⟨[(17, false), (20, false), (3, false), (2, false), (19, false), (12, true), (1, true)], [112, 110, 113, 28, 69, 72]⟩
  , ⟨[(20, false), (12, true), (3, false), (19, false), (2, false), (1, true)], [112, 114, 104, 28, 69, 52]⟩
  , ⟨[(17, true), (24, true), (19, false), (1, true), (7, true), (20, true), (2, false), (3, false)], [104, 23, 103]⟩
  , ⟨[(22, true), (2, true), (1, true), (23, true)], [14, 7]⟩
  , ⟨[(19, true), (11, true), (1, false), (2, false)], [35, 6]⟩
  , ⟨[(22, true), (23, true), (1, true), (2, false)], [63, 7]⟩
  , ⟨[(23, true), (17, true), (2, false), (1, true)], [104, 106]⟩
  , ⟨[(2, true), (1, false), (9, true), (11, true), (19, true)], [9, 6]⟩
  , ⟨[(22, false), (23, true), (1, true), (2, false), (6, false)], [53, 57]⟩
  , ⟨[(25, false), (1, false), (11, false), (20, false), (24, false)], [13, 58]⟩
  , ⟨[(24, true), (17, false), (1, false), (11, false), (13, false)], [5, 43]⟩
  , ⟨[(24, false), (25, true), (1, false), (11, false), (20, false)], [64, 22]⟩
  , ⟨[(9, true), (19, true), (1, true), (3, false), (23, false)], [73, 60]⟩
  , ⟨[(22, false), (2, true), (1, true), (5, false), (23, true)], [75, 21]⟩
  , ⟨[(11, false), (1, false), (13, true), (24, true), (25, false)], [79, 20]⟩
  , ⟨[(7, true), (3, true), (1, true), (11, true), (23, false)], [82, 46]⟩
  , ⟨[(23, true), (6, false), (2, false), (1, true), (24, true)], [101, 120]⟩
  , ⟨[(16, true), (24, false), (1, false), (11, false), (20, true)], [17, 67]⟩
  , ⟨[(7, false), (1, false), (11, true), (13, false), (19, false)], [19, 93]⟩
  , ⟨[(23, true), (6, false), (2, false), (1, true), (24, false)], [109, 106]⟩
  , ⟨[(23, true), (24, false), (2, false), (6, true), (1, true)], [111, 106]⟩
  , ⟨[(23, true), (2, false), (24, true), (17, false), (1, true)], [113, 130]⟩
  , ⟨[(23, false), (1, true), (3, false), (19, false), (17, true), (25, true)], [52, 69]⟩
  , ⟨[(5, true), (2, true), (1, true), (4, false), (22, false), (23, true)], [24, 3]⟩
  , ⟨[(4, true), (1, false), (2, false), (11, true), (13, false), (19, false)], [27, 132]⟩
  , ⟨[(5, true), (1, false), (11, false), (13, true), (24, true), (25, true)], [16, 32]⟩
  , ⟨[(18, true), (16, false), (1, false), (11, false), (20, true), (24, false)], [29, 80]⟩
  , ⟨[(2, true), (1, false), (8, true), (9, false), (11, true), (19, true)], [70, 6]⟩
  , ⟨[(12, true), (1, false), (13, true), (11, true), (18, true), (19, false)], [71, 55]⟩
  , ⟨[(7, false), (3, true), (1, true), (11, true), (13, true), (23, false)], [10, 81]⟩
  , ⟨[(22, false), (14, false), (1, true), (2, false), (6, true), (23, true)], [74, 57]⟩
  , ⟨[(7, false), (19, false), (1, true), (3, false), (23, false), (25, false)], [34, 28]⟩
  , ⟨[(2, true), (1, false), (8, false), (9, false), (11, true), (19, true)], [77, 6]⟩
  , ⟨[(4, true), (1, false), (7, true), (11, true), (13, false), (19, false)], [38, 138]⟩
  , ⟨[(13, true), (24, true), (1, false), (5, false), (6, true), (11, false)], [39, 20]⟩
  , ⟨[(7, false), (3, true), (1, true), (11, true), (13, false), (23, false)], [41, 81]⟩
  , ⟨[(22, false), (1, true), (2, false), (6, true), (17, false), (23, true)], [42, 144]⟩
  , ⟨[(18, false), (16, false), (1, false), (11, false), (20, true), (24, false)], [2, 80]⟩
  , ⟨[(11, false), (3, true), (1, true), (18, true), (19, false), (23, false)], [1, 26]⟩
  , ⟨[(11, false), (3, true), (1, true), (18, false), (21, true), (23, false)], [49, 45]⟩
  , ⟨[(13, false), (17, true), (1, false), (6, false), (11, false), (24, true)], [50, 56]⟩
  , ⟨[(23, false), (25, true), (3, false), (19, false), (12, true), (1, true)], [108, 103]⟩
  , ⟨[(9, false), (19, true), (1, true), (4, false), (3, false), (23, false)], [0, 15]⟩
  , ⟨[(25, false), (23, false), (1, true), (3, false), (7, true), (19, false)], [23, 28]⟩
  , ⟨[(6, false), (3, true), (1, true), (11, false), (18, true), (19, true), (23, false)], [8, 26]⟩
  , ⟨[(8, false), (1, false), (11, true), (13, true), (18, false), (19, false), (25, true)], [31, 47]⟩
  , ⟨[(8, true), (1, false), (11, true), (13, true), (18, false), (19, false), (23, true)], [61, 47]⟩
  , ⟨[(8, true), (3, true), (1, true), (11, false), (18, false), (20, false), (23, false)], [40, 153]⟩
  , ⟨[(4, true), (3, false), (1, true), (9, false), (16, false), (19, true), (23, false)], [62, 15]⟩
  , ⟨[(21, false), (23, false), (1, true), (3, false), (19, false), (12, true), (25, true)], [72, 136]⟩
  , ⟨[(12, false), (1, false), (3, false), (13, true), (11, true), (8, false), (19, false)], [11, 47]⟩
  , ⟨[(8, false), (3, true), (1, true), (11, false), (18, false), (20, false), (23, false)], [44, 153]⟩
  , ⟨[(8, true), (3, true), (1, false), (11, true), (13, true), (18, false), (19, false)], [65, 160]⟩
  , ⟨[(4, true), (3, false), (1, true), (9, false), (16, true), (19, true), (23, false)], [48, 15]⟩
  , ⟨[(2, true), (1, true), (5, true), (8, true), (22, false), (23, true), (25, true)], [66, 137]⟩
  , ⟨[(3, true), (1, true), (11, false), (18, true), (19, true), (23, false), (26, false)], [78, 158]⟩
  , ⟨[(8, false), (1, false), (11, true), (13, true), (18, false), (19, false), (25, false)], [18, 47]⟩
  , ⟨[(13, false), (1, false), (6, true), (11, false), (17, true), (23, false), (24, true)], [36, 33]⟩
  , ⟨[(17, true), (13, false), (1, false), (6, true), (11, false), (23, true), (24, true)], [51, 59]⟩
  , ⟨[(12, false), (1, false), (8, true), (11, true), (18, true), (19, false), (13, true)], [37, 83]⟩
  , ⟨[(8, false), (1, false), (11, true), (12, false), (13, true), (18, true), (19, false)], [54, 164]⟩
  , ⟨[(17, false), (1, true), (3, false), (19, false), (20, false), (21, false), (23, false), (25, true)], [30, 155]⟩
  , ⟨[(2, true), (1, true), (5, true), (8, false), (10, true), (22, false), (23, true), (25, true)], [25, 137]⟩
  , ⟨[(2, true), (1, true), (5, true), (8, false), (10, false), (22, false), (23, true), (25, true)], [12, 137]⟩
  , ⟨[(17, false), (1, true), (3, false), (19, false), (20, true), (21, false), (23, false), (25, true)], [4, 155]⟩
  , ⟨[(1, false), (2, false), (11, true), (13, false)], [118, 93, 132, 147, 138]⟩
  , ⟨[(1, false), (11, false), (6, false), (24, true), (13, false)], [154, 124, 89, 128, 139]⟩
  , ⟨[(1, false), (11, false), (6, false), (24, true)], [180, 89, 128, 139]⟩
  , ⟨[(1, false), (11, false), (24, false), (20, true)], [131, 140, 151, 80]⟩
  , ⟨[(1, false), (11, false), (24, true), (13, false)], [124, 181, 172, 171]⟩
  , ⟨[(1, false), (11, false), (24, true)], [183, 181, 128, 139, 148]⟩
  , ⟨[(1, false), (11, false)], [184, 182, 123, 125]⟩
  , ⟨[(1, false), (3, false), (19, false), (13, true)], [185, 47, 142, 173, 174, 164]⟩
  , ⟨[(1, false), (11, true), (19, false), (13, true), (3, true), (18, false)], [166, 185, 159, 170]⟩
  , ⟨[(1, false), (11, true), (19, false), (13, true), (3, true)], [187, 185, 142, 173, 174]⟩
  , ⟨[(1, false), (11, true), (19, false), (13, true)], [188, 185, 186, 93, 132, 147]⟩
  , ⟨[(1, false), (11, true), (19, false)], [189, 185, 93, 132, 147]⟩
  , ⟨[(1, false), (11, true), (19, true), (2, true)], [121, 185, 190, 118, 141, 146]⟩
  , ⟨[(1, true), (3, false), (23, false), (19, false), (25, false)], [28, 157, 145]⟩
  , ⟨[(1, true), (3, false), (23, false), (19, false)], [192, 69, 103, 175, 178, 163]⟩
  , ⟨[(1, true), (3, false), (23, false), (19, true), (9, false), (16, false)], [162, 193, 126, 156]⟩
  , ⟨[(1, true), (3, false), (23, false), (19, true), (16, true), (9, false)], [167, 193, 156, 126]⟩
  , ⟨[(1, true), (11, false), (23, false), (3, true), (18, false)], [153, 45, 161, 165]⟩
  , ⟨[(1, true), (11, false), (23, false), (19, false), (3, true)], [152, 196, 193, 126, 195, 194]⟩
  , ⟨[(1, true), (11, false), (23, false), (19, false)], [197, 193, 126, 195, 194]⟩
  , ⟨[(1, true), (11, false), (23, false), (19, true), (3, true)], [196, 169, 26, 158]⟩
  , ⟨[(1, true), (11, false), (23, false), (3, true)], [199, 198, 196, 169, 26]⟩
  , ⟨[(1, true), (11, true), (23, false), (3, true)], [129, 143, 149, 81]⟩
  , ⟨[(1, true), (23, true), (2, false)], [120, 119, 135, 150, 133, 122]⟩
  , ⟨[(1, true), (23, true)], [202, 117, 127, 3, 168, 176, 177, 137]⟩
  , ⟨[(1, false), (11, true)], [190, 185, 118, 191]⟩
  , ⟨[(1, true), (3, false)], [203, 193, 126, 195, 194, 156]⟩
  , ⟨[(1, true), (11, false), (23, false)], [200, 205, 185, 204]⟩
  , ⟨[(1, true), (11, true), (23, false)], [201, 205, 185, 204]⟩
  , ⟨[(1, true), (11, true)], [207, 203, 185, 204]⟩
  , ⟨[(1, true), (11, false)], [206, 203, 185, 204]⟩
  , ⟨[(23, true)], [203, 185, 204]⟩
  , ⟨[(3, false)], [210, 205, 185, 204]⟩
  , ⟨[(19, false), (13, true), (3, false)], [186, 205]⟩
  , ⟨[(17, false), (13, false), (3, false), (20, false), (1, false)], [84, 204]⟩
  , ⟨[(24, false), (4, false), (16, true), (3, false), (11, false)], [87, 205]⟩
  , ⟨[(13, true), (6, false), (24, true), (5, false), (1, false)], [89, 204]⟩
  , ⟨[(4, false), (24, false), (3, false), (6, false), (11, false)], [95, 205]⟩
  , ⟨[(4, false), (6, false), (5, false), (3, false), (1, false)], [97, 204]⟩
  , ⟨[(6, false), (4, false), (2, false), (5, false), (3, false)], [98, 205]⟩
  , ⟨[(4, false), (5, false), (3, false), (2, false), (11, true)], [100, 205]⟩
  , ⟨[(17, false), (16, false), (6, false), (13, false), (3, false), (11, false)], [85, 205]⟩
  , ⟨[(16, false), (13, false), (8, false), (6, false), (3, false), (11, false)], [86, 205]⟩
  , ⟨[(13, false), (8, false), (4, false), (6, false), (3, false), (11, false)], [88, 205]⟩
  , ⟨[(1, true)], [209, 208]⟩
  , ⟨[(11, false)], [223, 185]⟩
  , ⟨[], [223, 224, 204]⟩
  ]

set_option maxHeartbeats 40000000 in
/-- KERNEL replay of the refutation — plain `decide`, no `native_decide`. -/
theorem check_ok : RupCheckerFast.checkRefutationFast F steps = true := by decide

/-- The recovered CNF is unsatisfiable (kernel-checked LRAT replay +
`rup_sound` composition). -/
theorem instance_unsat : ¬ ∃ σ, satFormula σ F :=
  RupCheckerFast.checkRefutationFast_sound F steps check_ok

/-- The gadget's variable set: DIMACS variables `1..26`. -/
def s : Finset ℕ := Finset.Icc 1 26

set_option maxHeartbeats 4000000 in
/-- END-TO-END VERDICT: no point of the `[0,1]` box reaches the sat_relu
gadget's unsafe region `{Y₀ ≥ 1 ∧ Y₁ ≤ 0}` — real-arithmetic SAFE. -/
theorem instance_safe :
    ∀ x : ℕ → ℝ, (∀ j ∈ s, 0 ≤ x j ∧ x j ≤ 1) →
      ¬ (1 ≤ SatRelu.Y0 (SatReluVerdict.clausesOf F) x ∧
         SatRelu.Y1 s x ≤ 0) :=
  SatReluVerdict.safe_of_unsat F s (by decide) instance_unsat

end SatReluSweep_v26c84

end Crownproof

/-! ## Trust-base check -/

#print axioms Crownproof.SatReluSweep_v26c84.check_ok
#print axioms Crownproof.SatReluSweep_v26c84.instance_unsat
#print axioms Crownproof.SatReluSweep_v26c84.instance_safe
