/-
MACHINE-GENERATED by `ny-cert`'s `lrat_to_lean` — do not edit.

sat_relu Route A instance transcript:
* DIMACS source : inst.cnf  (p cnf 30 38)
* LRAT source   : inst.lrat  (32 addition steps kept)

The kernel replays the full LRAT refutation with PLAIN `decide`
(no `native_decide`, no extra axioms) through
`RupCheckerFast.checkRefutationFast`, then composes
`checkRefutationFast_sound` (CNF-unsat) with
`SatReluVerdict.safe_of_unsat` (gadget real-arithmetic safety).
-/
import NyProof.SatReluVerdict
import NyProof.RupCheckerFast

namespace Crownproof

namespace SatReluSweep_v30c38

open RupImport.RUP RupChecker

set_option maxRecDepth 65536

/-- The recovered DIMACS formula, literal-for-literal. -/
def F : Formula :=
  [ [(1, false), (7, false), (10, false), (18, false), (23, false)]
  , [(1, true), (6, true), (9, false), (27, false), (28, false), (30, true)]
  , [(1, true), (12, false), (13, false), (16, false), (21, false), (22, false), (28, true)]
  , [(1, true), (6, true), (7, false), (9, true), (16, true), (28, false)]
  , [(1, true), (20, true), (22, true), (23, true), (28, true)]
  , [(1, false), (7, true), (12, true), (23, false), (29, true)]
  , [(1, false), (7, false), (10, true), (23, false)]
  , [(1, false), (2, false), (8, true), (14, true), (15, false), (23, true)]
  , [(1, false), (7, false), (10, false), (18, true), (23, false)]
  , [(1, true), (2, true), (13, true), (22, false), (28, true)]
  , [(1, true), (6, true), (9, false), (12, false), (27, true), (28, false)]
  , [(1, true), (14, true), (20, false), (22, true), (23, true), (25, false), (28, true)]
  , [(1, true), (13, false), (16, true), (21, false), (22, false), (28, true)]
  , [(1, true), (4, false), (6, true), (7, true), (9, true), (28, false)]
  , [(1, true), (6, false), (28, false)]
  , [(1, false), (2, false), (8, true), (14, true), (15, true), (23, true)]
  , [(1, false), (7, true), (12, false), (23, false), (28, false), (29, true)]
  , [(1, false), (2, false), (14, false), (21, false), (22, false), (23, true)]
  , [(1, false), (2, false), (8, false), (14, true), (23, true), (27, false)]
  , [(1, true), (6, true), (9, false), (12, true), (27, true), (28, false)]
  , [(1, false), (7, true), (12, false), (23, false), (29, false)]
  , [(1, true), (14, false), (20, false), (22, true), (23, true), (25, false), (28, true)]
  , [(1, true), (6, true), (7, false), (9, true), (16, false), (28, false)]
  , [(1, true), (2, false), (13, true), (22, false), (28, true)]
  , [(1, false), (2, false), (14, false), (21, true), (22, false), (23, true)]
  , [(1, false), (7, true), (12, true), (23, false), (29, false)]
  , [(1, true), (20, false), (22, true), (23, true), (25, true), (28, true)]
  , [(1, false), (2, false), (8, false), (14, true), (23, true), (27, true)]
  , [(1, true), (6, true), (9, false), (27, false), (28, false), (30, false)]
  , [(1, true), (4, true), (6, true), (7, true), (9, true), (28, false)]
  , [(1, true), (3, false), (12, true), (13, false), (16, false), (21, false), (22, false), (28, true)]
  , [(1, true), (3, true), (12, true), (13, false), (16, false), (21, false), (22, false), (28, true)]
  , [(1, true), (22, true), (23, false), (28, true)]
  , [(1, false), (2, true), (6, false), (23, true)]
  , [(1, false), (2, false), (14, false), (22, true), (23, true)]
  , [(1, true), (13, false), (21, true), (22, false), (28, true)]
  , [(1, false), (2, true), (6, true), (23, true)]
  , [(1, false), (7, true), (12, false), (23, false), (28, true), (29, true)]
  ]

/-- The LRAT refutation: derived clause + database-index hints per step. -/
def steps : List RStep :=
  [ ⟨[(23, true), (14, false), (2, false), (1, false)], [34, 17, 24]⟩
  , ⟨[(23, false), (10, false), (7, false), (1, false)], [0, 8]⟩
  , ⟨[(23, true), (8, false), (2, false), (1, false)], [38, 18, 27]⟩
  , ⟨[(23, false), (7, false), (1, false)], [6, 0, 8]⟩
  , ⟨[(23, true), (2, false), (1, false)], [38, 40, 7, 15]⟩
  , ⟨[(12, false), (23, false), (1, false)], [41, 20, 37, 16]⟩
  , ⟨[(23, false), (1, false)], [41, 43, 5, 25]⟩
  , ⟨[(1, false)], [44, 42, 33, 36]⟩
  , ⟨[(9, true), (28, false), (7, true), (6, true)], [45, 13, 29]⟩
  , ⟨[(28, false), (12, true), (6, true), (7, true)], [45, 46, 19, 1, 28]⟩
  , ⟨[(22, false), (21, true), (28, true), (2, false)], [45, 23, 35]⟩
  , ⟨[(22, true), (14, true), (23, true), (28, true)], [45, 4, 26, 11]⟩
  , ⟨[(22, false), (12, true), (2, false), (28, true)], [45, 23, 48, 12, 30, 31]⟩
  , ⟨[(12, true), (7, true), (2, false), (6, true), (23, true)], [45, 47, 50, 4, 49, 26, 21]⟩
  , ⟨[(22, true), (28, true), (23, true)], [45, 4, 49, 26, 21]⟩
  , ⟨[(28, true), (12, false), (2, false), (23, true)], [45, 52, 23, 48, 12, 2]⟩
  , ⟨[(7, true), (6, true), (2, false), (23, true)], [45, 51, 53, 46, 10, 1, 28]⟩
  , ⟨[(9, false), (27, false), (28, false), (6, true)], [45, 1, 28]⟩
  , ⟨[(9, true), (28, false), (6, true), (7, false)], [45, 3, 22]⟩
  , ⟨[(28, false), (7, false), (6, true)], [45, 56, 55, 19, 10]⟩
  , ⟨[(28, true), (23, true), (2, false)], [52, 53, 50]⟩
  , ⟨[(23, true), (2, false)], [45, 58, 14, 57, 54]⟩
  , ⟨[(28, false)], [45, 14, 57, 46, 47, 55, 10]⟩
  , ⟨[(2, false)], [45, 60, 59, 32, 23, 48, 50, 12, 2]⟩
  , ⟨[(22, false), (12, false)], [45, 60, 61, 9, 35, 2, 12]⟩
  , ⟨[(22, true)], [45, 60, 32, 52]⟩
  , ⟨[(12, false)], [63, 62]⟩
  , ⟨[(13, true)], [63, 45, 61, 60, 9]⟩
  , ⟨[(21, true)], [65, 45, 63, 60, 35]⟩
  , ⟨[(16, true)], [66, 45, 65, 63, 60, 12]⟩
  , ⟨[(3, false)], [67, 45, 64, 65, 66, 63, 60, 30]⟩
  , ⟨[], [45, 60, 61, 63, 64, 65, 66, 67, 68, 31]⟩
  ]

set_option maxHeartbeats 40000000 in
/-- KERNEL replay of the refutation — plain `decide`, no `native_decide`. -/
theorem check_ok : RupCheckerFast.checkRefutationFast F steps = true := by decide

/-- The recovered CNF is unsatisfiable (kernel-checked LRAT replay +
`rup_sound` composition). -/
theorem instance_unsat : ¬ ∃ σ, satFormula σ F :=
  RupCheckerFast.checkRefutationFast_sound F steps check_ok

/-- The gadget's variable set: DIMACS variables `1..30`. -/
def s : Finset ℕ := Finset.Icc 1 30

set_option maxHeartbeats 4000000 in
/-- END-TO-END VERDICT: no point of the `[0,1]` box reaches the sat_relu
gadget's unsafe region `{Y₀ ≥ 1 ∧ Y₁ ≤ 0}` — real-arithmetic SAFE. -/
theorem instance_safe :
    ∀ x : ℕ → ℝ, (∀ j ∈ s, 0 ≤ x j ∧ x j ≤ 1) →
      ¬ (1 ≤ SatRelu.Y0 (SatReluVerdict.clausesOf F) x ∧
         SatRelu.Y1 s x ≤ 0) :=
  SatReluVerdict.safe_of_unsat F s (by decide) instance_unsat

end SatReluSweep_v30c38

end Crownproof

/-! ## Trust-base check -/

#print axioms Crownproof.SatReluSweep_v30c38.check_ok
#print axioms Crownproof.SatReluSweep_v30c38.instance_unsat
#print axioms Crownproof.SatReluSweep_v30c38.instance_safe
