/-
MACHINE-GENERATED by `ny-cert`'s `lrat_to_lean` — do not edit.

sat_relu Route A instance transcript:
* DIMACS source : inst.cnf  (p cnf 38 132)
* LRAT source   : inst.lrat  (286 addition steps kept)

The kernel replays the full LRAT refutation with PLAIN `decide`
(no `native_decide`, no extra axioms) through
`RupCheckerFast.checkRefutationFast`, then composes
`checkRefutationFast_sound` (CNF-unsat) with
`SatReluVerdict.safe_of_unsat` (gadget real-arithmetic safety).
-/
import NyProof.SatReluVerdict
import NyProof.RupCheckerFast

namespace Crownproof

namespace SatReluSweep_v38c132

open RupImport.RUP RupChecker

set_option maxRecDepth 65536

/-- The recovered DIMACS formula, literal-for-literal. -/
def F : Formula :=
  [ [(1, true), (3, false), (5, true), (8, true), (11, true), (22, true), (32, true), (34, true)]
  , [(1, false), (10, true), (14, false), (21, true), (30, false), (32, false), (38, true)]
  , [(1, true), (2, true), (10, false), (11, false), (19, true), (20, true), (31, false)]
  , [(1, true), (2, true), (11, true), (14, false), (15, false), (19, true), (21, true), (22, false), (29, false), (36, true), (37, true)]
  , [(1, false), (10, false), (11, false), (13, false), (14, true), (32, false), (35, false)]
  , [(1, false), (9, true), (14, false), (21, true), (32, false), (36, false), (38, false)]
  , [(1, true), (2, true), (5, true), (8, false), (11, false), (12, false), (19, false), (20, true), (24, false), (31, false), (38, true)]
  , [(1, true), (2, true), (5, true), (8, true), (11, false), (12, false), (19, false), (20, true), (24, false), (31, false)]
  , [(1, true), (5, true), (11, true), (21, true), (22, true), (32, false)]
  , [(1, false), (14, false), (21, false), (31, true), (32, false), (35, true)]
  , [(1, false), (2, false), (12, false), (14, true), (20, false), (21, true), (29, false), (32, true), (36, true)]
  , [(1, true), (5, true), (10, true), (11, true), (13, true), (14, true), (19, true), (21, true), (22, false)]
  , [(1, false), (11, true), (14, true), (32, false), (35, false)]
  , [(1, true), (2, false), (3, true), (11, false), (17, false), (24, false), (32, true)]
  , [(1, true), (5, false), (11, true), (13, false), (22, true)]
  , [(1, false), (5, false), (7, true), (14, true), (21, false), (32, false), (35, true), (36, false)]
  , [(1, false), (2, false), (4, false), (14, true), (18, true), (20, false), (21, true), (29, false), (32, true), (36, false)]
  , [(1, true), (2, false), (6, true), (9, false), (11, false), (12, true), (17, true), (19, true), (20, false), (32, true)]
  , [(1, false), (8, true), (10, true), (11, false), (14, true), (22, false), (32, false), (35, false)]
  , [(1, false), (14, false), (21, false), (29, false), (31, false), (32, false)]
  , [(1, false), (3, false), (5, true), (14, true), (28, true), (29, true), (31, true), (32, true), (37, true), (38, true)]
  , [(1, true), (4, false), (11, true), (14, false), (19, true), (21, true), (22, false), (36, false), (37, true)]
  , [(1, true), (3, false), (5, true), (8, false), (10, true), (11, true), (15, true), (22, true), (32, true), (33, true)]
  , [(1, false), (14, true), (20, false), (21, false), (23, false), (24, false), (29, false), (32, true), (36, true)]
  , [(1, false), (5, true), (6, true), (14, true), (18, false), (20, true), (29, false), (32, true)]
  , [(1, false), (9, false), (14, false), (21, true), (32, false), (38, false)]
  , [(1, false), (14, true), (20, false), (21, false), (29, false), (32, true), (36, false)]
  , [(1, false), (6, false), (14, true), (20, true), (29, false), (32, true)]
  , [(1, true), (5, true), (11, true), (13, false), (14, true), (19, true), (21, true), (22, false)]
  , [(1, true), (2, true), (5, true), (11, false), (12, true), (19, false), (20, true), (24, false), (31, false)]
  , [(1, false), (5, false), (7, true), (14, true), (21, false), (24, true), (32, false), (35, true), (36, true)]
  , [(1, false), (14, true), (20, false), (21, false), (23, false), (24, true), (29, false), (32, true), (36, true)]
  , [(1, true), (2, true), (3, true), (4, false), (11, false), (12, false), (20, true), (31, true)]
  , [(1, false), (14, true), (20, false), (21, false), (23, true), (29, false), (32, true), (36, true)]
  , [(1, false), (14, false), (21, false), (22, true), (29, true), (31, false), (32, false)]
  , [(1, false), (7, true), (14, true), (29, true), (31, true), (32, true), (36, false), (37, false)]
  , [(1, true), (2, true), (5, true), (8, false), (11, false), (12, false), (19, false), (20, true), (24, false), (31, false), (38, false)]
  , [(1, false), (4, true), (14, false), (21, false), (31, true), (32, false), (33, true), (35, false)]
  , [(1, true), (2, false), (11, true), (14, false), (19, true), (21, true), (22, false), (36, true), (37, true)]
  , [(1, false), (8, true), (10, true), (11, false), (14, true), (22, true), (24, false), (32, false), (35, false)]
  , [(1, false), (2, true), (14, true), (20, false), (21, true), (29, false), (32, true)]
  , [(1, true), (2, false), (6, false), (9, false), (11, false), (12, true), (17, true), (19, true), (20, false), (32, true)]
  , [(1, true), (5, false), (11, true), (14, true), (19, true), (21, true), (22, false)]
  , [(1, true), (2, false), (10, false), (11, false), (17, false), (24, true)]
  , [(1, true), (3, false), (5, true), (8, false), (10, true), (11, true), (22, true), (24, false), (32, true), (33, false)]
  , [(1, true), (3, false), (5, true), (8, false), (10, true), (11, true), (15, false), (22, true), (32, true), (33, true)]
  , [(1, true), (2, false), (9, false), (11, false), (12, true), (17, true), (19, false), (21, true), (32, true)]
  , [(1, true), (2, false), (11, false), (17, false), (24, false), (32, false)]
  , [(1, true), (2, false), (9, true), (11, false), (17, true), (32, true)]
  , [(1, true), (11, true), (19, false), (21, true), (22, false)]
  , [(1, false), (8, true), (10, true), (11, false), (14, true), (22, true), (24, true), (32, false), (35, false)]
  , [(1, true), (11, true), (14, false), (19, true), (21, true), (22, false), (37, false)]
  , [(1, true), (2, true), (10, true), (11, false), (19, true), (20, true), (31, false)]
  , [(1, true), (3, false), (5, true), (8, false), (10, true), (11, true), (22, true), (24, true), (32, true), (33, false)]
  , [(1, false), (5, false), (7, true), (14, true), (21, false), (24, false), (32, false), (35, true), (36, true)]
  , [(1, false), (9, false), (14, false), (15, true), (29, true), (32, true)]
  , [(1, false), (7, false), (14, true), (29, true), (31, true), (32, true), (36, false), (37, false)]
  , [(1, false), (3, false), (5, false), (14, true), (28, true), (29, true), (31, true), (32, true), (37, true), (38, true)]
  , [(1, false), (2, false), (3, false), (14, true), (28, false), (29, true), (31, true), (32, true), (37, true)]
  , [(1, true), (2, true), (11, true), (14, false), (19, true), (21, true), (22, false), (29, true), (36, true), (37, true)]
  , [(1, false), (5, false), (6, true), (14, true), (18, false), (20, true), (29, false), (32, true)]
  , [(1, false), (5, false), (7, false), (14, true), (16, false), (21, false), (32, false), (35, true)]
  , [(1, true), (5, true), (11, true), (21, false), (22, true), (32, false)]
  , [(1, true), (2, false), (3, true), (4, true), (5, true), (7, true), (10, false), (11, true), (22, true), (26, true), (28, false), (32, true)]
  , [(1, false), (6, true), (10, false), (14, true), (18, true), (20, true), (29, false), (32, true)]
  , [(1, false), (13, true), (14, false), (29, false), (32, true), (33, true)]
  , [(1, true), (2, true), (11, false), (12, true), (20, true), (23, false), (31, true), (37, true)]
  , [(1, true), (2, true), (3, false), (11, false), (12, false), (20, true), (31, true)]
  , [(1, true), (2, false), (3, true), (5, true), (10, false), (11, true), (22, true), (26, true), (28, true), (32, true)]
  , [(1, true), (2, true), (7, true), (11, false), (12, true), (20, true), (23, true), (31, true), (37, true)]
  , [(1, false), (14, false), (21, true), (30, true), (32, false), (38, true)]
  , [(1, false), (3, false), (14, true), (28, true), (29, true), (31, true), (32, true), (37, true), (38, false)]
  , [(1, false), (14, false), (15, false), (21, false), (31, true), (32, false), (33, false), (35, false)]
  , [(1, false), (14, false), (29, false), (32, true), (33, false)]
  , [(1, true), (11, true), (21, false), (22, false)]
  , [(1, false), (2, false), (12, true), (14, true), (20, false), (21, true), (29, false), (32, true), (36, true)]
  , [(1, false), (8, false), (10, true), (11, false), (14, true), (22, true), (28, false), (32, false), (35, false)]
  , [(1, false), (5, true), (14, true), (21, false), (25, false), (30, true), (32, false), (35, true)]
  , [(1, true), (2, false), (9, false), (11, false), (12, true), (17, true), (19, true), (20, true), (32, true)]
  , [(1, false), (8, false), (10, true), (11, false), (14, true), (28, true), (32, false), (35, false)]
  , [(1, false), (9, true), (10, false), (14, false), (16, false), (29, true), (32, true)]
  , [(1, false), (14, false), (21, false), (22, false), (29, true), (31, false), (32, false)]
  , [(1, false), (2, true), (3, false), (14, true), (28, false), (29, true), (31, true), (32, true), (37, true)]
  , [(1, false), (9, false), (14, false), (15, false), (29, true), (32, true)]
  , [(1, true), (2, true), (11, false), (20, false)]
  , [(1, false), (14, false), (15, true), (21, false), (31, true), (32, false), (33, false), (35, false)]
  , [(1, false), (14, true), (29, true), (31, true), (32, true), (36, true), (37, false)]
  , [(1, true), (2, true), (11, false), (12, true), (20, true), (31, true), (37, false)]
  , [(1, false), (10, false), (14, false), (21, true), (30, false), (32, false), (38, true)]
  , [(1, false), (9, true), (14, false), (21, true), (32, false), (36, true), (38, false)]
  , [(1, false), (3, true), (14, true), (29, true), (31, true), (32, true), (37, true)]
  , [(1, true), (2, true), (5, true), (11, false), (19, false), (20, true), (24, true), (31, false)]
  , [(1, true), (2, false), (3, true), (4, true), (5, true), (7, false), (10, false), (11, true), (22, true), (26, true), (28, false), (32, true)]
  , [(1, false), (10, false), (11, false), (13, true), (14, true), (32, false), (35, false)]
  , [(1, false), (8, false), (10, true), (11, false), (14, true), (22, false), (28, false), (32, false), (35, false)]
  , [(1, true), (2, false), (3, true), (4, false), (5, true), (10, false), (11, true), (22, true), (26, true), (28, false), (32, true)]
  , [(1, false), (2, false), (4, true), (14, true), (18, true), (20, false), (21, true), (29, false), (32, true), (36, false)]
  , [(1, true), (2, false), (9, true), (11, false), (17, true), (29, true), (30, true), (32, false)]
  , [(1, true), (5, false), (11, true), (13, true), (22, true)]
  , [(1, true), (5, true), (10, false), (11, true), (13, true), (14, true), (19, true), (21, true), (22, false)]
  , [(1, true), (2, false), (5, false), (8, false), (9, false), (11, false), (12, false), (17, true)]
  , [(1, true), (3, true), (5, true), (10, true), (11, true), (22, true), (32, true)]
  , [(1, false), (5, false), (7, false), (14, true), (16, true), (21, false), (31, true), (32, false), (35, true)]
  , [(1, true), (2, true), (7, false), (11, false), (12, true), (20, true), (23, true), (31, true), (37, true)]
  , [(1, true), (4, true), (11, true), (14, false), (19, true), (21, true), (22, false), (36, false), (37, true)]
  , [(1, false), (2, false), (14, true), (18, false), (20, false), (21, true), (29, false), (32, true), (36, false)]
  , [(1, false), (5, true), (14, true), (21, false), (25, true), (32, false), (35, true)]
  , [(1, false), (9, true), (10, false), (14, false), (16, true), (29, true), (32, true)]
  , [(1, true), (2, true), (3, true), (5, true), (10, false), (11, true), (22, true), (32, true)]
  , [(1, true), (2, false), (9, true), (11, false), (17, true), (30, false), (32, false)]
  , [(1, false), (9, true), (10, true), (14, false), (29, true), (32, true)]
  , [(1, false), (5, true), (14, true), (21, false), (25, false), (30, false), (32, false), (35, true)]
  , [(1, false), (5, false), (7, false), (14, true), (16, true), (21, false), (31, false), (32, false), (35, true)]
  , [(1, true), (2, false), (9, false), (11, false), (12, true), (17, true), (19, false), (21, false), (32, true)]
  , [(1, true), (2, false), (9, false), (11, false), (12, true), (17, true), (32, false)]
  , [(1, true), (3, false), (5, true), (8, true), (11, true), (22, true), (32, true), (34, false)]
  , [(1, true), (2, false), (3, false), (11, false), (17, false), (24, false), (32, true)]
  , [(1, true), (2, true), (11, true), (14, false), (15, true), (19, true), (21, true), (22, false), (29, false), (36, true), (37, true)]
  , [(1, true), (2, true), (3, true), (4, true), (11, false), (12, false), (20, true), (31, true)]
  , [(1, false), (14, true), (21, true), (32, false), (35, true)]
  , [(1, true), (2, false), (10, true), (11, false), (15, false), (17, false), (24, true)]
  , [(1, false), (14, true), (29, true), (31, false), (32, true)]
  , [(1, true), (2, false), (5, false), (8, true), (9, false), (11, false), (12, false), (17, true)]
  , [(1, true), (2, false), (10, true), (11, false), (15, true), (17, false), (24, true)]
  , [(1, false), (6, true), (10, true), (14, true), (18, true), (20, true), (29, false), (32, true)]
  , [(1, true), (3, false), (5, true), (8, false), (10, false), (11, true), (22, true), (32, true)]
  , [(1, false), (13, false), (14, false), (29, false), (32, true), (33, true)]
  , [(1, true), (2, true), (5, false), (11, false), (19, false), (20, true), (31, false)]
  , [(1, true), (2, false), (9, true), (11, false), (17, true), (29, false), (30, true), (32, false)]
  , [(1, false), (4, false), (14, false), (21, false), (31, true), (32, false), (33, true), (35, false)]
  , [(1, true), (2, false), (3, true), (5, true), (10, false), (11, true), (22, true), (26, false), (32, true)]
  , [(1, true), (2, false), (5, true), (9, false), (11, false), (12, false), (17, true)]
  ]

/-- The LRAT refutation: derived clause + database-index hints per step. -/
def steps : List RStep :=
  [ ⟨[(32, true), (29, false), (13, false), (14, false), (1, false)], [73, 126]⟩
  , ⟨[(29, false), (21, false), (14, false), (15, false), (1, false), (4, false), (13, false)], [132, 19, 9, 129, 72]⟩
  , ⟨[(31, true), (21, false), (4, false), (14, false), (15, false), (1, false), (32, false)], [9, 129, 72]⟩
  , ⟨[(21, false), (15, false), (14, false), (4, false), (1, false), (9, false), (13, false)], [133, 83, 134, 81, 34]⟩
  , ⟨[(32, false), (21, true), (10, false), (14, false), (1, false), (9, false)], [25, 70, 88]⟩
  , ⟨[(15, false), (14, false), (13, false), (1, false), (9, false), (10, false), (4, false)], [135, 136, 83, 132]⟩
  , ⟨[(32, true), (14, false), (9, false), (13, false), (1, false), (15, true)], [132, 55]⟩
  , ⟨[(31, false), (29, true), (21, false), (32, false), (14, false), (1, false)], [81, 34]⟩
  , ⟨[(31, true), (14, false), (4, false), (1, false), (32, false), (15, true), (21, false)], [9, 129, 85]⟩
  , ⟨[(14, false), (13, false), (4, false), (10, false), (9, false), (1, false)], [137, 138, 136, 140, 19, 81, 34]⟩
  , ⟨[(32, false), (21, false), (5, false), (7, false), (10, false), (11, false), (14, true), (13, false), (1, false)], [4, 61, 102, 112]⟩
  , ⟨[(29, false), (21, false), (6, false), (14, true), (1, false), (32, true)], [27, 26, 33, 23, 31]⟩
  , ⟨[(37, true), (32, true), (2, false), (3, false), (5, false), (14, true), (1, false), (29, true)], [121, 58, 71, 57]⟩
  , ⟨[(21, false), (13, false), (2, false), (3, false), (5, false), (6, false), (7, false), (10, false), (11, false), (1, false), (14, true)], [142, 143, 121, 144, 86, 56]⟩
  , ⟨[(29, true), (31, true), (7, false), (14, true), (32, true), (1, false), (2, false), (3, false), (5, false)], [144, 86, 56]⟩
  , ⟨[(29, false), (32, true), (2, false), (4, false), (6, false), (12, false), (21, true), (14, true), (1, false)], [27, 10, 105, 16]⟩
  , ⟨[(32, true), (14, true), (2, false), (3, false), (4, false), (5, false), (6, false), (7, false), (12, false), (1, false), (21, true)], [147, 121, 146]⟩
  , ⟨[(13, false), (12, false), (10, false), (11, false), (2, false), (3, false), (4, false), (5, false), (6, false), (7, false), (1, false), (9, false)], [141, 145, 148, 4, 119]⟩
  , ⟨[(17, true), (12, false), (5, false), (9, false), (2, false), (11, false), (1, true)], [100, 122]⟩
  , ⟨[(17, false), (11, false), (2, false), (1, true), (32, false), (10, false)], [43, 47]⟩
  , ⟨[(11, false), (2, false), (5, false), (9, false), (1, true), (32, false), (10, false)], [151, 114, 100, 122]⟩
  , ⟨[(11, true), (5, false), (14, true), (1, true), (13, false)], [14, 74, 49, 42]⟩
  , ⟨[(12, false), (31, true), (4, false), (2, true), (11, false), (1, true)], [84, 32, 67]⟩
  , ⟨[(31, true), (11, false), (4, false), (1, true), (2, true)], [84, 154, 87, 66, 69, 103]⟩
  , ⟨[(5, false), (4, false), (10, false), (1, true), (9, false), (32, false), (14, true), (13, false)], [153, 152, 84, 155, 127, 2]⟩
  , ⟨[(11, false), (2, true), (10, false), (5, true), (4, false), (1, true)], [155, 84, 2, 91, 29, 7, 6, 36]⟩
  , ⟨[(21, true), (19, false), (5, true), (11, true), (32, false), (1, true)], [49, 8]⟩
  , ⟨[(21, false), (11, true), (5, true), (1, true), (32, false)], [74, 62]⟩
  , ⟨[(11, true), (5, true), (32, false), (1, true), (13, false), (14, true)], [159, 8, 28, 158]⟩
  , ⟨[(4, false), (10, false), (9, false), (32, false), (1, true), (13, false), (14, true)], [156, 160, 157, 151, 114, 131]⟩
  , ⟨[(2, false), (5, true), (32, false), (9, false), (10, false), (1, true), (11, false)], [151, 114, 131]⟩
  , ⟨[(31, false), (19, false), (2, true), (11, false), (5, true), (12, false), (1, true)], [84, 91, 7, 6, 36]⟩
  , ⟨[(31, true), (12, false), (4, true), (2, true), (11, false), (1, true)], [84, 67, 118]⟩
  , ⟨[(12, false), (5, true), (4, true), (10, false), (1, true), (11, false), (2, true)], [84, 164, 2, 163]⟩
  , ⟨[(35, true), (14, true), (5, true), (1, false), (32, false)], [119, 106, 77, 111]⟩
  , ⟨[(14, true), (32, false), (10, false), (11, false), (1, false), (5, true)], [166, 4, 93]⟩
  , ⟨[(31, false), (32, false), (1, false), (14, false), (21, false)], [19, 139]⟩
  , ⟨[(4, false), (32, false), (1, false), (14, false), (21, false)], [168, 140, 134]⟩
  , ⟨[(32, false), (11, false), (10, false), (9, false), (1, false), (5, true)], [167, 136, 168, 9, 169, 37, 72, 85]⟩
  , ⟨[(15, true), (14, false), (1, false), (32, true), (9, false)], [55, 138, 73, 65]⟩
  , ⟨[(14, false), (32, true), (1, false), (9, false)], [171, 83, 132, 73, 65]⟩
  , ⟨[(20, true), (6, true), (10, false), (5, true), (14, true), (32, true), (29, false), (1, false)], [64, 24]⟩
  , ⟨[(21, false), (29, false), (10, false), (5, true), (14, true), (32, true), (1, false)], [143, 173, 26, 33, 23, 31]⟩
  , ⟨[(36, true), (20, false), (1, false), (14, true), (32, true), (21, true), (29, false), (2, false)], [10, 75]⟩
  , ⟨[(20, false), (29, false), (1, false), (14, true), (32, true), (2, false), (21, true)], [175, 105, 16, 96]⟩
  , ⟨[(29, false), (32, true), (1, false), (10, false), (5, true), (2, false), (14, true)], [174, 176, 27, 64, 24]⟩
  , ⟨[(37, false), (36, false), (29, true), (14, true), (32, true), (1, false)], [121, 56, 35]⟩
  , ⟨[(37, true), (32, true), (1, false), (5, true), (2, false), (14, true), (29, true)], [121, 90, 58, 71, 20]⟩
  , ⟨[(32, true), (5, true), (1, false), (2, false), (10, false), (9, false)], [172, 177, 121, 179, 86, 56, 35]⟩
  , ⟨[(14, true), (5, true), (1, false), (32, false), (11, true)], [12, 166]⟩
  , ⟨[(5, true), (10, false), (1, false), (9, false), (2, false)], [180, 170, 181, 136, 168, 169, 9, 37, 72, 85]⟩
  , ⟨[(21, false), (32, false), (1, false), (14, false)], [168, 169, 9, 37, 72, 85]⟩
  , ⟨[(38, true), (32, false), (10, false), (1, false), (14, false)], [183, 70, 88]⟩
  , ⟨[(32, false), (11, true), (10, false), (5, true), (1, false)], [181, 183, 136, 184, 5, 89]⟩
  , ⟨[(29, true), (14, false), (10, false), (32, true), (1, false)], [172, 80, 107]⟩
  , ⟨[(14, false), (32, true), (1, false), (10, false)], [186, 132, 73, 65]⟩
  , ⟨[(29, false), (32, true), (1, false), (10, false), (5, true), (2, true)], [187, 174, 40, 27, 173]⟩
  , ⟨[(37, true), (32, true), (1, false), (5, true), (2, true), (14, true), (29, true)], [121, 90, 82, 71, 20]⟩
  , ⟨[(32, true), (5, true), (1, false), (2, true), (10, false)], [187, 188, 121, 189, 86, 56, 35]⟩
  , ⟨[(5, true), (10, false), (1, false), (2, true)], [190, 185, 170, 167, 183, 184, 5, 89]⟩
  , ⟨[(14, false), (32, false), (1, false), (10, false)], [183, 184, 136, 5, 89]⟩
  , ⟨[(35, false), (32, false), (10, false), (11, false), (1, false)], [192, 4, 93]⟩
  , ⟨[(7, true), (36, true), (5, false), (35, true), (14, true), (32, false), (1, false)], [119, 30, 54]⟩
  , ⟨[(7, false), (32, false), (5, false), (1, false), (14, true), (35, true)], [119, 61, 102, 112]⟩
  , ⟨[(32, false), (11, false), (5, false), (10, false), (1, false)], [192, 193, 119, 195, 15, 30, 54]⟩
  , ⟨[(20, true), (29, false), (5, false), (10, false), (32, true), (1, false), (6, true)], [187, 60, 64]⟩
  , ⟨[(29, false), (24, false), (5, false), (10, false), (32, true), (21, false), (36, true), (1, false)], [187, 143, 197, 33, 23]⟩
  , ⟨[(29, true), (36, true), (1, false), (5, false), (14, true), (32, true), (2, true)], [121, 86, 90, 82, 71, 57]⟩
  , ⟨[(36, true), (21, false), (1, false), (10, false), (32, true), (2, true)], [191, 187, 199, 143, 197, 198, 33, 31]⟩
  , ⟨[(14, false), (1, false), (10, false)], [192, 187]⟩
  , ⟨[(22, false), (19, false), (1, true), (11, true)], [49, 74]⟩
  , ⟨[(11, true), (5, false), (1, true), (22, true)], [98, 14]⟩
  , ⟨[(5, true), (9, false), (1, false), (10, false)], [182, 191]⟩
  , ⟨[(29, false), (13, false), (1, false), (14, false), (32, true)], [126, 73]⟩
  , ⟨[(22, true), (1, true), (5, true), (11, true), (32, false)], [8, 159]⟩
  , ⟨[(9, false), (10, false), (32, false), (1, false), (14, false)], [136, 183]⟩
  , ⟨[(22, true), (1, true), (5, true), (11, true), (32, false)], [62, 206]⟩
  , ⟨[(11, false), (4, false), (10, false), (5, true), (2, true)], [157, 191]⟩
  , ⟨[(19, false), (5, true), (11, true), (32, false), (1, true)], [158, 159]⟩
  , ⟨[(29, false), (1, false), (14, false), (32, true), (33, true)], [65, 132]⟩
  , ⟨[(11, true), (32, false), (1, true), (13, false), (14, true)], [160, 153]⟩
  , ⟨[(12, false), (31, true), (2, true), (11, false), (1, true)], [164, 155]⟩
  , ⟨[(38, true), (30, true), (1, false), (14, false), (32, false)], [70, 183]⟩
  , ⟨[(14, true), (32, false), (10, false), (1, false), (5, true)], [167, 181]⟩
  , ⟨[(9, false), (32, false), (10, false), (1, false), (5, true)], [170, 185]⟩
  , ⟨[(9, false), (21, true), (1, false), (38, false), (14, false)], [25, 172]⟩
  , ⟨[(10, true), (1, false), (14, false), (29, true), (32, true)], [110, 172]⟩
  , ⟨[(7, false), (32, false), (1, false), (14, true), (35, true)], [195, 166]⟩
  , ⟨[(21, false), (29, false), (10, false), (5, true), (32, true), (1, false)], [174, 187]⟩
  , ⟨[(3, true), (17, false), (1, true), (11, false), (2, false), (24, false)], [13, 47]⟩
  , ⟨[(38, false), (1, false), (14, false), (32, false), (21, true), (36, false)], [5, 217]⟩
  , ⟨[(3, false), (12, false), (1, true), (11, false), (2, true), (31, true)], [67, 84]⟩
  , ⟨[(16, false), (29, true), (1, false), (10, false), (14, false), (32, true)], [80, 172]⟩
  , ⟨[(37, false), (1, false), (14, true), (32, true), (29, true), (36, true)], [86, 121]⟩
  , ⟨[(12, true), (37, false), (1, true), (11, false), (2, true), (31, true)], [87, 84]⟩
  , ⟨[(38, true), (1, false), (10, false), (14, false), (32, false), (21, true)], [88, 214]⟩
  , ⟨[(21, true), (9, true), (1, false), (14, false), (32, false), (38, false)], [89, 222]⟩
  , ⟨[(37, true), (3, true), (1, false), (14, true), (32, true), (29, true)], [90, 121]⟩
  , ⟨[(25, true), (35, true), (1, false), (5, true), (14, true), (32, false)], [106, 119]⟩
  , ⟨[(29, true), (1, false), (10, false), (14, false), (9, true), (32, true)], [107, 224]⟩
  , ⟨[(9, true), (1, true), (2, false), (11, false), (17, true), (30, false)], [109, 48]⟩
  , ⟨[(17, false), (24, false), (1, true), (2, false), (3, false), (11, false)], [116, 47]⟩
  , ⟨[(1, true), (2, false), (11, false), (15, false), (17, false), (24, true)], [120, 43]⟩
  , ⟨[(10, true), (1, true), (2, false), (11, false), (17, false), (24, true)], [123, 234]⟩
  , ⟨[(14, false), (1, false), (21, true), (30, false), (32, false), (38, true)], [1, 201]⟩
  , ⟨[(19, true), (1, true), (10, false), (11, false), (2, true), (31, false)], [2, 84]⟩
  , ⟨[(17, true), (12, false), (9, false), (2, false), (11, false), (1, true)], [150, 131]⟩
  , ⟨[(11, false), (5, false), (2, false), (9, false), (32, false), (10, false)], [152, 196]⟩
  , ⟨[(32, false), (5, true), (2, false), (9, false), (10, false), (11, false)], [162, 204]⟩
  , ⟨[(12, false), (4, true), (5, true), (10, false), (11, false), (2, true)], [165, 191]⟩
  , ⟨[(22, false), (19, true), (1, true), (14, true), (5, false), (11, true)], [42, 74]⟩
  , ⟨[(20, false), (29, false), (1, false), (14, true), (32, true), (21, true)], [176, 40]⟩
  , ⟨[(29, false), (32, true), (1, false), (10, false), (5, true), (2, false)], [177, 187]⟩
  , ⟨[(37, true), (32, true), (1, false), (5, true), (14, true), (29, true)], [189, 179]⟩
  , ⟨[(14, false), (11, true), (1, true), (19, true), (22, false), (37, false)], [51, 74]⟩
  , ⟨[(10, true), (1, true), (2, true), (11, false), (19, true), (31, false)], [52, 84]⟩
  , ⟨[(36, true), (5, false), (35, true), (14, true), (32, false), (1, false)], [194, 219]⟩
  , ⟨[(19, false), (1, true), (5, false), (11, false), (31, false), (2, true)], [127, 84]⟩
  , ⟨[(22, false), (19, true), (1, true), (13, false), (14, true), (11, true), (21, true)], [28, 242]⟩
  , ⟨[(3, true), (22, true), (1, true), (5, true), (2, true), (11, true), (32, true)], [108, 101]⟩
  , ⟨[(30, false), (1, false), (5, true), (14, true), (21, false), (32, false), (35, true)], [111, 230]⟩
  , ⟨[(12, false), (1, true), (4, true), (11, false), (2, true), (20, true), (31, true)], [118, 223]⟩
  , ⟨[(18, false), (1, false), (5, true), (14, true), (20, true), (29, false), (32, true)], [24, 27]⟩
  , ⟨[(10, true), (8, true), (1, false), (14, true), (22, false), (32, false), (35, false)], [18, 12]⟩
  , ⟨[(10, true), (1, false), (14, true), (18, true), (20, true), (29, false), (32, true)], [124, 27]⟩
  , ⟨[(9, true), (1, true), (2, false), (11, false), (17, true), (29, false), (32, false)], [128, 232]⟩
  , ⟨[(25, false), (1, false), (5, true), (14, true), (21, false), (32, false), (35, true)], [77, 252]⟩
  , ⟨[(10, true), (1, false), (8, false), (14, true), (28, true), (32, false), (35, false)], [79, 12]⟩
  , ⟨[(20, true), (18, false), (1, false), (14, true), (5, false), (29, false), (32, true)], [60, 27]⟩
  , ⟨[(37, true), (3, false), (2, false), (29, true), (14, true), (1, false), (32, true)], [144, 179]⟩
  , ⟨[(4, false), (1, true), (31, true), (11, false), (2, true), (20, true), (12, false)], [32, 223]⟩
  , ⟨[(20, false), (23, true), (1, false), (14, true), (21, false), (29, false), (32, true)], [33, 26]⟩
  , ⟨[(37, false), (7, true), (1, false), (14, true), (31, true), (32, true), (29, true)], [35, 225]⟩
  , ⟨[(18, true), (20, true), (1, false), (14, true), (6, true), (29, false), (32, true)], [64, 256]⟩
  , ⟨[(7, true), (1, false), (14, true), (5, false), (32, false), (35, true), (21, false)], [15, 248]⟩
  , ⟨[(19, false), (31, false), (1, true), (2, true), (11, false), (20, true), (24, true)], [91, 249]⟩
  , ⟨[(20, true), (10, false), (5, true), (14, true), (32, true), (29, false), (1, false)], [173, 27]⟩
  , ⟨[(8, true), (22, true), (1, true), (5, true), (11, true), (3, false), (32, true)], [0, 115]⟩
  , ⟨[(37, true), (23, false), (1, true), (11, false), (2, true), (31, true), (12, true)], [66, 84]⟩
  , ⟨[(9, true), (1, true), (2, false), (11, false), (17, true), (29, true), (32, false)], [97, 232]⟩
  , ⟨[(37, false), (7, false), (1, false), (14, true), (32, true), (29, true), (31, true)], [56, 225]⟩
  , ⟨[(19, true), (22, false), (1, true), (10, false), (11, true), (14, true), (21, true), (13, true)], [99, 242]⟩
  , ⟨[(20, false), (23, false), (1, false), (14, true), (21, false), (29, false), (24, false), (32, true)], [23, 26]⟩
  , ⟨[(19, false), (12, true), (1, true), (5, true), (2, true), (11, false), (20, true), (31, false)], [29, 267]⟩
  , ⟨[(3, false), (28, false), (2, true), (1, false), (14, true), (29, true), (32, true), (37, true)], [82, 121]⟩
  , ⟨[(20, false), (23, false), (1, false), (14, true), (21, false), (29, false), (32, true), (24, true)], [31, 26]⟩
  , ⟨[(20, false), (18, false), (1, false), (2, false), (14, true), (29, false), (32, true), (36, false)], [105, 26]⟩
  , ⟨[(16, true), (31, false), (1, false), (7, false), (14, true), (21, false), (32, false), (35, true)], [112, 166]⟩
  , ⟨[(17, true), (19, false), (1, true), (2, false), (11, false), (12, true), (21, false), (32, true)], [113, 48]⟩
  , ⟨[(19, true), (22, false), (1, true), (2, false), (11, true), (14, false), (21, true), (36, true)], [38, 246]⟩
  , ⟨[(10, true), (8, true), (1, false), (11, false), (14, true), (24, false), (32, false), (35, false)], [39, 255]⟩
  , ⟨[(38, false), (28, true), (1, false), (37, true), (14, true), (29, true), (32, true), (31, true)], [71, 229]⟩
  , ⟨[(3, true), (22, true), (1, true), (5, true), (10, false), (11, true), (26, false), (32, true)], [130, 251]⟩
  , ⟨[(10, true), (1, false), (8, false), (14, true), (22, true), (28, false), (32, false), (35, false)], [76, 12]⟩
  , ⟨[(12, true), (23, true), (1, true), (11, false), (2, true), (20, true), (7, true), (31, true)], [69, 226]⟩
  , ⟨[(10, true), (11, false), (1, false), (14, true), (22, false), (28, false), (32, false), (35, false)], [94, 255]⟩
  , ⟨[(17, true), (19, false), (1, true), (2, false), (11, false), (12, true), (21, true), (32, true)], [46, 48]⟩
  , ⟨[(12, false), (29, false), (1, false), (20, false), (14, true), (21, true), (32, true), (36, true)], [10, 40]⟩
  , ⟨[(10, true), (5, true), (1, true), (11, true), (13, true), (14, true), (19, true), (22, false)], [11, 74]⟩
  , ⟨[(10, true), (8, true), (1, false), (11, false), (14, true), (24, true), (32, false), (35, false)], [50, 255]⟩
  , ⟨[(17, true), (12, true), (1, true), (2, false), (11, false), (19, true), (20, true), (32, true)], [78, 48]⟩
  , ⟨[(19, true), (4, false), (1, true), (11, true), (14, false), (21, true), (22, false), (36, false)], [21, 246]⟩
  , ⟨[(19, true), (22, false), (1, true), (11, true), (14, false), (21, true), (4, true), (36, false)], [104, 246]⟩
  , ⟨[(28, false), (3, false), (1, false), (37, true), (14, true), (29, true), (32, true), (31, true)], [58, 276]⟩
  , ⟨[(16, true), (1, false), (5, false), (7, false), (14, true), (21, false), (32, false), (35, true)], [102, 279]⟩
  , ⟨[(12, true), (23, true), (1, true), (11, false), (2, true), (20, true), (7, false), (31, true)], [103, 226]⟩
  , ⟨[(28, true), (1, false), (14, true), (5, true), (29, true), (31, true), (32, true), (37, true), (3, false)], [20, 283]⟩
  , ⟨[(8, false), (3, false), (1, true), (5, true), (11, true), (22, true), (24, false), (32, true), (33, false)], [44, 125]⟩
  , ⟨[(8, true), (19, false), (1, true), (5, true), (2, true), (11, false), (12, false), (20, true), (31, false)], [7, 267]⟩
  , ⟨[(8, false), (3, false), (1, true), (5, true), (11, true), (15, false), (22, true), (32, true), (33, true)], [45, 125]⟩
  , ⟨[(28, true), (38, true), (1, false), (3, false), (14, true), (29, true), (32, true), (31, true), (37, true)], [57, 298]⟩
  , ⟨[(8, false), (3, false), (1, true), (5, true), (11, true), (15, true), (22, true), (32, true), (33, true)], [22, 125]⟩
  , ⟨[(36, false), (1, false), (14, true), (4, true), (2, false), (21, true), (29, false), (32, true), (20, false)], [96, 278]⟩
  , ⟨[(19, true), (17, true), (1, true), (2, false), (11, false), (6, true), (12, true), (20, false), (32, true)], [17, 48]⟩
  , ⟨[(17, true), (6, false), (1, true), (2, false), (11, false), (12, true), (19, true), (20, false), (32, true)], [41, 48]⟩
  , ⟨[(8, false), (3, false), (1, true), (5, true), (11, true), (22, true), (24, true), (32, true), (33, false)], [53, 125]⟩
  , ⟨[(3, true), (22, true), (1, true), (5, true), (10, false), (11, true), (26, true), (28, true), (32, true)], [68, 251]⟩
  , ⟨[(19, true), (22, false), (1, true), (2, true), (11, true), (14, false), (21, true), (29, true), (36, true)], [59, 246]⟩
  , ⟨[(4, false), (1, false), (2, false), (36, false), (14, true), (21, true), (29, false), (32, true), (20, false)], [16, 278]⟩
  , ⟨[(3, true), (22, true), (1, true), (4, false), (5, true), (10, false), (11, true), (26, true), (28, false), (32, true)], [95, 251]⟩
  , ⟨[(8, false), (38, true), (1, true), (5, true), (2, true), (11, false), (19, false), (24, false), (31, false), (12, false)], [6, 84]⟩
  , ⟨[(22, false), (19, true), (1, true), (2, true), (11, true), (14, false), (21, true), (15, true), (29, false), (36, true)], [117, 246]⟩
  , ⟨[(15, false), (19, true), (1, true), (2, true), (11, true), (14, false), (21, true), (22, false), (29, false), (36, true)], [3, 246]⟩
  , ⟨[(8, false), (19, false), (1, true), (5, true), (2, true), (11, false), (38, false), (20, true), (31, false), (12, false)], [36, 267]⟩
  , ⟨[(3, true), (7, false), (1, true), (4, true), (5, true), (10, false), (11, true), (22, true), (26, true), (28, false), (32, true)], [92, 251]⟩
  , ⟨[(3, true), (7, true), (1, true), (4, true), (5, true), (10, false), (11, true), (22, true), (26, true), (28, false), (32, true)], [63, 251]⟩
  , ⟨[(1, false), (14, false), (9, false), (21, true)], [217, 172, 183, 214, 236]⟩
  , ⟨[(1, false), (14, false), (9, false)], [318, 201, 183, 218, 73, 211]⟩
  , ⟨[(1, false), (14, false), (32, true)], [172, 201, 218, 73, 211]⟩
  , ⟨[(1, false), (32, false), (10, false)], [201, 215, 196, 12, 119, 219, 266, 193]⟩
  , ⟨[(1, false), (32, false), (14, false)], [183, 319, 228, 214, 236]⟩
  , ⟨[(1, false), (32, false), (14, false), (21, true), (9, true)], [228, 214, 236]⟩
  , ⟨[(1, false), (32, false), (5, false), (35, true)], [322, 119, 219, 266, 248]⟩
  , ⟨[(1, false), (32, false), (14, true), (10, true), (35, false), (8, false)], [259, 321, 322, 12, 287, 285]⟩
  , ⟨[(1, false), (32, false), (14, true), (10, true), (35, false)], [325, 321, 322, 12, 282, 291]⟩
  , ⟨[(1, false), (32, false), (14, true), (10, true)], [326, 322, 119, 166, 266, 219]⟩
  , ⟨[(1, false), (32, false)], [321, 322, 327, 12]⟩
  , ⟨[(1, false), (29, true), (3, false), (37, true)], [328, 320, 121, 295, 302, 283, 276]⟩
  , ⟨[(1, false), (32, true), (14, true), (21, false), (29, false), (20, false)], [263, 328, 320, 274, 277]⟩
  , ⟨[(1, false), (32, true), (14, true), (21, false), (29, false)], [330, 328, 320, 143, 265, 260, 254]⟩
  , ⟨[(1, false), (29, false), (20, false), (36, false)], [328, 320, 243, 26, 278]⟩
  , ⟨[(1, false), (29, false)], [328, 320, 331, 243, 27, 265, 260, 254, 332]⟩
  , ⟨[(1, false), (37, false)], [328, 333, 320, 178, 225, 272]⟩
  , ⟨[(1, true), (5, true), (11, false), (2, true), (19, false), (31, false), (20, true)], [275, 213, 163]⟩
  , ⟨[(1, true), (10, false), (11, false), (2, false), (17, false)], [43, 233, 221]⟩
  , ⟨[(1, true), (10, false), (11, false), (2, true), (31, false)], [237, 84, 249, 335]⟩
  , ⟨[(1, true), (10, false), (11, false), (2, true)], [337, 84, 213, 226, 270, 286, 297]⟩
  , ⟨[(1, true), (10, false), (32, true), (5, true), (11, true), (22, true), (3, false)], [125, 269, 284, 308, 311, 316, 317]⟩
  , ⟨[(1, true), (10, false), (32, true), (5, true), (11, true), (22, true)], [339, 284, 308, 311, 316, 317]⟩
  , ⟨[(1, true), (10, false), (32, true), (5, true), (11, true), (22, true), (3, true)], [284, 308, 311, 316, 317]⟩
  , ⟨[(1, true), (11, false), (2, false), (10, true), (17, false)], [235, 233, 221]⟩
  , ⟨[(1, true), (11, false), (2, false), (17, true), (9, true)], [232, 48, 257, 271]⟩
  , ⟨[(1, true), (11, false), (2, true), (5, false), (19, false)], [249, 84, 213, 226, 270, 286, 297]⟩
  , ⟨[(1, true), (11, false), (2, true), (5, false)], [344, 84, 338, 247, 213, 226, 270, 286, 297]⟩
  , ⟨[(1, true), (11, false), (2, true), (31, true), (37, true), (12, true)], [270, 84, 213, 286, 297]⟩
  , ⟨[(1, true), (11, false), (2, true), (31, true), (37, true)], [346, 84, 338, 345, 213, 247, 335]⟩
  , ⟨[(1, true), (11, false), (9, false), (2, false), (12, false)], [238, 336, 342]⟩
  , ⟨[(1, true), (14, false), (11, true), (2, false), (22, false), (21, true), (19, true)], [281, 74, 202, 294, 293]⟩
  , ⟨[(1, true), (14, false), (11, true), (2, true), (29, false), (22, false), (21, true), (19, true), (36, true)], [314, 74, 202, 313, 294, 293]⟩
  , ⟨[(1, true), (14, false), (11, true), (2, true), (29, false), (22, false), (21, true), (19, true)], [350, 74, 202, 294, 293]⟩
  , ⟨[(1, true), (14, false), (11, true), (2, true), (29, true), (22, false), (21, true), (19, true)], [309, 74, 202, 294, 293]⟩
  , ⟨[(1, true), (11, false), (2, false), (17, false)], [336, 342, 47]⟩
  , ⟨[(1, true), (32, false), (11, false), (9, false), (2, false), (17, true)], [114, 348, 84, 338, 345, 213, 247, 335]⟩
  , ⟨[(1, true), (32, true), (5, true), (11, true), (22, true), (3, true)], [251, 340, 101]⟩
  , ⟨[(1, true), (32, true), (5, true), (11, true), (22, true), (3, false), (15, false), (33, true)], [301, 340, 101, 269]⟩
  , ⟨[(1, true), (32, true), (5, true), (11, true), (22, true), (3, false), (15, false)], [356, 340, 101, 269, 307, 299]⟩
  , ⟨[(1, true), (32, true), (5, true), (11, true), (22, true), (3, false)], [357, 340, 101, 269, 303, 307, 299]⟩
  , ⟨[(1, true), (32, true), (11, false), (2, false), (20, false), (19, true), (17, true), (12, true)], [306, 353, 343, 348, 305, 288, 280]⟩
  , ⟨[(1, true), (10, false), (11, true), (14, true), (22, false), (19, true), (21, true)], [273, 153, 212, 340, 74, 202, 250]⟩
  , ⟨[(1, true), (10, false), (11, true), (14, true), (22, false), (19, true)], [360, 74, 203, 208, 340]⟩
  , ⟨[(1, true), (10, false), (11, true), (14, true), (22, false)], [361, 202, 203, 208, 340]⟩
  , ⟨[(1, true), (10, false), (11, true), (14, true)], [362, 203, 208, 340]⟩
  , ⟨[(1, true), (10, false), (32, true), (5, true), (11, true)], [340, 363, 74, 202, 349, 351, 352]⟩
  , ⟨[(1, true), (11, false), (2, true), (31, true)], [155, 347, 213, 226]⟩
  , ⟨[(1, true), (11, false), (2, true)], [84, 338, 345, 365, 247, 335, 267]⟩
  , ⟨[(1, true), (11, false), (32, true), (2, false), (19, false), (17, true), (21, true)], [288, 366, 353, 343, 348]⟩
  , ⟨[(1, true), (11, false), (32, true), (2, false), (19, false), (17, true)], [367, 366, 353, 343, 348, 354, 280, 359, 292]⟩
  , ⟨[(1, true), (11, true), (5, false)], [203, 74, 202, 242, 349, 351, 352]⟩
  , ⟨[(1, true), (14, false), (11, true), (22, false)], [74, 202, 349, 352, 351, 293]⟩
  , ⟨[(1, true), (32, true), (5, true), (11, true), (22, true)], [358, 364, 101, 74, 202, 370, 250, 290]⟩
  , ⟨[(1, true), (32, true), (5, true), (11, true)], [371, 364, 74, 202, 370, 250, 290]⟩
  , ⟨[(1, true), (32, true), (5, true)], [372, 366, 353, 368, 343, 348, 292, 359]⟩
  , ⟨[(1, true), (32, true)], [373, 369, 366, 353, 368, 343, 348, 292, 359]⟩
  , ⟨[(32, false), (1, true), (5, true), (11, true)], [208, 328, 210, 159, 370, 363, 250, 290]⟩
  , ⟨[(32, false), (1, true), (5, true)], [375, 328, 366, 353, 343, 354]⟩
  , ⟨[(32, false), (1, true)], [376, 328, 369, 366, 353, 343, 354]⟩
  , ⟨[(37, false)], [334, 374, 377]⟩
  , ⟨[(29, false)], [378, 333, 374, 377]⟩
  , ⟨[(14, false), (1, false)], [320, 328]⟩
  , ⟨[(3, false), (1, false), (29, true)], [329, 334]⟩
  , ⟨[(17, false), (1, true), (11, false)], [353, 366]⟩
  , ⟨[(5, false), (10, false), (32, false), (11, false)], [196, 377]⟩
  , ⟨[(9, true), (17, true), (1, true), (11, false)], [343, 366]⟩
  , ⟨[(14, true), (31, false), (32, true), (1, false)], [121, 333]⟩
  , ⟨[(10, false), (9, false), (32, false), (14, false)], [207, 377]⟩
  , ⟨[(9, false), (12, false), (1, true), (11, false)], [348, 366]⟩
  , ⟨[(11, true), (19, false), (32, false), (1, true)], [210, 369]⟩
  , ⟨[(21, false), (11, true), (32, false), (1, true)], [159, 369]⟩
  , ⟨[(13, false), (1, true), (14, true), (11, true)], [212, 374]⟩
  , ⟨[(32, false), (5, true), (14, true), (10, false)], [215, 377]⟩
  , ⟨[(32, false), (11, true), (14, true), (5, true)], [181, 377]⟩
  , ⟨[(10, false), (5, true), (32, false), (11, true)], [185, 377]⟩
  , ⟨[(10, false), (36, true), (21, false), (2, true), (1, false)], [200, 328]⟩
  , ⟨[(3, true), (14, true), (1, false), (29, true), (37, true)], [229, 328]⟩
  , ⟨[(9, false), (10, false), (2, false), (32, false), (11, false)], [240, 239]⟩
  , ⟨[(10, false), (5, true), (12, false), (11, false), (2, true)], [241, 209]⟩
  , ⟨[(22, false), (19, true), (1, true), (5, false), (11, true)], [242, 370]⟩
  , ⟨[(5, true), (1, false), (29, false), (32, true), (10, false)], [244, 191]⟩
  , ⟨[(14, true), (36, false), (37, false), (32, true), (1, false)], [178, 333]⟩
  , ⟨[(5, true), (14, true), (1, false), (29, true), (37, true)], [245, 328]⟩
  , ⟨[(13, false), (1, true), (22, false), (14, true), (11, true), (21, true)], [250, 202]⟩
  , ⟨[(32, true), (20, true), (5, true), (10, false), (29, false), (1, false)], [268, 380]⟩
  , ⟨[(5, true), (32, true), (2, false), (29, true), (37, true), (1, false)], [179, 380]⟩
  , ⟨[(2, false), (14, true), (29, true), (37, true), (1, false), (32, true)], [261, 395]⟩
  , ⟨[(2, true), (36, true), (5, false), (14, true), (32, true), (1, false)], [199, 333]⟩
  , ⟨[(22, false), (13, true), (1, true), (11, true), (5, true), (10, true), (19, true)], [290, 370]⟩
  , ⟨[(28, true), (38, false), (1, false), (37, true), (14, true), (29, true), (31, true)], [283, 328]⟩
  , ⟨[(7, false), (2, false), (14, true), (32, true), (1, false), (3, false), (31, true), (5, false)], [146, 333]⟩
  , ⟨[(4, false), (6, false), (2, false), (32, true), (29, false), (12, false), (21, true), (1, false)], [147, 380]⟩
  , ⟨[(13, false), (7, false), (32, false), (5, false), (10, false), (11, false), (14, true), (21, false)], [142, 377]⟩
  , ⟨[(7, false), (6, false), (13, false), (2, false), (5, false), (21, false), (3, false), (10, false), (11, false), (1, false)], [145, 201]⟩
  , ⟨[(1, true)], [374, 377]⟩
  , ⟨[(32, false)], [413, 328]⟩
  , ⟨[(14, false)], [413, 380]⟩
  , ⟨[(3, false)], [413, 379, 381]⟩
  , ⟨[], [378, 379, 413, 415, 416, 395]⟩
  ]

set_option maxHeartbeats 40000000 in
/-- KERNEL replay of the refutation — plain `decide`, no `native_decide`. -/
theorem check_ok : RupCheckerFast.checkRefutationFast F steps = true := by decide

/-- The recovered CNF is unsatisfiable (kernel-checked LRAT replay +
`rup_sound` composition). -/
theorem instance_unsat : ¬ ∃ σ, satFormula σ F :=
  RupCheckerFast.checkRefutationFast_sound F steps check_ok

/-- The gadget's variable set: DIMACS variables `1..38`. -/
def s : Finset ℕ := Finset.Icc 1 38

set_option maxHeartbeats 4000000 in
/-- END-TO-END VERDICT: no point of the `[0,1]` box reaches the sat_relu
gadget's unsafe region `{Y₀ ≥ 1 ∧ Y₁ ≤ 0}` — real-arithmetic SAFE. -/
theorem instance_safe :
    ∀ x : ℕ → ℝ, (∀ j ∈ s, 0 ≤ x j ∧ x j ≤ 1) →
      ¬ (1 ≤ SatRelu.Y0 (SatReluVerdict.clausesOf F) x ∧
         SatRelu.Y1 s x ≤ 0) :=
  SatReluVerdict.safe_of_unsat F s (by decide) instance_unsat

end SatReluSweep_v38c132

end Crownproof

/-! ## Trust-base check -/

#print axioms Crownproof.SatReluSweep_v38c132.check_ok
#print axioms Crownproof.SatReluSweep_v38c132.instance_unsat
#print axioms Crownproof.SatReluSweep_v38c132.instance_safe
