/-
MACHINE-GENERATED by `ny-cert`'s `lrat_to_lean` — do not edit.

sat_relu Route A instance transcript:
* DIMACS source : inst.cnf  (p cnf 39 77)
* LRAT source   : inst.lrat  (133 addition steps kept)

The kernel replays the full LRAT refutation with PLAIN `decide`
(no `native_decide`, no extra axioms) through
`RupCheckerFast.checkRefutationFast`, then composes
`checkRefutationFast_sound` (CNF-unsat) with
`SatReluVerdict.safe_of_unsat` (gadget real-arithmetic safety).
-/
import NyProof.SatReluVerdict
import NyProof.RupCheckerFast

namespace Crownproof

namespace SatReluSweep_v39c77

open RupImport.RUP RupChecker

set_option maxRecDepth 65536

/-- The recovered DIMACS formula, literal-for-literal. -/
def F : Formula :=
  [ [(1, true), (2, false), (3, true), (8, false), (14, true), (16, false), (39, true)]
  , [(1, true), (3, false), (21, false), (39, false)]
  , [(1, false), (12, true), (16, true), (27, true), (29, false)]
  , [(1, false), (12, true), (29, true), (32, true), (33, true), (37, false)]
  , [(1, true), (3, true), (8, false), (10, true), (13, true), (14, false), (26, false)]
  , [(1, false), (6, true), (12, false), (14, true), (21, true), (29, true)]
  , [(1, true), (3, true), (8, true), (16, false), (20, false), (22, false), (24, true)]
  , [(1, false), (5, true), (8, false), (12, true), (16, false), (19, true), (25, false), (29, false)]
  , [(1, true), (3, true), (4, true), (8, false), (10, true), (14, false), (26, true)]
  , [(1, false), (12, true), (29, true), (32, true), (33, false), (35, false)]
  , [(1, false), (8, true), (12, true), (16, false), (24, true), (29, false), (30, false), (31, true)]
  , [(1, false), (8, true), (12, true), (15, true), (16, false), (24, true), (29, false), (30, true)]
  , [(1, false), (5, false), (8, false), (12, true), (16, false), (28, true), (29, false), (32, true), (39, true)]
  , [(1, true), (3, true), (8, false), (14, true), (16, true)]
  , [(1, true), (3, true), (8, true), (16, false), (20, true), (22, false)]
  , [(1, false), (5, true), (8, false), (12, true), (16, false), (24, false), (25, true), (29, false), (30, true)]
  , [(1, false), (5, false), (8, false), (10, false), (12, true), (16, false), (28, false), (29, false), (31, true)]
  , [(1, false), (8, true), (12, true), (16, false), (24, true), (29, false), (30, false), (31, false), (33, false)]
  , [(1, true), (3, true), (8, true), (16, false), (20, false), (22, false), (24, false)]
  , [(1, false), (6, false), (12, false), (14, true), (21, true), (29, true)]
  , [(1, true), (3, false), (16, true), (19, true), (23, true), (33, false), (35, true), (37, true), (39, true)]
  , [(1, true), (3, true), (8, true), (21, true), (22, true)]
  , [(1, false), (5, false), (8, false), (10, true), (12, true), (16, false), (28, false), (29, false), (31, true)]
  , [(1, false), (8, true), (12, true), (16, false), (24, true), (29, false), (30, false), (31, false), (33, true)]
  , [(1, false), (12, true), (27, false), (29, true), (30, false), (32, false)]
  , [(1, false), (8, true), (12, true), (16, false), (24, false), (29, false)]
  , [(1, false), (5, false), (8, false), (12, true), (16, false), (18, false), (28, true), (29, false), (39, false)]
  , [(1, false), (8, true), (12, true), (15, false), (16, false), (24, true), (29, false), (30, true)]
  , [(1, true), (3, false), (16, true), (19, true), (23, true), (33, true), (35, true), (37, true), (39, true)]
  , [(1, false), (12, true), (27, true), (29, true), (32, false)]
  , [(1, false), (4, true), (7, false), (9, true), (12, false), (29, false)]
  , [(1, false), (7, true), (9, false), (12, false), (29, false)]
  , [(1, false), (5, true), (8, false), (12, true), (16, false), (24, false), (25, true), (29, false), (30, false)]
  , [(1, true), (3, true), (8, false), (10, true), (13, false), (14, false), (26, false)]
  , [(1, true), (3, false), (16, false), (23, true), (38, true), (39, true)]
  , [(1, false), (7, true), (12, true), (27, false), (29, true), (30, true), (32, false)]
  , [(1, true), (3, false), (4, false), (20, true), (21, false), (23, false), (39, true)]
  , [(1, true), (3, false), (9, false), (16, true), (23, true), (35, true), (37, false), (39, true)]
  , [(1, true), (3, false), (9, true), (16, true), (23, true), (35, true), (37, false), (39, true)]
  , [(1, true), (3, false), (10, false), (16, true), (19, false), (23, true), (35, true), (37, true), (39, true)]
  , [(1, true), (3, true), (8, true), (21, false), (22, true)]
  , [(1, false), (12, false), (21, false), (29, true), (38, true)]
  , [(1, false), (5, true), (8, false), (12, true), (16, false), (24, true), (25, true), (29, false)]
  , [(1, true), (3, false), (16, true), (23, true), (35, false), (39, true)]
  , [(1, false), (5, false), (8, false), (12, true), (16, false), (26, false), (28, true), (29, false), (32, false), (39, true)]
  , [(1, false), (7, false), (9, false), (12, false), (29, false)]
  , [(1, true), (3, false), (11, false), (20, false), (21, false), (23, false), (39, true)]
  , [(1, false), (12, false), (14, false), (21, true), (29, true), (36, true)]
  , [(1, false), (12, false), (14, false), (21, true), (29, true), (36, false), (38, false)]
  , [(1, true), (3, false), (21, true), (39, false)]
  , [(1, false), (7, false), (12, true), (27, false), (29, true), (30, true), (32, false)]
  , [(1, false), (12, false), (14, false), (21, true), (28, true), (29, true), (36, false), (38, true)]
  , [(1, false), (12, false), (14, true), (21, false), (29, true), (38, false)]
  , [(1, false), (12, true), (29, true), (32, true), (33, false), (35, true)]
  , [(1, true), (2, true), (3, true), (8, false), (14, true), (16, false), (36, false), (39, true)]
  , [(1, false), (5, false), (8, false), (12, true), (16, false), (18, true), (28, true), (29, false), (39, false)]
  , [(1, true), (3, false), (21, true), (23, false), (39, true)]
  , [(1, true), (3, true), (8, true), (16, true), (22, false)]
  , [(1, false), (5, true), (8, false), (12, true), (16, false), (19, false), (25, false), (29, false)]
  , [(1, false), (12, true), (16, true), (27, false), (29, false)]
  , [(1, true), (3, false), (11, true), (20, false), (21, false), (23, false), (39, true)]
  , [(1, false), (4, false), (9, true), (12, false), (29, false)]
  , [(1, false), (12, true), (29, true), (32, true), (33, true), (37, true)]
  , [(1, false), (5, false), (8, false), (10, false), (12, true), (16, false), (28, false), (29, false), (31, false)]
  , [(1, true), (3, true), (8, false), (14, true), (16, false), (39, false)]
  , [(1, false), (5, false), (8, false), (12, true), (16, false), (26, true), (28, true), (29, false), (32, false), (39, true)]
  , [(1, true), (3, true), (4, false), (8, false), (10, true), (14, false), (26, true)]
  , [(1, true), (3, false), (4, true), (20, true), (21, false), (23, false), (39, true)]
  , [(1, false), (4, true), (7, true), (9, true), (12, false), (17, true), (29, false)]
  , [(1, false), (5, false), (8, false), (10, true), (12, true), (16, false), (28, false), (29, false), (31, false)]
  , [(1, false), (4, true), (7, true), (9, true), (12, false), (17, false), (29, false)]
  , [(1, true), (3, false), (10, true), (16, true), (19, false), (23, true), (35, true), (37, true), (39, true)]
  , [(1, false), (12, false), (14, false), (21, false), (29, true), (38, false)]
  , [(1, true), (3, false), (16, false), (23, true), (38, false), (39, true)]
  , [(1, false), (12, false), (14, false), (21, true), (28, false), (29, true), (36, false), (38, true)]
  , [(1, true), (3, true), (8, false), (10, false), (14, false)]
  , [(1, true), (2, true), (3, true), (8, false), (14, true), (16, false), (36, true), (39, true)]
  ]

/-- The LRAT refutation: derived clause + database-index hints per step. -/
def steps : List RStep :=
  [ ⟨[(21, false), (14, false), (29, true), (12, false), (1, false)], [41, 72]⟩
  , ⟨[(14, false), (12, false), (1, false), (29, true)], [77, 47, 48, 51, 74]⟩
  , ⟨[(12, false), (9, false), (6, false), (7, false), (1, false)], [45, 78, 19, 41, 52]⟩
  , ⟨[(33, false), (32, true), (12, true), (29, true), (1, false)], [9, 53]⟩
  , ⟨[(32, true), (29, true), (12, true), (1, false)], [80, 3, 62]⟩
  , ⟨[(29, true), (12, true), (7, false), (1, false)], [81, 29, 24, 50]⟩
  , ⟨[(10, false), (28, false), (5, false), (8, false), (29, false), (12, true), (16, false), (1, false)], [16, 63]⟩
  , ⟨[(28, false), (16, false), (5, false), (8, false), (29, false), (12, true), (1, false)], [83, 22, 69]⟩
  , ⟨[(39, true), (32, false), (5, false), (8, false), (29, false), (12, true), (16, false), (1, false)], [84, 44, 65]⟩
  , ⟨[(39, false), (16, false), (5, false), (8, false), (29, false), (12, true), (1, false)], [84, 26, 55]⟩
  , ⟨[(16, false), (12, true), (5, false), (8, false), (1, false), (29, false)], [84, 86, 12, 44, 65]⟩
  , ⟨[(12, true), (8, false), (5, false), (1, false), (7, false)], [82, 87, 2, 59]⟩
  , ⟨[(12, false), (7, false), (6, false), (4, false), (1, false)], [79, 61, 78, 19, 41, 52]⟩
  , ⟨[(30, true), (16, false), (8, true), (29, false), (12, true), (1, false)], [25, 11, 27]⟩
  , ⟨[(16, false), (12, true), (1, false), (29, false), (8, true)], [25, 90, 10, 17, 23]⟩
  , ⟨[(7, false), (6, false), (5, false), (1, false), (4, false)], [89, 82, 88, 91, 2, 59]⟩
  , ⟨[(23, false), (11, false), (3, false), (21, false), (1, true), (39, true), (4, false)], [36, 46]⟩
  , ⟨[(23, true), (3, false), (16, true), (10, true), (1, true), (35, true), (37, true), (39, true), (33, true)], [28, 71]⟩
  , ⟨[(3, false), (35, true), (21, false), (39, true), (4, false), (16, true), (10, true), (1, true), (37, true), (33, true)], [94, 36, 93, 60]⟩
  , ⟨[(3, true), (21, false), (8, true), (16, true), (1, true)], [40, 57]⟩
  , ⟨[(23, false), (21, false), (4, false), (1, true), (3, false)], [1, 36, 93, 60]⟩
  , ⟨[(21, false), (9, true), (16, true), (33, true), (1, true), (4, false), (8, true)], [96, 1, 97, 43, 38, 28, 94, 39]⟩
  , ⟨[(3, false), (35, true), (16, true), (33, true), (21, true), (9, true), (39, true), (1, true)], [56, 38, 28, 94, 39]⟩
  , ⟨[(3, true), (21, true), (8, true), (16, true), (1, true)], [21, 57]⟩
  , ⟨[(9, true), (33, true), (16, true), (1, true), (8, true), (4, false)], [98, 100, 49, 56, 99, 43]⟩
  , ⟨[(21, true), (33, true), (8, true), (16, true), (1, true), (9, false)], [100, 49, 56, 43, 37, 28, 94, 39]⟩
  , ⟨[(33, true), (16, true), (1, true), (4, false), (8, true)], [101, 102, 96, 97, 1, 43, 37, 95, 28, 39]⟩
  , ⟨[(37, true), (3, false), (33, false), (16, true), (1, true), (23, true), (39, true)], [43, 20, 71, 39]⟩
  , ⟨[(21, false), (16, true), (8, true), (4, false), (1, true)], [103, 96, 97, 1, 43, 104, 38, 37]⟩
  , ⟨[(16, true), (4, false), (8, true), (1, true)], [103, 105, 100, 49, 56, 104, 43, 38, 37]⟩
  , ⟨[(3, false), (39, true), (16, false), (1, true), (21, true)], [56, 34, 73]⟩
  , ⟨[(3, true), (21, true), (8, true), (16, false), (1, true)], [21, 14, 6, 18]⟩
  , ⟨[(21, true), (16, false), (1, true), (8, true)], [108, 49, 107]⟩
  , ⟨[(12, true), (7, false), (16, true), (1, false)], [82, 2, 59]⟩
  , ⟨[(7, false), (9, false), (21, true), (1, false), (16, true)], [110, 79, 45, 5, 78]⟩
  , ⟨[(12, false), (9, false), (21, true), (1, false), (7, true)], [31, 78, 19, 5]⟩
  , ⟨[(29, true), (7, true), (1, false), (12, true)], [81, 29, 24, 35]⟩
  , ⟨[(9, false), (21, true), (16, true), (1, false)], [111, 112, 113, 2, 59]⟩
  , ⟨[(12, true), (7, true), (16, true), (1, false)], [113, 2, 59]⟩
  , ⟨[(12, false), (21, true), (4, false), (1, false), (9, true)], [61, 78, 19, 5]⟩
  , ⟨[(12, true), (16, true), (1, false)], [110, 115]⟩
  , ⟨[(21, true), (16, true), (4, false), (1, false)], [117, 114, 116]⟩
  , ⟨[(29, true), (12, false), (1, false), (21, false)], [78, 41, 52]⟩
  , ⟨[(16, true), (4, false), (1, false)], [117, 118, 119, 61, 31, 45]⟩
  , ⟨[(29, false), (12, false), (1, false), (4, false)], [61, 31, 45]⟩
  , ⟨[(12, false), (4, false), (1, false)], [121, 78, 119, 19, 5]⟩
  , ⟨[(29, true), (12, true), (1, false)], [82, 113]⟩
  , ⟨[(25, false), (4, false), (1, false)], [122, 120, 123, 91, 87, 7, 58]⟩
  , ⟨[(4, false), (1, false)], [120, 122, 123, 91, 87, 124, 42, 15, 32]⟩
  , ⟨[(25, false), (12, true), (1, false)], [117, 123, 91, 87, 7, 58]⟩
  , ⟨[(12, true), (1, false)], [117, 123, 91, 87, 126, 42, 15, 32]⟩
  , ⟨[(7, true), (29, false), (1, false)], [127, 125, 31, 68, 70]⟩
  , ⟨[(29, false), (1, false)], [127, 125, 128, 30, 45]⟩
  , ⟨[(1, false)], [127, 129, 78, 119, 19, 5]⟩
  , ⟨[(39, true), (16, false), (21, true), (14, true), (2, true)], [130, 109, 107, 54, 76]⟩
  , ⟨[(16, false), (14, true), (21, true), (2, true)], [130, 109, 131, 49, 64]⟩
  , ⟨[(37, true), (3, false), (16, true), (39, true), (23, true)], [130, 43, 104, 28, 94, 39]⟩
  , ⟨[(3, false), (16, true), (21, true)], [130, 49, 56, 43, 133, 38, 37]⟩
  , ⟨[(14, true), (21, true), (2, true)], [130, 132, 134, 13, 21, 57]⟩
  , ⟨[(26, false), (3, true), (14, false), (8, false)], [130, 75, 4, 33]⟩
  , ⟨[(16, true), (14, false), (21, true)], [130, 134, 100, 75, 136, 8, 66]⟩
  , ⟨[(3, true), (8, false), (14, false)], [130, 136, 75, 8, 66]⟩
  , ⟨[(21, true), (2, true)], [130, 135, 137, 109, 138, 49, 107]⟩
  , ⟨[(23, true), (3, false), (16, false), (39, true)], [130, 34, 73]⟩
  , ⟨[(3, false), (16, false), (21, false)], [130, 1, 140, 97, 67, 60, 46]⟩
  , ⟨[(16, false), (14, false), (21, false)], [130, 141, 138, 40, 14, 6, 18]⟩
  , ⟨[(37, true), (3, false), (39, true), (23, true)], [133, 140]⟩
  , ⟨[(3, false), (21, false), (39, false)], [1, 130]⟩
  , ⟨[(3, false), (21, false), (39, true), (23, false), (4, true), (20, true)], [67, 130]⟩
  , ⟨[(3, false), (21, false), (39, true), (23, false), (20, false), (11, false)], [46, 130]⟩
  , ⟨[(3, false), (21, false), (39, true), (23, false), (20, false), (11, true)], [60, 130]⟩
  , ⟨[(4, false), (3, false), (21, false), (39, true), (23, false), (20, true)], [36, 130]⟩
  , ⟨[(4, false), (14, false), (3, true), (8, false), (10, true), (26, true)], [66, 130]⟩
  , ⟨[(14, false), (3, true), (8, false), (4, true), (10, true), (26, true)], [8, 130]⟩
  , ⟨[(14, false), (3, true), (8, false), (10, false)], [75, 130]⟩
  , ⟨[(14, false), (3, true), (8, false), (26, false), (10, true), (13, false)], [33, 130]⟩
  , ⟨[(14, false), (3, true), (8, false), (26, false), (10, true), (13, true)], [4, 130]⟩
  , ⟨[(16, false), (3, false), (39, true), (23, true), (38, false)], [73, 130]⟩
  , ⟨[(16, false), (3, false), (39, true), (23, true), (38, true)], [34, 130]⟩
  , ⟨[(16, false), (3, true), (2, true), (8, false), (39, true), (14, true), (36, false)], [54, 130]⟩
  , ⟨[(16, false), (3, true), (2, true), (8, false), (39, true), (14, true), (36, true)], [76, 130]⟩
  , ⟨[(16, false), (3, true), (8, false), (14, true), (39, false)], [64, 130]⟩
  , ⟨[(16, false), (3, true), (8, false), (39, true), (14, true), (2, false)], [0, 130]⟩
  , ⟨[(16, false), (3, true), (8, true), (22, false), (20, false), (24, false)], [18, 130]⟩
  , ⟨[(16, false), (3, true), (8, true), (22, false), (20, false), (24, true)], [6, 130]⟩
  , ⟨[(16, false), (3, true), (8, true), (22, false), (20, true)], [14, 130]⟩
  , ⟨[(16, true), (3, false), (39, true), (9, false), (23, true), (35, true), (37, false)], [37, 130]⟩
  , ⟨[(16, true), (3, false), (39, true), (23, true), (9, true), (35, true), (37, false)], [38, 130]⟩
  , ⟨[(16, true), (3, false), (39, true), (23, true), (33, true), (37, true), (35, true), (19, true)], [28, 130]⟩
  , ⟨[(16, true), (3, false), (39, true), (23, true), (35, false)], [43, 130]⟩
  , ⟨[(16, true), (3, false), (39, true), (23, true), (37, true), (10, false), (35, true), (19, false)], [39, 130]⟩
  , ⟨[(16, true), (3, false), (39, true), (23, true), (37, true), (10, true), (35, true), (19, false)], [71, 130]⟩
  , ⟨[(16, true), (3, false), (39, true), (23, true), (37, true), (33, false), (35, true), (19, true)], [20, 130]⟩
  , ⟨[(16, true), (3, true), (8, false), (14, true)], [13, 130]⟩
  , ⟨[(16, true), (3, true), (8, true), (22, false)], [57, 130]⟩
  , ⟨[(21, false), (3, true), (8, true), (22, true)], [40, 130]⟩
  , ⟨[(21, true), (3, false), (39, false)], [49, 130]⟩
  , ⟨[(21, true), (3, false), (39, true), (23, false)], [56, 130]⟩
  , ⟨[(21, true), (3, true), (8, true), (22, true)], [21, 130]⟩
  , ⟨[(3, false), (16, false)], [130, 141, 107, 173, 154]⟩
  , ⟨[(3, true), (21, false), (8, true)], [172, 130, 96, 162, 160, 161]⟩
  , ⟨[(3, true), (21, false)], [177, 138, 170, 158, 159, 156, 157]⟩
  , ⟨[(16, true), (3, false), (39, true), (23, true), (9, false), (35, true)], [163, 130, 134, 144, 143, 97, 145, 146, 147]⟩
  , ⟨[(16, true), (3, false), (39, true), (23, true), (9, true), (35, true)], [164, 130, 134, 144, 143, 97, 145, 146, 147]⟩
  , ⟨[(16, true), (3, false), (39, true), (23, true)], [166, 134, 144, 179, 180]⟩
  , ⟨[(16, true), (3, true), (8, false)], [170, 130, 137, 178, 144, 181, 97, 145, 146, 147]⟩
  , ⟨[(16, true), (3, true)], [130, 178, 100, 182, 171]⟩
  , ⟨[(21, true), (3, false)], [173, 176, 134]⟩
  , ⟨[(3, false), (4, false), (21, false), (23, false)], [97, 130]⟩
  , ⟨[(3, false), (21, false)], [144, 176, 184, 181, 185, 145, 146, 147]⟩
  , ⟨[(3, true), (2, true)], [178, 139, 156]⟩
  , ⟨[(3, true), (16, false), (8, false), (39, true), (14, true)], [159, 139, 187, 186]⟩
  , ⟨[(3, true), (16, false), (8, false), (14, true)], [158, 130, 178, 183, 109, 188, 138]⟩
  , ⟨[(3, false), (16, true)], [134, 186]⟩
  , ⟨[(8, false), (3, true), (16, false)], [189, 138]⟩
  , ⟨[(39, true), (23, true), (16, true)], [181, 183]⟩
  , ⟨[(8, true), (4, false), (16, true)], [106, 130]⟩
  , ⟨[(16, false), (8, true), (21, true)], [109, 130]⟩
  , ⟨[(8, true), (22, true), (3, true)], [175, 178]⟩
  , ⟨[(23, true), (3, false), (39, true)], [140, 192]⟩
  , ⟨[(21, false), (16, true), (8, true), (1, true)], [96, 186]⟩
  , ⟨[(20, true), (22, false), (8, true), (16, false)], [162, 176]⟩
  , ⟨[(22, false), (24, true), (3, true), (8, true), (16, false)], [161, 198]⟩
  , ⟨[(9, false), (33, true), (8, true), (1, true), (21, true)], [102, 194]⟩
  , ⟨[(22, false), (24, false), (3, true), (8, true), (16, false)], [160, 198]⟩
  , ⟨[(9, true), (33, true), (16, true), (35, true), (21, true), (39, true), (1, true)], [99, 183]⟩
  , ⟨[(10, true), (33, true), (16, true), (1, true), (35, true), (23, true), (39, true), (37, true)], [94, 183]⟩
  , ⟨[(3, false)], [176, 190]⟩
  , ⟨[(21, false)], [204, 178]⟩
  , ⟨[(2, true)], [204, 187]⟩
  , ⟨[(16, true)], [204, 183]⟩
  , ⟨[(8, false)], [204, 207, 191]⟩
  , ⟨[], [204, 205, 207, 208, 194]⟩
  ]

set_option maxHeartbeats 40000000 in
/-- KERNEL replay of the refutation — plain `decide`, no `native_decide`. -/
theorem check_ok : RupCheckerFast.checkRefutationFast F steps = true := by decide

/-- The recovered CNF is unsatisfiable (kernel-checked LRAT replay +
`rup_sound` composition). -/
theorem instance_unsat : ¬ ∃ σ, satFormula σ F :=
  RupCheckerFast.checkRefutationFast_sound F steps check_ok

/-- The gadget's variable set: DIMACS variables `1..39`. -/
def s : Finset ℕ := Finset.Icc 1 39

set_option maxHeartbeats 4000000 in
/-- END-TO-END VERDICT: no point of the `[0,1]` box reaches the sat_relu
gadget's unsafe region `{Y₀ ≥ 1 ∧ Y₁ ≤ 0}` — real-arithmetic SAFE. -/
theorem instance_safe :
    ∀ x : ℕ → ℝ, (∀ j ∈ s, 0 ≤ x j ∧ x j ≤ 1) →
      ¬ (1 ≤ SatRelu.Y0 (SatReluVerdict.clausesOf F) x ∧
         SatRelu.Y1 s x ≤ 0) :=
  SatReluVerdict.safe_of_unsat F s (by decide) instance_unsat

end SatReluSweep_v39c77

end Crownproof

/-! ## Trust-base check -/

#print axioms Crownproof.SatReluSweep_v39c77.check_ok
#print axioms Crownproof.SatReluSweep_v39c77.instance_unsat
#print axioms Crownproof.SatReluSweep_v39c77.instance_safe
