/-
MACHINE-GENERATED by `ny-cert`'s `lrat_to_lean` — do not edit.

sat_relu Route A instance transcript:
* DIMACS source : inst.cnf  (p cnf 44 52)
* LRAT source   : inst.lrat  (40 addition steps kept)

The kernel replays the full LRAT refutation with PLAIN `decide`
(no `native_decide`, no extra axioms) through
`RupCheckerFast.checkRefutationFast`, then composes
`checkRefutationFast_sound` (CNF-unsat) with
`SatReluVerdict.safe_of_unsat` (gadget real-arithmetic safety).
-/
import NyProof.SatReluVerdict
import NyProof.RupCheckerFast

namespace Crownproof

namespace SatReluSweep_v44c52

open RupImport.RUP RupChecker

set_option maxRecDepth 65536

/-- The recovered DIMACS formula, literal-for-literal. -/
def F : Formula :=
  [ [(1, true), (2, true), (8, true), (16, false), (22, false), (42, true)]
  , [(1, true), (2, false), (3, false), (16, false), (20, true), (21, false)]
  , [(1, false), (18, false), (28, false), (31, false), (38, true), (42, false)]
  , [(1, true), (8, true), (11, true), (14, false), (16, true), (17, false), (22, false), (27, false)]
  , [(1, false), (11, false), (19, false), (31, true), (40, true), (42, true)]
  , [(1, true), (12, false), (14, true), (16, true), (18, true), (29, true)]
  , [(1, true), (12, true), (14, true), (16, true), (24, true), (28, false), (37, true)]
  , [(1, true), (8, true), (14, false), (16, true), (22, true), (27, false), (42, true)]
  , [(1, true), (12, false), (14, true), (16, true), (18, true), (29, false)]
  , [(1, true), (10, true), (12, true), (14, true), (15, false), (16, true), (23, false), (24, true), (25, true), (28, true)]
  , [(1, true), (8, true), (14, false), (16, true), (27, true), (37, false)]
  , [(1, false), (11, false), (17, false), (19, true), (31, true), (40, true)]
  , [(1, false), (11, false), (31, true), (40, false)]
  , [(1, true), (2, true), (16, false), (22, true), (24, true)]
  , [(1, false), (4, true), (11, false), (17, true), (19, true), (31, true), (32, false), (39, false), (40, true)]
  , [(1, false), (11, true), (31, true), (40, false)]
  , [(1, true), (2, false), (3, true), (16, false), (20, true), (32, true), (40, false)]
  , [(1, true), (2, false), (3, true), (16, false), (20, true), (32, false), (40, false)]
  , [(1, true), (2, false), (3, false), (16, false), (20, true), (21, true)]
  , [(1, true), (2, true), (8, false), (16, false), (22, false), (42, true)]
  , [(1, true), (2, false), (3, true), (16, false), (20, true), (40, true)]
  , [(1, true), (8, true), (11, false), (14, false), (16, true), (22, false), (27, false)]
  , [(1, true), (12, true), (14, true), (16, true), (24, false)]
  , [(1, true), (12, false), (14, true), (16, true), (18, false)]
  , [(1, true), (12, true), (14, true), (16, true), (24, true), (28, false), (37, false)]
  , [(1, true), (2, false), (6, false), (16, false), (20, false)]
  , [(1, true), (2, true), (16, false), (22, true), (24, false), (27, false)]
  , [(1, true), (2, false), (6, true), (16, false), (20, false)]
  , [(1, false), (28, true), (31, false), (43, false)]
  , [(1, true), (12, true), (14, true), (15, false), (16, true), (23, true), (24, true), (25, true), (28, true)]
  , [(1, false), (28, true), (31, false), (33, false), (43, true)]
  , [(1, false), (11, false), (19, false), (31, true), (40, true), (42, false)]
  , [(1, true), (8, false), (14, false), (15, false), (16, true)]
  , [(1, true), (8, true), (14, false), (16, true), (22, true), (27, false), (42, false)]
  , [(1, true), (10, false), (12, true), (14, true), (15, false), (16, true), (23, false), (24, true), (25, true), (28, true)]
  , [(1, true), (2, true), (16, false), (22, true), (24, false), (27, true)]
  , [(1, false), (11, false), (17, true), (19, true), (31, true), (32, true), (40, true)]
  , [(1, true), (12, true), (14, true), (15, false), (16, true), (24, true), (25, false), (28, true)]
  , [(1, false), (4, false), (9, false), (11, false), (17, true), (19, true), (31, true), (32, false), (39, true), (40, true)]
  , [(1, true), (2, true), (16, false), (22, false), (42, false)]
  , [(1, true), (12, true), (14, true), (15, true), (16, true), (24, true), (28, true)]
  , [(1, true), (8, false), (14, false), (15, true), (16, true)]
  , [(1, false), (4, false), (11, false), (17, true), (19, true), (31, true), (32, false), (39, false), (40, true)]
  , [(1, true), (8, true), (14, false), (16, true), (27, true), (37, true)]
  , [(1, false), (4, true), (11, false), (17, true), (19, true), (31, true), (32, false), (39, true), (40, true)]
  , [(1, true), (8, true), (11, true), (14, false), (16, true), (17, true), (22, false), (27, false)]
  , [(1, false), (4, false), (9, true), (11, false), (17, true), (19, true), (31, true), (32, false), (39, true), (40, true)]
  , [(1, false), (28, true), (31, false), (33, true), (43, true)]
  , [(1, false), (18, false), (28, false), (31, false), (38, false), (42, false)]
  , [(1, false), (11, true), (31, true), (40, true)]
  , [(1, false), (18, true), (28, false), (31, false), (42, false)]
  , [(1, false), (28, false), (31, false), (42, true)]
  ]

/-- The LRAT refutation: derived clause + database-index hints per step. -/
def steps : List RStep :=
  [ ⟨[(31, false), (28, false), (18, false), (1, false)], [51, 2, 48]⟩
  , ⟨[(31, true), (19, false), (11, false), (1, false)], [12, 4, 31]⟩
  , ⟨[(31, false), (18, false), (1, false)], [52, 28, 30, 47]⟩
  , ⟨[(31, true), (17, false), (1, false), (11, false)], [12, 11, 53]⟩
  , ⟨[(28, true), (31, false), (1, false)], [28, 30, 47]⟩
  , ⟨[(31, false), (1, false)], [54, 56, 50, 51]⟩
  , ⟨[(4, false), (11, false), (1, false)], [57, 12, 53, 55, 36, 42, 38, 46]⟩
  , ⟨[(11, false), (1, false)], [57, 12, 53, 55, 36, 58, 14, 44]⟩
  , ⟨[(1, false)], [57, 59, 15, 49]⟩
  , ⟨[(16, false), (6, false), (3, false), (2, false)], [60, 25, 1, 18]⟩
  , ⟨[(14, false), (8, false), (16, true)], [60, 32, 41]⟩
  , ⟨[(12, false), (14, true), (18, true), (16, true)], [60, 5, 8]⟩
  , ⟨[(14, true), (16, true), (28, false), (18, true)], [60, 63, 22, 6, 24]⟩
  , ⟨[(27, false), (16, true), (17, true), (42, true), (11, true), (14, false)], [60, 62, 7, 45]⟩
  , ⟨[(16, true), (42, true), (17, true), (11, true), (28, false), (18, true)], [60, 64, 62, 65, 10, 43]⟩
  , ⟨[(3, false), (16, false), (2, false)], [60, 61, 27, 1, 18]⟩
  , ⟨[(16, false), (40, true), (2, false)], [60, 67, 20, 25, 27]⟩
  , ⟨[(27, false), (17, true), (16, true), (14, false), (11, true), (42, false)], [60, 62, 33, 45]⟩
  , ⟨[(27, true), (14, false), (16, true)], [60, 62, 10, 43]⟩
  , ⟨[(17, true), (28, false), (16, true), (18, true), (11, true)], [64, 70, 66, 69]⟩
  , ⟨[(28, false), (18, true), (11, true), (16, true)], [60, 64, 62, 70, 71, 3, 7, 33]⟩
  , ⟨[(14, false), (42, false), (16, true), (11, true), (17, false)], [60, 62, 70, 3, 33]⟩
  , ⟨[(14, true), (18, true), (16, true), (28, true)], [60, 63, 22, 40, 37, 29, 9, 34]⟩
  , ⟨[(17, false), (14, false), (16, true), (11, true)], [60, 70, 62, 73, 3, 7]⟩
  , ⟨[(14, false), (16, true), (11, true)], [70, 75, 69, 65]⟩
  , ⟨[(22, true), (27, false), (16, false), (2, true)], [60, 13, 26]⟩
  , ⟨[(22, false), (42, true), (16, false), (2, true)], [60, 0, 19]⟩
  , ⟨[(22, true), (16, false), (2, true)], [60, 13, 77, 35]⟩
  , ⟨[(16, false), (2, true)], [60, 79, 39, 0, 19]⟩
  , ⟨[(12, false), (14, true), (16, true)], [60, 23, 63]⟩
  , ⟨[(18, true), (14, true), (16, true)], [74, 64]⟩
  , ⟨[(28, false), (14, true), (16, true)], [60, 81, 22, 6, 24]⟩
  , ⟨[(14, true), (16, true)], [60, 81, 22, 83, 40, 37, 29, 9, 34]⟩
  , ⟨[(16, true)], [60, 84, 62, 70, 76, 21, 7, 33]⟩
  , ⟨[(2, true)], [85, 80]⟩
  , ⟨[(40, true)], [85, 86, 68]⟩
  , ⟨[(3, false)], [85, 86, 67]⟩
  , ⟨[(20, true)], [60, 85, 86, 87, 88, 16, 17]⟩
  , ⟨[(6, false)], [89, 60, 86, 85, 25]⟩
  , ⟨[], [60, 85, 86, 89, 90, 27]⟩
  ]

set_option maxHeartbeats 40000000 in
/-- KERNEL replay of the refutation — plain `decide`, no `native_decide`. -/
theorem check_ok : RupCheckerFast.checkRefutationFast F steps = true := by decide

/-- The recovered CNF is unsatisfiable (kernel-checked LRAT replay +
`rup_sound` composition). -/
theorem instance_unsat : ¬ ∃ σ, satFormula σ F :=
  RupCheckerFast.checkRefutationFast_sound F steps check_ok

/-- The gadget's variable set: DIMACS variables `1..44`. -/
def s : Finset ℕ := Finset.Icc 1 44

set_option maxHeartbeats 4000000 in
/-- END-TO-END VERDICT: no point of the `[0,1]` box reaches the sat_relu
gadget's unsafe region `{Y₀ ≥ 1 ∧ Y₁ ≤ 0}` — real-arithmetic SAFE. -/
theorem instance_safe :
    ∀ x : ℕ → ℝ, (∀ j ∈ s, 0 ≤ x j ∧ x j ≤ 1) →
      ¬ (1 ≤ SatRelu.Y0 (SatReluVerdict.clausesOf F) x ∧
         SatRelu.Y1 s x ≤ 0) :=
  SatReluVerdict.safe_of_unsat F s (by decide) instance_unsat

end SatReluSweep_v44c52

end Crownproof

/-! ## Trust-base check -/

#print axioms Crownproof.SatReluSweep_v44c52.check_ok
#print axioms Crownproof.SatReluSweep_v44c52.instance_unsat
#print axioms Crownproof.SatReluSweep_v44c52.instance_safe
