/-
MACHINE-GENERATED by `ny-cert`'s `lrat_to_lean` — do not edit.

sat_relu Route A instance transcript:
* DIMACS source : inst.cnf  (p cnf 58 75)
* LRAT source   : inst.lrat  (166 addition steps kept)

The kernel replays the full LRAT refutation with PLAIN `decide`
(no `native_decide`, no extra axioms) through
`RupCheckerFast.checkRefutationFast`, then composes
`checkRefutationFast_sound` (CNF-unsat) with
`SatReluVerdict.safe_of_unsat` (gadget real-arithmetic safety).
-/
import NyProof.SatReluVerdict
import NyProof.RupCheckerFast

namespace Crownproof

namespace SatReluSweep_v58c75

open RupImport.RUP RupChecker

set_option maxRecDepth 65536

/-- The recovered DIMACS formula, literal-for-literal. -/
def F : Formula :=
  [ [(1, false), (16, false), (27, true), (39, false), (55, false), (57, false)]
  , [(1, false), (9, false), (17, false), (23, true), (27, false), (35, false), (39, false)]
  , [(1, true), (4, true), (9, false), (14, false), (34, true), (53, true)]
  , [(1, true), (4, false), (17, true), (28, true), (45, true), (53, true), (55, true)]
  , [(1, false), (27, true), (39, false), (51, false), (55, true), (56, true)]
  , [(1, false), (9, false), (17, false), (23, true), (27, false), (35, true), (39, false)]
  , [(1, false), (7, true), (12, true), (39, true), (45, false), (47, false)]
  , [(1, false), (9, true), (13, true), (23, true), (27, false), (32, false), (39, false)]
  , [(1, false), (26, true), (27, true), (32, true), (39, false), (51, true), (55, true)]
  , [(1, false), (9, true), (13, true), (23, true), (27, false), (32, true), (39, false)]
  , [(1, false), (3, false), (9, false), (17, true), (23, true), (27, false), (39, false)]
  , [(1, false), (23, true), (24, true), (27, true), (39, false), (55, false), (57, true), (58, false)]
  , [(1, true), (4, false), (5, true), (24, false), (45, false), (53, true), (57, true)]
  , [(1, false), (3, true), (9, false), (17, true), (23, true), (27, false), (39, false)]
  , [(1, true), (4, false), (45, false), (53, false), (56, true)]
  , [(1, true), (4, true), (9, false), (14, false), (26, true), (28, false), (34, false), (51, false), (53, true)]
  , [(1, true), (4, true), (35, false), (40, true), (53, false)]
  , [(1, false), (20, true), (26, false), (27, true), (32, true), (39, false), (51, true), (55, true)]
  , [(1, false), (20, false), (21, false), (23, false), (27, false), (39, false), (57, false)]
  , [(1, true), (4, false), (45, false), (46, true), (53, true), (57, false)]
  , [(1, true), (4, true), (9, false), (14, false), (26, false), (28, false), (34, false), (51, false), (53, true)]
  , [(1, false), (19, true), (23, false), (27, false), (39, false), (46, true), (52, true), (55, true), (57, true)]
  , [(1, false), (27, true), (32, false), (39, false), (51, true), (55, true)]
  , [(1, true), (4, false), (35, false), (45, true), (53, true), (55, false)]
  , [(1, true), (4, false), (17, true), (28, false), (45, true), (53, true), (55, true)]
  , [(1, false), (20, false), (26, false), (27, true), (32, true), (39, false), (45, false), (51, true), (55, true)]
  , [(1, true), (4, false), (24, true), (35, false), (45, false), (53, true), (57, true)]
  , [(1, false), (19, false), (23, false), (27, false), (39, false), (57, true)]
  , [(1, false), (12, true), (39, true), (45, true), (47, false)]
  , [(1, false), (19, true), (23, false), (27, false), (39, false), (46, true), (52, false), (55, true), (57, true)]
  , [(1, true), (4, true), (35, false), (40, false), (53, false)]
  , [(1, false), (11, true), (39, true), (47, true)]
  , [(1, true), (4, false), (35, true), (45, true), (53, true), (55, false)]
  , [(1, true), (4, false), (30, false), (45, true), (53, false), (56, true)]
  , [(1, true), (4, false), (17, false), (45, true), (53, true), (55, true)]
  , [(1, true), (4, true), (9, false), (14, false), (28, true), (34, false), (51, false), (53, true)]
  , [(1, true), (4, false), (45, false), (46, false), (53, true), (57, false)]
  , [(1, false), (9, true), (13, false), (23, true), (27, false), (39, false)]
  , [(1, false), (16, true), (27, true), (39, false), (55, false), (57, false)]
  , [(1, false), (20, false), (21, true), (23, false), (27, false), (39, false), (57, false)]
  , [(1, true), (4, false), (5, false), (24, false), (45, false), (53, true), (57, true)]
  , [(1, false), (2, false), (23, false), (27, true), (39, false), (55, false), (57, true)]
  , [(1, false), (19, true), (23, false), (27, false), (39, false), (55, false), (57, true)]
  , [(1, false), (2, true), (23, false), (27, true), (32, false), (36, false), (39, false), (55, false), (57, true)]
  , [(1, false), (12, false), (39, true), (47, false)]
  , [(1, false), (20, true), (23, false), (27, false), (39, false), (47, false), (57, false)]
  , [(1, false), (23, true), (27, true), (39, false), (55, false), (56, false), (57, true), (58, true)]
  , [(1, false), (7, false), (12, true), (39, true), (45, false), (47, false)]
  , [(1, false), (11, false), (39, true), (47, true)]
  , [(1, false), (2, true), (11, true), (23, false), (27, true), (32, true), (36, false), (39, false), (55, false), (57, true)]
  , [(1, true), (4, true), (14, true), (16, true), (49, true), (53, true), (58, true)]
  , [(1, true), (4, true), (35, true), (53, false)]
  , [(1, false), (27, true), (39, false), (51, false), (55, true), (56, false)]
  , [(1, true), (4, true), (14, true), (16, true), (49, true), (53, true), (58, false)]
  , [(1, true), (4, true), (9, false), (14, false), (24, false), (34, false), (51, true), (53, true)]
  , [(1, true), (4, true), (9, true), (14, false), (21, false), (30, true), (53, true)]
  , [(1, true), (4, false), (30, true), (45, true), (53, false), (56, true)]
  , [(1, false), (20, true), (23, false), (27, false), (39, false), (47, true), (57, false)]
  , [(1, false), (2, true), (23, false), (27, true), (36, true), (39, false), (44, false), (52, true), (55, false), (57, true)]
  , [(1, true), (4, false), (45, true), (53, false), (56, false)]
  , [(1, false), (19, true), (23, false), (27, false), (39, false), (46, false), (55, true), (57, true)]
  , [(1, true), (3, false), (4, false), (24, true), (35, true), (45, false), (53, true), (57, true)]
  , [(1, true), (4, true), (14, true), (16, false), (53, true)]
  , [(1, false), (2, true), (11, false), (23, false), (27, true), (32, true), (36, false), (39, false), (55, false), (57, true)]
  , [(1, false), (2, true), (23, false), (27, true), (36, true), (39, false), (44, true), (55, false), (57, true)]
  , [(1, true), (3, true), (4, false), (24, true), (35, true), (45, false), (53, true), (57, true)]
  , [(1, true), (4, true), (9, true), (14, false), (30, false), (53, true)]
  , [(1, false), (2, true), (23, false), (27, true), (36, true), (39, false), (44, false), (52, false), (55, false), (57, true)]
  , [(1, false), (23, true), (24, false), (27, true), (39, false), (55, false), (57, true), (58, false)]
  , [(1, false), (20, false), (26, false), (27, true), (32, true), (39, false), (45, true), (51, true), (55, true)]
  , [(1, false), (23, true), (27, true), (39, false), (55, false), (56, true), (57, true), (58, true)]
  , [(1, true), (4, true), (9, false), (14, false), (24, true), (34, false), (51, true), (53, true)]
  , [(1, true), (4, true), (14, true), (16, true), (49, false), (53, true)]
  , [(1, true), (4, false), (45, false), (53, false), (56, false)]
  , [(1, true), (4, true), (9, true), (14, false), (21, true), (30, true), (53, true)]
  ]

/-- The LRAT refutation: derived clause + database-index hints per step. -/
def steps : List RStep :=
  [ ⟨[(39, false), (27, false), (20, false), (21, false), (23, false), (1, false), (19, false)], [27, 18]⟩
  , ⟨[(39, true), (12, false), (11, false), (1, false)], [44, 48]⟩
  , ⟨[(51, false), (55, true), (39, false), (27, true), (1, false)], [4, 52]⟩
  , ⟨[(55, true), (27, true), (20, false), (1, false), (39, false)], [77, 22, 8, 25, 69]⟩
  , ⟨[(23, false), (21, false), (39, false), (2, false), (20, false), (1, false), (19, false)], [75, 78, 41, 0, 38]⟩
  , ⟨[(57, false), (27, true), (39, false), (1, false), (55, false)], [0, 38]⟩
  , ⟨[(58, false), (27, true), (39, false), (23, true), (1, false), (55, false)], [80, 11, 68]⟩
  , ⟨[(27, true), (23, true), (39, false), (1, false), (20, false)], [78, 80, 81, 46, 70]⟩
  , ⟨[(23, true), (20, false), (9, false), (39, false), (3, false), (1, false)], [82, 10, 1, 5]⟩
  , ⟨[(27, false), (20, false), (39, false), (19, false), (1, false), (23, false), (21, true)], [27, 39]⟩
  , ⟨[(20, false), (19, false), (2, false), (39, false), (1, false), (9, false), (3, false)], [83, 79, 84, 78, 80, 41]⟩
  , ⟨[(55, true), (27, true), (20, true), (1, false), (39, false)], [77, 22, 8, 17]⟩
  , ⟨[(27, true), (20, true), (39, false), (2, false), (1, false)], [86, 80, 41, 81, 46, 70]⟩
  , ⟨[(23, true), (27, false), (9, false), (1, false), (39, false), (3, false)], [10, 1, 5]⟩
  , ⟨[(19, false), (39, false), (1, false), (9, false), (3, false), (2, false)], [85, 87, 88, 27, 45, 57]⟩
  , ⟨[(57, false), (20, true), (39, false), (1, false), (27, false), (23, false)], [45, 57]⟩
  , ⟨[(20, true), (39, false), (2, false), (3, false), (9, false), (1, false)], [89, 87, 88, 90, 42, 60, 21, 29]⟩
  , ⟨[(4, false), (45, true), (1, true), (56, true), (17, false), (55, true)], [34, 56, 33]⟩
  , ⟨[(14, false), (4, true), (9, false), (51, true), (24, false), (1, true), (53, true)], [2, 54]⟩
  , ⟨[(4, true), (16, true), (1, true), (58, true), (9, false), (51, true), (24, false), (35, true)], [51, 93, 50, 72]⟩
  , ⟨[(4, false), (24, false), (1, true), (57, true), (56, true), (17, false), (55, true)], [92, 14, 12, 40]⟩
  , ⟨[(24, false), (51, true), (58, true), (9, false), (1, true), (35, true), (57, true), (56, true), (17, false), (55, true)], [95, 51, 93, 94, 62]⟩
  , ⟨[(14, false), (4, true), (9, false), (24, true), (51, true), (1, true), (53, true)], [2, 71]⟩
  , ⟨[(4, true), (51, true), (9, false), (35, true), (58, true), (1, true), (24, true)], [51, 97, 62, 72, 50]⟩
  , ⟨[(51, true), (58, true), (3, false), (35, true), (57, true), (56, true), (17, false), (55, true), (9, false), (1, true)], [96, 98, 92, 14, 61]⟩
  , ⟨[(4, false), (56, true), (3, false), (35, true), (57, true), (1, true), (17, false), (55, true)], [92, 95, 14, 61]⟩
  , ⟨[(14, true), (16, true), (53, true), (4, true), (58, true), (1, true)], [72, 50]⟩
  , ⟨[(14, false), (51, false), (9, false), (53, true), (4, true), (1, true)], [2, 35, 20, 15]⟩
  , ⟨[(14, true), (4, true), (1, true), (53, true)], [62, 72, 101, 53]⟩
  , ⟨[(4, true), (35, true), (9, false), (1, true)], [51, 103, 2, 102, 54, 71]⟩
  , ⟨[(53, true), (35, true), (3, false), (57, true), (55, true), (17, false), (1, true), (4, false)], [34, 61, 12, 40]⟩
  , ⟨[(35, true), (17, false), (3, false), (57, true), (55, true), (1, true), (9, false)], [104, 100, 105, 59, 73]⟩
  , ⟨[(45, false), (53, false), (4, false), (1, true)], [14, 73]⟩
  , ⟨[(53, false), (4, false), (1, true), (17, false), (55, true)], [107, 92, 59]⟩
  , ⟨[(4, false), (17, false), (57, true), (55, true), (1, true), (35, false)], [108, 34, 26, 12, 40]⟩
  , ⟨[(11, false), (39, true), (1, false), (45, false)], [76, 48, 6, 47]⟩
  , ⟨[(39, true), (45, false), (1, false)], [110, 31, 44, 6, 47]⟩
  , ⟨[(57, true), (55, true), (39, false), (23, false), (19, true), (1, false), (27, false)], [60, 21, 29]⟩
  , ⟨[(55, true), (19, true), (39, false), (1, false), (20, false), (23, false)], [78, 112, 18, 39]⟩
  , ⟨[(57, false), (20, false), (39, false), (1, false), (23, false), (55, false)], [80, 39, 18]⟩
  , ⟨[(9, false), (3, false), (39, false), (2, false), (1, false)], [89, 91, 83, 113, 114, 41, 42]⟩
  , ⟨[(23, false), (27, false), (57, true), (1, false), (39, false), (55, false)], [42, 27]⟩
  , ⟨[(27, false), (57, true), (9, true), (39, false), (1, false), (55, false)], [116, 37, 7, 9]⟩
  , ⟨[(57, true), (55, false), (2, false), (39, false), (1, false), (20, false), (9, true)], [117, 82, 41]⟩
  , ⟨[(55, false), (20, false), (9, true), (39, false), (1, false), (2, false)], [118, 80, 114, 37, 7, 9]⟩
  , ⟨[(23, true), (27, false), (9, true), (1, false), (39, false)], [37, 7, 9]⟩
  , ⟨[(20, false), (9, true), (1, false), (2, false), (39, false)], [119, 78, 120, 113, 79, 84]⟩
  , ⟨[(9, true), (39, false), (1, false), (2, false)], [121, 87, 120, 90, 117, 27, 112]⟩
  , ⟨[(57, true), (23, false), (55, true), (39, false), (1, false), (27, false)], [27, 112]⟩
  , ⟨[(23, false), (27, false), (1, false), (39, false), (55, true)], [123, 90, 39, 18]⟩
  , ⟨[(27, false), (55, true), (3, true), (9, false), (39, false), (1, false)], [124, 13, 1, 5]⟩
  , ⟨[(55, true), (39, false), (1, false), (9, false), (3, true)], [125, 78, 86]⟩
  , ⟨[(27, true), (55, true), (1, false), (39, false)], [78, 86]⟩
  , ⟨[(55, true), (39, false), (1, false)], [127, 124, 120, 126, 88]⟩
  , ⟨[(23, false), (27, false), (39, false), (1, false)], [128, 116, 90, 114]⟩
  , ⟨[(27, false), (39, false), (1, false)], [129, 120, 88, 13, 1, 5]⟩
  , ⟨[(23, true), (39, false), (1, false)], [128, 130, 80, 81, 46, 70]⟩
  , ⟨[(36, true), (52, false), (1, false), (39, false), (2, true)], [131, 128, 130, 80, 64, 67]⟩
  , ⟨[(36, false), (32, true), (1, false), (39, false), (2, true)], [131, 128, 130, 80, 49, 63]⟩
  , ⟨[(36, true), (39, false), (1, false), (2, true)], [131, 128, 130, 80, 64, 132, 58]⟩
  , ⟨[(39, false), (1, false), (2, true)], [128, 130, 80, 131, 134, 43, 49, 63]⟩
  , ⟨[(11, false), (39, true), (1, false)], [111, 76, 48, 28]⟩
  , ⟨[(1, false), (2, true)], [135, 111, 136, 31, 44, 28]⟩
  , ⟨[(35, true), (9, false), (45, true), (56, true), (55, false), (1, true)], [104, 32, 56, 33]⟩
  , ⟨[(4, false), (35, false), (56, true), (45, true), (55, false), (1, true)], [23, 33, 56]⟩
  , ⟨[(53, false), (35, false), (1, true), (4, true)], [16, 30]⟩
  , ⟨[(9, false), (56, true), (1, true), (45, true), (55, false)], [138, 139, 140, 103, 2, 102, 54, 71]⟩
  , ⟨[(35, false), (56, true), (45, true), (55, false), (1, true)], [141, 139, 140, 103, 66, 74, 55]⟩
  , ⟨[(45, false), (1, false), (55, true)], [128, 111]⟩
  , ⟨[(45, false), (1, false), (27, false)], [130, 111]⟩
  , ⟨[(45, false), (1, false), (23, true)], [131, 111]⟩
  , ⟨[(11, false), (1, false), (55, true)], [128, 136]⟩
  , ⟨[(11, false), (1, false), (27, false)], [130, 136]⟩
  , ⟨[(11, false), (1, false), (23, true)], [131, 136]⟩
  , ⟨[(47, true), (1, false), (39, true)], [31, 136]⟩
  , ⟨[(47, true), (1, false), (39, true)], [48, 149]⟩
  , ⟨[(9, true), (39, false), (1, false)], [122, 137]⟩
  , ⟨[(53, false), (1, true), (4, true)], [140, 51]⟩
  , ⟨[(27, true), (20, true), (39, false), (1, false)], [87, 137]⟩
  , ⟨[(47, false), (1, false), (39, true), (45, true)], [28, 44]⟩
  , ⟨[(3, false), (39, false), (2, false), (1, false)], [115, 151]⟩
  , ⟨[(20, false), (55, true), (1, false), (39, false)], [78, 130]⟩
  , ⟨[(57, false), (27, true), (39, false), (1, false)], [80, 128]⟩
  , ⟨[(55, true), (27, true), (1, false), (39, false)], [86, 156]⟩
  , ⟨[(56, false), (4, false), (1, true), (53, false)], [59, 107]⟩
  , ⟨[(56, false), (1, true), (4, false), (53, false)], [73, 159]⟩
  , ⟨[(57, false), (16, false), (1, false), (39, false), (55, false)], [0, 130]⟩
  , ⟨[(57, false), (1, false), (39, false), (27, true), (55, false)], [38, 161]⟩
  , ⟨[(51, false), (56, false), (1, false), (39, false), (55, true)], [52, 130]⟩
  , ⟨[(30, true), (53, false), (1, true), (4, false), (45, true)], [56, 159]⟩
  , ⟨[(30, false), (1, true), (9, true), (4, true), (53, true)], [66, 103]⟩
  , ⟨[(34, true), (1, true), (9, false), (4, true), (53, true)], [2, 103]⟩
  , ⟨[(58, false), (23, true), (39, false), (27, true), (1, false)], [81, 128]⟩
  , ⟨[(45, false), (57, false), (1, true), (46, true), (4, false)], [19, 107]⟩
  , ⟨[(57, false), (20, true), (39, false), (1, false), (27, false)], [90, 131]⟩
  , ⟨[(51, false), (9, false), (53, true), (4, true), (1, true)], [102, 103]⟩
  , ⟨[(32, false), (51, true), (1, false), (39, false), (55, true)], [22, 130]⟩
  , ⟨[(57, false), (20, false), (39, false), (1, false), (23, false)], [114, 128]⟩
  , ⟨[(51, false), (1, false), (39, false), (27, true), (55, true)], [4, 163]⟩
  , ⟨[(53, true), (4, false), (1, true), (55, false), (45, true)], [32, 23]⟩
  , ⟨[(53, false), (1, true), (45, true), (4, false), (56, true)], [33, 164]⟩
  , ⟨[(55, true), (1, true), (17, false), (4, false), (45, true)], [34, 108]⟩
  , ⟨[(57, false), (1, true), (4, false), (53, true), (45, false)], [36, 168]⟩
  , ⟨[(21, true), (19, false), (39, false), (20, false), (1, false), (27, false)], [84, 131]⟩
  , ⟨[(5, false), (24, false), (1, true), (45, false), (4, false), (57, true)], [40, 107]⟩
  , ⟨[(24, false), (1, true), (45, false), (4, false), (53, true), (57, true)], [12, 179]⟩
  , ⟨[(14, false), (21, true), (1, true), (9, true), (4, true), (53, true)], [74, 165]⟩
  , ⟨[(19, false), (39, false), (20, false), (27, false), (1, false), (23, false)], [75, 178]⟩
  , ⟨[(19, false), (21, false), (39, false), (2, false), (20, false), (1, false)], [79, 131]⟩
  , ⟨[(28, true), (1, true), (4, false), (45, true), (53, true), (55, true)], [3, 176]⟩
  , ⟨[(32, true), (26, true), (1, false), (51, true), (39, false), (55, true)], [8, 130]⟩
  , ⟨[(30, true), (1, true), (9, true), (4, true), (14, false), (53, true)], [55, 181]⟩
  , ⟨[(51, true), (24, false), (9, false), (4, true), (1, true), (53, true)], [93, 103]⟩
  , ⟨[(27, true), (23, false), (1, false), (39, false), (57, true), (55, false)], [41, 137]⟩
  , ⟨[(51, true), (9, false), (4, true), (14, false), (1, true), (53, true)], [97, 187]⟩
  , ⟨[(17, true), (1, true), (4, false), (45, true), (53, true), (55, true)], [24, 184]⟩
  , ⟨[(24, true), (4, false), (1, true), (57, true), (35, false), (45, false)], [26, 107]⟩
  , ⟨[(56, true), (1, false), (39, false), (23, true), (27, true), (55, false), (57, true)], [70, 167]⟩
  , ⟨[(3, false), (4, false), (35, true), (55, true), (17, false), (1, true), (57, true)], [105, 108]⟩
  , ⟨[(34, false), (1, true), (9, false), (14, false), (4, true), (51, true), (53, true)], [54, 189]⟩
  , ⟨[(58, true), (1, false), (39, false), (23, true), (27, true), (55, false), (57, true)], [46, 192]⟩
  , ⟨[(51, true), (34, false), (1, true), (9, false), (4, true), (14, false), (53, true)], [71, 194]⟩
  , ⟨[(24, true), (3, false), (1, true), (57, true), (45, false), (53, true), (4, false)], [61, 191]⟩
  , ⟨[(26, false), (51, true), (1, false), (20, true), (27, true), (39, false), (55, true)], [17, 171]⟩
  , ⟨[(4, false), (24, true), (1, true), (3, true), (35, true), (45, false), (57, true)], [65, 107]⟩
  , ⟨[(17, false), (56, true), (3, false), (4, false), (1, true), (57, true), (55, true)], [100, 109]⟩
  , ⟨[(51, false), (28, true), (1, true), (9, false), (4, true), (14, false), (53, true)], [35, 166]⟩
  , ⟨[(26, false), (51, true), (1, false), (45, false), (39, false), (27, true), (32, true), (55, true)], [25, 198]⟩
  , ⟨[(26, true), (1, true), (9, false), (4, true), (14, false), (34, false), (51, false), (53, true)], [15, 201]⟩
  , ⟨[(26, false), (1, false), (45, true), (27, true), (39, false), (32, true), (51, true), (55, true)], [69, 198]⟩
  , ⟨[(28, false), (1, true), (9, false), (14, false), (4, true), (34, false), (51, false), (53, true)], [20, 203]⟩
  , ⟨[(11, false), (36, false), (2, true), (1, false), (27, true), (23, false), (32, true), (39, false), (57, true)], [63, 146]⟩
  , ⟨[(1, false), (11, false)], [148, 147, 136, 146, 157, 188, 131]⟩
  , ⟨[(1, false), (27, false)], [147, 130, 144, 149, 154]⟩
  , ⟨[(1, false), (39, false)], [208, 128, 131, 162, 188, 206]⟩
  , ⟨[(1, true), (4, false), (53, false)], [107, 159, 175, 164]⟩
  , ⟨[(1, true), (4, false), (53, true), (45, true)], [174, 210, 176, 190]⟩
  , ⟨[(1, true), (4, false), (53, true)], [211, 210, 177, 180, 191, 197, 199]⟩
  , ⟨[(1, true), (4, false)], [212, 152, 210]⟩
  , ⟨[(1, true), (53, true), (9, false)], [213, 103, 170, 189, 166]⟩
  , ⟨[(1, true), (9, false)], [214, 213, 152, 103, 170, 189]⟩
  , ⟨[(1, true), (4, true)], [152, 213, 215, 103, 165, 186]⟩
  , ⟨[(39, false)], [209, 213, 215, 216]⟩
  , ⟨[(27, false)], [217, 208, 213, 215, 216]⟩
  , ⟨[(11, false)], [217, 218, 207, 213, 215, 216]⟩
  , ⟨[(9, false)], [217, 218, 219, 215, 137, 111, 149, 154]⟩
  , ⟨[(47, true), (1, false)], [149, 209]⟩
  , ⟨[(1, false), (45, false)], [111, 209]⟩
  , ⟨[(47, false), (45, true), (1, false)], [154, 209]⟩
  , ⟨[(12, false), (47, false), (1, false)], [44, 209]⟩
  , ⟨[(57, false), (1, false), (39, false)], [157, 208]⟩
  , ⟨[(20, true), (1, false), (39, false)], [153, 208]⟩
  , ⟨[(3, false), (1, false), (39, false)], [155, 137]⟩
  , ⟨[(57, false), (20, true), (39, false), (1, false)], [169, 225]⟩
  , ⟨[(55, true), (17, false), (53, false), (1, true)], [108, 216]⟩
  , ⟨[(19, false), (21, false), (39, false), (20, false), (1, false)], [183, 137]⟩
  , ⟨[(17, false), (56, true), (45, true), (55, true), (1, true)], [92, 216]⟩
  , ⟨[(17, false), (55, true), (35, false), (57, true), (1, true)], [109, 216]⟩
  , ⟨[(17, false), (24, false), (56, true), (55, true), (57, true), (1, true)], [95, 216]⟩
  , ⟨[(17, false), (56, true), (3, false), (1, true), (57, true), (55, true)], [200, 216]⟩
  , ⟨[(3, false), (35, true), (55, true), (17, false), (1, true), (57, true)], [193, 216]⟩
  , ⟨[(1, true)], [213, 216]⟩
  , ⟨[(47, true)], [236, 221]⟩
  , ⟨[(45, false)], [236, 222]⟩
  , ⟨[(2, true)], [236, 137]⟩
  , ⟨[], [236, 237, 238, 223]⟩
  ]

set_option maxHeartbeats 40000000 in
/-- KERNEL replay of the refutation — plain `decide`, no `native_decide`. -/
theorem check_ok : RupCheckerFast.checkRefutationFast F steps = true := by decide

/-- The recovered CNF is unsatisfiable (kernel-checked LRAT replay +
`rup_sound` composition). -/
theorem instance_unsat : ¬ ∃ σ, satFormula σ F :=
  RupCheckerFast.checkRefutationFast_sound F steps check_ok

/-- The gadget's variable set: DIMACS variables `1..58`. -/
def s : Finset ℕ := Finset.Icc 1 58

set_option maxHeartbeats 4000000 in
/-- END-TO-END VERDICT: no point of the `[0,1]` box reaches the sat_relu
gadget's unsafe region `{Y₀ ≥ 1 ∧ Y₁ ≤ 0}` — real-arithmetic SAFE. -/
theorem instance_safe :
    ∀ x : ℕ → ℝ, (∀ j ∈ s, 0 ≤ x j ∧ x j ≤ 1) →
      ¬ (1 ≤ SatRelu.Y0 (SatReluVerdict.clausesOf F) x ∧
         SatRelu.Y1 s x ≤ 0) :=
  SatReluVerdict.safe_of_unsat F s (by decide) instance_unsat

end SatReluSweep_v58c75

end Crownproof

/-! ## Trust-base check -/

#print axioms Crownproof.SatReluSweep_v58c75.check_ok
#print axioms Crownproof.SatReluSweep_v58c75.instance_unsat
#print axioms Crownproof.SatReluSweep_v58c75.instance_safe
