/-
MACHINE-GENERATED by `ny-cert`'s `lrat_to_lean` — do not edit.

sat_relu Route A instance transcript:
* DIMACS source : inst.cnf  (p cnf 67 154)
* LRAT source   : inst.lrat  (251 addition steps kept)

The kernel replays the full LRAT refutation with PLAIN `decide`
(no `native_decide`, no extra axioms) through
`RupCheckerFast.checkRefutationFast`, then composes
`checkRefutationFast_sound` (CNF-unsat) with
`SatReluVerdict.safe_of_unsat` (gadget real-arithmetic safety).
-/
import NyProof.SatReluVerdict
import NyProof.RupCheckerFast

namespace Crownproof

namespace SatReluSweep_v67c154

open RupImport.RUP RupChecker

set_option maxRecDepth 65536

/-- The recovered DIMACS formula, literal-for-literal. -/
def F : Formula :=
  [ [(1, false), (4, true), (42, true), (54, false), (56, true)]
  , [(1, true), (3, true), (6, true), (9, true), (11, false), (23, false), (24, true), (26, false), (28, false), (38, true), (54, true)]
  , [(1, true), (3, false), (10, false), (26, false), (32, true), (33, true), (46, false), (51, true)]
  , [(1, true), (3, false), (4, false), (11, true), (26, false), (30, false), (32, false), (53, false)]
  , [(1, false), (17, true), (23, true), (37, false), (44, false), (46, false), (54, true), (67, false)]
  , [(1, false), (4, false), (6, true), (7, false), (9, false), (42, true), (54, false)]
  , [(1, true), (5, true), (26, true), (43, false), (53, false), (55, true)]
  , [(1, false), (4, false), (6, false), (42, true), (52, true), (54, false)]
  , [(1, true), (3, true), (11, true), (17, true), (21, false), (26, false), (29, false), (49, false), (60, true)]
  , [(1, true), (3, false), (16, true), (18, false), (26, false), (28, false), (32, true), (33, true), (51, false)]
  , [(1, true), (3, true), (11, true), (26, false), (29, true), (49, false)]
  , [(1, false), (7, true), (18, false), (23, false), (46, true), (47, false), (49, false), (54, true), (67, false)]
  , [(1, false), (16, true), (17, true), (23, false), (47, true), (54, true)]
  , [(1, false), (23, true), (24, true), (37, false), (46, true), (54, true)]
  , [(1, true), (5, true), (15, false), (26, true), (27, false), (31, true), (40, false), (41, true), (43, true), (48, true)]
  , [(1, true), (3, true), (6, true), (11, true), (26, false), (49, true), (63, true)]
  , [(1, true), (3, true), (11, false), (13, true), (25, false), (26, false), (28, false), (54, false), (56, true), (65, false)]
  , [(1, true), (3, false), (10, true), (11, false), (13, true), (26, false), (32, false), (53, false)]
  , [(1, false), (6, false), (17, false), (42, false), (49, false), (54, false), (66, true)]
  , [(1, true), (3, true), (5, true), (6, false), (11, true), (26, false), (48, false), (49, true), (50, true)]
  , [(1, false), (4, true), (9, true), (42, true), (44, true), (54, false), (56, false)]
  , [(1, false), (23, true), (37, true), (45, false), (54, true), (58, true)]
  , [(1, true), (3, true), (8, true), (11, false), (26, false), (28, true), (37, false), (49, true)]
  , [(1, true), (3, true), (11, false), (23, true), (26, false), (28, false), (40, false), (54, true), (55, false)]
  , [(1, true), (3, true), (6, true), (11, true), (26, false), (49, true), (63, false)]
  , [(1, false), (6, true), (29, true), (42, false), (49, false), (54, false)]
  , [(1, true), (5, true), (15, true), (26, true), (31, true), (40, false), (43, true), (48, true)]
  , [(1, true), (3, true), (5, false), (6, false), (11, true), (26, false), (37, true), (42, false), (49, true)]
  , [(1, true), (3, true), (11, false), (13, false), (26, false), (28, false), (54, false), (60, true)]
  , [(1, true), (5, true), (7, true), (24, true), (26, true), (40, false), (43, true), (48, false), (67, false)]
  , [(1, false), (22, true), (24, false), (42, false), (47, false), (49, true), (54, false), (67, false)]
  , [(1, true), (3, true), (11, false), (13, true), (25, false), (26, false), (28, false), (54, false), (56, true), (65, true)]
  , [(1, true), (3, true), (6, false), (9, true), (11, false), (23, false), (24, true), (26, false), (28, false), (38, true), (54, true)]
  , [(1, false), (23, true), (37, true), (45, true), (50, false), (54, true), (58, true)]
  , [(1, false), (7, false), (18, false), (23, false), (46, true), (47, false), (49, false), (54, true), (67, false)]
  , [(1, true), (3, false), (18, false), (26, false), (32, false), (34, true), (53, true)]
  , [(1, true), (5, true), (26, true), (31, false), (39, true), (40, false), (43, true), (48, true)]
  , [(1, true), (3, true), (8, true), (9, false), (11, false), (26, false), (28, true), (37, true)]
  , [(1, true), (3, true), (8, true), (9, true), (11, false), (26, false), (28, true), (37, true)]
  , [(1, false), (6, true), (19, false), (29, false), (42, false), (49, false), (54, false)]
  , [(1, false), (23, false), (30, false), (32, false), (47, false), (49, false), (54, true), (67, true)]
  , [(1, true), (3, true), (9, false), (11, false), (14, false), (23, false), (26, false), (28, false), (38, true), (54, true), (55, true), (65, true)]
  , [(1, true), (3, true), (11, false), (23, false), (24, false), (26, false), (28, false), (38, false), (50, false), (54, true)]
  , [(1, false), (23, false), (30, false), (32, true), (47, false), (49, false), (54, true), (67, true)]
  , [(1, true), (3, true), (5, true), (6, false), (11, true), (26, false), (49, true), (50, false)]
  , [(1, true), (3, false), (18, false), (26, false), (32, false), (34, false), (37, true), (53, true), (55, false)]
  , [(1, true), (3, false), (16, true), (26, false), (28, true), (32, true), (51, false)]
  , [(1, false), (23, true), (24, false), (37, false), (46, true), (54, true)]
  , [(1, true), (3, true), (11, false), (23, true), (26, false), (28, false), (40, true), (42, false), (54, true), (55, false), (59, true)]
  , [(1, true), (3, true), (5, false), (6, false), (11, true), (26, false), (37, true), (42, true), (49, true)]
  , [(1, false), (4, false), (6, true), (7, false), (9, true), (42, true), (54, false)]
  , [(1, false), (22, false), (24, false), (42, false), (47, false), (49, true), (54, false), (67, false)]
  , [(1, true), (3, true), (11, false), (18, true), (23, true), (26, false), (28, false), (39, false), (52, true), (53, false), (54, true), (55, true), (66, true)]
  , [(1, true), (3, true), (5, true), (6, false), (11, true), (26, false), (27, false), (48, true), (49, true), (50, true)]
  , [(1, false), (23, false), (42, false), (47, false), (49, true), (54, true)]
  , [(1, true), (3, true), (11, false), (23, false), (24, true), (26, false), (28, false), (38, false), (50, false), (54, true)]
  , [(1, true), (3, false), (18, true), (26, false), (32, false), (40, true), (53, true), (65, true)]
  , [(1, true), (3, true), (6, true), (11, true), (17, false), (21, false), (26, false), (29, false), (31, false), (49, false)]
  , [(1, true), (3, false), (26, false), (32, true), (46, true), (51, true), (57, true)]
  , [(1, false), (6, true), (19, true), (29, false), (42, false), (49, false), (54, false)]
  , [(1, true), (3, false), (4, true), (11, true), (26, false), (30, false), (32, false), (53, false)]
  , [(1, true), (5, true), (7, false), (24, true), (26, true), (40, false), (43, true), (48, false), (67, false)]
  , [(1, true), (3, true), (11, false), (18, false), (23, true), (26, false), (28, false), (54, true), (55, true)]
  , [(1, false), (10, false), (18, true), (23, false), (46, true), (47, false), (49, false), (54, true), (67, false)]
  , [(1, true), (3, true), (11, true), (21, true), (26, false), (29, false), (49, false), (51, false), (54, false)]
  , [(1, false), (4, false), (6, true), (7, true), (42, true), (54, false)]
  , [(1, false), (23, false), (30, false), (46, false), (47, false), (49, false), (54, true), (67, false)]
  , [(1, true), (5, false), (26, true), (63, true)]
  , [(1, true), (5, true), (26, true), (31, false), (39, false), (40, false), (43, true), (48, true)]
  , [(1, true), (3, true), (9, false), (11, false), (15, true), (23, false), (26, false), (28, false), (38, true), (54, true), (55, true), (65, false)]
  , [(1, true), (3, false), (18, true), (26, false), (32, false), (40, false), (53, true), (65, true)]
  , [(1, false), (4, true), (42, true), (44, false), (54, false), (56, false)]
  , [(1, true), (5, true), (15, false), (26, true), (27, true), (31, true), (40, false), (41, true), (43, true), (48, true)]
  , [(1, true), (3, false), (9, false), (11, false), (13, false), (26, false), (32, false), (53, false)]
  , [(1, true), (3, true), (11, false), (13, false), (26, false), (28, false), (31, true), (54, false), (60, false)]
  , [(1, true), (5, true), (23, true), (26, true), (40, true), (43, true)]
  , [(1, true), (3, false), (9, true), (11, false), (13, false), (26, false), (32, false), (53, false)]
  , [(1, true), (3, true), (11, false), (18, true), (23, true), (26, false), (28, false), (52, false), (53, false), (54, true), (55, true)]
  , [(1, true), (3, true), (5, true), (6, false), (11, true), (26, false), (27, true), (44, false), (48, true), (49, true), (50, true)]
  , [(1, true), (5, false), (26, true), (63, false)]
  , [(1, false), (17, true), (23, true), (37, false), (44, true), (46, false), (54, true)]
  , [(1, true), (5, true), (24, false), (26, true), (40, false), (43, true), (48, false), (55, true), (67, false)]
  , [(1, true), (3, false), (16, true), (18, true), (26, false), (28, false), (32, true), (51, false)]
  , [(1, true), (3, true), (11, false), (15, true), (18, true), (23, true), (26, false), (28, false), (39, true), (52, true), (53, false), (54, true), (55, true), (66, true)]
  , [(1, true), (3, false), (16, false), (26, false), (32, true), (39, true), (51, false)]
  , [(1, false), (16, false), (23, false), (44, true), (47, true), (54, true)]
  , [(1, false), (24, false), (42, false), (47, false), (49, true), (54, false), (67, true)]
  , [(1, true), (3, true), (11, false), (13, true), (25, false), (26, false), (28, false), (54, false), (56, false)]
  , [(1, true), (3, true), (5, false), (6, false), (11, true), (17, true), (26, false), (37, false), (49, true)]
  , [(1, false), (23, true), (37, true), (45, true), (50, true), (54, true), (58, true)]
  , [(1, false), (17, true), (23, true), (37, false), (44, false), (46, false), (54, true), (67, true)]
  , [(1, true), (3, true), (11, true), (17, false), (21, false), (26, false), (29, false), (31, true), (49, false)]
  , [(1, true), (3, true), (9, false), (11, false), (23, false), (26, false), (28, false), (38, true), (41, false), (54, true), (55, false)]
  , [(1, true), (3, true), (6, false), (11, true), (17, false), (21, false), (26, false), (29, false), (31, false), (49, false)]
  , [(1, false), (4, false), (6, false), (42, true), (52, false), (54, false)]
  , [(1, true), (3, true), (11, true), (21, true), (26, false), (29, false), (49, false), (54, true)]
  , [(1, true), (3, true), (9, false), (11, false), (23, false), (26, false), (28, false), (38, true), (41, true), (54, true), (55, false)]
  , [(1, true), (5, true), (26, true), (43, false), (53, true), (55, true)]
  , [(1, true), (3, true), (9, false), (11, false), (15, false), (23, false), (26, false), (28, false), (38, true), (54, true), (55, true), (65, false)]
  , [(1, false), (24, false), (34, false), (42, false), (47, true), (49, true), (54, false)]
  , [(1, false), (23, false), (30, true), (46, false), (47, false), (49, false), (54, true), (65, false), (67, false)]
  , [(1, true), (5, true), (26, true), (40, false), (43, true), (48, false), (56, false), (67, true)]
  , [(1, true), (3, false), (10, true), (26, false), (32, true), (46, false), (51, true)]
  , [(1, true), (3, false), (16, false), (26, false), (32, true), (39, false), (51, false)]
  , [(1, true), (5, true), (15, false), (26, true), (31, true), (40, false), (41, false), (43, true), (48, true), (62, true)]
  , [(1, true), (3, true), (11, true), (17, true), (21, false), (26, false), (29, false), (49, false), (60, false)]
  , [(1, true), (3, false), (10, false), (26, false), (32, true), (33, false), (46, false), (51, true)]
  , [(1, true), (3, true), (11, false), (18, true), (23, true), (26, false), (28, false), (52, true), (53, false), (54, true), (55, true), (66, false)]
  , [(1, true), (3, false), (26, false), (32, true), (46, true), (51, true), (57, false), (64, false)]
  , [(1, true), (3, false), (18, false), (26, false), (32, false), (34, false), (53, true), (55, true)]
  , [(1, true), (3, false), (26, false), (32, true), (46, true), (51, true), (57, false), (64, true)]
  , [(1, false), (23, true), (37, true), (54, true), (58, false)]
  , [(1, true), (5, true), (26, true), (31, true), (43, false), (55, false)]
  , [(1, false), (16, true), (17, false), (23, false), (47, true), (54, true), (55, true)]
  , [(1, false), (23, false), (42, true), (47, false), (49, true), (54, true)]
  , [(1, true), (3, true), (11, false), (15, false), (18, true), (23, true), (26, false), (28, false), (39, true), (52, true), (53, false), (54, true), (55, true), (66, true)]
  , [(1, true), (3, true), (6, false), (8, true), (11, false), (23, true), (26, false), (28, true), (37, false), (49, false)]
  , [(1, true), (5, true), (26, true), (40, false), (43, true), (48, false), (56, true), (67, true)]
  , [(1, true), (3, true), (6, true), (8, true), (11, false), (26, false), (28, true), (37, false), (49, false)]
  , [(1, false), (16, true), (17, false), (23, false), (47, true), (54, true), (55, false)]
  , [(1, true), (5, true), (23, false), (26, true), (40, true), (43, true)]
  , [(1, false), (23, false), (30, true), (46, false), (47, false), (49, false), (54, true), (65, true), (67, false)]
  , [(1, true), (3, true), (6, false), (8, true), (11, false), (23, false), (26, false), (28, true), (37, false), (49, false)]
  , [(1, false), (2, false), (24, true), (42, false), (49, true), (54, false)]
  , [(1, true), (3, true), (9, true), (11, false), (23, false), (24, false), (26, false), (28, false), (38, true), (54, true)]
  , [(1, true), (3, true), (5, true), (6, false), (11, true), (26, false), (27, true), (44, true), (48, true), (49, true), (50, true)]
  , [(1, true), (3, true), (8, false), (11, false), (26, false), (28, true)]
  , [(1, false), (10, true), (18, true), (23, false), (46, true), (47, false), (49, false), (54, true), (67, false)]
  , [(1, true), (5, true), (24, false), (26, true), (40, false), (43, true), (48, false), (55, false), (67, false)]
  , [(1, true), (3, true), (11, false), (23, true), (26, false), (28, false), (40, true), (42, true), (54, true), (55, false)]
  , [(1, true), (5, true), (26, true), (31, false), (43, false), (55, false)]
  , [(1, true), (3, false), (10, false), (11, false), (13, true), (26, false), (32, false), (53, false)]
  , [(1, true), (3, true), (11, true), (21, true), (26, false), (29, false), (49, false), (51, true), (54, false)]
  , [(1, true), (3, true), (11, false), (13, false), (26, false), (28, false), (31, false), (54, false), (60, false)]
  , [(1, true), (3, true), (11, false), (18, true), (23, true), (26, false), (28, false), (53, true), (54, true), (55, true)]
  , [(1, false), (23, false), (30, true), (47, false), (49, false), (54, true), (67, true)]
  , [(1, false), (24, false), (34, true), (42, false), (47, true), (49, true), (54, false)]
  , [(1, false), (6, false), (17, true), (42, false), (49, false), (54, false)]
  , [(1, true), (3, false), (18, true), (26, false), (32, false), (53, true), (65, false)]
  , [(1, true), (3, false), (11, true), (26, false), (30, true), (32, false), (53, false)]
  , [(1, true), (5, true), (15, false), (26, true), (31, true), (40, false), (41, false), (43, true), (48, true), (62, false)]
  , [(1, true), (3, true), (11, false), (23, false), (26, false), (28, false), (38, false), (50, true), (54, true)]
  , [(1, true), (3, false), (18, false), (26, false), (32, false), (34, false), (37, false), (53, true), (55, false)]
  , [(1, false), (4, true), (9, false), (42, true), (44, true), (54, false), (56, false)]
  , [(1, false), (2, true), (24, true), (42, false), (49, true), (54, false)]
  , [(1, true), (3, true), (11, false), (13, true), (25, true), (26, false), (28, false), (54, false)]
  , [(1, true), (3, true), (5, false), (6, false), (11, true), (17, false), (26, false), (31, true), (37, false), (49, true)]
  , [(1, false), (17, false), (23, true), (37, false), (46, false), (54, true)]
  , [(1, false), (6, false), (17, false), (42, false), (49, false), (54, false), (66, false)]
  , [(1, true), (3, true), (11, false), (23, true), (26, false), (28, false), (40, true), (42, false), (54, true), (55, false), (59, false)]
  , [(1, true), (3, true), (5, false), (6, false), (11, true), (17, false), (26, false), (31, false), (37, false), (49, true)]
  , [(1, false), (16, false), (23, false), (44, false), (47, true), (54, true)]
  , [(1, true), (3, true), (9, false), (11, false), (14, true), (23, false), (26, false), (28, false), (38, true), (54, true), (55, true), (65, true)]
  , [(1, true), (3, false), (16, true), (18, false), (26, false), (28, false), (32, true), (33, false), (51, false)]
  ]

/-- The LRAT refutation: derived clause + database-index hints per step. -/
def steps : List RStep :=
  [ ⟨[(54, false), (49, false), (6, false), (17, false), (42, false), (1, false)], [18, 148]⟩
  , ⟨[(49, false), (47, false), (23, false), (30, false), (46, false), (1, false), (32, false), (6, false), (17, false), (42, false)], [154, 40, 66]⟩
  , ⟨[(47, false), (46, false), (22, false), (24, false), (42, false), (23, false), (30, false), (1, false), (32, false), (6, false), (17, false)], [155, 54, 86, 51]⟩
  , ⟨[(47, true), (44, false), (6, false), (17, false), (42, false), (24, false), (34, false), (16, false), (23, false), (1, false)], [151, 99, 18, 148]⟩
  , ⟨[(49, false), (47, false), (6, false), (7, false), (17, false), (18, false), (23, false), (30, false), (32, false), (42, false), (1, false), (46, true)], [154, 40, 34]⟩
  , ⟨[(47, false), (42, false), (22, false), (24, false), (1, false), (23, false), (6, false), (7, false), (17, false), (18, false), (30, false), (32, false)], [156, 158, 54, 86, 51]⟩
  , ⟨[(42, false), (34, false), (24, false), (1, false), (6, false), (17, false), (16, false), (23, false), (22, false), (7, false), (18, false), (30, false), (32, false)], [159, 157, 85, 154, 99]⟩
  , ⟨[(54, false), (42, true), (4, false), (6, false), (1, false)], [7, 94]⟩
  , ⟨[(47, true), (54, true), (16, false), (23, false), (1, false)], [151, 85]⟩
  , ⟨[(42, true), (32, false), (7, false), (18, false), (23, false), (30, false), (1, false), (16, false), (4, false), (6, false)], [161, 162, 114, 40, 66, 34]⟩
  , ⟨[(32, false), (30, false), (17, false), (1, false), (24, false), (16, false), (23, false), (22, false), (7, false), (18, false), (6, false), (4, false)], [163, 159, 160, 162, 136, 154]⟩
  , ⟨[(47, true), (54, false), (24, false), (42, false), (1, false), (49, true)], [99, 136]⟩
  , ⟨[(54, false), (42, false), (22, false), (24, false), (1, false), (6, false), (17, false)], [154, 165, 86, 51]⟩
  , ⟨[(42, false), (30, false), (6, false), (7, false), (16, false), (17, false), (18, false), (22, false), (23, false), (24, false), (1, false), (32, true)], [166, 162, 54, 43, 66, 34]⟩
  , ⟨[(30, false), (24, false), (7, false), (18, false), (23, false), (16, false), (4, false), (6, false), (17, false), (22, false), (1, false)], [164, 167, 161, 162, 114, 43, 66, 34]⟩
  , ⟨[(42, true), (30, true), (23, false), (1, false), (7, false), (18, false), (16, false), (4, false), (6, false)], [161, 162, 114, 135, 34, 100, 121]⟩
  , ⟨[(24, false), (23, false), (1, false), (7, false), (18, false), (16, false), (22, false), (6, false), (17, false), (4, false)], [168, 169, 166, 162, 54, 135, 34, 100, 121]⟩
  , ⟨[(51, false), (26, false), (16, false), (32, true), (3, false), (1, true)], [84, 103]⟩
  , ⟨[(26, false), (10, false), (3, false), (32, true), (1, true), (46, false), (16, false)], [171, 2, 106]⟩
  , ⟨[(26, true), (5, false), (1, true)], [67, 79]⟩
  , ⟨[(26, false), (3, false), (1, true), (32, true), (46, false), (16, false)], [171, 172, 102]⟩
  , ⟨[(43, false), (31, false), (26, true), (1, true)], [173, 130, 6, 97]⟩
  , ⟨[(31, false), (39, false), (24, false), (67, false), (23, false), (26, true), (1, true)], [173, 175, 120, 68, 81, 128]⟩
  , ⟨[(41, false), (48, true), (26, true), (31, true), (40, false), (43, true), (1, true)], [173, 26, 104, 140]⟩
  , ⟨[(48, true), (43, true), (26, true), (31, true), (1, true), (40, false)], [173, 26, 177, 14, 72]⟩
  , ⟨[(43, true), (31, true), (24, false), (67, false), (23, false), (26, true), (1, true)], [173, 120, 178, 81, 128]⟩
  , ⟨[(31, true), (26, true), (24, false), (67, false), (23, false), (1, true)], [173, 179, 112, 6, 97]⟩
  , ⟨[(26, true), (23, false), (24, false), (67, false), (1, true)], [173, 180, 175, 176, 120, 36, 81, 128]⟩
  , ⟨[(11, false), (9, false), (54, true), (24, false), (26, false), (23, false), (3, true), (55, false), (41, true), (8, false), (1, true)], [126, 96, 42, 141]⟩
  , ⟨[(11, true), (31, false), (6, false), (17, false), (3, true), (26, false), (1, true), (49, false), (54, true)], [10, 95, 93]⟩
  , ⟨[(8, false), (41, true), (54, true), (24, false), (26, false), (23, false), (3, true), (11, false), (55, false), (1, true)], [126, 182, 124, 42, 141]⟩
  , ⟨[(28, false), (9, true), (54, true), (24, false), (26, false), (23, false), (3, true), (11, false), (1, true)], [124, 42, 141]⟩
  , ⟨[(9, true), (8, true), (6, false), (54, true), (49, false), (24, false), (26, false), (23, false), (3, true), (11, false), (1, true)], [185, 122, 38]⟩
  , ⟨[(49, false), (54, true), (46, false), (67, false), (23, false), (1, false), (47, false)], [66, 100, 121]⟩
  , ⟨[(54, true), (23, false), (1, false), (46, false), (67, false), (16, false)], [162, 187, 54, 114]⟩
  , ⟨[(4, true), (9, true), (42, true), (54, false), (1, false)], [0, 20, 71]⟩
  , ⟨[(9, true), (42, true), (1, false), (54, false)], [189, 161, 50, 65]⟩
  , ⟨[(4, false), (6, true), (54, false), (42, true), (1, false)], [190, 5, 65]⟩
  , ⟨[(4, true), (42, true), (54, false), (1, false)], [190, 0, 71, 143]⟩
  , ⟨[(42, true), (54, false), (1, false)], [190, 192, 161, 5, 65]⟩
  , ⟨[(49, true), (54, false), (24, false), (67, false), (1, false)], [193, 165, 30, 51]⟩
  , ⟨[(6, true), (54, false), (1, false), (49, false)], [193, 25, 39, 59]⟩
  , ⟨[(54, false), (67, false), (24, false), (1, false)], [193, 194, 195, 154, 137]⟩
  , ⟨[(37, true), (54, true), (1, false), (23, true)], [111, 21, 33, 89]⟩
  , ⟨[(67, false), (24, false), (46, false), (16, false), (1, false)], [196, 188, 197, 147, 4, 80]⟩
  , ⟨[(54, true), (23, true), (1, false), (46, false), (67, true)], [197, 147, 80, 90]⟩
  , ⟨[(49, false), (17, true), (54, false), (1, false)], [193, 195, 137]⟩
  , ⟨[(49, true), (54, false), (67, true), (24, false), (1, false)], [193, 165, 86]⟩
  , ⟨[(54, false), (24, false), (1, false), (67, true)], [193, 201, 195, 200, 154]⟩
  , ⟨[(54, false), (67, false), (2, true), (1, false)], [193, 196, 144, 195, 200, 154]⟩
  , ⟨[(23, false), (49, false), (46, false), (54, true), (67, false), (17, false), (1, false)], [188, 187, 113, 119]⟩
  , ⟨[(23, true), (17, false), (1, false), (46, false), (54, true)], [197, 147]⟩
  , ⟨[(47, true), (17, false), (54, true), (1, false), (23, false), (16, true)], [113, 119]⟩
  , ⟨[(17, false), (67, false), (46, false), (1, false), (54, true)], [205, 188, 204, 206, 54, 114]⟩
  , ⟨[(23, false), (67, false), (46, false), (1, false), (54, true)], [207, 188, 12, 187, 114, 54]⟩
  , ⟨[(67, false), (46, false), (1, false), (2, true)], [203, 207, 208, 197, 4, 80]⟩
  , ⟨[(49, true), (47, false), (23, false), (54, true), (1, false)], [54, 114]⟩
  , ⟨[(47, false), (54, true), (67, true), (1, false), (23, false)], [210, 135, 40, 43]⟩
  , ⟨[(54, true), (46, false), (1, false), (67, true)], [199, 211, 162, 206, 12]⟩
  , ⟨[(46, false), (1, false), (2, true)], [209, 212, 193, 202, 144, 195, 200, 154]⟩
  , ⟨[(54, false), (67, true), (2, true), (1, false)], [193, 202, 144, 195, 200, 154]⟩
  , ⟨[(23, false), (17, false), (54, true), (67, true), (1, false)], [211, 162, 206]⟩
  , ⟨[(23, true), (54, true), (1, false), (46, true)], [197, 47, 13]⟩
  , ⟨[(67, true), (1, false), (2, true)], [213, 214, 216, 211, 215, 162, 12]⟩
  , ⟨[(18, true), (47, false), (67, false), (46, true), (1, false), (54, true)], [216, 210, 63, 127]⟩
  , ⟨[(47, false), (1, false), (54, true), (46, true), (67, false)], [216, 210, 218, 11, 34]⟩
  , ⟨[(1, false), (2, true)], [213, 217, 203, 216, 219, 162, 12, 206]⟩
  , ⟨[(54, false), (24, false), (1, false)], [202, 196]⟩
  , ⟨[(23, true), (17, false), (1, false), (54, true)], [205, 216]⟩
  , ⟨[(17, false), (46, false), (1, false), (54, true)], [207, 212]⟩
  , ⟨[(23, false), (46, false), (1, false), (54, true)], [208, 212]⟩
  , ⟨[(17, false), (54, true), (1, false), (47, true), (23, false)], [206, 162]⟩
  , ⟨[(23, true), (1, true), (26, true), (40, true), (43, true)], [75, 173]⟩
  , ⟨[(55, true), (53, true), (1, true), (26, true), (43, false)], [97, 173]⟩
  , ⟨[(55, true), (1, true), (26, true), (5, true), (43, false)], [6, 227]⟩
  , ⟨[(31, true), (43, false), (1, true), (26, true), (55, false)], [112, 173]⟩
  , ⟨[(40, true), (43, true), (1, true), (23, false), (26, true)], [120, 173]⟩
  , ⟨[(49, true), (24, true), (1, false), (42, false), (54, false)], [123, 220]⟩
  , ⟨[(23, true), (37, false), (1, false), (17, false), (54, true)], [147, 216]⟩
  , ⟨[(6, false), (54, false), (49, false), (42, false), (1, false)], [154, 200]⟩
  , ⟨[(16, true), (1, false), (47, true), (23, false), (54, true)], [12, 225]⟩
  , ⟨[(47, true), (49, true), (24, false), (54, false), (1, false)], [165, 193]⟩
  , ⟨[(34, false), (1, false), (24, false), (49, true), (47, true), (54, false)], [99, 193]⟩
  , ⟨[(3, false), (1, true), (26, false), (28, true), (32, true), (51, false)], [46, 171]⟩
  , ⟨[(47, true), (1, false), (24, false), (42, false), (49, true), (54, false)], [136, 236]⟩
  , ⟨[(37, false), (44, true), (1, false), (23, true), (46, false), (54, true)], [80, 232]⟩
  , ⟨[(22, false), (6, false), (54, false), (24, false), (1, false), (17, false)], [166, 193]⟩
  , ⟨[(47, false), (49, false), (67, false), (54, true), (1, false), (23, false)], [187, 219]⟩
  , ⟨[(6, true), (3, true), (1, true), (11, true), (26, false), (49, true)], [24, 15]⟩
  , ⟨[(33, true), (51, true), (1, true), (3, false), (32, true), (46, false), (26, false)], [2, 102]⟩
  , ⟨[(48, false), (56, true), (1, true), (26, true), (43, true), (40, false), (67, true)], [117, 173]⟩
  , ⟨[(26, false), (3, false), (1, true), (32, true), (46, true), (51, true), (64, false)], [108, 58]⟩
  , ⟨[(37, false), (44, false), (1, false), (23, true), (46, false), (54, true), (67, false)], [4, 232]⟩
  , ⟨[(32, false), (3, false), (1, true), (18, false), (26, false), (53, true), (55, true)], [109, 35]⟩
  , ⟨[(3, false), (1, true), (18, true), (26, false), (28, false), (32, true), (51, false)], [82, 171]⟩
  , ⟨[(11, true), (26, false), (1, true), (4, false), (3, false), (32, false), (53, false)], [3, 139]⟩
  , ⟨[(24, false), (22, false), (1, false), (49, true), (47, false), (42, false), (54, false)], [51, 221]⟩
  , ⟨[(39, false), (48, true), (1, true), (26, true), (43, true), (31, false), (40, false)], [68, 173]⟩
  , ⟨[(26, false), (3, false), (1, true), (32, true), (46, true), (51, true), (64, true)], [110, 58]⟩
  , ⟨[(13, true), (11, false), (1, true), (3, false), (26, false), (32, false), (53, false)], [17, 131]⟩
  , ⟨[(18, true), (3, false), (1, true), (26, false), (32, false), (40, true), (53, true)], [56, 138]⟩
  , ⟨[(18, true), (3, false), (1, true), (26, false), (32, false), (53, true), (65, true)], [70, 254]⟩
  , ⟨[(48, false), (1, true), (26, true), (5, true), (43, true), (40, false), (67, true)], [101, 244]⟩
  , ⟨[(37, false), (44, false), (1, false), (23, true), (46, false), (54, true), (67, true)], [90, 232]⟩
  , ⟨[(37, false), (28, true), (1, true), (3, true), (26, false), (11, false), (49, true)], [22, 126]⟩
  , ⟨[(33, false), (51, true), (1, true), (3, false), (32, true), (46, false), (26, false)], [106, 102]⟩
  , ⟨[(3, false), (1, true), (11, true), (26, false), (30, false), (32, false), (53, false)], [60, 249]⟩
  , ⟨[(15, true), (48, true), (1, true), (26, true), (31, true), (43, true), (40, false)], [26, 173]⟩
  , ⟨[(11, true), (21, true), (1, true), (3, true), (26, false), (49, false), (54, true)], [95, 10]⟩
  , ⟨[(47, false), (22, true), (1, false), (24, false), (42, false), (49, true), (54, false)], [30, 221]⟩
  , ⟨[(40, false), (48, true), (1, true), (26, true), (5, true), (43, true), (39, true)], [36, 178]⟩
  , ⟨[(28, true), (37, true), (1, true), (3, true), (11, false), (26, false), (9, false)], [37, 126]⟩
  , ⟨[(28, true), (37, true), (1, true), (3, true), (11, false), (26, false), (8, true)], [38, 265]⟩
  , ⟨[(13, false), (32, false), (1, true), (3, false), (11, false), (26, false), (53, false)], [73, 76]⟩
  , ⟨[(65, false), (30, true), (1, false), (46, false), (23, false), (49, false), (54, true), (47, false)], [100, 212]⟩
  , ⟨[(30, true), (1, false), (46, false), (23, false), (49, false), (54, true), (47, false), (67, false)], [121, 268]⟩
  , ⟨[(18, true), (10, true), (1, false), (46, true), (47, false), (49, false), (54, true), (67, false)], [127, 216]⟩
  , ⟨[(48, false), (26, true), (1, true), (24, false), (55, false), (40, false), (43, true), (67, false)], [128, 173]⟩
  , ⟨[(5, false), (11, true), (1, true), (6, false), (3, true), (37, true), (42, true), (49, true)], [49, 173]⟩
  , ⟨[(11, true), (21, true), (1, true), (3, true), (26, false), (49, false), (51, true), (54, false)], [132, 10]⟩
  , ⟨[(28, false), (13, false), (1, true), (3, true), (26, false), (11, false), (31, false), (54, false)], [133, 28]⟩
  , ⟨[(48, false), (55, true), (1, true), (24, false), (26, true), (43, true), (40, false), (67, false)], [81, 173]⟩
  , ⟨[(7, false), (18, false), (1, false), (46, true), (23, false), (47, false), (49, false), (54, true)], [34, 211]⟩
  , ⟨[(32, false), (3, false), (1, true), (18, false), (26, false), (37, false), (53, true), (55, false)], [142, 35]⟩
  , ⟨[(13, true), (1, true), (3, true), (11, false), (26, false), (28, false), (54, false), (56, false)], [87, 145]⟩
  , ⟨[(5, false), (11, true), (1, true), (6, false), (3, true), (17, true), (37, false), (49, true)], [88, 173]⟩
  , ⟨[(3, false), (1, true), (18, false), (26, false), (28, false), (32, true), (33, true), (51, false)], [9, 171]⟩
  , ⟨[(3, false), (1, true), (18, false), (26, false), (28, false), (32, true), (33, false), (51, false)], [153, 171]⟩
  , ⟨[(31, true), (21, false), (1, true), (17, false), (3, true), (26, false), (11, true), (49, false)], [91, 10]⟩
  , ⟨[(21, false), (11, true), (1, true), (3, true), (17, true), (26, false), (49, false), (60, true)], [8, 10]⟩
  , ⟨[(48, false), (11, true), (1, true), (6, false), (3, true), (26, false), (5, true), (49, true)], [19, 44]⟩
  , ⟨[(5, false), (11, true), (1, true), (6, false), (3, true), (37, true), (42, false), (49, true)], [27, 173]⟩
  , ⟨[(7, false), (1, true), (24, true), (26, true), (40, false), (43, true), (48, false), (67, false)], [61, 173]⟩
  , ⟨[(18, true), (10, false), (1, false), (46, true), (47, false), (49, false), (54, true), (67, false)], [63, 216]⟩
  , ⟨[(21, true), (1, true), (3, true), (26, false), (29, false), (49, false), (11, true), (54, false)], [64, 273]⟩
  , ⟨[(21, false), (11, true), (1, true), (3, true), (17, true), (26, false), (49, false), (60, false)], [105, 10]⟩
  , ⟨[(26, true), (1, true), (24, true), (7, true), (40, false), (43, true), (48, false), (67, false)], [29, 173]⟩
  , ⟨[(18, false), (1, false), (23, false), (46, true), (47, false), (49, false), (54, true), (67, false)], [11, 276]⟩
  , ⟨[(32, false), (3, false), (1, true), (18, false), (26, false), (37, true), (53, true), (55, false)], [45, 35]⟩
  , ⟨[(6, true), (3, true), (1, true), (8, true), (11, false), (26, false), (28, true), (37, false)], [118, 258]⟩
  , ⟨[(28, false), (13, false), (1, true), (3, true), (26, false), (11, false), (31, true), (54, false)], [74, 28]⟩
  , ⟨[(11, false), (1, true), (3, true), (23, true), (26, false), (28, false), (53, true), (54, true), (55, true)], [134, 62]⟩
  , ⟨[(25, false), (13, true), (1, true), (3, true), (11, false), (26, false), (28, false), (54, false), (65, false)], [16, 278]⟩
  , ⟨[(8, true), (28, true), (1, true), (6, false), (3, true), (23, false), (26, false), (11, false), (37, false)], [122, 258]⟩
  , ⟨[(11, true), (21, false), (1, true), (6, false), (17, false), (3, true), (26, false), (29, false), (49, false)], [93, 282]⟩
  , ⟨[(6, true), (3, true), (1, true), (11, true), (17, false), (21, false), (26, false), (31, false), (49, false)], [57, 10]⟩
  , ⟨[(41, false), (62, false), (1, true), (26, true), (31, true), (40, false), (43, true), (48, true), (15, false)], [140, 173]⟩
  , ⟨[(11, false), (26, false), (1, true), (3, true), (23, true), (28, false), (42, true), (54, true), (55, false)], [129, 23]⟩
  , ⟨[(27, false), (5, true), (1, true), (6, false), (3, true), (26, false), (11, true), (49, true), (50, true)], [53, 284]⟩
  , ⟨[(41, false), (62, true), (1, true), (26, true), (31, true), (40, false), (43, true), (48, true), (15, false)], [104, 173]⟩
  , ⟨[(38, false), (1, true), (23, false), (24, false), (26, false), (3, true), (11, false), (28, false), (54, true)], [42, 141]⟩
  , ⟨[(5, false), (11, true), (1, true), (6, false), (3, true), (26, false), (31, true), (37, false), (49, true)], [146, 279]⟩
  , ⟨[(48, true), (27, true), (1, true), (26, true), (31, true), (40, false), (15, false), (43, true), (41, true)], [72, 173]⟩
  , ⟨[(8, true), (11, false), (1, true), (6, false), (3, true), (23, true), (26, false), (28, true), (37, false)], [116, 258]⟩
  , ⟨[(25, false), (13, true), (1, true), (3, true), (11, false), (26, false), (28, false), (54, false), (65, true)], [31, 278]⟩
  , ⟨[(11, false), (3, true), (1, true), (23, false), (26, false), (28, false), (38, false), (50, false), (54, true)], [55, 304]⟩
  , ⟨[(5, false), (11, true), (1, true), (6, false), (3, true), (26, false), (31, false), (37, false), (49, true)], [150, 279]⟩
  , ⟨[(6, true), (3, true), (1, true), (9, true), (11, false), (23, false), (26, false), (28, false), (38, true), (54, true)], [1, 124]⟩
  , ⟨[(11, true), (1, true), (6, false), (3, true), (26, false), (5, true), (27, true), (44, true), (49, true), (50, true)], [125, 284]⟩
  , ⟨[(11, false), (1, true), (3, true), (23, true), (26, false), (28, false), (52, false), (53, false), (54, true), (55, true)], [77, 62]⟩
  , ⟨[(28, false), (38, true), (1, true), (3, true), (23, false), (26, false), (9, false), (11, false), (54, true), (55, false)], [92, 96]⟩
  , ⟨[(11, true), (27, true), (1, true), (6, false), (3, true), (26, false), (5, true), (44, false), (49, true), (50, true)], [78, 284]⟩
  , ⟨[(11, false), (26, false), (1, true), (3, true), (23, true), (28, false), (42, false), (54, true), (55, false), (59, true)], [48, 23]⟩
  , ⟨[(11, false), (26, false), (1, true), (3, true), (23, true), (28, false), (42, false), (54, true), (55, false), (59, false)], [149, 23]⟩
  , ⟨[(9, true), (11, false), (1, true), (6, false), (3, true), (23, false), (26, false), (28, false), (38, true), (54, true)], [32, 124]⟩
  , ⟨[(11, false), (1, true), (3, true), (23, true), (26, false), (28, false), (52, true), (53, false), (54, true), (55, true), (66, false)], [107, 62]⟩
  , ⟨[(28, false), (1, true), (3, true), (11, false), (23, false), (26, false), (9, false), (38, true), (54, true), (55, true), (65, false)], [69, 98]⟩
  , ⟨[(38, true), (1, true), (3, true), (9, false), (23, false), (26, false), (28, false), (11, false), (54, true), (55, true), (65, true)], [152, 41]⟩
  , ⟨[(11, false), (1, true), (3, true), (23, true), (26, false), (28, false), (39, false), (52, true), (53, false), (54, true), (55, true), (66, true)], [52, 62]⟩
  , ⟨[(15, true), (1, true), (3, true), (11, false), (23, true), (26, false), (28, false), (39, true), (52, true), (53, false), (54, true), (55, true), (66, true)], [83, 62]⟩
  , ⟨[(15, false), (1, true), (3, true), (11, false), (23, true), (26, false), (28, false), (39, true), (52, true), (53, false), (54, true), (55, true), (66, true)], [115, 62]⟩
  , ⟨[(1, false), (54, false)], [221, 193, 231, 195, 233]⟩
  , ⟨[(1, false), (23, false), (17, false)], [325, 224, 215, 219, 162, 234, 225]⟩
  , ⟨[(1, false), (54, true), (23, false), (47, true)], [162, 325, 224, 234, 219, 211]⟩
  , ⟨[(1, false), (54, true), (23, false)], [327, 325, 224, 219, 211]⟩
  , ⟨[(1, false), (54, true)], [328, 325, 197, 216, 239, 212, 246]⟩
  , ⟨[(1, true), (26, false), (3, false), (11, false), (32, false), (53, false)], [253, 267]⟩
  , ⟨[(1, true), (26, false), (3, false), (11, true), (32, false), (53, false)], [249, 139, 260]⟩
  , ⟨[(1, true), (26, false), (3, false), (32, true), (51, false)], [171, 237, 248, 280, 281]⟩
  , ⟨[(1, true), (26, false), (3, false), (32, false), (37, false), (53, true), (55, false)], [277, 255, 138]⟩
  , ⟨[(1, true), (26, false), (3, false), (32, false), (37, false), (53, true)], [333, 247, 255, 138]⟩
  , ⟨[(1, true), (26, false), (3, false), (32, false), (37, false)], [334, 331, 330]⟩
  , ⟨[(1, true), (26, false), (3, false), (32, false), (37, true), (53, true), (55, false)], [292, 255, 138]⟩
  , ⟨[(1, true), (26, false), (3, false), (32, false), (37, true), (53, true)], [336, 247, 255, 138]⟩
  , ⟨[(1, true), (26, false), (3, false), (32, false), (37, true)], [337, 331, 330]⟩
  , ⟨[(1, true), (26, false), (3, false), (32, false), (53, true), (18, true)], [254, 255, 138]⟩
  , ⟨[(1, true), (26, false), (3, false), (32, false)], [335, 338, 339]⟩
  , ⟨[(1, true), (26, false), (3, false), (46, true)], [340, 332, 252, 245, 58]⟩
  , ⟨[(1, true), (26, false), (3, true), (11, false), (28, true)], [126, 266, 293, 307, 297]⟩
  , ⟨[(1, true), (26, false), (17, false), (49, false), (3, true), (6, true), (11, true), (31, false)], [299, 10, 262, 288]⟩
  , ⟨[(1, true), (26, false), (17, false), (49, false), (3, true), (6, true), (11, true)], [343, 10, 282, 262, 288]⟩
  , ⟨[(1, true), (26, false), (17, false), (49, false), (3, true), (11, true), (31, true)], [282, 10, 262, 288]⟩
  , ⟨[(1, true), (26, false), (17, false), (49, false), (3, true), (11, true)], [345, 10, 344, 298, 262, 288]⟩
  , ⟨[(1, true), (26, false), (49, false), (3, true), (11, true), (17, true), (21, false)], [289, 10, 346, 283, 262, 288]⟩
  , ⟨[(1, true), (26, false), (49, false), (3, true), (11, true), (17, true)], [347, 10, 262, 288]⟩
  , ⟨[(1, true), (26, false), (49, true), (3, true), (5, false), (11, true), (6, false), (37, false)], [310, 242, 305, 272, 285]⟩
  , ⟨[(1, true), (26, false), (49, true), (3, true), (5, false), (11, true), (6, false)], [349, 242, 272, 285]⟩
  , ⟨[(1, true), (26, false), (49, true), (3, true), (5, false), (11, true), (31, true), (6, false)], [305, 242, 272, 285]⟩
  , ⟨[(1, true), (26, false), (49, true), (3, true), (11, true)], [242, 350, 44, 302, 315, 312, 284]⟩
  , ⟨[(1, true), (26, true), (24, false), (67, false), (43, true), (40, false), (55, false)], [271, 181, 226, 178, 251, 264, 173]⟩
  , ⟨[(1, true), (26, true), (24, false), (67, false), (43, true), (40, false)], [353, 173, 181, 226, 275, 178, 264, 251]⟩
  , ⟨[(1, true), (26, true), (24, false), (67, false), (43, true)], [354, 173, 181, 226, 175, 228, 229]⟩
  , ⟨[(1, true), (26, true), (24, false), (67, false)], [355, 173, 175, 228, 229]⟩
  , ⟨[(1, true), (26, true), (43, false)], [173, 175, 228, 229, 227]⟩
  , ⟨[(1, true), (26, true), (43, true), (31, false), (40, false), (48, true)], [251, 173, 357, 264, 256, 356, 286, 290]⟩
  , ⟨[(1, true), (26, true), (43, true), (31, false), (40, false)], [358, 173, 357, 256, 356, 286, 290]⟩
  , ⟨[(1, true), (26, true), (43, true), (31, false)], [359, 357, 226, 230]⟩
  , ⟨[(1, true), (26, true), (43, true), (31, true), (40, false)], [178, 173, 357, 256, 356, 286, 290]⟩
  , ⟨[(1, true), (26, true), (43, true), (31, true)], [361, 357, 226, 230]⟩
  , ⟨[(1, true), (26, true)], [357, 360, 362, 264]⟩
  , ⟨[(1, true), (49, true), (3, true), (11, true)], [363, 352, 272]⟩
  , ⟨[(1, true), (46, false), (3, false)], [363, 340, 332, 243, 259, 102]⟩
  , ⟨[(1, true), (49, true), (3, true), (11, true)], [363, 352, 279]⟩
  , ⟨[(1, true), (49, true), (3, true), (11, true)], [363, 352, 285]⟩
  , ⟨[(1, true), (54, true), (23, false), (26, false), (3, true), (6, true), (11, false), (9, true), (28, false)], [311, 363, 342, 141, 309]⟩
  , ⟨[(1, true), (54, true), (23, false), (26, false), (3, true), (11, false), (9, true), (6, false), (28, false)], [318, 363, 342, 141, 309]⟩
  , ⟨[(1, true), (54, true), (23, false), (26, false), (3, true), (11, false), (28, false), (55, false), (9, false)], [314, 363, 342, 141, 309]⟩
  , ⟨[(1, true), (54, true), (23, false), (26, false), (3, true), (11, false), (28, false), (55, false)], [370, 363, 342, 368, 369]⟩
  , ⟨[(1, true), (54, true), (23, false), (26, false), (3, true), (11, false), (55, true), (28, false), (9, false), (65, true)], [321, 363, 342, 141, 309]⟩
  , ⟨[(1, true), (54, true), (23, false), (26, false), (3, true), (11, false), (55, true), (28, false), (9, false)], [372, 363, 342, 371, 320, 141, 309]⟩
  , ⟨[(1, true), (54, true), (23, false), (26, false), (3, true), (11, false), (55, true), (28, false)], [373, 363, 342, 368, 369]⟩
  , ⟨[(1, true), (54, true), (23, false), (26, false), (3, true), (11, false), (55, true)], [374, 363, 342, 352, 348, 346]⟩
  , ⟨[(1, true), (54, true), (23, false), (3, true), (11, false)], [363, 342, 375, 371, 124]⟩
  , ⟨[(1, true), (54, true), (23, true), (3, true), (11, false), (55, false)], [363, 342, 301, 316, 317, 23]⟩
  , ⟨[(1, true), (54, true), (23, true), (3, true), (11, false)], [363, 342, 377, 295, 313, 319, 322, 323, 324, 62]⟩
  , ⟨[(1, true), (49, false), (3, true), (11, true)], [363, 348, 346, 262]⟩
  , ⟨[(54, false), (3, true), (11, false), (13, false)], [325, 363, 342, 274, 294, 28]⟩
  , ⟨[(54, false), (1, true), (26, false), (3, true), (11, false), (28, false), (13, true)], [145, 325, 363, 342, 380, 296, 308]⟩
  , ⟨[(54, false), (1, true), (26, false), (3, true), (11, false), (28, false)], [381, 325, 363, 380, 352, 348, 346]⟩
  , ⟨[(54, false), (1, true), (26, false), (3, true), (11, false)], [382, 325, 363, 342, 352, 348, 346]⟩
  , ⟨[(54, false), (1, true), (26, false), (3, true)], [383, 325, 363, 352, 348, 346]⟩
  , ⟨[(1, true), (3, true), (11, true)], [379, 363, 352, 348, 346]⟩
  , ⟨[(1, true), (3, false)], [363, 341, 365, 267]⟩
  , ⟨[(1, true), (54, true), (3, true), (11, false)], [378, 363, 386, 385, 376, 384]⟩
  , ⟨[(1, true), (54, false), (3, true)], [384, 363, 325, 329]⟩
  , ⟨[(1, true), (54, false)], [388, 386, 325, 329]⟩
  , ⟨[(26, true)], [363, 220, 325, 329]⟩
  , ⟨[(3, false)], [390, 386, 220, 325, 329]⟩
  , ⟨[(1, true), (11, true)], [385, 386]⟩
  , ⟨[(11, false), (1, true), (3, true)], [387, 389]⟩
  , ⟨[(67, false), (24, false), (54, false)], [196, 389]⟩
  , ⟨[(49, true), (47, true), (24, false), (54, false)], [235, 389]⟩
  , ⟨[(28, true), (11, false), (1, true), (3, true)], [342, 363]⟩
  , ⟨[(22, false), (24, false), (6, false), (54, false), (17, false)], [240, 389]⟩
  , ⟨[(6, false), (31, false), (54, true), (3, true), (17, false), (1, true), (26, false), (49, false)], [183, 393]⟩
  , ⟨[(37, false), (8, true), (1, true), (28, true), (3, true), (23, false), (11, false), (6, false)], [297, 363]⟩
  , ⟨[(32, false), (7, false), (18, false), (23, false), (42, true), (1, false), (16, false), (4, false), (6, false)], [163, 169]⟩
  , ⟨[(1, true)], [391, 392, 393]⟩
  , ⟨[(54, true)], [401, 329]⟩
  , ⟨[(2, true)], [401, 220]⟩
  , ⟨[], [401, 402, 325]⟩
  ]

set_option maxHeartbeats 40000000 in
/-- KERNEL replay of the refutation — plain `decide`, no `native_decide`. -/
theorem check_ok : RupCheckerFast.checkRefutationFast F steps = true := by decide

/-- The recovered CNF is unsatisfiable (kernel-checked LRAT replay +
`rup_sound` composition). -/
theorem instance_unsat : ¬ ∃ σ, satFormula σ F :=
  RupCheckerFast.checkRefutationFast_sound F steps check_ok

/-- The gadget's variable set: DIMACS variables `1..67`. -/
def s : Finset ℕ := Finset.Icc 1 67

set_option maxHeartbeats 4000000 in
/-- END-TO-END VERDICT: no point of the `[0,1]` box reaches the sat_relu
gadget's unsafe region `{Y₀ ≥ 1 ∧ Y₁ ≤ 0}` — real-arithmetic SAFE. -/
theorem instance_safe :
    ∀ x : ℕ → ℝ, (∀ j ∈ s, 0 ≤ x j ∧ x j ≤ 1) →
      ¬ (1 ≤ SatRelu.Y0 (SatReluVerdict.clausesOf F) x ∧
         SatRelu.Y1 s x ≤ 0) :=
  SatReluVerdict.safe_of_unsat F s (by decide) instance_unsat

end SatReluSweep_v67c154

end Crownproof

/-! ## Trust-base check -/

#print axioms Crownproof.SatReluSweep_v67c154.check_ok
#print axioms Crownproof.SatReluSweep_v67c154.instance_unsat
#print axioms Crownproof.SatReluSweep_v67c154.instance_safe
