/-
MACHINE-GENERATED by `ny-cert`'s `lrat_to_lean` — do not edit.

sat_relu Route A instance transcript:
* DIMACS source : inst.cnf  (p cnf 73 156)
* LRAT source   : inst.lrat  (289 addition steps kept)

The kernel replays the full LRAT refutation with PLAIN `decide`
(no `native_decide`, no extra axioms) through
`RupCheckerFast.checkRefutationFast`, then composes
`checkRefutationFast_sound` (CNF-unsat) with
`SatReluVerdict.safe_of_unsat` (gadget real-arithmetic safety).
-/
import NyProof.SatReluVerdict
import NyProof.RupCheckerFast

namespace Crownproof

namespace SatReluSweep_v73c156

open RupImport.RUP RupChecker

set_option maxRecDepth 65536

/-- The recovered DIMACS formula, literal-for-literal. -/
def F : Formula :=
  [ [(1, false), (2, false), (3, true), (9, true), (16, false), (22, true), (47, false), (58, true), (68, true)]
  , [(1, false), (2, true), (3, false), (12, true), (13, true), (16, false), (19, false), (26, false), (46, true), (58, true)]
  , [(1, false), (2, true), (16, false), (46, false), (56, false), (58, true)]
  , [(1, false), (2, true), (3, true), (12, true), (16, false), (28, false), (46, true), (58, true), (60, false)]
  , [(1, true), (5, false), (8, false), (25, false), (30, true), (32, false), (34, false), (54, true), (57, true)]
  , [(1, true), (8, false), (13, true), (16, false), (18, true), (32, true), (44, true), (54, true), (57, true)]
  , [(1, false), (6, false), (16, true), (17, false), (29, false)]
  , [(1, false), (2, false), (6, false), (7, false), (14, true), (16, false), (18, false), (40, false), (63, false), (68, false)]
  , [(1, true), (8, false), (41, false), (56, false), (57, false)]
  , [(1, true), (5, true), (8, false), (12, false), (13, true), (16, true), (18, true), (32, true), (44, true), (54, true), (57, true)]
  , [(1, false), (6, true), (16, true), (17, false), (20, true), (27, false), (29, false), (42, true)]
  , [(1, true), (8, false), (13, true), (25, true), (32, true), (44, false), (56, false), (57, true)]
  , [(1, false), (2, true), (12, false), (14, true), (16, false), (46, true), (58, true)]
  , [(1, true), (8, false), (18, false), (32, true), (44, true), (54, true), (57, true), (58, false)]
  , [(1, false), (2, true), (16, false), (46, false), (56, true), (58, true)]
  , [(1, true), (7, false), (8, false), (13, false), (27, false), (29, false), (32, true), (44, false), (57, true)]
  , [(1, true), (4, true), (8, false), (18, true), (34, false), (41, true), (43, true), (47, true), (57, false), (58, true)]
  , [(1, false), (2, false), (14, false), (16, false), (63, false), (66, false), (67, true), (68, false)]
  , [(1, false), (8, false), (16, true), (17, false), (29, true), (43, false), (59, false)]
  , [(1, false), (2, true), (3, false), (12, true), (16, false), (26, true), (46, true), (47, true), (58, true)]
  , [(1, false), (2, false), (6, false), (7, true), (14, true), (16, false), (18, false), (46, true), (63, false), (68, false)]
  , [(1, true), (4, false), (8, false), (34, false), (41, true), (47, true), (57, false), (58, true)]
  , [(1, false), (8, true), (16, true), (17, false), (29, true), (35, false), (43, false), (64, false)]
  , [(1, false), (2, false), (9, false), (16, false), (22, true), (28, false), (47, false), (58, true), (68, true)]
  , [(1, false), (8, true), (16, true), (17, false), (29, true), (35, false), (43, false), (64, true)]
  , [(1, true), (8, false), (20, true), (25, false), (30, false), (32, false), (34, false), (57, true)]
  , [(1, false), (6, true), (12, true), (16, true), (17, false), (20, false), (26, true), (29, false), (52, false)]
  , [(1, true), (8, false), (13, true), (25, false), (32, true), (44, false), (56, false), (57, true)]
  , [(1, false), (2, false), (14, false), (16, false), (50, true), (63, false), (66, false), (67, false), (68, false)]
  , [(1, true), (8, true), (20, false), (21, false), (37, true), (43, true), (64, true)]
  , [(1, false), (2, false), (9, false), (16, false), (22, true), (28, true), (47, false), (50, true), (58, true), (68, true)]
  , [(1, false), (2, false), (16, false), (22, false), (24, true), (47, false), (58, true), (68, true)]
  , [(1, false), (2, false), (16, false), (22, false), (24, false), (47, false), (48, false), (58, true), (68, true)]
  , [(1, false), (6, true), (16, true), (17, false), (20, true), (27, true), (29, false), (42, true), (52, false)]
  , [(1, false), (2, false), (14, true), (16, false), (18, true), (23, true), (35, true), (52, true), (61, false), (63, false), (67, false), (68, false)]
  , [(1, false), (4, false), (16, true), (17, false), (29, true), (39, true), (43, true), (59, false)]
  , [(1, false), (2, true), (11, false), (16, false), (43, true), (58, false)]
  , [(1, true), (8, false), (13, true), (27, true), (32, true), (44, false), (56, true), (57, true), (68, true)]
  , [(1, false), (2, false), (10, true), (16, true), (17, true), (29, true)]
  , [(1, false), (2, true), (11, true), (16, false), (58, false), (72, true), (73, false)]
  , [(1, true), (8, false), (13, false), (18, true), (32, true), (44, true), (54, true), (57, true)]
  , [(1, true), (8, true), (31, false), (37, false), (54, true), (69, true), (71, true)]
  , [(1, true), (8, false), (41, false), (56, true), (57, false), (60, false)]
  , [(1, false), (2, true), (11, true), (16, false), (58, false), (72, true), (73, true)]
  , [(1, false), (2, false), (10, false), (16, true), (17, true), (54, false)]
  , [(1, true), (8, false), (32, true), (44, true), (52, false), (54, false), (57, true)]
  , [(1, false), (2, true), (3, false), (12, true), (16, false), (26, true), (46, true), (47, false), (58, true)]
  , [(1, false), (16, true), (17, false), (29, true), (39, true), (43, true), (59, true)]
  , [(1, false), (2, false), (16, false), (22, false), (24, false), (47, false), (48, true), (58, true), (68, true)]
  , [(1, false), (8, true), (16, true), (17, false), (29, true), (35, true), (43, false)]
  , [(1, false), (2, false), (14, false), (16, false), (63, false), (66, true), (68, false), (73, false)]
  , [(1, false), (2, false), (14, true), (16, false), (18, true), (23, false), (52, true), (61, false), (63, false), (67, false), (68, false)]
  , [(1, false), (2, false), (3, false), (16, false), (47, false), (58, false), (68, true)]
  , [(1, true), (8, false), (34, true), (41, true), (47, true), (57, false), (58, true)]
  , [(1, true), (7, true), (8, false), (13, false), (25, true), (32, true), (40, true), (44, false), (57, true)]
  , [(1, true), (8, true), (19, false), (21, false), (37, true), (43, true), (64, false)]
  , [(1, false), (2, false), (14, false), (16, false), (63, false), (66, true), (68, false), (73, true)]
  , [(1, false), (2, false), (6, true), (14, true), (16, false), (18, false), (24, true), (28, false), (55, true), (63, false), (66, false), (68, false), (73, false)]
  , [(1, false), (14, false), (16, true), (17, false), (29, true), (35, true), (39, false), (43, true), (62, true)]
  , [(1, true), (8, false), (41, true), (57, false), (58, false), (73, false)]
  , [(1, true), (8, false), (12, true), (25, true), (32, false), (34, false), (57, true), (58, true), (70, false)]
  , [(1, false), (2, true), (3, false), (12, true), (13, true), (16, false), (19, true), (26, false), (46, true), (58, true)]
  , [(1, true), (2, true), (8, false), (9, true), (16, false), (32, false), (34, true), (57, true)]
  , [(1, true), (2, false), (8, false), (32, false), (34, true), (43, false), (57, true)]
  , [(1, false), (2, false), (6, false), (7, true), (14, true), (16, false), (18, false), (46, false), (63, false), (68, false)]
  , [(1, true), (8, true), (31, false), (37, false), (54, true), (69, true), (71, false)]
  , [(1, true), (2, true), (8, false), (9, false), (32, false), (34, true), (57, true)]
  , [(1, false), (2, true), (3, true), (12, true), (16, false), (28, false), (46, true), (58, true), (60, true)]
  , [(1, false), (8, false), (16, true), (17, false), (29, true), (43, false), (59, true)]
  , [(1, true), (8, true), (11, false), (37, true), (43, false)]
  , [(1, false), (2, true), (11, true), (16, false), (17, false), (23, true), (58, false), (71, true), (72, false), (73, true)]
  , [(1, false), (2, true), (11, false), (16, false), (34, true), (43, false), (58, false)]
  , [(1, true), (7, true), (8, false), (13, false), (25, false), (32, true), (40, true), (44, false), (57, true)]
  , [(1, true), (8, true), (18, false), (19, true), (21, false), (37, true), (43, true), (64, false)]
  , [(1, true), (8, false), (41, true), (46, true), (57, false), (58, false), (73, true)]
  , [(1, true), (8, false), (22, true), (41, true), (47, false), (57, false), (58, true)]
  , [(1, false), (2, false), (3, false), (9, true), (16, false), (22, true), (47, false), (58, true), (68, true)]
  , [(1, false), (2, true), (12, false), (14, false), (16, false), (38, true), (46, true), (58, true)]
  , [(1, true), (8, true), (26, false), (31, false), (37, false), (69, false)]
  , [(1, true), (2, true), (8, false), (9, true), (16, true), (32, false), (34, true), (57, true)]
  , [(1, true), (8, false), (25, true), (32, false), (34, false), (39, true), (57, true), (58, true), (70, true)]
  , [(1, false), (6, true), (16, true), (17, false), (20, false), (29, false), (52, true)]
  , [(1, true), (8, false), (20, false), (25, false), (30, false), (31, true), (32, false), (34, false), (57, true)]
  , [(1, false), (2, false), (6, true), (14, true), (16, false), (18, false), (24, true), (28, true), (50, false), (55, true), (63, false), (66, false), (68, false), (73, false)]
  , [(1, false), (2, false), (16, false), (47, true), (68, true)]
  , [(1, false), (2, false), (14, true), (16, false), (18, true), (52, false), (63, false), (68, false)]
  , [(1, true), (8, false), (18, false), (32, true), (44, true), (54, true), (57, true), (58, true)]
  , [(1, true), (7, false), (8, false), (13, false), (27, false), (29, true), (32, true), (44, false), (57, true)]
  , [(1, true), (5, true), (8, false), (12, true), (13, true), (16, true), (18, true), (32, true), (44, true), (54, true), (57, true)]
  , [(1, true), (8, false), (22, false), (41, true), (47, false), (57, false), (58, true)]
  , [(1, false), (2, false), (10, true), (16, true), (17, true), (29, false), (31, true)]
  , [(1, true), (8, false), (25, true), (32, false), (34, false), (38, true), (57, true), (58, false)]
  , [(1, true), (4, true), (7, true), (8, false), (18, false), (34, false), (41, true), (47, true), (57, false), (58, true)]
  , [(1, false), (6, true), (12, false), (16, true), (17, false), (20, false), (26, true), (29, false), (52, false)]
  , [(1, false), (2, true), (9, false), (11, true), (16, false), (17, false), (23, false), (58, false), (71, true), (72, false), (73, true)]
  , [(1, false), (2, true), (11, true), (16, false), (58, false), (72, false), (73, false)]
  , [(1, true), (8, false), (20, false), (25, false), (30, false), (31, false), (32, false), (34, false), (57, true)]
  , [(1, false), (14, true), (16, true), (17, false), (29, true), (39, false), (43, true)]
  , [(1, true), (4, true), (8, false), (18, true), (34, false), (41, true), (43, false), (47, true), (57, false), (58, true)]
  , [(1, true), (8, true), (20, true), (21, false), (37, true), (43, true), (64, true)]
  , [(1, false), (2, true), (9, true), (11, true), (16, false), (17, false), (23, false), (58, false), (71, true), (72, false), (73, true)]
  , [(1, false), (14, false), (16, true), (17, false), (29, true), (35, false), (39, false), (43, true)]
  , [(1, true), (7, true), (8, false), (13, false), (32, true), (40, false), (44, false), (57, true), (71, true)]
  , [(1, true), (8, true), (31, false), (37, false), (54, false), (69, true)]
  , [(1, false), (6, true), (16, true), (17, false), (20, true), (27, true), (29, false), (42, true), (52, true)]
  , [(1, false), (2, false), (16, false), (63, true), (68, false)]
  , [(1, false), (2, false), (6, true), (14, true), (16, false), (18, false), (55, false), (63, false), (67, false), (68, false)]
  , [(1, true), (8, false), (25, true), (32, false), (34, false), (39, false), (57, true), (58, true), (70, true)]
  , [(1, true), (8, false), (41, false), (56, true), (57, false), (60, true)]
  , [(1, false), (6, true), (16, true), (17, false), (20, false), (26, false), (29, false), (52, false), (57, false)]
  , [(1, false), (2, false), (6, true), (14, true), (16, false), (18, false), (24, false), (55, true), (63, false), (68, false)]
  , [(1, true), (5, true), (8, false), (25, false), (30, true), (32, false), (34, false), (54, true), (57, true)]
  , [(1, false), (2, true), (16, true), (17, true)]
  , [(1, false), (2, false), (14, true), (16, false), (18, true), (52, true), (61, true), (63, false), (67, false), (68, false)]
  , [(1, false), (2, true), (12, false), (14, false), (16, false), (38, false), (46, true), (58, true)]
  , [(1, false), (6, true), (16, true), (17, false), (20, true), (29, false), (42, false)]
  , [(1, true), (5, false), (8, false), (13, true), (16, true), (18, true), (32, true), (44, true), (54, true), (57, true)]
  , [(1, false), (2, false), (3, true), (16, false), (26, false), (47, false), (58, false), (68, true)]
  , [(1, true), (8, true), (26, true), (31, false), (37, false), (69, false)]
  , [(1, true), (8, false), (41, true), (46, false), (57, false), (58, false), (73, true)]
  , [(1, true), (4, true), (7, false), (8, false), (18, false), (34, false), (41, true), (47, true), (57, false), (58, true)]
  , [(1, true), (8, true), (31, true), (37, false)]
  , [(1, true), (8, true), (18, true), (19, true), (21, false), (37, true), (43, true), (64, false)]
  , [(1, true), (8, false), (13, true), (32, true), (44, false), (56, true), (57, true), (68, false)]
  , [(1, true), (8, false), (32, true), (44, true), (52, true), (54, false), (57, true)]
  , [(1, false), (14, false), (16, true), (17, false), (29, true), (35, true), (39, false), (43, true), (62, false)]
  , [(1, false), (2, true), (11, true), (16, false), (17, true), (58, false), (72, false), (73, true)]
  , [(1, true), (7, true), (8, false), (13, false), (32, true), (40, false), (44, false), (57, true), (71, false)]
  , [(1, true), (8, true), (21, true), (37, true), (43, true)]
  , [(1, true), (8, false), (25, true), (32, false), (34, false), (38, false), (57, true), (58, false)]
  , [(1, false), (2, true), (9, false), (11, false), (16, false), (34, false), (43, false), (58, false)]
  , [(1, false), (4, true), (16, true), (17, false), (29, true), (39, true), (43, true), (59, false)]
  , [(1, false), (2, false), (6, true), (14, true), (16, false), (18, false), (24, true), (55, true), (63, false), (66, true), (68, false)]
  , [(1, false), (2, true), (9, true), (11, false), (16, false), (34, false), (43, false), (58, false)]
  , [(1, false), (2, true), (11, true), (16, false), (17, false), (58, false), (71, false), (72, false), (73, true)]
  , [(1, true), (8, false), (12, false), (25, true), (32, false), (34, false), (57, true), (58, true), (70, false)]
  , [(1, true), (2, false), (8, false), (32, false), (34, true), (43, true), (57, true)]
  , [(1, false), (6, true), (16, true), (17, false), (20, false), (26, false), (29, false), (52, false), (57, true)]
  , [(1, false), (2, false), (14, false), (16, false), (50, false), (63, false), (66, false), (67, false), (68, false)]
  , [(1, false), (2, false), (6, true), (14, true), (16, false), (18, false), (24, true), (28, true), (50, true), (55, true), (63, false), (66, false), (68, false), (73, false)]
  , [(1, false), (2, false), (9, false), (16, false), (22, true), (28, true), (47, false), (50, false), (58, true), (68, true)]
  , [(1, false), (2, false), (3, true), (16, false), (26, true), (41, false), (47, false), (58, false), (68, true)]
  , [(1, true), (8, true), (11, true), (37, true), (43, false)]
  , [(1, false), (2, false), (6, true), (14, true), (16, false), (18, false), (24, true), (55, true), (63, false), (66, false), (68, false), (73, true)]
  , [(1, false), (2, false), (3, true), (16, false), (26, true), (41, true), (47, false), (58, false), (68, true)]
  , [(1, true), (8, false), (25, false), (30, true), (32, false), (34, false), (54, false), (57, true)]
  , [(1, false), (2, true), (3, false), (12, true), (13, false), (16, false), (26, false), (46, true), (58, true)]
  , [(1, true), (7, false), (8, false), (13, false), (27, true), (32, true), (44, false), (57, true)]
  , [(1, true), (8, false), (13, true), (27, false), (32, true), (44, false), (56, true), (57, true), (68, true)]
  , [(1, false), (2, true), (3, true), (12, true), (16, false), (28, true), (46, true), (58, true)]
  , [(1, false), (2, false), (10, true), (16, true), (17, true), (29, false), (31, false)]
  , [(1, false), (2, false), (14, true), (16, false), (18, true), (52, true), (63, false), (67, true), (68, false)]
  , [(1, false), (2, false), (6, true), (14, true), (16, false), (18, false), (55, false), (63, false), (67, true), (68, false)]
  , [(1, false), (2, false), (14, true), (16, false), (18, true), (23, true), (35, false), (52, true), (61, false), (63, false), (67, false), (68, false)]
  , [(1, false), (2, false), (10, false), (16, true), (17, true), (54, true)]
  , [(1, false), (2, false), (6, false), (7, false), (14, true), (16, false), (18, false), (40, true), (63, false), (68, false)]
  ]

/-- The LRAT refutation: derived clause + database-index hints per step. -/
def steps : List RStep :=
  [ ⟨[(66, false), (68, false), (2, false), (14, false), (16, false), (50, false), (1, false)], [105, 17, 138]⟩
  , ⟨[(68, false), (50, false), (2, false), (14, false), (16, false), (1, false)], [105, 156, 50, 56]⟩
  , ⟨[(68, true), (48, false), (2, false), (16, false), (22, false), (24, false), (47, false), (1, false), (3, false)], [52, 32]⟩
  , ⟨[(66, true), (68, false), (2, false), (14, false), (16, false), (1, false)], [105, 50, 56]⟩
  , ⟨[(68, false), (16, false), (2, false), (14, false), (1, false)], [105, 157, 159, 17, 28]⟩
  , ⟨[(22, false), (16, false), (2, false), (1, false), (68, true), (58, true)], [84, 31, 32, 48]⟩
  , ⟨[(16, false), (14, false), (2, false), (9, false), (3, false), (1, false)], [160, 84, 52, 161, 23, 30, 140]⟩
  , ⟨[(43, false), (17, false), (8, false), (16, true), (1, false), (29, true)], [18, 68]⟩
  , ⟨[(39, true), (17, false), (4, false), (16, true), (1, false), (29, true), (43, true)], [47, 35]⟩
  , ⟨[(17, false), (14, false), (4, false), (6, false), (8, false), (1, false), (16, true)], [6, 163, 164, 101, 58, 125]⟩
  , ⟨[(14, false), (10, false), (2, false), (1, false), (4, false), (6, false), (8, false), (9, false), (3, false)], [162, 165, 44, 154]⟩
  , ⟨[(17, true), (16, true), (2, false), (10, false), (1, false)], [44, 154]⟩
  , ⟨[(16, true), (10, false), (2, false), (4, false), (6, false), (8, false), (1, false), (14, true)], [167, 6, 163, 164, 97]⟩
  , ⟨[(68, true), (47, false), (2, false), (9, false), (16, false), (1, false), (3, false)], [52, 161, 23, 30, 140]⟩
  , ⟨[(18, false), (68, false), (2, false), (6, false), (7, false), (16, false), (14, true), (1, false)], [105, 7, 155]⟩
  , ⟨[(68, false), (35, true), (2, false), (6, false), (7, false), (16, false), (14, true), (1, false)], [105, 170, 85, 151, 113, 34, 51]⟩
  , ⟨[(68, true), (16, false), (9, false), (2, false), (1, false), (3, false)], [84, 169]⟩
  , ⟨[(10, false), (9, false), (2, false), (6, false), (7, false), (1, false), (3, false), (4, false), (8, false)], [166, 168, 172, 105, 170, 171, 85, 151, 113, 51, 153]⟩
  , ⟨[(57, false), (58, true), (8, false), (47, false), (22, true), (1, true)], [75, 8, 42, 108]⟩
  , ⟨[(32, false), (31, false), (2, false), (8, false), (57, true), (20, false), (25, false), (30, false), (1, true)], [96, 63, 136]⟩
  , ⟨[(13, false), (54, true), (8, false), (7, false), (29, true), (32, true), (57, true), (18, true), (1, true)], [40, 147, 87]⟩
  , ⟨[(54, true), (29, true), (8, false), (32, true), (56, true), (57, true), (68, false), (16, false), (18, true), (7, false), (1, true)], [176, 5, 123]⟩
  , ⟨[(29, true), (56, true), (8, false), (7, false), (32, true), (57, true), (1, true), (68, false), (52, true), (16, false), (18, true)], [177, 124, 123, 147, 87]⟩
  , ⟨[(44, false), (56, true), (8, false), (68, false), (7, false), (57, true), (32, true), (1, true), (29, false)], [123, 15, 147]⟩
  , ⟨[(44, true), (32, true), (16, false), (8, false), (18, true), (1, true), (57, true), (52, true)], [124, 40, 5]⟩
  , ⟨[(29, false), (32, true), (8, false), (68, false), (7, false), (57, true), (25, false), (1, true), (44, false)], [179, 27, 15, 147]⟩
  , ⟨[(32, true), (25, false), (8, false), (7, false), (57, true), (1, true), (68, false), (52, true), (16, false), (18, true)], [180, 181, 178, 27, 147, 87]⟩
  , ⟨[(34, true), (32, false), (2, false), (8, false), (1, true), (57, true)], [63, 136]⟩
  , ⟨[(30, false), (25, false), (2, false), (8, false), (57, true), (20, false), (1, true), (32, false)], [183, 175, 82]⟩
  , ⟨[(25, false), (20, false), (8, false), (57, true), (2, false), (1, true), (7, false), (68, false), (52, true), (16, false), (18, true)], [182, 183, 184, 145, 111, 4]⟩
  , ⟨[(70, false), (32, false), (8, false), (57, true), (58, true), (25, true), (1, true), (34, false)], [60, 135]⟩
  , ⟨[(32, false), (25, true), (2, false), (8, false), (57, true), (58, true), (1, true)], [183, 186, 80, 107]⟩
  , ⟨[(29, true), (54, true), (16, false), (8, false), (68, false), (7, false), (18, true), (52, true), (57, true), (32, true), (25, true), (1, true)], [180, 178, 176, 11]⟩
  , ⟨[(29, false), (25, true), (8, false), (68, false), (7, false), (57, true), (1, true), (32, true), (44, false)], [179, 11, 15, 147]⟩
  , ⟨[(25, true), (58, true), (2, false), (16, false), (8, false), (68, false), (7, false), (18, true), (52, true), (1, true), (57, true)], [187, 180, 189, 178, 11, 147, 87]⟩
  , ⟨[(58, true), (22, true), (8, false), (2, false), (7, false), (68, false), (52, true), (16, false), (18, true), (47, false), (1, true)], [174, 190, 182, 185, 183, 25, 145, 111, 4]⟩
  , ⟨[(68, false), (16, false), (2, false), (1, false), (18, true)], [105, 160, 85, 151, 113, 51, 34, 153]⟩
  , ⟨[(3, false), (16, false), (1, false), (47, false), (22, true), (58, true), (2, false), (68, true)], [76, 172]⟩
  , ⟨[(16, false), (18, true), (2, false), (47, false), (22, true), (58, true), (1, false)], [192, 193, 0, 23, 30, 140]⟩
  , ⟨[(17, true), (29, true), (2, false), (16, true), (1, false), (54, true)], [154, 38]⟩
  , ⟨[(29, true), (54, true), (16, true), (14, true), (8, false), (2, false), (1, false)], [195, 163, 97, 47, 164, 131]⟩
  , ⟨[(17, false), (29, false), (16, true), (20, true), (1, false), (52, true)], [6, 115, 10, 104]⟩
  , ⟨[(54, true), (14, true), (2, false), (16, true), (20, true), (52, true), (1, false), (8, false)], [196, 197, 154, 90, 150]⟩
  , ⟨[(29, false), (54, false), (2, false), (16, true), (1, false), (20, true), (52, true)], [197, 44, 90, 150]⟩
  , ⟨[(17, true), (54, false), (1, false), (16, true), (2, false), (29, true)], [44, 38]⟩
  , ⟨[(14, true), (52, true), (16, true), (8, false), (2, false), (20, true), (1, false)], [198, 199, 200, 163, 97, 164, 47, 131]⟩
  , ⟨[(39, true), (29, true), (16, true), (1, false), (17, false), (43, true)], [164, 47, 131]⟩
  , ⟨[(54, false), (52, true), (1, false), (8, false), (20, true), (16, true), (2, false)], [201, 199, 200, 163, 202, 101, 58, 125]⟩
  , ⟨[(29, true), (14, false), (1, false), (8, false), (16, true), (2, false), (54, true)], [195, 163, 202, 101, 58, 125]⟩
  , ⟨[(52, true), (16, true), (2, false), (1, false), (20, true), (8, false)], [201, 203, 204, 197, 154, 90, 150]⟩
  , ⟨[(17, true), (29, false), (2, false), (16, true), (1, false), (54, true)], [154, 90, 150]⟩
  , ⟨[(29, false), (54, true), (1, false), (20, true), (52, false), (16, true), (2, false)], [206, 6, 115, 10, 33]⟩
  , ⟨[(54, true), (16, true), (1, false), (8, false), (20, true), (2, false)], [205, 207, 196, 204]⟩
  , ⟨[(46, true), (28, true), (1, false), (16, false), (14, false), (58, true), (3, true), (2, true)], [149, 77, 114]⟩
  , ⟨[(46, false), (58, true), (1, false), (16, false), (2, true)], [2, 14]⟩
  , ⟨[(12, false), (14, false), (1, false), (16, false), (58, true), (2, true)], [210, 77, 114]⟩
  , ⟨[(3, true), (14, false), (1, false), (16, false), (58, true), (2, true)], [210, 211, 209, 3, 67]⟩
  , ⟨[(14, false), (58, true), (1, false), (16, false), (47, false), (2, true)], [210, 211, 212, 46, 146, 1, 61]⟩
  , ⟨[(3, false), (58, true), (1, false), (16, false), (47, false), (2, true)], [210, 213, 12, 46, 146, 1, 61]⟩
  , ⟨[(58, true), (47, false), (1, false), (16, false), (2, true)], [210, 213, 12, 214, 149, 3, 67]⟩
  , ⟨[(73, true), (23, true), (1, false), (16, false), (17, false), (58, false), (11, true), (2, true)], [43, 134, 70]⟩
  , ⟨[(73, false), (11, true), (1, false), (16, false), (58, false), (2, true)], [39, 95]⟩
  , ⟨[(11, true), (17, false), (1, false), (16, false), (2, true), (58, false)], [217, 43, 216, 134, 100, 94]⟩
  , ⟨[(11, false), (58, false), (1, false), (16, false), (2, true)], [36, 71, 133, 130]⟩
  , ⟨[(58, false), (16, false), (1, false), (2, true)], [219, 217, 218, 43, 126]⟩
  , ⟨[(3, true), (12, true), (1, false), (16, false), (2, true)], [220, 210, 149, 3, 67]⟩
  , ⟨[(12, true), (16, false), (1, false), (2, true)], [220, 215, 210, 221, 19, 146, 1, 61]⟩
  , ⟨[(16, false), (1, false), (2, true)], [220, 210, 222, 12, 77, 114]⟩
  , ⟨[(29, true), (43, false), (16, true), (1, false), (17, false)], [163, 49, 22, 24]⟩
  , ⟨[(14, false), (58, true), (2, false), (16, false), (1, false), (3, false)], [160, 162, 84, 161, 76]⟩
  , ⟨[(55, true), (6, true), (2, false), (16, false), (14, true), (68, false), (18, false), (73, true), (1, false)], [105, 110, 132, 143]⟩
  , ⟨[(6, true), (73, true), (2, false), (16, false), (14, true), (68, false), (18, false), (1, false)], [105, 226, 106, 152]⟩
  , ⟨[(6, false), (46, true), (2, false), (16, false), (14, true), (68, false), (18, false), (1, false)], [105, 170, 20]⟩
  , ⟨[(55, true), (6, true), (2, false), (16, false), (14, true), (68, false), (18, false), (1, false)], [105, 227, 110, 132, 57, 83, 139]⟩
  , ⟨[(6, true), (18, false), (2, false), (16, false), (14, true), (1, false), (68, false)], [105, 229, 106, 152]⟩
  , ⟨[(22, true), (47, false), (1, false), (2, false), (16, false), (58, true), (3, false)], [225, 194, 193, 105, 230, 170, 228, 64]⟩
  , ⟨[(68, false), (14, true), (2, false), (1, false), (16, false)], [105, 192, 230, 170, 228, 64]⟩
  , ⟨[(58, true), (16, false), (1, false), (3, false), (2, false)], [225, 232, 84, 161, 193]⟩
  , ⟨[(68, true), (16, false), (1, false), (2, false), (3, false)], [233, 84, 52]⟩
  , ⟨[(16, false), (2, false), (1, false), (3, false)], [234, 160, 232]⟩
  , ⟨[(17, false), (6, false), (1, false), (14, true), (16, true)], [6, 224, 97, 202]⟩
  , ⟨[(17, true), (2, false), (1, false), (16, true)], [167, 38, 90, 150]⟩
  , ⟨[(52, true), (29, false), (17, false), (16, true), (6, true), (1, false)], [197, 81]⟩
  , ⟨[(26, false), (20, false), (17, false), (16, true), (6, true), (29, false), (1, false)], [238, 109, 137]⟩
  , ⟨[(20, false), (29, false), (17, false), (16, true), (6, true), (1, false)], [238, 239, 93, 26]⟩
  , ⟨[(29, false), (6, true), (17, false), (16, true), (1, false)], [238, 240, 115, 10, 33]⟩
  , ⟨[(14, true), (16, true), (1, false), (17, false)], [236, 241, 224, 97, 202]⟩
  , ⟨[(58, false), (26, true), (1, false), (2, false), (16, false), (68, true), (3, true)], [84, 141, 144]⟩
  , ⟨[(58, true), (68, true), (1, false), (2, false), (16, false), (3, true)], [84, 161, 0, 23, 140, 30]⟩
  , ⟨[(68, true), (16, false), (2, false), (1, false), (3, true)], [84, 244, 117, 141, 144]⟩
  , ⟨[(16, false), (2, false), (1, false), (3, true)], [245, 160, 232]⟩
  , ⟨[(29, true), (16, true), (1, false), (17, false)], [242, 224, 202, 101, 58, 125]⟩
  , ⟨[(2, false), (1, false), (3, true)], [246, 237, 247, 6, 241]⟩
  , ⟨[(1, false), (3, true)], [248, 223, 112, 247, 6, 241]⟩
  , ⟨[(37, false), (54, false), (26, true), (31, false), (8, true), (1, true)], [103, 118]⟩
  , ⟨[(37, true), (64, true), (8, true), (43, true), (20, true), (1, true)], [99, 128]⟩
  , ⟨[(37, false), (8, true), (31, false), (1, true), (26, true)], [118, 250, 41, 65]⟩
  , ⟨[(8, true), (18, false), (1, true), (43, true), (20, true), (31, false), (26, true)], [252, 128, 251, 55, 73]⟩
  , ⟨[(32, false), (25, false), (8, false), (34, false), (1, true), (54, true), (57, true), (20, true)], [25, 111, 4]⟩
  , ⟨[(32, true), (56, true), (68, false), (58, false), (57, true), (8, false), (18, false), (54, true), (13, true), (1, true)], [13, 123]⟩
  , ⟨[(32, false), (34, false), (8, false), (1, true), (54, true), (57, true), (20, true), (38, false), (58, false)], [129, 254]⟩
  , ⟨[(32, true), (13, true), (68, false), (58, false), (57, true), (8, false), (18, false), (54, true), (1, true)], [13, 255, 27, 11]⟩
  , ⟨[(32, false), (38, false), (1, true), (54, true), (57, true), (20, true), (8, false), (58, false), (2, true), (9, false)], [66, 129, 254]⟩
  , ⟨[(32, true), (7, true), (68, false), (58, false), (57, true), (8, false), (18, false), (54, true), (71, false), (1, true)], [13, 257, 127, 54, 72]⟩
  , ⟨[(32, false), (54, true), (8, false), (57, true), (58, false), (1, true), (20, true), (2, true), (9, false)], [66, 254, 258, 91]⟩
  , ⟨[(54, true), (18, false), (2, true), (68, false), (58, false), (9, false), (20, true), (27, true), (57, true), (1, true), (8, false)], [260, 13, 257, 147, 259, 102, 54, 72]⟩
  , ⟨[(17, true), (2, true), (1, false)], [112, 223]⟩
  , ⟨[(16, false), (1, false), (3, false)], [235, 223]⟩
  , ⟨[(17, true), (16, true), (1, false)], [237, 262]⟩
  , ⟨[(37, false), (8, true), (1, true), (26, true)], [252, 121]⟩
  , ⟨[(6, false), (1, false), (17, false), (16, true)], [6, 247]⟩
  , ⟨[(68, true), (47, true), (1, false), (16, false)], [84, 223]⟩
  , ⟨[(68, false), (63, true), (1, false), (16, false)], [105, 223]⟩
  , ⟨[(37, true), (1, true), (8, true), (43, false)], [142, 69]⟩
  , ⟨[(68, false), (14, false), (16, false), (1, false)], [160, 223]⟩
  , ⟨[(68, false), (18, true), (1, false), (16, false)], [192, 223]⟩
  , ⟨[(68, false), (2, false), (1, false), (16, false)], [232, 270]⟩
  , ⟨[(29, false), (17, false), (16, true), (1, false)], [241, 266]⟩
  , ⟨[(29, true), (10, true), (1, false), (2, false), (16, true)], [38, 247]⟩
  , ⟨[(60, false), (57, false), (1, true), (8, false), (41, false)], [42, 8]⟩
  , ⟨[(8, true), (1, true), (31, false), (37, false), (69, false)], [78, 265]⟩
  , ⟨[(37, false), (69, true), (1, true), (8, true), (54, false)], [103, 121]⟩
  , ⟨[(41, false), (57, false), (1, true), (8, false), (56, true)], [108, 275]⟩
  , ⟨[(37, false), (69, false), (1, true), (26, true), (8, true)], [118, 121]⟩
  , ⟨[(22, false), (58, true), (1, false), (16, false), (68, true)], [161, 223]⟩
  , ⟨[(68, true), (9, false), (16, false), (3, false), (1, false)], [172, 223]⟩
  , ⟨[(54, true), (29, true), (2, false), (16, true), (1, false)], [195, 247]⟩
  , ⟨[(52, true), (20, true), (16, true), (1, false), (17, false)], [197, 247]⟩
  , ⟨[(29, true), (1, false), (16, true), (2, false), (17, true)], [200, 282]⟩
  , ⟨[(54, true), (2, false), (16, true), (1, false), (17, true)], [206, 282]⟩
  , ⟨[(71, true), (69, true), (1, true), (8, true), (37, false), (54, true)], [41, 121]⟩
  , ⟨[(42, false), (20, true), (1, false), (16, true), (29, false), (17, false)], [115, 266]⟩
  , ⟨[(46, false), (57, false), (1, true), (8, false), (41, true), (58, false)], [119, 59]⟩
  , ⟨[(32, true), (44, true), (1, true), (8, false), (54, false), (57, true)], [124, 45]⟩
  , ⟨[(31, false), (10, true), (1, false), (2, false), (16, true), (17, true)], [150, 274]⟩
  , ⟨[(58, false), (47, false), (1, false), (2, false), (16, false), (68, true)], [52, 249]⟩
  , ⟨[(19, false), (1, true), (8, true), (37, true), (43, true), (64, false)], [55, 128]⟩
  , ⟨[(8, true), (1, true), (21, false), (37, true), (43, true), (64, true)], [29, 251]⟩
  , ⟨[(8, false), (4, false), (17, false), (6, false), (1, false), (16, true)], [165, 242]⟩
  , ⟨[(54, true), (1, true), (31, false), (8, true), (37, false), (69, true)], [65, 286]⟩
  , ⟨[(34, true), (32, false), (1, true), (9, false), (8, false), (57, true)], [66, 183]⟩
  , ⟨[(22, true), (18, true), (16, false), (47, false), (58, true), (1, false)], [194, 223]⟩
  , ⟨[(57, false), (1, true), (8, false), (41, true), (58, false), (73, true)], [74, 288]⟩
  , ⟨[(8, false), (54, true), (1, false), (29, true), (16, true), (2, false)], [204, 196]⟩
  , ⟨[(52, true), (1, false), (16, true), (17, false), (29, false), (6, true)], [81, 283]⟩
  , ⟨[(8, false), (1, true), (41, true), (47, false), (57, false), (58, true)], [89, 174]⟩
  , ⟨[(31, true), (10, true), (1, false), (2, false), (16, true), (17, true)], [90, 274]⟩
  , ⟨[(24, true), (22, false), (1, false), (16, false), (47, false), (58, true), (68, true)], [31, 223]⟩
  , ⟨[(21, false), (1, true), (18, false), (8, true), (37, true), (43, true), (64, false)], [73, 292]⟩
  , ⟨[(39, false), (35, false), (1, false), (16, true), (17, false), (29, true), (43, true)], [101, 242]⟩
  , ⟨[(8, false), (1, true), (2, true), (16, false), (32, false), (34, true), (57, true)], [62, 296]⟩
  , ⟨[(7, false), (6, false), (2, false), (68, false), (16, false), (14, true), (1, false)], [170, 271]⟩
  , ⟨[(7, false), (35, true), (6, false), (68, false), (16, false), (14, true), (1, false)], [171, 223]⟩
  , ⟨[(8, false), (9, true), (1, true), (2, true), (32, false), (34, true), (57, true)], [79, 306]⟩
  , ⟨[(8, true), (1, true), (19, true), (21, false), (37, true), (43, true), (64, false)], [122, 304]⟩
  , ⟨[(44, true), (32, true), (1, true), (18, false), (8, false), (54, true), (57, true)], [86, 13]⟩
  , ⟨[(25, true), (1, true), (8, false), (32, false), (34, false), (57, true), (58, false)], [129, 91]⟩
  , ⟨[(56, false), (1, true), (8, false), (13, true), (32, true), (44, false), (57, true)], [27, 11]⟩
  , ⟨[(27, false), (1, false), (16, true), (20, true), (17, false), (29, false), (6, true)], [10, 287]⟩
  , ⟨[(57, false), (1, true), (8, false), (4, false), (47, true), (41, true), (58, true)], [21, 53]⟩
  , ⟨[(68, true), (22, true), (1, false), (16, false), (58, true), (3, false), (2, false)], [193, 267]⟩
  , ⟨[(62, false), (35, true), (1, false), (16, true), (17, false), (29, true), (43, true), (39, false)], [125, 242]⟩
  , ⟨[(30, false), (31, true), (1, true), (8, false), (25, false), (32, false), (34, false), (57, true)], [82, 25]⟩
  , ⟨[(58, true), (46, true), (1, false), (16, false), (3, false), (12, true), (47, false), (26, true)], [46, 263]⟩
  , ⟨[(26, false), (57, true), (1, false), (16, true), (17, false), (20, false), (29, false), (6, true)], [137, 300]⟩
  , ⟨[(13, false), (1, true), (8, false), (7, false), (44, false), (29, true), (32, true), (57, true)], [87, 147]⟩
  , ⟨[(12, true), (13, false), (1, false), (3, false), (16, false), (26, false), (46, true), (58, true)], [146, 263]⟩
  , ⟨[(32, true), (27, false), (1, true), (13, true), (8, false), (44, false), (56, true), (57, true)], [148, 123]⟩
  , ⟨[(48, false), (1, false), (2, false), (16, false), (58, true), (22, false), (47, false), (68, true)], [32, 303]⟩
  , ⟨[(24, false), (1, false), (2, false), (16, false), (58, true), (22, false), (47, false), (68, true)], [48, 324]⟩
  , ⟨[(12, false), (20, false), (1, false), (16, true), (17, false), (26, true), (6, true), (29, false)], [93, 300]⟩
  , ⟨[(42, true), (1, false), (16, true), (20, true), (17, false), (29, false), (6, true), (52, false)], [33, 314]⟩
  , ⟨[(34, false), (30, false), (1, true), (8, false), (20, false), (25, false), (32, false), (57, true)], [96, 318]⟩
  , ⟨[(30, true), (5, false), (1, true), (8, false), (34, false), (25, false), (32, false), (57, true)], [4, 145]⟩
  , ⟨[(42, true), (1, false), (16, true), (20, true), (17, false), (6, true), (29, false), (52, true)], [104, 314]⟩
  , ⟨[(25, true), (1, true), (39, false), (8, false), (32, false), (57, true), (58, true), (34, false)], [107, 186]⟩
  , ⟨[(20, false), (1, false), (16, true), (17, false), (6, true), (26, true), (29, false), (52, false)], [26, 326]⟩
  , ⟨[(26, false), (1, false), (16, true), (17, false), (20, false), (29, false), (6, true), (52, false)], [109, 320]⟩
  , ⟨[(30, true), (5, true), (1, true), (8, false), (25, false), (32, false), (34, false), (57, true)], [111, 145]⟩
  , ⟨[(40, true), (1, true), (8, false), (7, true), (32, true), (13, false), (44, false), (57, true)], [54, 72]⟩
  , ⟨[(13, true), (1, true), (8, false), (32, true), (44, false), (56, true), (57, true), (27, true)], [37, 123]⟩
  , ⟨[(9, true), (22, true), (1, false), (2, false), (16, false), (68, true), (47, false), (58, true)], [76, 249]⟩
  , ⟨[(13, false), (1, true), (8, false), (7, false), (29, false), (32, true), (44, false), (57, true)], [15, 147]⟩
  , ⟨[(35, true), (1, false), (14, false), (16, true), (17, false), (29, true), (43, true), (39, false)], [58, 317]⟩
  , ⟨[(47, true), (26, true), (1, false), (16, false), (12, true), (46, true), (3, false), (58, true)], [19, 263]⟩
  , ⟨[(70, true), (1, true), (8, false), (25, true), (32, false), (57, true), (58, true), (34, false)], [80, 331]⟩
  , ⟨[(9, false), (28, false), (1, false), (2, false), (68, true), (16, false), (22, true), (58, true)], [23, 267]⟩
  , ⟨[(40, false), (1, true), (8, false), (7, true), (32, true), (44, false), (57, true), (13, false)], [127, 102]⟩
  , ⟨[(32, true), (44, true), (1, true), (16, false), (8, false), (18, true), (54, true), (57, true)], [5, 40]⟩
  , ⟨[(67, true), (55, false), (1, false), (16, false), (14, true), (18, false), (63, false), (6, true), (68, false)], [152, 223]⟩
  , ⟨[(46, false), (1, false), (2, false), (14, true), (16, false), (18, false), (6, false), (63, false), (68, false)], [64, 307]⟩
  , ⟨[(55, true), (24, false), (1, false), (16, false), (14, true), (18, false), (6, true), (63, false), (68, false)], [110, 223]⟩
  , ⟨[(4, true), (1, true), (8, false), (18, false), (7, true), (41, true), (47, true), (57, false), (58, true)], [92, 53]⟩
  , ⟨[(61, true), (67, false), (1, false), (52, true), (16, false), (18, true), (14, true), (63, false), (68, false)], [113, 223]⟩
  , ⟨[(50, true), (1, false), (2, false), (9, false), (16, false), (47, false), (22, true), (58, true), (68, true)], [30, 342]⟩
  , ⟨[(32, true), (5, false), (1, true), (8, false), (16, true), (18, true), (44, true), (54, true), (57, true)], [116, 40]⟩
  , ⟨[(50, false), (9, false), (1, false), (2, false), (16, false), (47, false), (22, true), (58, true), (68, true)], [140, 342]⟩
  , ⟨[(4, true), (1, true), (8, false), (18, false), (34, false), (41, true), (47, true), (57, false), (58, true)], [120, 348]⟩
  , ⟨[(4, true), (1, true), (8, false), (18, true), (41, true), (43, false), (47, true), (57, false), (58, true)], [98, 53]⟩
  , ⟨[(4, true), (1, true), (8, false), (18, true), (41, true), (43, true), (47, true), (57, false), (58, true)], [16, 53]⟩
  , ⟨[(7, true), (1, false), (2, false), (14, true), (16, false), (18, false), (6, false), (63, false), (68, false)], [20, 346]⟩
  , ⟨[(19, false), (2, true), (1, false), (12, true), (16, false), (3, false), (26, false), (46, true), (58, true)], [1, 322]⟩
  , ⟨[(26, false), (2, true), (1, false), (12, true), (16, false), (3, false), (13, true), (46, true), (58, true)], [61, 357]⟩
  , ⟨[(67, false), (55, false), (1, false), (16, false), (14, true), (18, false), (63, false), (6, true), (68, false)], [106, 223]⟩
  , ⟨[(8, false), (5, true), (1, true), (12, true), (16, true), (18, true), (32, true), (44, true), (54, true), (57, true)], [88, 40]⟩
  , ⟨[(67, false), (1, false), (2, false), (14, true), (16, false), (18, true), (52, true), (63, false), (23, false), (68, false)], [51, 349]⟩
  , ⟨[(66, true), (24, true), (1, false), (16, false), (14, true), (18, false), (6, true), (63, false), (55, true), (68, false)], [132, 223]⟩
  , ⟨[(32, true), (5, true), (1, true), (8, false), (12, false), (16, true), (18, true), (44, true), (54, true), (57, true)], [9, 40]⟩
  , ⟨[(61, false), (1, false), (2, false), (14, true), (16, false), (35, false), (52, true), (18, true), (63, false), (67, false), (68, false)], [153, 361]⟩
  , ⟨[(61, false), (1, false), (2, false), (14, true), (16, false), (35, true), (18, true), (52, true), (63, false), (67, false), (68, false)], [34, 361]⟩
  , ⟨[(24, true), (1, false), (2, false), (16, false), (14, true), (18, false), (6, true), (63, false), (55, true), (68, false), (73, true)], [143, 362]⟩
  , ⟨[(28, false), (1, false), (2, false), (16, false), (14, true), (18, false), (24, true), (6, true), (63, false), (55, true), (68, false), (73, false)], [57, 362]⟩
  , ⟨[(55, true), (66, false), (1, false), (2, false), (16, false), (14, true), (18, false), (6, true), (28, true), (50, true), (63, false), (68, false), (73, false)], [139, 347]⟩
  , ⟨[(55, true), (50, false), (1, false), (2, false), (16, false), (14, true), (18, false), (6, true), (28, true), (63, false), (66, false), (68, false), (73, false)], [83, 347]⟩
  , ⟨[(1, false), (16, true)], [264, 249, 263, 273, 247]⟩
  , ⟨[(1, true), (8, false), (57, false), (41, false)], [275, 8, 278]⟩
  , ⟨[(1, true), (8, false), (57, true), (29, false), (32, true), (44, false), (7, false)], [338, 313, 323, 336]⟩
  , ⟨[(1, true), (8, false), (57, true), (29, true), (32, true), (44, false), (7, false)], [321, 313, 323, 336]⟩
  , ⟨[(1, true), (8, false), (57, true), (32, false), (34, false), (25, false), (30, false)], [318, 25, 328]⟩
  , ⟨[(1, true), (8, false), (57, true), (32, false), (34, false), (25, false)], [374, 329, 334, 145]⟩
  , ⟨[(1, true), (8, false), (57, true), (32, true), (44, false), (7, false)], [372, 373, 147]⟩
  , ⟨[(1, true), (8, false), (57, true), (32, true), (44, false), (13, false), (7, true)], [343, 376, 335, 313, 323, 336]⟩
  , ⟨[(1, true), (8, false), (57, true), (54, true), (32, true), (18, true), (44, true)], [40, 344, 351, 360, 363]⟩
  , ⟨[(1, true), (8, false), (57, true), (58, false), (32, false), (34, false)], [312, 375, 183, 296, 309]⟩
  , ⟨[(1, true), (8, false), (57, true), (58, false), (32, false)], [379, 183, 296, 309]⟩
  , ⟨[(1, true), (8, false), (58, false), (57, false)], [371, 298, 59, 288]⟩
  , ⟨[(1, true), (8, false), (58, true), (57, false)], [371, 301, 315, 53, 353, 354, 355, 174]⟩
  , ⟨[(1, true), (8, false), (58, true), (32, false), (34, false)], [382, 375, 186, 341, 331]⟩
  , ⟨[(1, true), (8, false), (57, true), (32, true), (44, false)], [376, 377, 313, 323, 336, 123]⟩
  , ⟨[(1, true), (8, true), (37, false)], [121, 276, 295, 277, 279]⟩
  , ⟨[(1, true), (8, true)], [385, 269, 128, 293, 310, 292, 251]⟩
  , ⟨[(1, true), (2, true), (57, true), (32, false)], [386, 380, 383, 309, 296, 306]⟩
  , ⟨[(1, true), (2, true), (57, true)], [387, 386, 384, 289, 311, 378]⟩
  , ⟨[(1, true), (2, true)], [388, 386, 381, 382]⟩
  , ⟨[(1, true), (57, false)], [386, 381, 382, 371]⟩
  , ⟨[(1, true), (32, false)], [386, 389, 390, 380, 183, 383, 296]⟩
  , ⟨[(1, true), (8, false), (57, true), (32, true)], [384, 386, 390, 391, 289, 311, 378]⟩
  , ⟨[(1, true), (8, false), (57, true)], [392, 391, 249, 370, 263]⟩
  , ⟨[(1, true), (8, false)], [393, 390, 249, 370, 263]⟩
  , ⟨[(57, false)], [390, 249, 370, 263]⟩
  , ⟨[(32, false)], [395, 391, 249, 370, 263]⟩
  , ⟨[(16, true)], [395, 396, 370, 386, 389, 394]⟩
  , ⟨[(2, true)], [395, 396, 397, 389, 262, 223]⟩
  , ⟨[(17, true), (2, true)], [262, 389]⟩
  , ⟨[(1, false), (2, true)], [223, 370]⟩
  , ⟨[(1, false), (16, false)], [263, 249]⟩
  , ⟨[(68, false), (1, false), (2, false)], [272, 370]⟩
  , ⟨[(68, false), (14, false), (1, false)], [270, 370]⟩
  , ⟨[(68, false), (18, true), (1, false)], [271, 370]⟩
  , ⟨[(68, true), (47, true), (1, false)], [267, 370]⟩
  , ⟨[(68, false), (63, true), (1, false)], [268, 370]⟩
  , ⟨[(22, false), (58, true), (1, false), (68, true)], [280, 370]⟩
  , ⟨[(58, false), (47, false), (1, false), (2, false), (68, true)], [291, 370]⟩
  , ⟨[(17, false), (6, false), (8, false), (4, false), (16, true)], [294, 394]⟩
  , ⟨[(22, true), (18, true), (47, false), (58, true), (1, false)], [297, 370]⟩
  , ⟨[(8, false), (54, true), (29, true), (16, true), (2, false)], [299, 394]⟩
  , ⟨[(52, true), (20, true), (16, true), (2, false), (8, false)], [205, 394]⟩
  , ⟨[(54, true), (8, false), (20, true), (16, true), (2, false)], [208, 394]⟩
  , ⟨[(26, true), (18, false), (31, false), (20, true), (43, true), (1, true)], [253, 394]⟩
  , ⟨[(6, false), (35, true), (7, false), (68, false), (16, false), (1, false)], [308, 403]⟩
  , ⟨[(25, true), (58, true), (57, true), (32, false), (8, false), (1, true)], [187, 389]⟩
  , ⟨[(58, true), (1, false), (16, false), (68, true), (3, false), (2, false)], [316, 407]⟩
  , ⟨[(14, true), (29, true), (2, false), (8, false), (54, true), (16, true)], [196, 394]⟩
  , ⟨[(24, true), (22, false), (1, false), (47, false), (58, true), (68, true)], [303, 370]⟩
  , ⟨[(9, true), (22, true), (1, false), (2, false), (68, true), (47, false), (58, true)], [337, 370]⟩
  , ⟨[(22, false), (1, false), (16, false), (2, false), (58, true), (47, false), (68, true)], [325, 419]⟩
  , ⟨[(14, true), (10, false), (6, false), (4, false), (16, true), (2, false), (8, false)], [168, 394]⟩
  , ⟨[(52, true), (44, true), (8, false), (18, true), (1, true), (57, true), (16, false)], [180, 391]⟩
  , ⟨[(48, false), (22, false), (1, false), (2, false), (58, true), (47, false), (68, true)], [324, 370]⟩
  , ⟨[(9, false), (28, false), (1, false), (2, false), (68, true), (22, true), (58, true)], [342, 370]⟩
  , ⟨[(20, false), (30, false), (32, false), (57, true), (25, false), (8, false), (1, true)], [184, 389]⟩
  , ⟨[(25, true), (7, false), (44, false), (29, false), (68, false), (57, true), (8, false), (1, true)], [189, 391]⟩
  , ⟨[(67, false), (55, false), (1, false), (14, true), (18, false), (63, false), (6, true), (68, false)], [359, 370]⟩
  , ⟨[(50, false), (1, false), (2, false), (16, false), (47, false), (22, true), (58, true), (68, true)], [352, 420]⟩
  , ⟨[(14, false), (10, false), (2, false), (4, false), (6, false), (8, false), (9, false), (3, false)], [166, 394]⟩
  , ⟨[(9, false), (1, false), (2, false), (16, false), (47, false), (22, true), (58, true), (68, true)], [350, 429]⟩
  , ⟨[(67, true), (55, false), (1, false), (14, true), (18, false), (63, false), (6, true), (68, false)], [345, 370]⟩
  , ⟨[(24, false), (48, false), (2, false), (16, false), (22, false), (47, false), (1, false), (3, false)], [158, 402]⟩
  , ⟨[(55, true), (24, false), (1, false), (14, true), (18, false), (6, true), (63, false), (68, false)], [347, 370]⟩
  , ⟨[(6, false), (4, false), (2, false), (10, false), (9, false), (1, false), (7, false), (8, false)], [173, 249]⟩
  , ⟨[(18, false), (58, false), (54, true), (13, true), (68, false), (57, true), (8, false), (1, true)], [257, 391]⟩
  , ⟨[(66, true), (24, true), (1, false), (14, true), (18, false), (6, true), (63, false), (55, true), (68, false)], [362, 370]⟩
  , ⟨[(71, false), (58, false), (18, false), (54, true), (7, true), (68, false), (57, true), (8, false), (1, true)], [259, 391]⟩
  , ⟨[(7, false), (18, true), (8, false), (56, true), (54, true), (29, true), (68, false), (57, true), (32, true), (16, false)], [177, 404]⟩
  , ⟨[(18, true), (52, true), (8, false), (7, false), (56, true), (29, true), (68, false), (57, true), (16, false), (32, true)], [178, 404]⟩
  , ⟨[(18, true), (7, false), (2, false), (16, false), (58, true), (68, false), (8, false), (25, true), (52, true), (57, true)], [190, 404]⟩
  , ⟨[(1, false)], [397, 401]⟩
  , ⟨[(8, false)], [442, 394]⟩
  , ⟨[], [397, 442, 443, 386]⟩
  ]

set_option maxHeartbeats 40000000 in
/-- KERNEL replay of the refutation — plain `decide`, no `native_decide`. -/
theorem check_ok : RupCheckerFast.checkRefutationFast F steps = true := by decide

/-- The recovered CNF is unsatisfiable (kernel-checked LRAT replay +
`rup_sound` composition). -/
theorem instance_unsat : ¬ ∃ σ, satFormula σ F :=
  RupCheckerFast.checkRefutationFast_sound F steps check_ok

/-- The gadget's variable set: DIMACS variables `1..73`. -/
def s : Finset ℕ := Finset.Icc 1 73

set_option maxHeartbeats 4000000 in
/-- END-TO-END VERDICT: no point of the `[0,1]` box reaches the sat_relu
gadget's unsafe region `{Y₀ ≥ 1 ∧ Y₁ ≤ 0}` — real-arithmetic SAFE. -/
theorem instance_safe :
    ∀ x : ℕ → ℝ, (∀ j ∈ s, 0 ≤ x j ∧ x j ≤ 1) →
      ¬ (1 ≤ SatRelu.Y0 (SatReluVerdict.clausesOf F) x ∧
         SatRelu.Y1 s x ≤ 0) :=
  SatReluVerdict.safe_of_unsat F s (by decide) instance_unsat

end SatReluSweep_v73c156

end Crownproof

/-! ## Trust-base check -/

#print axioms Crownproof.SatReluSweep_v73c156.check_ok
#print axioms Crownproof.SatReluSweep_v73c156.instance_unsat
#print axioms Crownproof.SatReluSweep_v73c156.instance_safe
