/-
MACHINE-GENERATED by `ny-cert`'s `lrat_to_lean` — do not edit.

sat_relu Route A instance transcript:
* DIMACS source : inst.cnf  (p cnf 82 130)
* LRAT source   : inst.lrat  (124 addition steps kept)

The kernel replays the full LRAT refutation with PLAIN `decide`
(no `native_decide`, no extra axioms) through
`RupCheckerFast.checkRefutationFast`, then composes
`checkRefutationFast_sound` (CNF-unsat) with
`SatReluVerdict.safe_of_unsat` (gadget real-arithmetic safety).
-/
import NyProof.SatReluVerdict
import NyProof.RupCheckerFast

namespace Crownproof

namespace SatReluSweep_v82c130

open RupImport.RUP RupChecker

set_option maxRecDepth 65536

/-- The recovered DIMACS formula, literal-for-literal. -/
def F : Formula :=
  [ [(1, true), (13, true), (18, true), (23, true), (30, true), (50, false), (60, false), (67, true)]
  , [(1, false), (8, true), (18, true), (21, true), (26, true), (50, false), (80, true)]
  , [(1, false), (8, true), (37, false), (50, true), (56, false), (57, false)]
  , [(1, true), (38, true), (52, true), (54, false), (60, true)]
  , [(1, false), (8, true), (37, false), (50, true), (56, true)]
  , [(1, true), (13, true), (18, true), (32, true), (50, true), (60, false), (64, false), (70, true)]
  , [(1, true), (21, false), (33, true), (38, false), (43, true), (57, true), (60, true)]
  , [(1, true), (6, true), (18, false), (33, true), (60, false), (62, true), (68, false), (69, true), (77, true)]
  , [(1, true), (6, true), (18, false), (33, true), (38, false), (51, false), (60, false), (68, true), (69, true), (79, true)]
  , [(1, false), (8, false), (18, true), (26, true), (70, false), (71, false), (81, true)]
  , [(1, true), (6, false), (16, false), (18, false), (23, false), (25, true), (44, false), (59, false), (60, false), (78, false)]
  , [(1, true), (21, true), (38, false), (60, true)]
  , [(1, false), (8, false), (18, false), (20, true), (41, false), (58, true), (61, true)]
  , [(1, false), (7, true), (8, true), (9, false), (16, true), (36, true), (37, true), (50, true)]
  , [(1, false), (8, true), (28, true), (40, false), (50, false), (75, false), (80, false)]
  , [(1, true), (13, false), (18, true), (22, false), (32, true), (44, true), (51, false), (60, false)]
  , [(1, false), (8, true), (10, false), (34, true), (36, false), (37, true), (50, true)]
  , [(1, true), (38, true), (43, true), (52, false), (60, true), (80, true)]
  , [(1, true), (5, false), (6, true), (18, false), (33, true), (47, true), (60, false), (68, true), (69, true), (79, false)]
  , [(1, false), (8, false), (18, false), (20, true), (41, true), (58, true), (61, true)]
  , [(1, false), (8, true), (28, false), (37, true), (40, false), (50, false), (79, false), (80, false)]
  , [(1, false), (8, true), (28, false), (40, false), (50, false), (74, true), (79, true), (80, false)]
  , [(1, false), (8, false), (18, true), (25, false), (42, true), (44, false), (71, true)]
  , [(1, true), (6, true), (18, false), (33, false), (37, false), (59, false), (60, false), (66, true), (69, true), (82, false)]
  , [(1, true), (13, true), (18, true), (32, false), (34, true), (50, true), (60, false), (75, true)]
  , [(1, true), (6, true), (18, false), (33, true), (60, false), (62, false), (68, false), (69, true), (77, true)]
  , [(1, true), (6, true), (18, false), (33, false), (59, true), (60, false), (66, true), (69, true), (73, true)]
  , [(1, true), (6, true), (18, false), (33, false), (60, false), (63, true), (66, false), (69, true)]
  , [(1, true), (6, false), (16, false), (18, false), (23, true), (44, false), (59, false), (60, false), (78, false)]
  , [(1, false), (8, true), (30, true), (37, false), (50, true), (56, false), (57, true)]
  , [(1, false), (7, true), (8, true), (9, false), (16, false), (36, true), (37, true), (50, true)]
  , [(1, false), (8, false), (18, true), (34, true), (61, true), (70, true), (71, false)]
  , [(1, true), (13, true), (18, true), (32, true), (50, true), (60, false), (64, true), (70, true), (77, true)]
  , [(1, false), (8, true), (18, true), (40, true), (50, false), (63, true), (78, true), (80, false)]
  , [(1, true), (6, true), (18, false), (33, true), (47, false), (60, false), (68, true), (69, true), (72, true), (79, false)]
  , [(1, false), (7, false), (8, true), (36, true), (37, true), (40, false), (50, true)]
  , [(1, true), (6, true), (18, false), (33, false), (60, false), (63, false), (66, false), (69, true)]
  , [(1, true), (6, true), (18, false), (60, false), (69, false)]
  , [(1, true), (6, true), (18, false), (33, true), (38, true), (60, false), (68, true), (69, true), (77, false), (79, true)]
  , [(1, false), (8, false), (18, false), (23, true), (53, false), (61, false), (65, true)]
  , [(1, false), (8, false), (18, false), (20, false), (34, false), (58, true), (61, true)]
  , [(1, true), (13, false), (18, true), (22, true), (32, true), (51, false), (60, false)]
  , [(1, true), (6, true), (18, false), (33, true), (47, false), (60, false), (68, true), (69, true), (72, false), (79, false)]
  , [(1, false), (8, true), (21, false), (26, true), (50, false), (80, true)]
  , [(1, true), (6, true), (18, false), (33, true), (60, false), (68, false), (69, true), (77, false)]
  , [(1, false), (8, false), (18, false), (58, false), (61, true), (80, false)]
  , [(1, true), (13, true), (18, true), (30, true), (45, true), (50, false), (60, false), (67, false)]
  , [(1, false), (8, true), (40, true), (50, false), (78, false), (80, false)]
  , [(1, false), (7, false), (8, true), (21, true), (36, true), (37, true), (40, true), (50, true), (53, true), (62, false)]
  , [(1, true), (38, true), (44, true), (52, false), (60, true), (80, false)]
  , [(1, false), (8, true), (28, false), (37, false), (40, false), (50, false), (79, false), (80, false)]
  , [(1, false), (7, true), (8, true), (9, true), (36, true), (37, true), (50, true)]
  , [(1, true), (6, true), (18, false), (33, true), (38, false), (51, true), (60, false), (68, true), (69, true), (79, true)]
  , [(1, false), (8, true), (18, false), (40, true), (50, false), (63, true), (78, true), (80, false)]
  , [(1, false), (8, true), (10, true), (36, false), (37, true), (47, true), (50, true), (77, true)]
  , [(1, false), (7, false), (8, true), (21, false), (29, true), (36, true), (37, true), (40, true), (50, true), (62, false), (65, true)]
  , [(1, false), (8, true), (30, false), (33, false), (37, false), (50, true), (56, false), (57, true)]
  , [(1, true), (13, false), (18, true), (37, true), (51, true), (60, false), (77, true)]
  , [(1, true), (13, true), (18, true), (30, false), (48, true), (50, false), (60, false)]
  , [(1, false), (8, false), (18, false), (20, false), (34, true), (58, true), (61, true)]
  , [(1, false), (8, false), (18, false), (58, false), (61, true), (80, true)]
  , [(1, true), (13, false), (18, true), (22, false), (29, true), (32, true), (44, false), (51, false), (60, false)]
  , [(1, false), (6, true), (8, true), (28, true), (40, false), (50, false), (75, true), (80, false)]
  , [(1, true), (13, true), (18, true), (30, true), (32, true), (50, true), (60, false), (67, false), (70, false)]
  , [(1, false), (8, true), (30, false), (33, true), (37, false), (50, true), (56, false), (57, true)]
  , [(1, false), (7, false), (8, true), (21, false), (33, false), (36, true), (37, true), (40, true), (50, true), (62, false), (65, false)]
  , [(1, false), (6, false), (8, true), (28, true), (29, true), (30, true), (40, false), (50, false), (75, true), (80, false)]
  , [(1, false), (8, false), (18, true), (42, false), (56, false), (71, true)]
  , [(1, true), (21, false), (38, false), (43, false), (60, true)]
  , [(1, true), (13, true), (18, true), (23, false), (27, false), (30, true), (32, false), (50, false), (60, false), (67, true)]
  , [(1, true), (13, true), (18, true), (23, false), (27, false), (30, true), (32, true), (50, false), (60, false), (67, true)]
  , [(1, true), (6, true), (18, false), (33, false), (59, false), (60, false), (66, true), (69, true), (82, true)]
  , [(1, true), (13, true), (18, true), (30, false), (48, false), (50, false), (60, false)]
  , [(1, true), (13, true), (18, true), (32, true), (50, true), (60, false), (64, true), (70, true), (77, false)]
  , [(1, false), (7, false), (8, true), (21, false), (33, true), (36, true), (37, true), (40, true), (50, true), (62, false), (65, false)]
  , [(1, true), (6, false), (18, false), (59, false), (60, false), (78, true)]
  , [(1, false), (8, false), (18, true), (42, false), (56, true), (71, true)]
  , [(1, true), (38, true), (43, false), (52, false), (60, true), (80, true)]
  , [(1, false), (6, false), (8, true), (28, true), (30, false), (40, false), (50, false), (75, true), (80, false)]
  , [(1, true), (21, false), (33, false), (38, false), (43, true), (60, true)]
  , [(1, false), (8, false), (18, true), (25, true), (42, true), (71, true)]
  , [(1, false), (8, true), (10, false), (34, false), (36, false), (37, true), (50, true)]
  , [(1, true), (13, true), (18, true), (23, false), (27, true), (30, true), (50, false), (60, false), (67, true)]
  , [(1, true), (6, false), (18, false), (59, true), (60, false)]
  , [(1, false), (8, false), (18, false), (41, false), (61, false), (65, false), (80, false), (82, false)]
  , [(1, false), (8, false), (18, true), (70, false), (71, false), (81, false)]
  , [(1, true), (13, true), (18, true), (30, false), (32, true), (50, true), (60, false), (67, false), (70, false)]
  , [(1, true), (6, false), (16, false), (18, false), (44, true), (59, false), (60, false), (78, false)]
  , [(1, false), (8, false), (18, true), (25, false), (42, true), (44, true), (71, true)]
  , [(1, false), (8, false), (18, false), (41, false), (61, false), (65, false), (80, true), (82, true)]
  , [(1, true), (13, true), (18, true), (30, true), (45, false), (50, false), (60, false), (67, false)]
  , [(1, false), (8, false), (18, true), (34, true), (61, false), (70, true), (71, false)]
  , [(1, true), (13, false), (18, true), (23, true), (32, false), (51, false), (60, false)]
  , [(1, true), (13, false), (18, true), (22, false), (29, false), (32, true), (44, false), (51, false), (60, false)]
  , [(1, true), (13, true), (18, true), (32, false), (34, false), (50, true), (60, false), (75, true)]
  , [(1, true), (13, false), (18, true), (37, true), (51, true), (60, false), (71, true), (77, false)]
  , [(1, true), (13, false), (18, true), (23, false), (32, false), (51, false), (60, false)]
  , [(1, false), (8, true), (28, false), (40, false), (50, false), (74, false), (79, true), (80, false)]
  , [(1, true), (13, true), (18, true), (32, false), (50, true), (60, false), (75, false)]
  , [(1, true), (6, false), (16, true), (18, false), (47, false), (59, false), (60, false), (78, false)]
  , [(1, true), (8, true), (13, false), (18, true), (37, false), (51, true), (60, false)]
  , [(1, false), (6, false), (8, true), (28, true), (29, false), (30, true), (40, false), (50, false), (75, true), (80, false)]
  , [(1, true), (5, true), (6, true), (18, false), (33, true), (47, true), (60, false), (68, true), (69, true), (79, false)]
  , [(1, false), (8, false), (18, true), (26, false), (70, false), (71, false), (81, true)]
  , [(1, true), (6, false), (16, true), (18, false), (47, true), (59, false), (60, false), (78, false)]
  , [(1, false), (8, false), (18, false), (22, true), (41, false), (61, false), (65, false), (80, true), (82, false)]
  , [(1, false), (8, true), (40, true), (50, false), (63, false), (78, true), (80, false)]
  , [(1, false), (8, false), (18, false), (41, false), (61, false), (65, false), (80, false), (82, true)]
  , [(1, false), (7, false), (8, true), (21, true), (36, true), (37, true), (40, true), (50, true), (53, false), (62, false)]
  , [(1, true), (8, false), (13, false), (18, true), (37, false), (51, true), (60, false)]
  , [(1, false), (7, false), (8, true), (36, true), (37, true), (40, true), (50, true), (62, true)]
  , [(1, false), (8, true), (26, false), (50, false), (80, true)]
  , [(1, false), (8, false), (18, false), (23, true), (53, true), (61, false), (65, true)]
  , [(1, true), (13, true), (18, true), (32, true), (50, true), (60, false), (67, true), (70, false)]
  , [(1, true), (6, true), (18, false), (33, false), (37, true), (59, false), (60, false), (66, true), (69, true), (82, false)]
  , [(1, true), (21, false), (33, true), (38, false), (43, true), (57, false), (60, true)]
  , [(1, true), (38, true), (52, true), (54, true), (60, true)]
  , [(1, true), (38, true), (44, false), (52, false), (60, true), (80, false)]
  , [(1, true), (13, false), (18, true), (37, true), (51, true), (60, false), (71, false), (77, false)]
  , [(1, true), (6, false), (16, false), (18, false), (23, false), (25, false), (44, false), (59, false), (60, false), (78, false)]
  , [(1, false), (8, true), (10, true), (36, false), (37, true), (50, true), (77, false)]
  , [(1, false), (8, true), (10, true), (36, false), (37, true), (47, false), (50, true), (77, true)]
  , [(1, true), (6, true), (18, false), (33, false), (59, true), (60, false), (66, true), (69, true), (73, false)]
  , [(1, false), (8, false), (18, true), (34, false), (70, true), (71, false)]
  , [(1, false), (8, false), (18, false), (22, false), (41, false), (61, false), (65, false), (80, true), (82, false)]
  , [(1, false), (8, true), (18, false), (21, true), (26, true), (50, false), (80, true)]
  , [(1, true), (6, true), (18, false), (33, true), (38, true), (60, false), (68, true), (69, true), (77, true), (79, true)]
  , [(1, false), (8, false), (18, false), (23, false), (61, false), (65, true)]
  , [(1, false), (7, false), (8, true), (21, false), (29, false), (36, true), (37, true), (40, true), (50, true), (62, false), (65, true)]
  , [(1, false), (8, false), (18, false), (41, true), (61, false), (65, false)]
  ]

/-- The LRAT refutation: derived clause + database-index hints per step. -/
def steps : List RStep :=
  [ ⟨[(80, false), (61, false), (8, false), (18, false), (41, false), (1, false), (65, false)], [84, 107]⟩
  , ⟨[(61, false), (41, false), (8, false), (18, false), (22, false), (1, false), (23, false)], [127, 130, 89, 124]⟩
  , ⟨[(61, true), (34, false), (8, false), (18, false), (20, false), (1, false)], [40, 45, 60]⟩
  , ⟨[(61, false), (23, false), (18, false), (22, false), (1, false), (8, false)], [127, 129, 131]⟩
  , ⟨[(61, true), (20, false), (8, false), (18, false), (1, false)], [132, 59, 45, 60]⟩
  , ⟨[(23, false), (61, false), (8, false), (18, false), (1, false)], [133, 127, 129, 130, 89, 105]⟩
  , ⟨[(65, false), (41, false), (8, false), (18, false), (61, false), (1, false), (22, true), (80, true)], [89, 105]⟩
  , ⟨[(65, true), (61, false), (8, false), (18, false), (1, false)], [135, 39, 112]⟩
  , ⟨[(61, false), (18, false), (8, false), (1, false)], [137, 129, 130, 136, 124, 89]⟩
  , ⟨[(58, true), (18, false), (8, false), (1, false)], [138, 134, 12, 19]⟩
  , ⟨[(18, false), (8, false), (1, false)], [138, 139, 45, 60]⟩
  , ⟨[(71, false), (26, false), (8, false), (61, true), (34, true), (1, false)], [140, 31, 85, 103]⟩
  , ⟨[(42, false), (71, true), (8, false), (1, false)], [140, 67, 76]⟩
  , ⟨[(71, true), (25, false), (8, false), (1, false)], [140, 142, 22, 88]⟩
  , ⟨[(71, false), (34, true), (8, false), (61, true), (1, false)], [140, 31, 141, 85, 9]⟩
  , ⟨[(71, true), (8, false), (1, false)], [140, 142, 143, 80]⟩
  , ⟨[(60, false), (16, false), (18, false), (44, true), (6, false), (1, true)], [83, 75, 87]⟩
  , ⟨[(38, false), (21, false), (1, true), (60, true)], [68, 79, 6, 115]⟩
  , ⟨[(52, true), (38, true), (1, true), (60, true)], [3, 116]⟩
  , ⟨[(38, true), (60, true), (1, true), (80, true)], [148, 17, 77]⟩
  , ⟨[(60, true), (80, true), (1, true)], [149, 11, 147]⟩
  , ⟨[(6, false), (60, false), (18, false), (1, true), (44, true)], [83, 146, 75, 99, 104]⟩
  , ⟨[(68, false), (62, false), (18, false), (6, true), (60, false), (33, true), (1, true)], [37, 44, 25]⟩
  , ⟨[(68, true), (51, false), (18, false), (6, true), (60, false), (47, true), (38, false), (33, true), (5, false), (1, true)], [37, 8, 18]⟩
  , ⟨[(68, false), (33, true), (18, false), (6, true), (60, false), (1, true)], [37, 44, 7, 25]⟩
  , ⟨[(5, false), (33, true), (18, false), (6, true), (60, false), (47, true), (38, false), (1, true)], [37, 154, 18, 153, 52]⟩
  , ⟨[(33, true), (38, false), (18, false), (6, true), (60, false), (47, true), (1, true)], [37, 154, 155, 102, 8, 52]⟩
  , ⟨[(66, false), (33, false), (18, false), (6, true), (60, false), (1, true)], [37, 27, 36]⟩
  , ⟨[(33, false), (59, false), (18, false), (6, true), (60, false), (1, true)], [37, 157, 71, 23, 114]⟩
  , ⟨[(79, true), (38, true), (18, false), (6, true), (60, false), (33, true), (1, true)], [37, 154, 38, 126]⟩
  , ⟨[(47, true), (33, true), (18, false), (6, true), (60, false), (1, true)], [37, 154, 156, 159, 18, 102]⟩
  , ⟨[(79, false), (33, true), (18, false), (6, true), (60, false), (1, true)], [37, 160, 154, 34, 42]⟩
  , ⟨[(33, true), (60, false), (18, false), (1, true), (6, true)], [37, 154, 161, 159, 8, 52]⟩
  , ⟨[(60, false), (44, true), (18, false), (1, true)], [151, 37, 162, 157, 158, 26, 122]⟩
  , ⟨[(50, false), (28, false), (8, true), (1, false), (79, true), (80, false), (78, false)], [47, 21, 97]⟩
  , ⟨[(50, true), (10, false), (8, true), (33, false), (21, false), (37, true), (7, false), (62, false), (65, false), (34, true), (1, false)], [16, 35, 65]⟩
  , ⟨[(50, false), (78, false), (8, true), (6, true), (80, false), (79, true), (1, false)], [47, 164, 14, 62]⟩
  , ⟨[(7, true), (36, true), (8, true), (1, false), (37, true), (50, true), (16, true)], [13, 51]⟩
  , ⟨[(21, false), (10, false), (8, true), (33, false), (37, true), (62, false), (50, true), (34, true), (1, false), (7, false)], [16, 35, 165, 55, 128]⟩
  , ⟨[(10, false), (34, true), (8, true), (37, true), (50, true), (62, false), (33, false), (1, false), (16, true)], [16, 167, 35, 168, 48, 108]⟩
  , ⟨[(21, true), (36, true), (8, true), (37, true), (62, false), (50, true), (1, false), (7, false)], [35, 48, 108]⟩
  , ⟨[(36, true), (50, true), (8, true), (37, true), (1, false), (62, false), (33, false), (16, true)], [167, 35, 170, 65, 55, 128]⟩
  , ⟨[(50, true), (16, true), (8, true), (37, true), (47, false), (77, true), (62, false), (33, false), (1, false)], [171, 121, 81, 16]⟩
  , ⟨[(28, true), (50, false), (8, true), (6, true), (80, false), (1, false), (40, false)], [14, 62]⟩
  , ⟨[(50, false), (63, false), (8, true), (79, true), (80, false), (6, true), (1, false)], [166, 106, 173, 21, 97]⟩
  , ⟨[(36, false), (10, false), (8, true), (1, false), (37, true), (50, true)], [81, 16]⟩
  , ⟨[(36, true), (40, false), (8, true), (37, true), (1, false), (50, true), (16, true)], [167, 35]⟩
  , ⟨[(36, false), (50, true), (8, true), (37, true), (1, false), (47, false), (77, true)], [121, 81, 16]⟩
  , ⟨[(16, true), (50, true), (8, true), (33, false), (47, false), (77, true), (37, true), (1, false)], [177, 172, 167, 176, 110]⟩
  , ⟨[(7, false), (40, true), (8, true), (33, false), (37, true), (36, true), (50, true), (1, false)], [110, 170, 65, 55, 128]⟩
  , ⟨[(7, true), (50, true), (8, true), (37, true), (1, false), (36, true), (16, false)], [30, 51]⟩
  , ⟨[(50, true), (37, true), (33, false), (8, true), (1, false), (47, false), (77, true)], [177, 178, 180, 35, 179]⟩
  , ⟨[(50, false), (79, true), (18, false), (6, true), (80, false), (1, false)], [140, 166, 174, 53, 173, 21, 97]⟩
  , ⟨[(40, false), (6, true), (8, true), (80, false), (37, true), (50, false), (1, false), (79, false)], [20, 173]⟩
  , ⟨[(40, true), (50, false), (18, false), (80, false), (1, false)], [140, 47, 106, 53]⟩
  , ⟨[(6, true), (50, false), (18, false), (80, false), (37, true), (1, false)], [140, 184, 182, 183]⟩
  , ⟨[(28, true), (50, false), (8, true), (80, false), (1, false), (40, false), (6, false)], [14, 78, 66, 101]⟩
  , ⟨[(50, false), (37, true), (18, false), (80, false), (1, false)], [140, 184, 185, 186, 20, 21, 97]⟩
  , ⟨[(36, true), (40, false), (8, true), (50, true), (37, true), (1, false)], [176, 35, 180]⟩
  , ⟨[(36, false), (37, true), (8, true), (1, false), (50, true)], [175, 120, 121, 54]⟩
  , ⟨[(7, true), (37, true), (8, true), (1, false), (50, true)], [189, 167, 180]⟩
  , ⟨[(37, true), (80, false), (18, false), (1, false)], [140, 187, 189, 188, 190, 110, 179, 170, 74, 55, 128]⟩
  , ⟨[(50, true), (37, false), (8, true), (1, false)], [4, 2, 29, 56, 64]⟩
  , ⟨[(28, false), (80, false), (8, true), (1, false), (37, false), (40, false)], [192, 50, 21, 97]⟩
  , ⟨[(80, false), (18, false), (1, false)], [140, 191, 192, 184, 193, 173, 186]⟩
  , ⟨[(50, false), (18, false), (1, false)], [194, 140, 111, 43, 125]⟩
  , ⟨[(18, false), (1, false)], [140, 195, 192, 189, 190, 188, 110, 179, 170, 74, 55, 128]⟩
  , ⟨[(50, true), (8, true), (1, false), (37, true)], [189, 190, 188, 110, 179, 170, 74, 55, 128]⟩
  , ⟨[(80, true), (21, false), (50, false), (8, true), (1, false)], [111, 43]⟩
  , ⟨[(40, true), (80, false), (50, false), (8, true), (1, false)], [196, 47, 106, 33]⟩
  , ⟨[(28, false), (80, false), (37, true), (8, true), (1, false)], [197, 199, 20, 21, 97]⟩
  , ⟨[(80, false), (8, true), (37, true), (1, false)], [197, 199, 200, 173, 186]⟩
  , ⟨[(8, true), (37, true), (1, false)], [196, 197, 201, 111, 198, 1]⟩
  , ⟨[(70, false), (26, true), (8, false), (1, false)], [196, 145, 85, 9]⟩
  , ⟨[(70, true), (8, false), (1, false)], [196, 145, 123, 91, 144]⟩
  , ⟨[(8, false), (1, false)], [196, 145, 204, 85, 203, 103]⟩
  , ⟨[(80, false), (1, false)], [205, 202, 192, 199, 193, 173, 186]⟩
  , ⟨[(1, false)], [196, 205, 202, 192, 206, 111, 198, 1]⟩
  , ⟨[(13, true), (30, false), (18, true), (50, false), (60, false)], [207, 58, 72]⟩
  , ⟨[(32, false), (13, false), (18, true), (60, false), (51, false)], [207, 92, 96]⟩
  , ⟨[(13, false), (29, false), (18, true), (60, false), (8, true), (37, false)], [207, 100, 209, 41, 15, 93]⟩
  , ⟨[(67, false), (13, true), (60, false), (18, true), (50, false)], [207, 208, 46, 90]⟩
  , ⟨[(13, true), (18, true), (50, false), (60, false)], [207, 208, 211, 0, 82, 69, 70]⟩
  , ⟨[(18, true), (60, false), (8, true), (37, false), (50, false)], [207, 212, 100, 209, 210, 41, 15, 61]⟩
  , ⟨[(16, false), (6, false), (60, false), (23, false), (18, false)], [207, 163, 83, 75, 10, 119]⟩
  , ⟨[(6, false), (23, false), (60, false), (18, false)], [207, 83, 75, 214, 99, 104]⟩
  , ⟨[(6, true), (18, false), (60, false)], [207, 37, 162, 157, 158, 26, 122]⟩
  , ⟨[(60, false), (50, false), (37, false), (8, true)], [207, 213, 163, 216, 83, 215, 75, 28, 99, 104]⟩
  , ⟨[(38, true), (44, false), (60, true)], [207, 150, 117, 148]⟩
  , ⟨[(38, false), (60, true)], [207, 11, 147]⟩
  , ⟨[(60, true)], [207, 150, 219, 148, 218, 49]⟩
  , ⟨[(13, false), (44, true), (8, true), (37, false)], [207, 220, 163, 100, 209, 41, 15]⟩
  , ⟨[(70, true), (32, true), (13, true), (18, true), (50, true)], [207, 220, 5, 32, 73]⟩
  , ⟨[(32, true), (18, true), (50, true), (13, true)], [207, 220, 222, 113, 63, 86]⟩
  , ⟨[(44, true), (8, true), (37, false)], [207, 220, 217, 163, 221, 223, 98, 24, 94]⟩
  , ⟨[(13, true), (18, true), (50, true)], [207, 220, 223, 98, 24, 94]⟩
  , ⟨[(18, true), (8, true), (37, false)], [207, 220, 224, 217, 225, 100, 209, 210, 41, 61]⟩
  , ⟨[(8, true), (37, false)], [207, 220, 224, 226, 216, 83, 215, 75, 28, 99, 104]⟩
  , ⟨[(18, false)], [207, 220, 163, 216, 83, 215, 75, 28, 99, 104]⟩
  , ⟨[(13, false), (37, false), (44, false)], [207, 220, 228, 227, 109, 209, 41, 61, 93]⟩
  , ⟨[(13, true)], [220, 228, 212, 225]⟩
  , ⟨[(51, false), (32, true), (44, false)], [207, 220, 228, 230, 41, 61, 93]⟩
  , ⟨[(51, true), (37, true)], [207, 220, 228, 230, 57, 95, 118]⟩
  , ⟨[(44, false)], [220, 228, 230, 229, 232, 209, 231]⟩
  , ⟨[(32, false)], [207, 220, 228, 230, 233, 209, 232, 100, 109]⟩
  , ⟨[(8, true)], [207, 220, 228, 230, 233, 234, 227, 232, 15, 41]⟩
  , ⟨[(37, false), (51, true)], [220, 230, 235, 228, 207, 109]⟩
  , ⟨[(37, true), (51, true), (71, false), (77, false)], [220, 230, 228, 207, 118]⟩
  , ⟨[(37, true), (51, true), (77, true)], [220, 230, 228, 207, 57]⟩
  , ⟨[(37, true), (71, true), (51, true), (77, false)], [220, 230, 228, 207, 95]⟩
  , ⟨[(51, false), (22, false)], [220, 234, 233, 230, 228, 207, 15]⟩
  , ⟨[(51, false), (22, true)], [220, 234, 230, 228, 207, 41]⟩
  , ⟨[(38, false), (21, false), (60, true)], [147, 207]⟩
  , ⟨[(52, true), (38, true), (60, true)], [148, 207]⟩
  , ⟨[(33, true), (6, true), (1, true), (18, false)], [162, 220]⟩
  , ⟨[(51, false), (32, false), (60, false), (13, false)], [209, 228]⟩
  , ⟨[(7, true), (36, true), (8, true), (1, false), (50, true), (16, true)], [167, 227]⟩
  , ⟨[(21, true), (62, false), (8, true), (36, true), (50, true), (1, false), (7, false)], [170, 227]⟩
  , ⟨[(36, true), (62, false), (8, true), (1, false), (50, true), (16, true), (33, false)], [171, 227]⟩
  , ⟨[(10, false), (34, true), (8, true), (50, true), (62, false), (33, false), (1, false), (16, true)], [169, 227]⟩
  , ⟨[(10, false), (34, true), (8, true), (33, false), (62, false), (50, true), (21, false), (1, false), (7, false)], [168, 227]⟩
  , ⟨[(51, true)], [236, 232]⟩
  , ⟨[(22, false)], [251, 240]⟩
  , ⟨[], [251, 252, 241]⟩
  ]

set_option maxHeartbeats 40000000 in
/-- KERNEL replay of the refutation — plain `decide`, no `native_decide`. -/
theorem check_ok : RupCheckerFast.checkRefutationFast F steps = true := by decide

/-- The recovered CNF is unsatisfiable (kernel-checked LRAT replay +
`rup_sound` composition). -/
theorem instance_unsat : ¬ ∃ σ, satFormula σ F :=
  RupCheckerFast.checkRefutationFast_sound F steps check_ok

/-- The gadget's variable set: DIMACS variables `1..82`. -/
def s : Finset ℕ := Finset.Icc 1 82

set_option maxHeartbeats 4000000 in
/-- END-TO-END VERDICT: no point of the `[0,1]` box reaches the sat_relu
gadget's unsafe region `{Y₀ ≥ 1 ∧ Y₁ ≤ 0}` — real-arithmetic SAFE. -/
theorem instance_safe :
    ∀ x : ℕ → ℝ, (∀ j ∈ s, 0 ≤ x j ∧ x j ≤ 1) →
      ¬ (1 ≤ SatRelu.Y0 (SatReluVerdict.clausesOf F) x ∧
         SatRelu.Y1 s x ≤ 0) :=
  SatReluVerdict.safe_of_unsat F s (by decide) instance_unsat

end SatReluSweep_v82c130

end Crownproof

/-! ## Trust-base check -/

#print axioms Crownproof.SatReluSweep_v82c130.check_ok
#print axioms Crownproof.SatReluSweep_v82c130.instance_unsat
#print axioms Crownproof.SatReluSweep_v82c130.instance_safe
