/-
MACHINE-GENERATED by `ny-cert`'s `lrat_to_lean` — do not edit.

sat_relu Route A instance transcript:
* DIMACS source : inst.cnf  (p cnf 95 275)
* LRAT source   : inst.lrat  (401 addition steps kept)

The kernel replays the full LRAT refutation with PLAIN `decide`
(no `native_decide`, no extra axioms) through
`RupCheckerFast.checkRefutationFast`, then composes
`checkRefutationFast_sound` (CNF-unsat) with
`SatReluVerdict.safe_of_unsat` (gadget real-arithmetic safety).
-/
import NyProof.SatReluVerdict
import NyProof.RupCheckerFast

namespace Crownproof

namespace SatReluSweep_v95c275

open RupImport.RUP RupChecker

set_option maxRecDepth 65536

/-- The recovered DIMACS formula, literal-for-literal. -/
def F : Formula :=
  [ [(1, true), (2, false), (6, false), (22, true), (27, true), (32, false), (37, false), (47, false), (48, true), (61, false), (66, true), (71, false)]
  , [(1, false), (12, true), (17, true), (52, true), (53, false), (60, false), (74, false), (85, false), (87, false), (93, true), (95, true)]
  , [(1, false), (20, false), (53, false), (64, true), (74, true), (82, true), (89, false), (95, true)]
  , [(1, false), (9, false), (20, false), (31, false), (53, true), (61, true), (65, true), (66, true), (74, true), (78, false), (80, true), (95, true)]
  , [(1, true), (6, true), (10, true), (14, true), (37, true), (42, false), (52, false), (69, true), (77, false)]
  , [(1, false), (10, false), (16, false), (32, true), (37, false), (44, false), (56, true), (62, true), (95, false)]
  , [(1, false), (16, false), (36, false), (44, true), (64, false), (71, true), (80, false), (95, false)]
  , [(1, false), (20, true), (47, false), (51, false), (74, true), (79, false), (95, true)]
  , [(1, false), (5, false), (9, false), (20, false), (33, false), (42, false), (53, true), (61, true), (66, false), (74, true), (78, false), (80, true), (95, true)]
  , [(1, true), (6, false), (9, true), (10, true), (14, false), (18, false), (28, false), (33, false), (37, true), (48, true), (83, false)]
  , [(1, true), (17, true), (37, false), (43, false), (47, false), (71, true), (78, false)]
  , [(1, true), (37, false), (43, false), (47, false), (53, false), (71, true), (78, true), (83, true)]
  , [(1, true), (17, true), (37, false), (43, true), (47, false), (54, true), (65, false), (71, true)]
  , [(1, true), (22, false), (37, false), (41, false), (47, false), (49, false), (57, false), (61, true), (71, false)]
  , [(1, true), (5, true), (27, true), (37, false), (47, true), (83, true), (92, true)]
  , [(1, true), (6, true), (14, true), (27, false), (37, true), (42, true), (77, false)]
  , [(1, true), (6, true), (12, true), (24, false), (28, true), (37, true), (39, true), (50, false), (70, false), (77, true), (95, false)]
  , [(1, false), (9, false), (20, false), (53, true), (60, true), (61, true), (65, false), (66, true), (68, true), (74, true), (78, false), (80, true), (95, true)]
  , [(1, true), (6, false), (9, true), (10, true), (14, false), (18, true), (28, false), (33, false), (37, true), (48, true), (83, false)]
  , [(1, false), (12, true), (38, false), (60, true), (62, false), (74, false), (87, false), (95, true)]
  , [(1, false), (7, false), (9, false), (12, false), (19, false), (69, true), (74, false), (87, false), (92, true), (95, true)]
  , [(1, true), (2, false), (6, false), (22, true), (27, false), (32, false), (37, false), (47, false), (48, true), (64, false), (71, false), (73, false), (80, false)]
  , [(1, false), (20, true), (47, true), (51, false), (74, true), (79, false), (95, true)]
  , [(1, true), (6, false), (9, true), (28, true), (37, true), (58, true), (76, false)]
  , [(1, false), (3, false), (49, true), (74, false), (87, true), (89, true), (95, true)]
  , [(1, false), (16, false), (26, true), (36, true), (44, true), (71, false), (95, false)]
  , [(1, false), (9, false), (20, false), (53, true), (61, true), (65, false), (66, true), (68, false), (74, true), (78, false), (80, true), (95, true)]
  , [(1, true), (6, true), (13, true), (28, false), (37, true), (38, true), (59, false), (77, true)]
  , [(1, false), (13, false), (15, false), (16, true), (41, false), (44, true), (53, false), (79, false), (95, false)]
  , [(1, false), (12, true), (44, false), (62, false), (75, true), (92, true), (95, false)]
  , [(1, false), (37, true), (43, false), (44, false), (51, false), (62, true), (95, false)]
  , [(1, false), (7, false), (12, false), (51, false), (53, false), (74, false), (78, false), (87, false), (92, false), (95, true)]
  , [(1, false), (21, true), (44, false), (62, false), (70, true), (89, true), (92, false), (95, false)]
  , [(1, false), (5, true), (12, true), (17, true), (53, true), (60, false), (74, false), (87, false), (93, true), (94, false), (95, true)]
  , [(1, false), (16, false), (36, false), (44, true), (64, true), (72, true), (95, false)]
  , [(1, false), (9, false), (20, false), (31, true), (53, true), (61, true), (65, true), (66, true), (74, true), (78, false), (80, true), (81, false), (95, true)]
  , [(1, false), (44, false), (62, false), (75, false), (92, true), (95, false)]
  , [(1, true), (2, false), (6, false), (22, true), (27, false), (32, false), (35, true), (37, false), (47, false), (48, true), (71, false), (73, true)]
  , [(1, false), (9, true), (20, false), (40, true), (53, true), (54, true), (61, true), (74, true), (78, false), (80, true), (93, true), (95, true)]
  , [(1, true), (17, true), (37, false), (43, true), (47, false), (54, false), (65, false), (71, true)]
  , [(1, false), (3, true), (4, true), (7, true), (15, true), (16, true), (26, true), (44, true), (64, true), (95, false)]
  , [(1, true), (6, false), (22, false), (37, false), (47, false), (49, true), (61, true), (71, false)]
  , [(1, false), (12, true), (38, true), (60, true), (74, false), (79, true), (87, false), (95, true)]
  , [(1, false), (4, false), (12, true), (35, true), (53, false), (60, false), (74, false), (87, false), (93, false), (95, true)]
  , [(1, true), (6, false), (9, true), (10, false), (14, false), (28, false), (33, false), (37, true), (48, true), (83, false)]
  , [(1, true), (6, false), (14, true), (28, false), (37, true), (43, false), (48, true), (54, false), (74, true), (83, false)]
  , [(1, false), (20, false), (27, true), (53, true), (61, true), (74, true), (80, false), (85, false), (95, true)]
  , [(1, false), (7, false), (9, false), (12, false), (19, true), (74, false), (87, false), (92, true), (95, true)]
  , [(1, false), (16, false), (36, false), (44, true), (64, true), (72, false), (95, false)]
  , [(1, false), (7, true), (12, false), (36, true), (74, false), (87, false), (95, true)]
  , [(1, true), (6, true), (22, true), (37, false), (44, true), (47, false), (71, false)]
  , [(1, false), (4, false), (12, true), (53, true), (60, false), (74, false), (87, false), (93, false), (95, true)]
  , [(1, false), (7, false), (9, true), (12, false), (19, true), (74, false), (87, false), (92, true), (95, true)]
  , [(1, false), (20, false), (44, true), (53, true), (61, false), (68, true), (74, true), (91, false), (95, true)]
  , [(1, true), (22, false), (37, false), (41, true), (47, false), (48, false), (49, false), (61, true), (71, false), (90, false)]
  , [(1, false), (13, true), (15, false), (16, true), (17, false), (37, true), (44, true), (54, false), (95, false)]
  , [(1, true), (22, false), (37, false), (41, false), (47, false), (49, false), (57, true), (61, true), (71, false)]
  , [(1, false), (10, true), (23, false), (35, false), (37, false), (42, true), (44, false), (60, false), (62, true), (95, false)]
  , [(1, false), (10, false), (16, false), (32, true), (37, false), (44, false), (56, false), (62, true), (95, false)]
  , [(1, true), (17, true), (34, false), (37, false), (43, true), (47, false), (65, true), (71, true)]
  , [(1, false), (14, false), (21, true), (44, false), (50, false), (62, false), (70, true), (89, false), (92, false), (95, false)]
  , [(1, false), (3, true), (37, true), (57, false), (60, true), (74, false), (87, true), (95, true)]
  , [(1, true), (6, true), (7, true), (14, true), (27, true), (37, true), (42, true), (77, false)]
  , [(1, true), (2, false), (6, false), (22, true), (27, false), (32, false), (37, false), (47, false), (48, true), (64, false), (71, false), (73, false), (80, true)]
  , [(1, false), (3, true), (4, false), (15, true), (16, true), (44, true), (95, false)]
  , [(1, true), (6, true), (14, false), (19, false), (37, true), (77, false)]
  , [(1, true), (6, false), (9, false), (28, true), (37, true), (63, true), (76, false)]
  , [(1, true), (9, false), (17, false), (37, false), (43, false), (47, false), (71, true), (78, false)]
  , [(1, false), (3, false), (49, false), (51, false), (74, false), (87, true), (89, true), (95, true)]
  , [(1, true), (6, true), (14, true), (29, true), (37, true), (42, false), (52, true), (77, false)]
  , [(1, false), (20, false), (23, true), (27, false), (53, true), (61, true), (74, true), (80, false), (86, true), (95, true)]
  , [(1, true), (2, false), (12, true), (36, true), (37, false), (47, true), (92, false)]
  , [(1, false), (3, true), (7, false), (26, true), (37, true), (60, false), (74, false), (87, true), (95, true)]
  , [(1, true), (9, true), (17, false), (37, false), (43, false), (47, false), (71, true), (78, false)]
  , [(1, false), (20, false), (23, false), (27, false), (53, true), (61, true), (74, true), (80, false), (86, true), (95, true)]
  , [(1, false), (9, false), (20, false), (33, true), (53, true), (60, true), (61, true), (66, false), (74, true), (78, false), (80, true), (95, true)]
  , [(1, true), (12, false), (29, false), (36, true), (37, false), (47, true), (63, false), (75, false), (92, false)]
  , [(1, false), (44, false), (62, false), (70, false), (82, false), (92, false), (95, false)]
  , [(1, false), (3, true), (4, true), (7, false), (15, true), (16, true), (26, true), (44, true), (64, true), (95, false)]
  , [(1, true), (37, false), (43, false), (47, false), (71, true), (78, true), (83, false)]
  , [(1, true), (12, false), (37, false), (47, true), (75, true), (86, true), (92, false)]
  , [(1, true), (6, false), (28, false), (37, true), (42, true), (48, false), (52, true), (84, false)]
  , [(1, false), (9, false), (20, false), (33, false), (42, true), (53, true), (61, true), (66, false), (74, true), (78, false), (80, true), (95, true)]
  , [(1, false), (3, true), (10, true), (37, false), (44, false), (46, true), (60, true), (62, true), (95, false)]
  , [(1, true), (6, false), (9, false), (28, true), (37, true), (63, false), (76, false)]
  , [(1, true), (6, false), (28, false), (37, true), (48, false), (52, false), (58, false)]
  , [(1, true), (6, true), (28, true), (37, true), (39, false), (70, false), (77, true), (95, false)]
  , [(1, false), (13, false), (15, false), (16, true), (41, true), (44, true), (53, false), (79, false), (80, false), (95, false)]
  , [(1, true), (17, false), (25, false), (37, false), (43, true), (47, false), (71, true)]
  , [(1, false), (12, true), (38, true), (60, true), (74, false), (79, false), (87, false), (95, true)]
  , [(1, false), (20, false), (53, false), (74, true), (89, true), (95, true)]
  , [(1, false), (7, false), (12, false), (60, false), (67, false), (74, false), (78, true), (87, false), (88, true), (92, false), (95, true)]
  , [(1, true), (6, true), (14, true), (37, true), (42, false), (52, false), (69, false), (77, false)]
  , [(1, false), (16, false), (36, false), (44, true), (64, false), (71, false), (95, false)]
  , [(1, false), (21, false), (44, false), (62, false), (70, true), (92, false), (95, false)]
  , [(1, false), (37, true), (44, false), (51, true), (62, true), (69, true), (95, false)]
  , [(1, false), (7, false), (9, true), (12, false), (19, false), (69, true), (74, false), (87, false), (92, true), (95, true)]
  , [(1, true), (6, true), (7, false), (14, true), (27, true), (37, true), (42, true), (77, false)]
  , [(1, true), (6, true), (28, true), (37, true), (54, false), (66, false), (70, true), (77, true)]
  , [(1, true), (5, true), (19, false), (27, false), (37, false), (47, true), (83, true), (92, true)]
  , [(1, false), (3, true), (37, true), (57, true), (60, true), (74, false), (87, true), (95, true)]
  , [(1, true), (17, true), (34, true), (37, false), (43, true), (47, false), (65, true), (71, true)]
  , [(1, false), (20, false), (27, false), (53, true), (61, true), (74, true), (80, false), (86, false), (95, true)]
  , [(1, false), (20, true), (38, true), (51, true), (55, false), (68, true), (74, true), (95, true)]
  , [(1, false), (13, true), (15, false), (16, true), (44, true), (54, true), (72, true), (95, false)]
  , [(1, true), (6, false), (14, false), (28, false), (37, true), (39, true), (42, false), (48, false), (52, true)]
  , [(1, false), (7, false), (12, false), (19, false), (69, false), (74, false), (87, false), (92, true), (95, true)]
  , [(1, false), (3, true), (7, true), (19, false), (26, true), (37, true), (60, false), (74, false), (87, true), (95, true)]
  , [(1, true), (12, false), (37, false), (47, true), (75, true), (86, false), (92, false)]
  , [(1, true), (31, true), (37, false), (47, true), (76, true), (83, false), (92, true)]
  , [(1, true), (6, false), (28, false), (37, true), (48, true), (83, true)]
  , [(1, true), (6, true), (12, true), (24, false), (28, true), (37, true), (39, true), (50, true), (70, false), (77, true), (95, false)]
  , [(1, true), (6, false), (18, false), (28, true), (37, true), (76, true)]
  , [(1, true), (2, false), (6, false), (22, true), (32, true), (37, false), (47, false), (71, false)]
  , [(1, false), (3, true), (4, true), (15, true), (16, true), (26, false), (44, true), (64, true), (95, false)]
  , [(1, false), (9, true), (20, false), (40, false), (46, true), (53, true), (59, false), (61, true), (74, true), (78, false), (80, true), (95, true)]
  , [(1, false), (6, true), (20, false), (53, true), (61, true), (74, true), (78, true), (80, true), (95, true)]
  , [(1, true), (6, false), (18, true), (28, true), (37, true), (76, true)]
  , [(1, false), (5, false), (12, true), (17, true), (48, false), (53, true), (58, false), (60, false), (74, false), (77, true), (87, false), (93, true), (95, true)]
  , [(1, false), (9, false), (20, false), (33, true), (35, true), (53, true), (60, false), (61, true), (66, false), (74, true), (78, false), (80, true), (95, true)]
  , [(1, true), (2, true), (6, false), (11, true), (22, true), (37, false), (47, false), (71, false)]
  , [(1, true), (6, true), (22, false), (37, false), (47, false), (49, true), (61, true), (71, false), (79, false), (93, false)]
  , [(1, true), (22, false), (37, false), (41, true), (47, false), (48, false), (49, false), (61, true), (71, false), (90, true)]
  , [(1, false), (3, false), (54, false), (66, true), (68, false), (74, false), (87, true), (89, false), (95, true)]
  , [(1, true), (2, false), (6, false), (22, true), (32, false), (37, false), (47, false), (48, false), (70, true), (71, false)]
  , [(1, false), (9, true), (20, false), (40, false), (53, true), (59, true), (61, true), (74, true), (78, false), (80, true), (95, true)]
  , [(1, true), (6, true), (28, true), (37, true), (54, true), (70, true), (77, true), (79, true)]
  , [(1, true), (31, false), (37, false), (47, true), (76, true), (83, false), (92, true)]
  , [(1, false), (7, false), (12, false), (60, false), (74, false), (78, true), (87, false), (88, false), (92, false), (95, true)]
  , [(1, true), (6, true), (13, false), (28, false), (37, true), (38, true), (59, false), (77, true)]
  , [(1, false), (13, false), (15, false), (16, true), (41, true), (44, true), (53, false), (79, false), (80, true), (95, false)]
  , [(1, false), (9, true), (20, false), (40, true), (53, true), (54, false), (61, true), (74, true), (78, false), (80, true), (93, true), (95, true)]
  , [(1, true), (6, true), (28, false), (37, true), (38, false), (59, false), (77, true)]
  , [(1, true), (17, false), (25, true), (37, false), (43, true), (47, false), (71, true)]
  , [(1, true), (6, true), (14, true), (29, false), (37, true), (42, false), (52, true), (77, false)]
  , [(1, true), (12, false), (29, true), (37, false), (47, true), (75, false), (92, false)]
  , [(1, false), (13, true), (15, false), (16, true), (17, false), (37, false), (44, true), (54, false), (95, false)]
  , [(1, false), (3, false), (15, true), (16, true), (44, true), (82, false), (95, false)]
  , [(1, true), (12, true), (36, false), (37, false), (47, true), (92, false)]
  , [(1, false), (14, false), (21, true), (44, false), (50, true), (62, false), (70, true), (89, false), (92, false), (95, false)]
  , [(1, true), (6, false), (14, false), (28, false), (37, true), (39, false), (42, false), (48, false), (52, true)]
  , [(1, false), (12, true), (17, true), (52, false), (53, false), (60, false), (74, false), (85, false), (87, false), (93, true), (95, true)]
  , [(1, false), (5, true), (10, false), (16, true), (32, true), (37, false), (44, false), (62, true), (89, false), (95, false)]
  , [(1, false), (10, false), (32, false), (37, false), (44, false), (57, true), (62, true), (95, false)]
  , [(1, true), (2, true), (11, false), (12, true), (36, true), (37, false), (47, true), (54, true), (92, false)]
  , [(1, false), (10, true), (37, false), (42, false), (44, false), (60, false), (62, true), (95, false)]
  , [(1, true), (6, true), (28, true), (37, true), (54, false), (66, true), (70, true), (77, true)]
  , [(1, false), (5, false), (10, false), (16, true), (32, true), (37, false), (44, false), (62, true), (80, true), (95, false)]
  , [(1, false), (12, true), (17, false), (60, false), (63, true), (74, false), (87, false), (93, true), (95, true)]
  , [(1, true), (6, true), (22, false), (37, false), (47, false), (49, true), (61, true), (71, false), (79, true)]
  , [(1, true), (6, false), (28, false), (37, true), (48, false), (52, false), (58, true)]
  , [(1, false), (37, true), (43, true), (44, false), (51, false), (62, true), (95, false)]
  , [(1, false), (7, false), (12, false), (16, true), (60, true), (74, false), (78, true), (87, false), (92, false), (95, true)]
  , [(1, false), (7, true), (12, false), (36, false), (74, false), (87, false), (95, true)]
  , [(1, false), (5, false), (12, true), (17, true), (48, true), (53, true), (58, false), (60, false), (74, false), (77, true), (87, false), (93, true), (95, true)]
  , [(1, false), (3, true), (24, true), (37, false), (44, false), (71, false), (74, false), (79, true), (87, true), (92, false), (95, true)]
  , [(1, false), (12, false), (44, false), (62, false), (75, true), (92, true), (95, false)]
  , [(1, false), (3, true), (10, true), (24, true), (37, false), (44, false), (71, false), (73, false), (74, false), (87, true), (89, false), (92, true), (95, true)]
  , [(1, false), (13, false), (15, false), (16, true), (44, true), (79, true), (95, false)]
  , [(1, false), (3, false), (27, false), (54, false), (66, false), (74, false), (87, true), (89, false), (95, true)]
  , [(1, false), (44, false), (62, false), (70, false), (82, true), (92, false), (95, false)]
  , [(1, false), (3, true), (10, true), (37, false), (44, false), (46, false), (60, true), (62, true), (95, false)]
  , [(1, true), (6, false), (14, true), (28, false), (37, true), (48, true), (54, true), (83, false)]
  , [(1, true), (9, false), (33, false), (37, false), (43, false), (47, false), (53, true), (71, true), (78, true), (83, true)]
  , [(1, false), (9, true), (20, false), (40, true), (53, true), (61, true), (74, true), (78, false), (80, true), (93, false), (95, true)]
  , [(1, false), (7, false), (12, false), (60, false), (67, true), (74, false), (78, true), (87, false), (88, true), (92, false), (95, true)]
  , [(1, false), (13, false), (15, false), (16, true), (44, true), (53, true), (79, false), (95, false)]
  , [(1, false), (20, true), (38, false), (51, true), (55, false), (68, true), (74, true), (95, true)]
  , [(1, true), (6, false), (14, true), (28, false), (37, true), (43, true), (48, true), (54, false), (74, true), (83, false)]
  , [(1, true), (6, true), (14, false), (19, true), (37, true), (77, false)]
  , [(1, true), (6, true), (12, false), (28, true), (37, true), (39, true), (70, false), (77, true), (86, true), (95, false)]
  , [(1, false), (12, true), (17, false), (60, false), (63, false), (74, false), (87, false), (93, true), (95, true)]
  , [(1, false), (3, false), (49, false), (51, true), (74, false), (87, true), (89, true), (95, true)]
  , [(1, false), (9, false), (18, false), (20, false), (31, true), (53, true), (61, true), (65, true), (66, true), (74, true), (78, false), (80, true), (81, true), (95, true)]
  , [(1, false), (20, true), (51, false), (74, true), (79, true), (95, true)]
  , [(1, false), (6, false), (20, false), (53, true), (61, true), (74, true), (78, true), (80, true), (95, true)]
  , [(1, false), (7, false), (12, false), (51, false), (53, true), (74, false), (78, false), (87, false), (92, false), (95, true)]
  , [(1, false), (12, true), (38, false), (60, true), (62, true), (74, false), (87, false), (95, true)]
  , [(1, false), (9, false), (20, false), (53, true), (60, false), (61, true), (65, false), (66, true), (68, true), (74, true), (78, false), (80, true), (95, true)]
  , [(1, true), (6, true), (10, false), (14, true), (37, true), (42, false), (52, false), (69, true), (77, false)]
  , [(1, false), (5, false), (10, false), (16, true), (32, true), (37, false), (44, false), (62, true), (80, false), (95, false)]
  , [(1, false), (37, true), (44, false), (51, true), (62, true), (69, false), (95, false)]
  , [(1, true), (6, true), (28, true), (37, true), (54, true), (70, true), (77, true), (79, false)]
  , [(1, false), (3, true), (24, true), (37, false), (44, false), (71, false), (73, true), (74, false), (87, true), (92, true), (95, true)]
  , [(1, true), (2, false), (6, false), (22, true), (32, false), (37, false), (47, false), (48, false), (70, false), (71, false)]
  , [(1, false), (13, true), (15, false), (16, true), (17, true), (44, true), (54, false), (95, false)]
  , [(1, true), (9, false), (33, true), (37, false), (43, false), (47, false), (53, true), (71, true), (78, true), (83, true)]
  , [(1, false), (5, true), (10, false), (16, true), (17, false), (32, true), (37, false), (44, false), (62, true), (89, true), (95, false)]
  , [(1, false), (20, false), (53, false), (64, true), (74, true), (82, false), (89, false), (95, true)]
  , [(1, false), (3, true), (4, true), (15, true), (16, true), (44, true), (64, false), (95, false)]
  , [(1, false), (7, false), (12, false), (16, false), (60, true), (74, false), (78, true), (87, false), (92, false), (95, true)]
  , [(1, false), (20, true), (32, false), (51, true), (55, true), (74, true), (95, true)]
  , [(1, false), (9, true), (20, false), (40, false), (46, false), (53, true), (59, false), (61, true), (74, true), (78, false), (80, true), (95, true)]
  , [(1, false), (20, true), (32, true), (51, true), (55, true), (74, true), (95, true)]
  , [(1, false), (5, true), (9, false), (20, false), (33, false), (42, false), (53, true), (61, true), (66, false), (74, true), (78, false), (80, true), (95, true)]
  , [(1, false), (20, false), (27, true), (53, true), (61, true), (74, true), (80, false), (85, true), (95, true)]
  , [(1, false), (14, true), (21, true), (44, false), (62, false), (70, true), (89, false), (92, false), (95, false)]
  , [(1, false), (10, true), (23, false), (35, true), (37, false), (42, true), (44, false), (60, false), (62, true), (95, false)]
  , [(1, false), (3, true), (10, true), (24, true), (37, false), (44, false), (71, false), (73, false), (74, false), (87, true), (89, true), (92, true), (95, true)]
  , [(1, false), (3, false), (12, false), (27, true), (54, false), (66, false), (74, false), (87, true), (89, false), (90, false), (95, true)]
  , [(1, true), (2, true), (11, true), (12, true), (36, true), (37, false), (47, true), (92, false)]
  , [(1, true), (6, false), (14, false), (28, false), (33, true), (37, true), (48, true), (83, false)]
  , [(1, true), (5, true), (19, true), (27, false), (37, false), (47, true), (83, true), (92, true)]
  , [(1, true), (9, true), (37, false), (43, false), (47, false), (53, true), (71, true), (78, true), (83, true)]
  , [(1, true), (6, false), (14, true), (28, false), (37, true), (42, false), (48, false), (52, true)]
  , [(1, true), (6, false), (28, false), (37, true), (42, true), (48, false), (52, true), (84, true)]
  , [(1, false), (3, true), (7, true), (19, true), (26, true), (37, true), (60, false), (74, false), (87, true), (95, true)]
  , [(1, false), (3, true), (24, true), (37, false), (44, false), (71, false), (74, false), (79, false), (87, true), (92, false), (95, true)]
  , [(1, true), (6, true), (28, true), (37, true), (70, false), (77, true), (88, false), (95, true)]
  , [(1, false), (5, true), (12, true), (17, true), (24, false), (53, true), (60, false), (74, false), (87, false), (93, true), (94, true), (95, true)]
  , [(1, false), (13, true), (15, false), (16, true), (30, true), (44, true), (54, true), (72, false), (95, false)]
  , [(1, false), (2, false), (3, false), (29, false), (54, true), (70, false), (74, false), (87, true), (89, false), (95, true)]
  , [(1, false), (20, false), (40, false), (53, true), (61, false), (74, true), (91, true), (95, true)]
  , [(1, false), (3, false), (54, false), (66, true), (68, true), (74, false), (87, true), (89, false), (95, true)]
  , [(1, false), (3, false), (29, true), (54, true), (74, false), (87, true), (89, false), (95, true)]
  , [(1, false), (7, false), (12, false), (51, true), (74, false), (78, false), (87, false), (92, false), (95, true)]
  , [(1, true), (7, true), (30, true), (37, false), (47, true), (76, false), (83, false), (92, true)]
  , [(1, false), (12, true), (17, true), (53, false), (60, false), (74, false), (85, true), (87, false), (93, true), (95, true)]
  , [(1, false), (20, false), (44, false), (53, true), (61, false), (74, true), (91, false), (95, true)]
  , [(1, true), (6, true), (28, false), (37, true), (59, true), (77, true)]
  , [(1, false), (3, false), (29, false), (54, true), (70, true), (74, false), (87, true), (89, false), (95, true)]
  , [(1, false), (3, false), (15, true), (16, true), (44, true), (82, true), (95, false)]
  , [(1, true), (2, false), (6, false), (22, true), (27, true), (32, false), (37, false), (47, false), (48, true), (61, false), (66, false), (71, false)]
  , [(1, false), (3, true), (26, false), (37, true), (60, false), (74, false), (82, false), (87, true), (95, true)]
  , [(1, false), (16, false), (23, true), (26, false), (36, true), (44, true), (95, false)]
  , [(1, false), (20, false), (44, true), (53, true), (61, false), (68, false), (74, true), (91, false), (95, true)]
  , [(1, false), (3, true), (37, false), (71, true), (74, false), (87, true), (95, true)]
  , [(1, false), (16, false), (23, false), (26, false), (36, true), (44, true), (95, false)]
  , [(1, false), (3, true), (10, false), (24, true), (37, false), (44, false), (71, false), (73, false), (74, false), (87, true), (92, true), (95, true)]
  , [(1, true), (6, false), (9, true), (28, true), (37, true), (58, false), (76, false)]
  , [(1, false), (5, false), (12, true), (17, true), (53, true), (60, false), (74, false), (77, false), (87, false), (93, true), (95, true)]
  , [(1, false), (5, true), (12, true), (17, true), (24, true), (53, true), (60, false), (74, false), (87, false), (93, true), (94, true), (95, true)]
  , [(1, false), (10, false), (32, false), (37, false), (44, false), (57, false), (62, true), (65, false), (95, false)]
  , [(1, true), (6, true), (28, true), (37, true), (70, false), (77, true), (88, true), (95, true)]
  , [(1, true), (6, false), (14, true), (28, false), (37, true), (48, true), (54, false), (74, false), (83, false)]
  , [(1, true), (2, false), (6, false), (22, true), (27, true), (32, false), (37, false), (47, false), (48, true), (61, true), (71, false)]
  , [(1, true), (2, false), (6, false), (22, true), (27, false), (32, false), (37, false), (47, false), (48, true), (64, true), (71, false), (73, false)]
  , [(1, true), (22, false), (37, false), (47, false), (61, false), (71, false)]
  , [(1, true), (2, false), (6, false), (22, true), (27, false), (32, false), (35, false), (37, false), (47, false), (48, true), (71, false), (73, true)]
  , [(1, true), (22, false), (37, false), (41, true), (47, false), (48, true), (49, false), (61, true), (71, false)]
  , [(1, false), (3, true), (26, false), (37, true), (60, false), (74, false), (82, true), (87, true), (95, true)]
  , [(1, false), (3, false), (12, true), (27, true), (54, false), (66, false), (74, false), (87, true), (89, false), (95, true)]
  , [(1, false), (4, false), (12, true), (35, false), (53, false), (60, false), (74, false), (87, false), (93, false), (95, true)]
  , [(1, true), (2, true), (11, false), (12, true), (36, true), (37, false), (47, true), (54, false), (92, false)]
  , [(1, true), (30, false), (37, false), (47, true), (76, false), (83, false), (92, true)]
  , [(1, true), (12, false), (29, false), (37, false), (47, true), (63, true), (75, false), (92, false)]
  , [(1, false), (5, true), (10, false), (16, true), (17, true), (32, true), (37, false), (44, false), (62, true), (89, true), (95, false)]
  , [(1, false), (9, false), (20, false), (33, true), (35, false), (53, true), (60, false), (61, true), (66, false), (74, true), (78, false), (80, true), (95, true)]
  , [(1, false), (3, true), (24, false), (37, false), (44, false), (71, false), (74, false), (87, true), (95, true)]
  , [(1, false), (16, false), (36, false), (44, true), (64, false), (71, true), (80, true), (95, false)]
  , [(1, true), (6, false), (9, false), (14, false), (28, false), (33, false), (37, true), (48, true), (83, false)]
  , [(1, false), (3, false), (10, true), (37, false), (44, false), (60, true), (62, true), (95, false)]
  , [(1, true), (12, false), (29, false), (36, false), (37, false), (47, true), (63, false), (75, false), (92, false)]
  , [(1, true), (6, true), (22, false), (37, false), (47, false), (49, true), (61, true), (71, false), (79, false), (93, true)]
  , [(1, false), (9, false), (18, true), (20, false), (31, true), (53, true), (61, true), (65, true), (66, true), (74, true), (78, false), (80, true), (81, true), (95, true)]
  , [(1, false), (20, true), (51, true), (55, false), (68, false), (74, true), (95, true)]
  , [(1, false), (13, true), (15, false), (16, true), (30, false), (44, true), (54, true), (72, false), (95, false)]
  , [(1, false), (10, false), (32, false), (37, false), (44, false), (57, false), (62, true), (65, true), (95, false)]
  , [(1, false), (3, true), (37, false), (44, true), (64, false), (71, false), (74, false), (87, true), (95, true)]
  , [(1, false), (4, true), (12, true), (60, false), (74, false), (87, false), (93, false), (95, true)]
  , [(1, true), (7, false), (30, true), (37, false), (47, true), (76, false), (83, false), (92, true)]
  , [(1, false), (16, false), (26, true), (36, true), (44, true), (71, true), (95, false)]
  , [(1, false), (5, false), (12, true), (17, true), (53, true), (58, true), (60, false), (74, false), (77, true), (87, false), (93, true), (95, true)]
  , [(1, false), (3, true), (37, false), (44, true), (64, true), (71, false), (74, false), (87, true), (95, true)]
  , [(1, true), (6, true), (12, true), (24, true), (28, true), (37, true), (39, true), (70, false), (77, true), (95, false)]
  , [(1, true), (5, false), (37, false), (47, true), (83, true), (92, true)]
  , [(1, false), (2, true), (3, false), (29, false), (54, true), (70, false), (74, false), (87, true), (89, false), (95, true)]
  , [(1, false), (10, true), (23, true), (37, false), (42, true), (44, false), (60, false), (62, true), (95, false)]
  , [(1, false), (20, false), (53, false), (64, false), (74, true), (89, false), (95, true)]
  , [(1, true), (6, true), (22, true), (23, true), (37, false), (44, false), (47, false), (71, false)]
  , [(1, true), (6, true), (12, false), (28, true), (37, true), (39, true), (70, false), (77, true), (86, false), (95, false)]
  , [(1, false), (3, false), (12, false), (27, true), (54, false), (66, false), (74, false), (87, true), (89, false), (90, true), (95, true)]
  , [(1, true), (2, true), (6, false), (11, false), (22, true), (37, false), (47, false), (71, false)]
  , [(1, true), (6, true), (22, true), (23, false), (37, false), (44, false), (47, false), (71, false)]
  , [(1, false), (20, false), (40, true), (53, true), (61, false), (74, true), (91, true), (95, true)]
  ]

/-- The LRAT refutation: derived clause + database-index hints per step. -/
def steps : List RStep :=
  [ ⟨[(92, false), (87, false), (7, false), (12, false), (51, false), (53, false), (74, false), (78, false), (1, false), (44, false), (62, false), (70, false), (82, false)], [77, 31]⟩
  , ⟨[(87, false), (82, false), (7, false), (12, false), (19, false), (69, false), (74, false), (44, false), (62, false), (75, false), (51, false), (53, false), (78, false), (70, false), (1, false)], [275, 36, 106]⟩
  , ⟨[(95, true), (87, true), (3, false), (27, false), (54, false), (66, false), (74, false), (1, false), (49, false), (51, false)], [68, 159]⟩
  , ⟨[(82, false), (78, false), (44, false), (62, false), (70, false), (75, false), (3, false), (27, false), (54, false), (66, false), (74, false), (49, false), (51, false), (7, false), (12, false), (19, false), (69, false), (53, false), (1, false)], [276, 277, 36, 77]⟩
  , ⟨[(95, false), (82, true), (44, false), (62, false), (70, false), (1, false), (75, false)], [36, 160]⟩
  , ⟨[(78, false), (75, false), (7, false), (12, false), (51, false), (53, false), (74, false), (19, false), (69, false), (3, false), (27, false), (54, false), (66, false), (49, false), (44, false), (62, false), (70, false), (1, false)], [278, 279, 277, 106, 31]⟩
  , ⟨[(95, true), (78, true), (7, false), (12, false), (60, false), (67, false), (74, false), (1, false), (19, false), (69, false), (3, false), (27, false), (54, false), (66, false), (49, false), (51, false)], [277, 106, 128, 91]⟩
  , ⟨[(75, false), (74, false), (44, false), (62, false), (70, false), (7, false), (12, false), (60, false), (67, false), (1, false), (19, false), (69, false), (3, false), (27, false), (54, false), (66, false), (49, false), (51, false), (53, false)], [280, 281, 36, 279, 77]⟩
  , ⟨[(95, false), (75, true), (44, false), (62, false), (70, false), (12, false), (1, false)], [156, 77, 160]⟩
  , ⟨[(74, false), (70, false), (7, false), (12, false), (51, false), (53, false), (19, false), (69, false), (60, false), (67, false), (3, false), (27, false), (54, false), (66, false), (49, false), (44, false), (62, false), (1, false)], [282, 283, 277, 281, 106, 31]⟩
  , ⟨[(95, true), (74, true), (20, false), (53, false), (64, false), (1, false)], [90, 268]⟩
  , ⟨[(70, false), (69, false), (44, false), (62, false), (12, false), (20, false), (53, false), (64, false), (7, false), (51, false), (19, false), (1, false), (60, false), (67, false), (3, false), (27, false), (54, false), (66, false), (49, false)], [284, 285, 283, 36, 279, 77]⟩
  , ⟨[(95, false), (70, true), (12, false), (44, false), (62, false), (21, false), (1, false)], [94, 36, 156]⟩
  , ⟨[(69, false), (67, false), (7, false), (12, false), (51, false), (53, false), (19, false), (60, false), (1, false), (3, false), (27, false), (54, false), (66, false), (49, false), (20, false), (64, false), (44, false), (62, false), (21, false)], [286, 287, 285, 277, 281, 106, 31]⟩
  , ⟨[(95, true), (67, false), (3, false), (7, false), (9, false), (12, false), (19, false), (20, false), (27, false), (49, false), (51, false), (53, false), (54, false), (60, false), (64, false), (66, false), (1, false), (69, true)], [285, 277, 20, 31, 128, 91]⟩
  , ⟨[(95, false), (62, false), (44, false), (1, false), (12, false), (21, false)], [287, 283, 36, 279, 77]⟩
  , ⟨[(71, true), (47, false), (37, false), (43, false), (78, true), (1, true), (53, false)], [11, 79]⟩
  , ⟨[(47, false), (43, false), (22, false), (37, false), (49, false), (41, false), (1, true), (78, true), (53, false)], [291, 237, 13, 56]⟩
  , ⟨[(47, true), (37, false), (12, false), (29, false), (36, false), (1, true), (75, false), (92, false)], [245, 252]⟩
  , ⟨[(43, false), (37, false), (53, false), (49, false), (78, true), (22, false), (1, true), (47, false)], [292, 291, 237, 239, 54, 122]⟩
  , ⟨[(41, true), (37, false), (49, false), (22, false), (1, true), (47, false), (71, false)], [237, 239, 54, 122]⟩
  , ⟨[(37, false), (36, false), (22, false), (49, false), (17, false), (25, false), (53, false), (78, true), (12, false), (29, false), (1, true), (75, false), (92, false)], [293, 294, 88, 237, 295, 13, 56]⟩
  , ⟨[(52, false), (48, false), (6, false), (28, false), (37, true), (1, true)], [85, 150]⟩
  , ⟨[(42, true), (48, false), (6, false), (28, false), (37, true), (1, true)], [297, 81, 205]⟩
  , ⟨[(48, false), (37, true), (6, false), (14, false), (28, false), (1, true)], [297, 298, 105, 140]⟩
  , ⟨[(37, true), (33, false), (9, false), (6, false), (14, false), (28, false), (1, true)], [299, 110, 250]⟩
  , ⟨[(47, false), (43, true), (22, false), (37, false), (49, false), (17, false), (25, false), (1, true)], [88, 295, 237, 13, 56]⟩
  , ⟨[(47, true), (37, false), (12, false), (92, false), (75, false), (29, false), (1, true), (36, true)], [245, 76]⟩
  , ⟨[(37, false), (29, false), (49, false), (17, false), (25, false), (1, true), (53, false), (78, true), (12, false), (92, false), (75, false), (22, false)], [296, 302, 294, 301]⟩
  , ⟨[(37, true), (28, false), (6, false), (14, false), (1, true), (9, false)], [299, 300, 110, 201]⟩
  , ⟨[(37, false), (25, false), (49, false), (17, false), (22, false), (1, true), (53, false), (78, true), (12, false), (75, false), (92, false)], [303, 135, 294, 301]⟩
  , ⟨[(37, true), (18, false), (9, false), (6, false), (1, true), (14, false)], [304, 112, 66, 84]⟩
  , ⟨[(95, false), (70, false), (92, false), (44, false), (62, false), (1, false), (75, false)], [279, 77]⟩
  , ⟨[(74, false), (67, false), (7, false), (12, false), (60, false), (1, false), (78, true), (92, false), (95, true), (3, false), (27, false), (54, false), (66, false), (49, false), (51, false)], [277, 128, 91]⟩
  , ⟨[(20, false), (67, false), (49, false), (9, false), (12, false), (53, false), (7, false), (51, false), (95, true), (82, false), (19, false), (69, true), (3, false), (27, false), (54, false), (66, false), (60, false), (1, false), (74, true)], [289, 90, 188]⟩
  , ⟨[(67, false), (60, false), (51, false), (95, true), (47, false), (49, false), (9, false), (12, false), (53, false), (7, false), (82, false), (19, false), (69, true), (3, false), (27, false), (54, false), (66, false), (1, false), (78, true), (92, false)], [308, 309, 7, 174]⟩
  , ⟨[(20, true), (74, true), (51, false), (1, false), (95, true), (47, false)], [7, 174]⟩
  , ⟨[(74, true), (82, false), (53, false), (1, false), (95, true), (51, false), (47, false)], [311, 285, 90, 188]⟩
  , ⟨[(60, false), (66, false), (49, false), (12, false), (92, false), (78, true), (7, false), (51, false), (95, true), (74, false), (3, false), (27, false), (54, false), (1, false)], [277, 308, 128, 165]⟩
  , ⟨[(66, false), (54, false), (7, false), (12, false), (74, false), (78, true), (92, false), (95, true), (49, false), (51, false), (3, false), (27, false), (1, false)], [277, 313, 152, 190]⟩
  , ⟨[(87, false), (60, true), (7, false), (12, false), (74, false), (78, true), (1, false), (92, false), (95, true)], [152, 190]⟩
  , ⟨[(87, true), (54, false), (95, true), (74, false), (89, false), (3, false), (1, false), (66, true)], [123, 213]⟩
  , ⟨[(87, false), (74, false), (7, false), (12, false), (78, true), (1, false), (92, false), (95, true)], [315, 128, 91, 165]⟩
  , ⟨[(3, false), (74, false), (49, false), (12, false), (29, true), (90, true), (51, false), (95, true), (1, false), (87, true)], [68, 214, 316, 277, 271]⟩
  , ⟨[(82, false), (95, true), (7, false), (37, true), (1, false), (57, true), (49, false), (12, false), (29, true), (90, true), (51, false), (78, true), (92, false), (53, false), (47, false)], [312, 317, 318, 100, 223, 72]⟩
  , ⟨[(74, false), (95, true), (37, true), (49, false), (12, false), (92, false), (78, true), (29, true), (57, true), (90, true), (7, false), (51, false), (1, false), (82, true)], [317, 318, 100, 240, 72]⟩
  , ⟨[(95, true), (51, false), (53, false), (1, false), (47, false), (37, true), (49, false), (12, false), (92, false), (78, true), (29, true), (57, true), (90, true), (7, false)], [319, 320, 311, 285, 90, 2]⟩
  , ⟨[(51, false), (44, false), (14, false), (1, false), (92, false), (12, false), (75, false), (37, true), (43, true), (53, false), (47, false), (49, false), (78, true), (29, true), (57, true), (90, true), (7, false)], [321, 151, 307, 290, 32, 60, 139]⟩
  , ⟨[(95, false), (70, true), (44, false), (62, false), (1, false), (92, false)], [94, 32, 196, 60, 139]⟩
  , ⟨[(74, true), (53, false), (95, true), (1, false), (89, false), (51, false), (47, false)], [311, 312, 2, 285]⟩
  , ⟨[(37, true), (90, true), (92, false), (95, true), (51, false), (47, false), (74, false), (53, false), (82, true), (12, false), (78, true), (7, false), (49, false), (29, true), (1, false)], [317, 318, 321, 61, 72, 240]⟩
  , ⟨[(90, true), (29, true), (92, false), (44, false), (95, true), (51, false), (47, false), (74, false), (53, false), (82, true), (12, false), (78, true), (7, false), (49, false), (1, false)], [317, 318, 325, 226, 248, 155, 207]⟩
  , ⟨[(3, true), (37, false), (44, false), (74, false), (1, false), (87, true), (92, false), (95, true)], [226, 248, 155, 207]⟩
  , ⟨[(3, false), (29, true), (95, true), (89, false), (51, false), (74, false), (12, false), (87, true), (49, false), (1, false), (90, false)], [214, 316, 277, 199]⟩
  , ⟨[(60, false), (3, true), (95, true), (74, false), (82, true), (87, true), (7, false), (1, false), (37, true)], [72, 240]⟩
  , ⟨[(3, true), (7, false), (92, false), (44, false), (95, true), (74, false), (82, true), (1, false), (87, true)], [327, 329, 100, 61]⟩
  , ⟨[(29, true), (49, false), (92, false), (44, false), (95, true), (89, false), (51, false), (47, false), (53, false), (82, true), (12, false), (78, true), (7, false), (1, false)], [324, 317, 330, 326, 328]⟩
  , ⟨[(49, false), (7, false), (92, false), (44, false), (95, true), (70, true), (89, false), (51, false), (47, false), (53, false), (82, true), (12, false), (78, true), (1, false)], [324, 317, 330, 331, 220, 316, 277, 199, 271]⟩
  , ⟨[(54, false), (87, true), (95, true), (89, false), (74, false), (12, false), (1, false), (3, false)], [316, 159, 199, 271]⟩
  , ⟨[(7, false), (78, true), (92, false), (44, false), (95, true), (70, true), (89, false), (74, false), (82, true), (12, false), (1, false)], [317, 330, 333, 214, 220]⟩
  , ⟨[(3, false), (87, true), (95, true), (70, true), (89, false), (74, false), (12, false), (1, false)], [333, 214, 220]⟩
  , ⟨[(60, false), (87, true), (95, true), (74, false), (82, true), (7, true), (1, false), (3, true), (37, true)], [240, 107, 206]⟩
  , ⟨[(87, true), (7, true), (92, false), (44, false), (95, true), (70, true), (89, false), (74, false), (82, true), (12, false), (1, false)], [335, 327, 336, 100, 61]⟩
  , ⟨[(7, true), (12, false), (92, false), (44, false), (95, true), (70, true), (89, false), (74, false), (82, true), (1, false)], [337, 49, 153]⟩
  , ⟨[(12, false), (82, true), (92, false), (44, false), (95, true), (70, true), (89, false), (51, false), (74, false), (53, false), (1, false)], [338, 334, 31, 335, 330]⟩
  , ⟨[(7, true), (12, false), (95, true), (74, false), (1, false), (87, false)], [49, 153]⟩
  , ⟨[(12, false), (53, false), (1, false), (92, false), (95, true), (70, true), (89, false), (51, false), (3, false), (74, false)], [335, 340, 31, 317]⟩
  , ⟨[(60, true), (87, false), (62, false), (95, true), (12, true), (74, false), (1, false)], [19, 42, 89]⟩
  , ⟨[(93, false), (87, false), (95, true), (12, true), (74, false), (53, false), (1, false), (60, false)], [259, 43, 242]⟩
  , ⟨[(17, false), (87, false), (95, true), (12, true), (74, false), (1, false), (60, false), (93, true)], [148, 171]⟩
  , ⟨[(87, false), (53, false), (62, false), (95, true), (1, false), (74, false), (12, true)], [342, 343, 344, 217, 1, 141]⟩
  , ⟨[(54, false), (74, false), (1, false), (95, true), (89, false), (3, false), (12, true), (87, true)], [316, 241, 159]⟩
  , ⟨[(53, false), (47, false), (1, false), (92, false), (62, false), (95, true), (70, true), (89, false), (51, false), (3, false)], [324, 341, 345, 346, 214, 220]⟩
  , ⟨[(87, true), (12, true), (1, false), (95, true), (70, true), (89, false), (74, false), (3, false)], [346, 214, 220]⟩
  , ⟨[(5, false), (58, true), (95, true), (53, true), (74, false), (60, false), (87, false), (12, true), (17, true), (93, true), (1, false)], [230, 262]⟩
  , ⟨[(5, true), (24, true), (95, true), (53, true), (74, false), (60, false), (87, false), (12, true), (17, true), (93, true), (1, false)], [33, 231]⟩
  , ⟨[(5, false), (93, true), (95, true), (53, true), (74, false), (60, false), (87, false), (12, true), (17, true), (1, false)], [230, 349, 154, 118]⟩
  , ⟨[(93, true), (17, true), (95, true), (53, true), (74, false), (60, false), (87, false), (12, true), (1, false)], [351, 33, 209, 231]⟩
  , ⟨[(93, false), (12, true), (95, true), (53, true), (74, false), (1, false), (87, false), (60, false)], [259, 51]⟩
  , ⟨[(12, true), (74, false), (1, false), (62, false), (95, true), (70, true), (89, false), (53, true), (3, false)], [348, 342, 353, 344, 352]⟩
  , ⟨[(74, false), (53, true), (1, false), (92, false), (62, false), (95, true), (70, true), (89, false), (51, false), (3, false)], [354, 335, 340, 317, 176]⟩
  , ⟨[(87, false), (12, false), (1, false), (74, false), (92, false), (95, true)], [340, 317, 215, 176, 31]⟩
  , ⟨[(60, false), (7, false), (1, false), (95, true), (74, false), (37, true), (87, true), (82, false), (3, true)], [72, 223]⟩
  , ⟨[(60, true), (87, true), (1, false), (95, true), (74, false), (3, true), (37, true)], [100, 61]⟩
  , ⟨[(7, false), (87, true), (1, false), (92, false), (44, false), (95, true), (74, false), (3, true)], [327, 358, 330, 357]⟩
  , ⟨[(12, false), (74, false), (1, false), (92, false), (44, false), (95, true), (70, true), (89, false), (3, true)], [356, 327, 358, 359, 338, 223, 107, 206]⟩
  , ⟨[(87, true), (74, false), (3, true), (1, false), (95, true), (92, false), (44, false)], [327, 358, 359, 336, 223, 107, 206]⟩
  , ⟨[(74, false), (89, false), (1, false), (92, false), (44, false), (62, false), (70, true), (3, true)], [323, 360, 361, 342, 345, 353, 344, 352]⟩
  , ⟨[(61, true), (33, true), (27, false), (53, true), (20, false), (74, true), (95, true), (9, false), (1, false), (60, false), (35, false), (66, false), (78, false)], [247, 102, 74, 70]⟩
  , ⟨[(61, false), (20, false), (1, false), (53, true), (74, true), (95, true), (44, false)], [218, 274, 212]⟩
  , ⟨[(80, false), (23, true), (95, true), (74, true), (53, true), (61, true), (20, false), (27, false), (1, false)], [102, 70]⟩
  , ⟨[(80, true), (9, false), (95, true), (74, true), (53, true), (78, false), (61, true), (20, false), (66, false), (1, false), (33, false)], [82, 8, 194]⟩
  , ⟨[(80, false), (27, false), (95, true), (74, true), (53, true), (61, true), (20, false), (1, false)], [102, 365, 74]⟩
  , ⟨[(9, false), (27, false), (95, true), (74, true), (60, false), (53, true), (78, false), (61, true), (20, false), (66, false), (1, false)], [367, 366, 119, 363]⟩
  , ⟨[(40, false), (80, true), (95, true), (74, true), (53, true), (78, false), (61, true), (20, false), (1, false), (9, true)], [125, 192, 115]⟩
  , ⟨[(27, false), (66, false), (95, true), (74, true), (60, false), (53, true), (93, true), (78, false), (61, true), (20, false), (1, false)], [367, 368, 369, 38, 131]⟩
  , ⟨[(9, true), (80, true), (95, true), (74, true), (53, true), (93, true), (78, false), (61, true), (20, false), (1, false)], [369, 38, 131]⟩
  , ⟨[(80, true), (66, false), (95, true), (74, true), (60, false), (53, true), (93, true), (78, false), (61, true), (20, false), (1, false)], [371, 366, 119, 247]⟩
  , ⟨[(66, false), (20, false), (95, true), (74, true), (60, false), (53, true), (93, true), (78, false), (1, false), (61, true)], [370, 372, 46, 195]⟩
  , ⟨[(76, true), (1, true), (6, false), (37, true), (28, true)], [117, 112]⟩
  , ⟨[(14, false), (6, true), (1, true), (37, true), (77, false)], [169, 65]⟩
  , ⟨[(20, true), (1, false), (51, false), (74, true), (79, false), (95, true)], [22, 311]⟩
  , ⟨[(76, true), (47, true), (1, true), (37, false), (83, false), (92, true)], [127, 109]⟩
  , ⟨[(28, false), (6, true), (1, true), (37, true), (38, false), (77, true)], [132, 219]⟩
  , ⟨[(43, true), (1, true), (17, false), (37, false), (47, false), (71, true)], [133, 88]⟩
  , ⟨[(92, true), (1, false), (12, false), (44, false), (62, false), (95, false)], [156, 36]⟩
  , ⟨[(82, true), (1, false), (92, false), (44, false), (62, false), (95, false)], [160, 323]⟩
  , ⟨[(75, true), (1, false), (44, false), (62, false), (92, true), (95, false)], [29, 380]⟩
  , ⟨[(37, true), (1, false), (44, false), (51, false), (62, true), (95, false)], [30, 151]⟩
  , ⟨[(62, true), (1, false), (37, true), (44, false), (51, true), (95, false)], [181, 95]⟩
  , ⟨[(20, true), (1, false), (51, true), (55, true), (74, true), (95, true)], [193, 191]⟩
  , ⟨[(15, true), (16, true), (1, false), (3, false), (44, true), (95, false)], [221, 137]⟩
  , ⟨[(26, false), (44, true), (1, false), (16, false), (36, true), (95, false)], [227, 224]⟩
  , ⟨[(9, true), (6, false), (1, true), (28, true), (37, true), (76, false)], [229, 23]⟩
  , ⟨[(27, true), (1, true), (37, false), (47, true), (83, true), (92, true)], [14, 265]⟩
  , ⟨[(36, true), (16, false), (1, false), (26, true), (44, true), (95, false)], [261, 25]⟩
  , ⟨[(12, true), (1, true), (2, false), (37, false), (47, true), (92, false)], [71, 138]⟩
  , ⟨[(70, false), (1, false), (92, false), (44, false), (62, false), (95, false)], [77, 381]⟩
  , ⟨[(95, false), (70, false), (44, false), (62, false), (1, false), (75, false)], [307, 36]⟩
  , ⟨[(37, false), (47, true), (1, true), (12, false), (75, true), (92, false)], [80, 108]⟩
  , ⟨[(76, false), (1, true), (9, false), (6, false), (37, true), (28, true)], [84, 66]⟩
  , ⟨[(64, true), (44, true), (1, false), (16, false), (36, false), (95, false)], [34, 48]⟩
  , ⟨[(51, true), (87, true), (1, false), (3, false), (74, false), (89, true), (95, true)], [172, 24]⟩
  , ⟨[(13, true), (6, true), (1, true), (28, false), (37, true), (38, true), (77, true)], [27, 219]⟩
  , ⟨[(14, true), (6, true), (1, true), (7, false), (37, true), (42, true), (77, false)], [97, 15]⟩
  , ⟨[(37, false), (5, true), (1, true), (19, false), (47, true), (83, true), (92, true)], [99, 389]⟩
  , ⟨[(38, true), (20, true), (1, false), (51, true), (55, false), (74, true), (95, true)], [103, 255]⟩
  , ⟨[(6, true), (1, true), (28, false), (37, true), (38, true), (59, false), (77, true)], [129, 398]⟩
  , ⟨[(37, false), (17, true), (1, true), (43, true), (47, false), (65, false), (71, true)], [39, 12]⟩
  , ⟨[(37, false), (1, true), (6, false), (22, false), (47, false), (49, true), (71, false)], [41, 237]⟩
  , ⟨[(28, true), (6, true), (1, true), (37, true), (54, false), (70, true), (77, true)], [146, 98]⟩
  , ⟨[(38, true), (1, false), (12, true), (74, false), (60, true), (87, false), (95, true)], [42, 89]⟩
  , ⟨[(14, true), (28, false), (1, true), (6, false), (37, true), (48, true), (54, true)], [162, 110]⟩
  , ⟨[(44, true), (16, true), (1, false), (13, false), (15, false), (53, true), (95, false)], [166, 158]⟩
  , ⟨[(38, false), (20, true), (1, false), (51, true), (55, false), (74, true), (95, true)], [167, 255]⟩
  , ⟨[(38, false), (60, true), (1, false), (12, true), (74, false), (87, false), (95, true)], [177, 342]⟩
  , ⟨[(28, true), (6, true), (1, true), (37, true), (54, true), (70, true), (77, true)], [182, 126]⟩
  , ⟨[(20, false), (1, false), (82, false), (53, false), (74, true), (89, false), (95, true)], [188, 285]⟩
  , ⟨[(15, true), (1, false), (3, true), (16, true), (44, true), (64, false), (95, false)], [189, 64]⟩
  , ⟨[(11, true), (1, true), (2, true), (12, true), (37, false), (47, true), (92, false)], [200, 138]⟩
  , ⟨[(33, true), (1, true), (6, false), (14, false), (28, false), (37, true), (48, true)], [201, 110]⟩
  , ⟨[(5, true), (1, true), (27, false), (37, false), (47, true), (83, true), (92, true)], [202, 400]⟩
  , ⟨[(28, false), (1, true), (6, false), (37, true), (42, false), (48, false), (52, true)], [204, 299]⟩
  , ⟨[(7, true), (1, true), (37, false), (47, true), (76, false), (83, false), (92, true)], [216, 244]⟩
  , ⟨[(28, true), (6, true), (1, true), (37, true), (70, false), (77, true), (95, true)], [233, 208]⟩
  , ⟨[(17, true), (1, true), (37, false), (43, true), (47, false), (65, true), (71, true)], [59, 101]⟩
  , ⟨[(47, true), (63, true), (1, true), (12, false), (37, false), (75, false), (92, false)], [245, 135]⟩
  , ⟨[(64, false), (44, true), (1, false), (16, false), (36, false), (80, true), (95, false)], [249, 93]⟩
  , ⟨[(47, true), (1, true), (7, false), (37, false), (76, false), (83, false), (92, true)], [260, 244]⟩
  , ⟨[(6, true), (1, true), (14, true), (27, true), (37, true), (42, true), (77, false)], [62, 399]⟩
  , ⟨[(22, true), (6, true), (1, true), (23, true), (37, false), (47, false), (71, false)], [269, 50]⟩
  , ⟨[(6, false), (1, true), (2, true), (22, true), (37, false), (47, false), (71, false)], [272, 120]⟩
  , ⟨[(22, true), (6, true), (1, true), (23, false), (37, false), (47, false), (71, false)], [273, 50]⟩
  , ⟨[(61, false), (1, false), (53, true), (20, false), (74, true), (91, true), (95, true)], [274, 212]⟩
  , ⟨[(71, true), (78, false), (1, true), (9, false), (37, false), (43, false), (47, false)], [67, 10]⟩
  , ⟨[(89, true), (87, true), (1, false), (3, false), (51, false), (74, false), (95, true)], [68, 24]⟩
  , ⟨[(14, true), (6, true), (1, true), (37, true), (42, false), (52, true), (77, false)], [69, 134]⟩
  , ⟨[(17, false), (1, true), (37, false), (43, false), (47, false), (71, true), (78, false)], [73, 429]⟩
  , ⟨[(47, true), (12, false), (92, false), (75, false), (37, false), (1, true), (36, true)], [302, 135]⟩
  , ⟨[(78, true), (74, false), (12, false), (87, false), (1, false), (92, false), (95, true)], [317, 340]⟩
  , ⟨[(64, false), (44, true), (1, false), (16, false), (36, false), (80, false), (95, false)], [6, 93]⟩
  , ⟨[(53, false), (1, false), (20, false), (74, true), (82, true), (89, false), (95, true)], [2, 285]⟩
  , ⟨[(54, false), (87, true), (1, false), (95, true), (89, false), (3, false), (74, false)], [346, 333]⟩
  , ⟨[(87, true), (1, false), (95, true), (70, true), (89, false), (74, false), (3, false)], [348, 335]⟩
  , ⟨[(93, false), (95, true), (12, true), (74, false), (1, false), (87, false), (60, false)], [353, 343]⟩
  , ⟨[(9, true), (19, true), (1, false), (7, false), (12, false), (74, false), (87, false), (95, true)], [52, 356]⟩
  , ⟨[(62, true), (65, false), (1, false), (10, false), (32, false), (37, false), (44, false), (95, false)], [232, 143]⟩
  , ⟨[(48, false), (39, true), (1, true), (6, false), (14, false), (28, false), (37, true), (42, false)], [105, 297]⟩
  , ⟨[(14, true), (28, false), (1, true), (6, false), (37, true), (48, true), (54, false), (74, false)], [234, 110]⟩
  , ⟨[(15, true), (1, false), (3, true), (16, true), (26, false), (44, true), (64, true), (95, false)], [114, 64]⟩
  , ⟨[(26, false), (82, true), (1, false), (3, true), (74, false), (37, true), (87, true), (95, true)], [240, 358]⟩
  , ⟨[(1, true), (2, true), (12, true), (36, true), (37, false), (47, true), (54, false), (92, false)], [243, 414]⟩
  , ⟨[(10, true), (6, true), (1, true), (14, true), (37, true), (42, false), (52, false), (77, false)], [4, 92]⟩
  , ⟨[(24, false), (37, false), (1, false), (3, true), (44, false), (74, false), (87, true), (95, true)], [248, 226]⟩
  , ⟨[(36, false), (47, true), (1, true), (29, false), (63, false), (37, false), (75, false), (92, false)], [252, 138]⟩
  , ⟨[(15, false), (13, true), (1, false), (16, true), (30, false), (44, true), (54, true), (95, false)], [256, 104]⟩
  , ⟨[(62, true), (65, true), (1, false), (10, false), (32, false), (37, false), (44, false), (95, false)], [257, 143]⟩
  , ⟨[(37, false), (44, true), (1, false), (3, true), (64, false), (74, false), (87, true), (95, true)], [258, 226]⟩
  , ⟨[(15, false), (13, true), (1, false), (16, true), (37, false), (44, true), (54, false), (95, false)], [136, 185]⟩
  , ⟨[(10, false), (6, true), (1, true), (14, true), (37, true), (42, false), (52, false), (77, false)], [179, 92]⟩
  , ⟨[(61, true), (1, false), (53, true), (20, false), (74, true), (78, true), (80, true), (95, true)], [116, 175]⟩
  , ⟨[(37, false), (44, true), (1, false), (3, true), (64, true), (74, false), (87, true), (95, true)], [263, 226]⟩
  , ⟨[(23, true), (10, true), (1, false), (37, false), (44, false), (60, false), (62, true), (95, false)], [267, 145]⟩
  , ⟨[(48, false), (1, true), (6, false), (14, false), (28, false), (37, true), (42, false), (39, false)], [140, 297]⟩
  , ⟨[(87, false), (1, false), (7, false), (12, false), (19, false), (69, false), (74, false), (95, true)], [106, 356]⟩
  , ⟨[(1, true), (2, true), (12, true), (36, true), (37, false), (47, true), (54, true), (92, false)], [144, 414]⟩
  , ⟨[(93, false), (1, false), (53, true), (12, true), (74, false), (87, false), (60, false), (95, true)], [51, 259]⟩
  , ⟨[(57, true), (1, true), (22, false), (37, false), (49, false), (71, false), (47, false), (61, true)], [56, 295]⟩
  , ⟨[(32, true), (1, false), (10, false), (16, false), (44, false), (37, false), (62, true), (95, false)], [58, 5]⟩
  , ⟨[(15, false), (16, true), (1, false), (13, false), (41, false), (44, true), (79, false), (95, false)], [28, 408]⟩
  , ⟨[(26, true), (7, false), (1, false), (37, true), (3, true), (74, false), (87, true), (95, true)], [72, 358]⟩
  , ⟨[(37, false), (9, true), (1, true), (43, false), (47, false), (71, true), (78, true), (83, true)], [203, 291]⟩
  , ⟨[(22, false), (6, true), (1, true), (37, false), (47, false), (49, true), (71, false), (79, true)], [149, 237]⟩
  , ⟨[(47, true), (1, true), (12, false), (29, false), (37, false), (63, false), (75, false), (92, false)], [76, 449]⟩
  , ⟨[(61, true), (57, false), (1, true), (22, false), (37, false), (49, false), (71, false), (47, false)], [13, 295]⟩
  , ⟨[(85, false), (80, false), (1, false), (53, true), (20, false), (74, true), (61, true), (95, true)], [46, 367]⟩
  , ⟨[(15, false), (13, true), (1, false), (16, true), (30, true), (44, true), (54, true), (95, false)], [210, 104]⟩
  , ⟨[(27, false), (54, false), (1, false), (89, false), (3, false), (87, true), (74, false), (95, true)], [159, 316]⟩
  , ⟨[(82, true), (7, false), (95, true), (74, false), (87, true), (3, true), (1, false), (37, true)], [329, 358]⟩
  , ⟨[(19, true), (87, false), (1, false), (7, false), (12, false), (74, false), (92, true), (95, true)], [47, 440]⟩
  , ⟨[(82, true), (95, true), (74, false), (60, false), (87, true), (1, false), (3, true), (37, true)], [336, 473]⟩
  , ⟨[(10, true), (46, false), (1, false), (44, false), (37, false), (60, true), (62, true), (95, false)], [161, 251]⟩
  , ⟨[(53, true), (1, false), (20, false), (61, false), (68, true), (74, true), (91, false), (95, true)], [53, 364]⟩
  , ⟨[(10, true), (46, true), (1, false), (44, false), (37, false), (60, true), (62, true), (95, false)], [83, 251]⟩
  , ⟨[(54, true), (1, false), (3, false), (70, true), (74, false), (87, true), (89, false), (95, true)], [220, 214]⟩
  , ⟨[(26, false), (1, false), (37, true), (60, false), (74, false), (3, true), (87, true), (95, true)], [223, 445]⟩
  , ⟨[(93, true), (95, true), (53, true), (74, false), (60, false), (87, false), (12, true), (1, false)], [352, 344]⟩
  , ⟨[(15, false), (13, true), (1, false), (16, true), (17, false), (44, true), (54, false), (95, false)], [55, 453]⟩
  , ⟨[(7, false), (1, false), (95, true), (74, false), (37, true), (87, true), (60, false), (3, true)], [357, 473]⟩
  , ⟨[(53, true), (1, false), (20, false), (61, false), (68, false), (74, true), (91, false), (95, true)], [225, 364]⟩
  , ⟨[(80, false), (1, false), (53, true), (20, false), (74, true), (61, true), (27, true), (95, true)], [195, 470]⟩
  , ⟨[(54, true), (29, false), (1, false), (2, false), (3, false), (74, false), (87, true), (89, false), (95, true)], [211, 479]⟩
  , ⟨[(10, true), (1, false), (35, false), (37, false), (42, true), (44, false), (60, false), (62, true), (95, false)], [57, 457]⟩
  , ⟨[(14, true), (28, false), (1, true), (6, false), (37, true), (43, true), (48, true), (54, false), (74, true)], [168, 110]⟩
  , ⟨[(28, true), (6, true), (1, true), (12, false), (37, true), (70, false), (77, true), (86, true), (95, false)], [170, 86]⟩
  , ⟨[(19, false), (26, true), (1, false), (3, true), (37, true), (60, false), (74, false), (87, true), (95, true)], [107, 465]⟩
  , ⟨[(4, false), (35, false), (1, false), (12, true), (60, false), (74, false), (87, false), (93, false), (95, true)], [242, 461]⟩
  , ⟨[(4, true), (15, true), (1, false), (7, true), (3, true), (16, true), (44, true), (64, true), (95, false)], [40, 444]⟩
  , ⟨[(22, false), (6, true), (1, true), (37, false), (47, false), (49, true), (71, false), (79, false), (93, true)], [253, 237]⟩
  , ⟨[(22, true), (1, true), (2, false), (6, false), (37, false), (47, false), (48, false), (70, false), (71, false)], [184, 113]⟩
  , ⟨[(33, true), (43, false), (1, true), (9, false), (37, false), (47, false), (71, true), (78, true), (83, true)], [186, 291]⟩
  , ⟨[(12, true), (6, true), (1, true), (24, true), (28, true), (37, true), (70, false), (77, true), (95, false)], [264, 86]⟩
  , ⟨[(54, true), (29, false), (2, true), (1, false), (3, false), (74, false), (87, true), (89, false), (95, true)], [266, 479]⟩
  , ⟨[(43, false), (71, true), (1, true), (9, false), (37, false), (47, false), (53, true), (78, true), (83, true)], [163, 495]⟩
  , ⟨[(22, false), (6, true), (1, true), (37, false), (47, false), (49, true), (71, false), (79, false), (93, false)], [121, 237]⟩
  , ⟨[(10, true), (1, false), (23, false), (37, false), (42, true), (44, false), (60, false), (62, true), (95, false)], [197, 487]⟩
  , ⟨[(87, false), (1, false), (7, false), (9, false), (12, false), (19, false), (69, true), (74, false), (95, true)], [20, 356]⟩
  , ⟨[(32, true), (16, true), (1, false), (5, false), (10, false), (37, false), (44, false), (62, true), (95, false)], [147, 180]⟩
  , ⟨[(32, false), (22, true), (1, true), (2, false), (6, false), (37, false), (47, false), (48, false), (71, false)], [124, 494]⟩
  , ⟨[(4, true), (15, true), (1, false), (7, false), (3, true), (16, true), (44, true), (64, true), (95, false)], [78, 444]⟩
  , ⟨[(4, false), (35, true), (1, false), (12, true), (60, false), (74, false), (87, false), (93, false), (95, true)], [43, 461]⟩
  , ⟨[(26, true), (1, false), (7, true), (3, true), (37, true), (60, false), (74, false), (87, true), (95, true)], [206, 490]⟩
  , ⟨[(6, false), (1, true), (10, false), (14, false), (28, false), (33, false), (37, true), (48, true), (83, false)], [44, 304]⟩
  , ⟨[(14, true), (28, false), (1, true), (6, false), (37, true), (43, false), (48, true), (54, false), (74, true)], [45, 110]⟩
  , ⟨[(9, true), (69, true), (1, false), (7, false), (12, false), (19, false), (74, false), (87, false), (95, true)], [96, 356]⟩
  , ⟨[(93, true), (85, true), (1, false), (53, false), (12, true), (74, false), (60, false), (87, false), (95, true)], [217, 344]⟩
  , ⟨[(41, true), (16, true), (1, false), (13, false), (15, false), (44, true), (79, false), (80, true), (95, false)], [130, 408]⟩
  , ⟨[(41, true), (16, true), (1, false), (13, false), (15, false), (44, true), (53, false), (79, false), (95, false)], [87, 511]⟩
  , ⟨[(28, true), (6, true), (1, true), (12, false), (37, true), (70, false), (77, true), (86, false), (95, false)], [270, 86]⟩
  , ⟨[(5, false), (77, false), (1, false), (12, true), (53, true), (60, false), (74, false), (17, true), (87, false), (95, true)], [230, 439]⟩
  , ⟨[(66, false), (1, false), (3, false), (12, false), (54, false), (74, false), (87, true), (89, false), (90, true), (95, true)], [271, 472]⟩
  , ⟨[(9, true), (6, false), (1, true), (14, false), (18, true), (28, false), (33, false), (37, true), (48, true), (83, false)], [18, 507]⟩
  , ⟨[(10, false), (16, true), (1, false), (5, true), (17, true), (32, true), (37, false), (44, false), (62, true), (95, false)], [246, 142]⟩
  , ⟨[(27, true), (1, false), (3, false), (12, false), (54, false), (74, false), (87, true), (89, false), (66, false), (95, true)], [199, 515]⟩
  , ⟨[(94, false), (5, true), (1, false), (12, true), (53, true), (60, false), (74, false), (87, false), (17, true), (95, true)], [33, 439]⟩
  , ⟨[(6, false), (22, true), (1, true), (2, false), (27, true), (37, false), (47, false), (48, true), (61, true), (71, false)], [235, 113]⟩
  , ⟨[(12, true), (6, true), (1, true), (28, true), (37, true), (39, true), (50, false), (70, false), (77, true), (95, false)], [16, 496]⟩
  , ⟨[(73, true), (1, false), (3, true), (44, false), (71, false), (37, false), (74, false), (87, true), (92, true), (95, true)], [183, 448]⟩
  , ⟨[(37, false), (1, false), (3, true), (44, false), (71, false), (74, false), (79, false), (87, true), (92, false), (95, true)], [207, 448]⟩
  , ⟨[(52, true), (1, false), (12, true), (53, false), (60, false), (74, false), (17, true), (87, false), (93, true), (95, true)], [1, 510]⟩
  , ⟨[(24, true), (1, false), (3, true), (44, false), (71, false), (74, false), (37, false), (87, true), (92, false), (95, true)], [155, 523]⟩
  , ⟨[(12, true), (6, true), (1, true), (28, true), (37, true), (39, true), (50, true), (70, false), (77, true), (95, false)], [111, 496]⟩
  , ⟨[(10, false), (16, true), (1, false), (5, true), (17, false), (32, true), (37, false), (44, false), (62, true), (95, false)], [187, 142]⟩
  , ⟨[(52, false), (1, false), (12, true), (53, false), (60, false), (74, false), (17, true), (87, false), (93, true), (95, true)], [141, 510]⟩
  , ⟨[(9, true), (6, false), (1, true), (14, false), (18, false), (28, false), (33, false), (37, true), (48, true), (83, false)], [9, 507]⟩
  , ⟨[(40, false), (46, false), (1, false), (20, false), (9, true), (53, true), (61, true), (74, true), (78, false), (80, true), (95, true)], [192, 125]⟩
  , ⟨[(22, true), (1, true), (2, false), (27, false), (6, false), (37, false), (47, false), (48, true), (64, true), (71, false), (73, false)], [236, 113]⟩
  , ⟨[(40, true), (54, false), (1, false), (20, false), (53, true), (9, true), (61, true), (74, true), (78, false), (80, true), (95, true)], [131, 164]⟩
  , ⟨[(59, false), (1, false), (20, false), (9, true), (53, true), (40, false), (61, true), (74, true), (78, false), (80, true), (95, true)], [115, 530]⟩
  , ⟨[(10, false), (1, false), (3, true), (37, false), (44, false), (71, false), (73, false), (74, false), (87, true), (92, true), (95, true)], [228, 448]⟩
  , ⟨[(24, true), (1, false), (12, true), (17, true), (53, true), (60, false), (74, false), (87, false), (93, true), (5, true), (95, true)], [231, 519]⟩
  , ⟨[(22, true), (1, true), (2, false), (27, false), (6, false), (35, false), (37, false), (47, false), (48, true), (71, false), (73, true)], [238, 113]⟩
  , ⟨[(40, true), (54, true), (1, false), (20, false), (53, true), (9, true), (61, true), (74, true), (78, false), (80, true), (95, true)], [38, 164]⟩
  , ⟨[(6, false), (22, true), (1, true), (2, false), (27, true), (37, false), (47, false), (48, true), (61, false), (66, true), (71, false)], [0, 113]⟩
  , ⟨[(58, true), (1, false), (12, true), (53, true), (17, true), (60, false), (74, false), (5, false), (87, false), (93, true), (95, true)], [262, 514]⟩
  , ⟨[(6, false), (22, true), (1, true), (2, false), (27, true), (37, false), (47, false), (48, true), (61, false), (66, false), (71, false)], [222, 113]⟩
  , ⟨[(22, true), (1, true), (2, false), (27, false), (6, false), (35, true), (37, false), (47, false), (48, true), (71, false), (73, true)], [37, 113]⟩
  , ⟨[(65, true), (1, false), (9, false), (53, true), (20, false), (61, true), (66, true), (74, true), (78, false), (80, true), (81, false), (95, true)], [35, 3]⟩
  , ⟨[(22, true), (1, true), (2, false), (27, false), (6, false), (37, false), (47, false), (48, true), (64, false), (71, false), (73, false), (80, false)], [21, 113]⟩
  , ⟨[(5, true), (1, false), (9, false), (20, false), (33, false), (53, true), (61, true), (66, false), (74, true), (78, false), (80, true), (95, true)], [194, 82]⟩
  , ⟨[(48, true), (1, false), (12, true), (17, true), (53, true), (5, false), (60, false), (74, false), (77, true), (87, false), (93, true), (95, true)], [154, 539]⟩
  , ⟨[(33, true), (35, false), (1, false), (61, true), (80, true), (53, true), (9, false), (66, false), (74, true), (78, false), (20, false), (95, true)], [247, 75]⟩
  , ⟨[(58, false), (1, false), (12, true), (17, true), (53, true), (5, false), (60, false), (74, false), (77, true), (87, false), (93, true), (95, true)], [118, 545]⟩
  , ⟨[(10, true), (1, false), (3, true), (37, false), (44, false), (71, false), (73, false), (74, false), (87, true), (89, false), (92, true), (95, true)], [157, 448]⟩
  , ⟨[(10, true), (1, false), (3, true), (37, false), (44, false), (71, false), (73, false), (74, false), (87, true), (89, true), (92, true), (95, true)], [198, 448]⟩
  , ⟨[(60, true), (61, true), (1, false), (9, false), (53, true), (20, false), (65, false), (66, true), (74, true), (78, false), (80, true), (95, true)], [17, 26]⟩
  , ⟨[(68, true), (65, false), (1, false), (9, false), (53, true), (20, false), (61, true), (66, true), (74, true), (78, false), (80, true), (95, true)], [178, 550]⟩
  , ⟨[(42, false), (1, false), (80, true), (9, false), (20, false), (33, false), (53, true), (66, false), (74, true), (78, false), (61, true), (95, true)], [8, 544]⟩
  , ⟨[(9, false), (1, false), (80, true), (33, true), (53, true), (60, false), (20, false), (61, true), (74, true), (78, false), (66, false), (95, true)], [119, 546]⟩
  , ⟨[(22, true), (1, true), (2, false), (27, false), (6, false), (37, false), (47, false), (48, true), (64, false), (71, false), (73, false), (80, true)], [63, 113]⟩
  , ⟨[(18, true), (31, true), (1, false), (20, false), (9, false), (53, true), (61, true), (65, true), (66, true), (74, true), (78, false), (80, true), (95, true)], [254, 542]⟩
  , ⟨[(31, true), (65, true), (1, false), (9, false), (18, false), (53, true), (20, false), (61, true), (66, true), (74, true), (78, false), (80, true), (95, true)], [173, 542]⟩
  , ⟨[(1, false), (37, false), (95, false), (44, false), (62, true), (60, true), (10, true)], [251, 478, 476]⟩
  , ⟨[(1, false), (37, false), (95, false), (44, false), (16, false), (62, true), (10, false)], [463, 441, 451]⟩
  , ⟨[(1, false), (37, false), (95, false), (44, false), (16, false), (62, true)], [558, 557, 145, 457, 500]⟩
  , ⟨[(1, false), (37, false), (95, false), (44, false), (16, true), (62, true), (10, false), (5, false)], [502, 441, 451]⟩
  , ⟨[(1, false), (37, false), (95, false), (44, false), (16, true), (62, true), (17, false), (10, false), (5, true)], [527, 441, 451]⟩
  , ⟨[(1, false), (37, false), (95, false), (44, false), (16, true), (62, true), (17, false), (10, false)], [561, 560, 557, 145, 457, 500]⟩
  , ⟨[(1, false), (37, false), (95, false), (44, false), (16, true), (62, true), (17, false)], [562, 557, 145, 457, 500]⟩
  , ⟨[(1, false), (37, false), (95, false), (44, false), (16, true), (62, true), (17, true), (10, false), (5, true)], [517, 441, 451]⟩
  , ⟨[(1, false), (37, false), (95, false), (44, false), (16, true), (62, true), (17, true), (10, false)], [564, 560, 557, 145, 457, 500]⟩
  , ⟨[(1, false), (37, false), (95, false), (44, false), (16, true), (62, true), (17, true)], [565, 557, 145, 457, 500]⟩
  , ⟨[(1, false), (37, false), (95, false), (44, false), (16, true), (62, true), (89, false), (10, false), (5, true)], [142, 441, 451]⟩
  , ⟨[(1, false), (37, false), (95, false), (44, false), (16, true), (62, true)], [563, 566, 567]⟩
  , ⟨[(1, false), (37, false), (95, false), (44, false), (62, true)], [559, 563, 566, 143]⟩
  , ⟨[(1, false), (95, false), (44, true), (16, true), (54, false), (15, false), (13, true)], [453, 185, 482]⟩
  , ⟨[(1, false), (95, false), (44, false), (62, false), (92, true)], [380, 36, 382]⟩
  , ⟨[(1, false), (95, false), (44, false), (92, false), (62, false)], [392, 323, 569, 383, 384]⟩
  , ⟨[(1, false), (95, false), (44, false), (92, false)], [572, 569, 383, 384]⟩
  , ⟨[(1, false), (95, false), (44, false)], [573, 571, 569, 383, 384]⟩
  , ⟨[(1, false), (95, false), (44, true), (3, true), (16, true), (15, true)], [64, 413, 492, 504]⟩
  , ⟨[(1, false), (95, false), (44, true), (16, false), (36, false)], [396, 574, 422, 435]⟩
  , ⟨[(1, false), (95, false), (44, true), (16, false)], [576, 574, 390, 387]⟩
  , ⟨[(1, false), (95, false), (16, true), (15, false), (79, false), (13, false)], [574, 464, 408, 512, 511]⟩
  , ⟨[(1, false), (95, false), (15, false), (79, false), (13, false)], [578, 574, 577, 464, 408, 512]⟩
  , ⟨[(1, false), (95, false), (44, true), (16, true), (15, false), (79, true)], [158, 574, 577, 570, 471, 450]⟩
  , ⟨[(1, false), (95, false), (44, true), (16, true), (15, false)], [580, 574, 577, 579, 570, 471, 450]⟩
  , ⟨[(1, false), (95, false), (44, true), (16, true)], [581, 574, 577, 386, 575]⟩
  , ⟨[(1, false), (95, true), (37, false), (74, false), (44, false), (87, true), (3, true)], [448, 361, 226, 522, 534, 548, 549]⟩
  , ⟨[(1, false), (95, true), (37, false), (74, false), (44, true), (87, true), (3, true)], [456, 452]⟩
  , ⟨[(1, false), (95, true), (37, true), (74, false), (87, true), (3, true)], [358, 480, 506, 483, 465]⟩
  , ⟨[(1, false), (95, true), (74, true), (20, false), (53, true), (61, false)], [364, 428, 477, 484]⟩
  , ⟨[(1, false), (95, true), (74, true), (51, false), (20, true)], [311, 174, 376]⟩
  , ⟨[(1, false), (95, true), (74, false), (12, false), (87, false)], [356, 340, 474, 459, 509, 501, 440]⟩
  , ⟨[(1, false), (95, true), (74, false), (87, false), (60, true)], [588, 410, 406, 342]⟩
  , ⟨[(1, false), (95, true), (74, false), (87, false)], [588, 589, 439, 344, 481, 524, 528, 510]⟩
  , ⟨[(1, false), (95, true), (74, false), (87, true), (3, false), (51, false)], [430, 590, 437, 214, 486, 497]⟩
  , ⟨[(1, false), (95, true), (74, false), (87, true), (3, false)], [591, 590, 397, 437, 214, 486, 497]⟩
  , ⟨[(1, false), (95, true), (74, false), (87, true)], [592, 590, 585, 584, 583]⟩
  , ⟨[(1, false), (95, true), (74, false), (87, true), (3, false), (51, true)], [397, 590, 437, 214, 486, 497]⟩
  , ⟨[(1, false), (95, true), (74, true), (20, false), (53, false)], [285, 90, 436, 412]⟩
  , ⟨[(1, false), (95, true), (74, true), (20, false), (9, false), (78, false), (80, true), (65, false), (66, true)], [595, 586, 26, 551, 550]⟩
  , ⟨[(1, false), (95, true), (74, true), (20, false), (53, true), (9, false), (60, true), (61, true), (78, false), (80, true), (66, false)], [75, 595, 586, 366, 596, 3, 555, 556]⟩
  , ⟨[(1, false), (95, true), (74, true), (20, false), (53, true), (9, false), (60, true), (61, true), (78, false), (80, true)], [597, 595, 586, 596, 3, 555, 556]⟩
  , ⟨[(1, false), (95, true), (74, true), (20, false), (53, true), (9, false), (60, true), (61, true), (78, false)], [598, 595, 586, 485, 367]⟩
  , ⟨[(1, false), (95, true), (74, true), (20, false), (53, true), (9, false), (60, true), (61, true)], [599, 595, 586, 455, 485, 367]⟩
  , ⟨[(1, false), (95, true), (74, true), (20, false), (53, true), (9, false), (61, true), (78, false), (18, false), (80, true), (65, true), (31, true)], [556, 595, 586, 600, 366, 553]⟩
  , ⟨[(1, false), (95, true), (74, true), (20, false), (53, true), (9, false), (61, true), (78, false), (80, true), (65, true), (66, true)], [3, 595, 586, 555, 601]⟩
  , ⟨[(1, false), (95, true), (74, true), (20, false), (53, true), (9, false), (61, true), (78, false), (80, true), (65, true)], [602, 595, 586, 600, 366, 553]⟩
  , ⟨[(1, false), (95, true), (74, true), (20, false), (53, true), (9, false), (61, true), (78, false), (80, true)], [603, 595, 586, 600, 596, 366, 553]⟩
  , ⟨[(1, false), (95, true), (74, true), (20, false), (53, true), (9, false), (61, true), (78, false)], [604, 595, 586, 485, 367]⟩
  , ⟨[(1, false), (95, true), (74, true), (20, false), (9, true), (78, false), (80, true)], [595, 586, 369, 532, 537, 164]⟩
  , ⟨[(1, false), (95, true), (74, true), (20, false), (53, true), (61, true), (27, false)], [367, 595, 586, 455, 605, 606]⟩
  , ⟨[(1, false), (95, true), (74, true), (20, false), (53, true), (61, true)], [607, 595, 586, 485, 455, 605, 606]⟩
  , ⟨[(1, false), (95, true), (74, true), (20, false), (53, true), (61, true), (27, true)], [485, 595, 586, 455, 605, 606]⟩
  , ⟨[(1, false), (95, true), (74, true), (20, true)], [587, 385, 401, 409, 255]⟩
  , ⟨[(1, true), (37, false), (6, false), (47, false), (71, false), (22, false)], [404, 237, 462, 469]⟩
  , ⟨[(1, true), (37, false), (6, false), (47, false), (71, false), (48, true), (22, true), (27, false), (2, false), (35, false)], [536, 426, 531, 543, 554]⟩
  , ⟨[(1, true), (37, false), (6, false), (47, false), (71, false), (48, true), (22, true), (27, false), (2, false)], [612, 611, 426, 113, 503, 541, 531, 543, 554]⟩
  , ⟨[(1, true), (37, false), (6, false), (47, false), (71, false), (48, true), (22, true), (27, false), (2, false), (35, true)], [541, 611, 426, 113, 503, 531, 543, 554]⟩
  , ⟨[(1, true), (37, false), (6, false), (47, false), (71, false)], [611, 426, 113, 503, 613, 520, 538, 540, 494]⟩
  , ⟨[(1, true), (37, false), (47, false), (6, true), (71, false), (22, true)], [50, 425, 427]⟩
  , ⟨[(1, true), (37, false), (47, false), (6, true), (71, false), (22, false), (79, false), (49, true)], [493, 616, 237, 499, 462, 469]⟩
  , ⟨[(1, true), (37, false), (47, false), (6, true), (71, false), (22, false), (79, false)], [617, 616, 237, 462, 469]⟩
  , ⟨[(1, true), (37, false), (47, false), (6, true), (71, false), (22, false)], [618, 616, 237, 467, 462, 469]⟩
  , ⟨[(1, true), (37, false), (47, false), (6, true), (71, false), (22, false), (79, false), (93, false)], [499, 616, 237, 462, 469]⟩
  , ⟨[(1, true), (37, false), (47, false), (71, false)], [615, 616, 619, 295]⟩
  , ⟨[(1, true), (37, false), (47, false), (43, false), (78, false)], [621, 10, 432, 429]⟩
  , ⟨[(1, true), (37, false), (47, false), (9, false), (83, true), (43, false)], [621, 622, 291, 498, 495]⟩
  , ⟨[(1, true), (37, false), (47, false), (71, true), (43, true)], [379, 621, 420, 403]⟩
  , ⟨[(1, true), (37, false), (47, false), (71, true)], [624, 621, 622, 79, 623, 466]⟩
  , ⟨[(1, true), (37, false), (47, false), (43, false)], [621, 622, 79, 623, 466, 291]⟩
  , ⟨[(1, true), (37, false), (47, false)], [626, 621, 625]⟩
  , ⟨[(1, true), (37, false), (47, true), (92, true), (76, false), (7, false)], [423, 627, 265, 389, 416]⟩
  , ⟨[(1, true), (37, false), (47, true), (92, true), (76, false)], [628, 627, 418, 265, 389, 416]⟩
  , ⟨[(1, true), (37, false), (47, true), (92, true)], [629, 627, 377, 265, 389, 416]⟩
  , ⟨[(1, true), (37, false), (47, true), (92, true), (76, true)], [377, 627, 265, 389, 416]⟩
  , ⟨[(1, true), (37, false), (12, false)], [627, 630, 394, 421, 433, 135, 449, 468]⟩
  , ⟨[(1, true), (37, false), (92, false), (47, true), (12, true)], [391, 627, 632, 630, 138, 446, 460]⟩
  , ⟨[(1, true), (37, false)], [627, 632, 633, 630, 449]⟩
  , ⟨[(1, true), (37, true), (6, false), (28, false), (14, false)], [304, 634, 299, 110, 415, 529, 516]⟩
  , ⟨[(1, true), (37, true), (6, false), (28, false), (14, true), (54, true)], [407, 634, 298, 297, 417]⟩
  , ⟨[(1, true), (37, true), (6, false), (28, false), (83, true)], [110, 634, 298, 297, 417]⟩
  , ⟨[(1, true), (37, true), (6, false), (28, true)], [374, 634, 395, 388]⟩
  , ⟨[(1, true), (37, true), (6, false), (74, true), (28, false), (14, true), (54, false), (43, false)], [508, 634, 298, 297, 417]⟩
  , ⟨[(1, true), (37, true), (6, false), (74, true), (28, false), (14, true), (54, false)], [639, 634, 638, 635, 636, 488, 298, 297, 417]⟩
  , ⟨[(1, true), (37, true), (6, false), (74, true), (28, false), (14, true), (54, false), (43, true)], [488, 634, 638, 298, 297, 417]⟩
  , ⟨[(1, true), (6, true), (28, false), (77, true)], [634, 219, 378, 402, 398]⟩
  , ⟨[(1, true), (6, true), (77, false), (42, true)], [634, 375, 15, 424, 399]⟩
  , ⟨[(1, true), (6, true), (77, false)], [634, 375, 643, 431, 454, 447, 92]⟩
  , ⟨[(1, true), (37, true), (74, false), (6, false), (28, false), (14, true), (54, false)], [443, 634, 638, 298, 297, 417]⟩
  , ⟨[(1, true), (37, true), (95, false), (6, true), (12, false), (28, true), (77, true), (70, false)], [513, 634, 644, 642, 489, 411, 405]⟩
  , ⟨[(1, true), (37, true), (95, false), (6, true), (12, false), (28, true), (77, true)], [646, 634, 644, 642, 411, 405]⟩
  , ⟨[(1, true), (95, false), (6, true), (12, true), (70, false)], [634, 644, 642, 86, 521, 526, 496]⟩
  , ⟨[(1, true), (95, false), (6, true), (70, false)], [648, 634, 644, 642, 647, 86, 521, 526]⟩
  , ⟨[(1, true), (95, true), (37, true), (6, true), (28, true), (77, true)], [419, 634, 644, 642, 411, 405]⟩
  , ⟨[(1, true), (95, true), (37, true), (6, true), (28, true)], [650, 634, 644, 638, 635, 636, 640, 645]⟩
  , ⟨[(1, false), (95, false)], [574, 577, 582, 579]⟩
  , ⟨[(1, false), (95, true), (74, false)], [590, 652, 593, 610, 595, 608, 586]⟩
  , ⟨[(1, false), (95, true)], [653, 652, 610, 595, 608, 586]⟩
  , ⟨[(1, true), (6, true)], [644, 634, 642, 651, 649, 411, 405]⟩
  , ⟨[(1, true), (37, true), (6, false), (28, false)], [635, 634, 655, 638, 636, 640, 645]⟩
  , ⟨[(37, false)], [634, 652, 654]⟩
  , ⟨[(6, true)], [657, 655, 652, 654]⟩
  , ⟨[(28, true), (1, true), (6, false)], [638, 634]⟩
  , ⟨[(1, true), (28, false), (6, false)], [656, 634]⟩
  , ⟨[(62, false), (21, false), (12, false), (44, false), (1, false)], [290, 654]⟩
  , ⟨[(9, false), (18, false), (14, false), (37, true), (1, true)], [306, 655]⟩
  , ⟨[(75, false), (62, false), (44, false), (1, false), (70, false)], [393, 654]⟩
  , ⟨[(44, false), (95, false), (62, false), (12, false), (70, false), (1, false)], [283, 663]⟩
  , ⟨[(92, false), (78, true), (74, false), (12, false), (1, false), (87, false)], [434, 652]⟩
  , ⟨[(89, false), (87, true), (1, false), (70, true), (74, false), (3, false)], [438, 652]⟩
  , ⟨[(60, false), (7, false), (1, false), (37, true), (74, false), (87, true), (3, true)], [483, 652]⟩
  , ⟨[(3, false), (89, false), (1, false), (62, false), (12, true), (70, true), (74, false), (53, true)], [354, 652]⟩
  , ⟨[(70, true), (89, false), (1, false), (74, false), (44, false), (92, false), (12, false), (3, true)], [360, 652]⟩
  , ⟨[(51, false), (53, false), (1, false), (92, false), (70, true), (89, false), (12, false), (3, false), (74, false)], [341, 652]⟩
  , ⟨[(53, false), (3, false), (1, false), (92, false), (62, false), (70, true), (89, false), (51, false), (47, false)], [347, 652]⟩
  , ⟨[(53, true), (51, false), (1, false), (92, false), (62, false), (70, true), (89, false), (74, false), (3, false)], [355, 652]⟩
  , ⟨[(1, true)], [658, 659, 660]⟩
  , ⟨[(95, false)], [673, 652]⟩
  , ⟨[], [673, 674, 654]⟩
  ]

set_option maxHeartbeats 40000000 in
/-- KERNEL replay of the refutation — plain `decide`, no `native_decide`. -/
theorem check_ok : RupCheckerFast.checkRefutationFast F steps = true := by decide

/-- The recovered CNF is unsatisfiable (kernel-checked LRAT replay +
`rup_sound` composition). -/
theorem instance_unsat : ¬ ∃ σ, satFormula σ F :=
  RupCheckerFast.checkRefutationFast_sound F steps check_ok

/-- The gadget's variable set: DIMACS variables `1..95`. -/
def s : Finset ℕ := Finset.Icc 1 95

set_option maxHeartbeats 4000000 in
/-- END-TO-END VERDICT: no point of the `[0,1]` box reaches the sat_relu
gadget's unsafe region `{Y₀ ≥ 1 ∧ Y₁ ≤ 0}` — real-arithmetic SAFE. -/
theorem instance_safe :
    ∀ x : ℕ → ℝ, (∀ j ∈ s, 0 ≤ x j ∧ x j ≤ 1) →
      ¬ (1 ≤ SatRelu.Y0 (SatReluVerdict.clausesOf F) x ∧
         SatRelu.Y1 s x ≤ 0) :=
  SatReluVerdict.safe_of_unsat F s (by decide) instance_unsat

end SatReluSweep_v95c275

end Crownproof

/-! ## Trust-base check -/

#print axioms Crownproof.SatReluSweep_v95c275.check_ok
#print axioms Crownproof.SatReluSweep_v95c275.instance_unsat
#print axioms Crownproof.SatReluSweep_v95c275.instance_safe
